### ISSUE TITLE
Add: EBS Cinema [US/ET] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#10014]
### Channel Name

EBS Cinema

### Owners (optional)

EBS Television Global

### Country

US

### Subdivision (optional)

US-MD

### City (optional)

Silver Spring

### Broadcast Area

c/ET

### Languages

amh;eng

### Categories (optional)

movies

### NSFW

FALSE

### Website (optional)

https://ebstv.tv/

### Logo

https://i.imgur.com/goe5FOP.png

**Comment by Dum4G** [comment]
EBSCinema.us
