### ISSUE TITLE
Add: EBS Musika [US/ET] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#10015]
### Channel Name

EBS Musika

### Owners (optional)

EBS Television Global

### Country

US

### Subdivision (optional)

US-MD

### City (optional)

Silver Spring

### Broadcast Area

c/ET

### Languages

amh;eng

### Categories (optional)

music

### NSFW

FALSE

### Website (optional)

https://ebstv.tv/

### Logo

https://i.imgur.com/lMKTqng.png

**Comment by Dum4G** [comment]
EBSMusika.us
