### ISSUE TITLE
Add: Warner TV Italy

### ISSUE THREAD

**Issue by infid0** [iptv-org/database#1014]
### Channel Name

Warner TV Italy

### Country

IT

### Broadcast Area

IT

### Languages

ITA

### Categories (optional)

Movie

### NSFW

FALSE

### Launched (optional)

2022-10-30

### Website (optional)

https://warnertv.it/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Warner2018LA.png/512px-Warner2018LA.png

### Notes

EPG ID: `WarnerTVItaly.it`

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/e7c0c2fdfeda7fe4fb3d8d7a480aa0b0953b2afc
