### ISSUE TITLE
Edit: Nethra TV [LK] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#10153]
### Channel ID (required)

NethraTV.in

### Owners

Sri Lanka Rupavahini Corporation

### Country

LK

### City

Colombo

### Broadcast Area

c/LK

### Languages

tam

### Categories

general

### NSFW

None

### Launched

2008-01-01

### Website

https://nethratv.lk/

### Logo

https://i.imgur.com/vSrIN1U.jpg

**Comment by Dum4G** [comment]
Only NethraTV.in exists

**Comment by Carlinhos027** [comment]
> Only NethraTV.in exists in db

Fixed
