### ISSUE TITLE
Edit: Fuse East

### ISSUE THREAD

**Issue by cr0op** [iptv-org/database#1022]
### Channel ID (required)

FuseEast.us

### Channel Name

Backstage

### Country

US

### Languages

eng

### Replaced By

Backstage.us

### Website

https://www.fuse.tv/v/fuse-backstage/a4068154335cc15ab055a34979c5e1c4

### Logo

https://image.xumo.com/v1/channels/channel/99991303/600x337.jpg?type=channelTile

**Comment by freearhey** [comment]
Backstage added in https://github.com/iptv-org/database/commit/dc7c36cfef479d41d1ec8b4afbdc94bdb5c9a730

To fix the description of a particular stream you need to change it `tvg-id` to `Backstage.us`:

https://github.com/iptv-org/iptv/blob/master/streams/us_xumo.m3u#L66-L67
