### ISSUE TITLE
Edit: Pluto TV Pluto After School Cartoons

### ISSUE THREAD

**Issue by cr0op** [iptv-org/database#1023]
### Channel ID (required)

ForeverKids.us

### Channel Name

Forever Kids

### Country

US

### Broadcast Area

s/US

### Languages

eng

### Categories

kids

### NSFW

FALSE

### Replaced By

ForeverKids.us

### Website

https://pluto.tv/en/live-tv/forever-kids

### Logo

https://images.pluto.tv/channels/56171fafada51f8004c4b40f/colorLogoPNG.png

### Notes

the channel on the playlist currently listed as "Pluto TV Pluto After School Cartoons" is actually called "Forever Kids" and should be updated to reflect that

**Comment by freearhey** [comment]
Forever Kids already in the database: https://iptv-org.github.io/?q=Forever%20Kids

To fix the description of the stream you just need to set its `tvg-id` to `ForeverKids.us`: 

https://github.com/iptv-org/iptv/blob/master/streams/us_pluto.m3u#L1280-L1281
