### ISSUE TITLE
Ae

### ISSUE THREAD

**Issue by lc22daalbania** [iptv-org/database#10358]
### Channel Name

A&e

### Country

Brazil

### Broadcast Area

Brazil

### Languages

Português 

### NSFW

FALSE

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/A%26E_Network_logo.svg/512px-A%26E_Network_logo.svg.png

### Notes

Jj

**Comment by Dum4G** [comment]
https://iptv-org.github.io/channels/br/AE
