### ISSUE TITLE
Edit: Fox (Spain)

### ISSUE THREAD

**Issue by flexxer4** [iptv-org/database#10415]
### Channel ID (required)

Starchannel.es

### Channel Name

Star Channel (Spain)

### Owners

The Walt Disney Corporation

### Languages

esp

### NSFW

None

### Launched

2024-04-11

### Website

https://www.starchannel.es/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Star_Channel_2020.svg/512px-Star_Channel_2020.svg.png

### Notes

Fox Spain becomes Star Channel Spain

**Comment by BellezaEmporium** [comment]
Duplicate.
