### ISSUE TITLE
Canal RED1 

### ISSUE THREAD

**Issue by TheMZPro** [iptv-org/database#10431]
### Channel Name

Canal RED1

### Alternative Names (optional)

Red de Entretenimiento Digital

### Owners (optional)

MZ Producciones TV

### Country

CR

### City (optional)

San José 

### Broadcast Area

sj/cr/ca

### Languages

Esp

### Categories (optional)

Entretenimento

### NSFW

FALSE

### Launched (optional)

2013-09-18

### Website (optional)

www.mzproducciones.com

### Logo

https://scontent.fsyq3-1.fna.fbcdn.net/v/t39.30808-6/301263078_419695370144333_2909078913471512100_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=5f2048&_nc_ohc=1wKxY-BKCmAAX-vmfmM&_nc_ht=scontent.fsyq3-1.fna&oh=00_AfBZp_aze1-hzpfT8OI39Q0ltCn531tlnPn1FmV_ttBDQQ&oe=6601ED5E

### Notes

https://app.viloud.tv/hls/channel/3fb163ed91023cdc277bfa748c62e162.m3u8

**Comment by Alstruit** [comment]
#10609

**Comment by Moratony** [comment]
https://app.viloud.tv/hls/channel/13f265f9b0a5b3ad9b968124db986450.m3u8   update
