### ISSUE TITLE
Edit: La 7

### ISSUE THREAD

**Issue by maikeln80** [iptv-org/database#10432]
### Channel ID (required)

La7.es

### City

Murcia

### NSFW

None

### Website

https://www.la7tv.es/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/La_7_logo.svg/150px-La_7_logo.svg.png

**Comment by Carlinhos027** [comment]
All the data that is already in the database is correct, the only thing we can correct is the logo.
