### ISSUE TITLE
Edit: Cartoon Network (Vietnam)

### ISSUE THREAD

**Issue by Hieuhuynhxuan** [iptv-org/database#10529]
### Channel ID (required)

CartoonNetworkVietnam.vn

### Channel Name

Cartoon Network

### Owners

Warner Bros. Discovery Asia - Pacific; Msky Company Limited

### Country

VN

### Broadcast Area

c/VN

### Languages

vie;eng

### Categories

animation;kids

### NSFW

None

### Launched

1995-07-29

### Website

https://cartoonnetwork.com.vn

### Logo

https://i.postimg.cc/6phyxVfm/Cartoon-Network-logo.png

**Comment by Alstruit** [comment]
Reverted to original. Adding "Vietnam" to id is redundant since ".vn" exists.
