### ISSUE TITLE
Add: IRR-TV [FI/RU] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#10619]
### Channel Name

IRR-TV

### Country

FI

### City (optional)

Kerava

### Broadcast Area

c/FI

### Languages

fin

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://irr-tv.fi/

### Logo

https://i.imgur.com/FIlutht.png

**Comment by Dum4G** [comment]
Not sure if it has to do something with Russia and anything besides religion
https://fi.wikipedia.org/wiki/IRR-TV

**Comment by AntiPontifex** [comment]
fwiw, it seems to be a cultural channel

**Comment by BellezaEmporium** [comment]
> Not sure if it has to do something with Russia and anything besides religion https://fi.wikipedia.org/wiki/IRR-TV

It's mainly targeted to Russian audiences (or at least it collaborated/worked with them) by what the Wiki seems to tell.
![image](https://github.com/iptv-org/database/assets/30985701/69f88bdf-d769-4f88-b7b0-a5a094e36933)

**Comment by Dum4G** [comment]
So far I haven't seen a single TV show from them in Russian.

**Comment by AntiPontifex** [comment]
Well spotted, Belleza: remove the rus lang tag then?

**Comment by BellezaEmporium** [comment]
> So far I haven't seen a single TV show from them in Russian.

I don't believe they'll air shows in Russian, but it's more about showing Russians that also speak Finnish some Russian stuff.

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/database/assets/30985701/c98c3592-4742-4f1a-b68c-d0586d9307bb)
Borked translation, but the message is clear lol. From https://irr-tv.fi/irr-tv/

**Comment by BellezaEmporium** [comment]
Found out a similar PR was opened for the same channel, containing the same info. Closing this as dupe.
