### ISSUE TITLE
AGRO CANAL

### ISSUE THREAD

**Issue by Felipe11767** [iptv-org/database#10614]
### Channel ID (required)

AgroCanal.br

### Country

BR

### Categories

business

### NSFW

None

### Logo

https://i.imgur.com/5XyopHf.png

**Comment by BellezaEmporium** [comment]
I must say I understand the idea of adding "Variety" as a category, though this isn't a recognized category in our listings. It should be discussed.

**Comment by BellezaEmporium** [comment]
After some discussion with part of the team, we thought "Business" was more fitting. AgroCanal is a brazilian business channel, after all.
