### ISSUE TITLE
Edit: Ratih TV channel changed to Kebumen TV

### ISSUE THREAD

**Issue by singkie** [iptv-org/database#10613]
### Channel ID (required)

KebumenTV.id

### Channel Name

Kebumen TV

### Alternative Names

Ratih TV

### NSFW

None

### Replaced By

RatihTV.id

### Website

https://id.wikipedia.org/wiki/Kebumen_TV

### Logo

https://upload.wikimedia.org/wikipedia/id/1/12/Logo_KebumenTV.png

**Comment by BellezaEmporium** [comment]
You've specified the reverse situation. The best way would be to create an channel edit, for RatihTV.id, precise the closure date and replacement channel.

**Comment by singkie** [comment]
@BellezaEmporium please approve #10626
