### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Boblapine** [iptv-org/database#10764]
Hi,
   For what I read, all the playlists are made with the data in the database.  It seems wrong because all the site I'm trying in VLC doesn't work. It looks like there is missing parts for the playlist in the DB.  Where can I get them.

My goal is to create my own DB to make my own playlists.
Help will be appreciate.

Thank you.

**Comment by BellezaEmporium** [comment]
The playlists are in iptv-org/iptv. The link is only made within the database thanks to the tvg-id. It permits to have all channel informations (and EPG in some way).

If you want to create your own playlist, you can use the tool that's available in https://iptv-org.github.io.
