### ISSUE TITLE
Edit: Zoy TV

### ISSUE THREAD

**Issue by ZoyMilton** [iptv-org/database#10849]
### Channel ID (required)

ZoyTV.bo

### Owners

Zoy

### Country

BO

### City

Cochabamba

### Languages

Español

### NSFW

None

### Launched

2015-09-21

### Website

https://zoy.tv

### Logo

https://i.ibb.co/KmkFhpw/ZOY-logo.png

**Comment by BellezaEmporium** [comment]
Website doesn't load up for me.

I see we have a "tucableiptv" website that's an embed to your stream, though.

**Comment by Alstruit** [comment]
Logo is way too big. Must be under 512x512 pixels.

**Comment by Dum4G** [comment]
@ZoyMilton at this point ZoyTV is renamed to ZoyTV Plus?

**Comment by BellezaEmporium** [comment]
On checks, Zoy + redirects to the Spanish Smurfs stream.

**Comment by Dum4G** [comment]
Looks like non of the streams provided are his own, basically a wrapper for https://stream.ads.ottera.tv/playlist.m3u8
