### ISSUE TITLE
VoA Persian and IraneFarda doesn't appear in playlists

### ISSUE THREAD

**Issue by Rayrsn** [iptv-org/database#1096]
VoA Persian and IraneFarda are Persian news channels, they appear to be in the [channels](https://github.com/iptv-org/database/blob/master/data/channels.csv) but they don't show up in either Iran's playlist or Persian's playlist.

**Comment by freearhey** [comment]
You'd better ask for help here: https://github.com/iptv-org/iptv/issues

This repository only stores channel descriptions.

**Comment by AntiPontifex** [comment]
Since VoA is based in the United States, they appear on the US list: they both are there.
