### ISSUE TITLE
Add: Discovery Kids Australia

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#10971]
### Channel Name

Discovery Kids

### Owners (optional)

Warner Bros. Discovery Asia-Pacific

### Country

AU

### Broadcast Area

c/AU

### Languages

eng

### Categories (optional)

kids

### NSFW

FALSE

### Launched (optional)

2014-11-03

### Closed (optional)

2020-02-01

### Logo

https://i.imgur.com/2JPtmZR.png

### Notes

Please block when added, Discovery-owned https://en.wikipedia.org/wiki/Discovery_Kids_(Australian_TV_channel)

**Comment by BellezaEmporium** [comment]
No point in adding closed channels in the blocklist when those don't air.
