### ISSUE TITLE
Add: DKids

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#10970]
### Channel Name

DKids

### Owners (optional)

Discovery EMEA

### Country

AE

### Broadcast Area

r/MENA

### Languages

ara

### Categories (optional)

kids

### NSFW

FALSE

### Launched (optional)

2016-08-01

### Closed (optional)

2021-02-08

### Logo

https://upload.wikimedia.org/wikipedia/commons/b/b6/DKids.png

### Notes

Please block when added, Discovery-owned https://en.wikipedia.org/wiki/DKids

**Comment by BellezaEmporium** [comment]
Little difference. While the channel is aired in Saudi Arabia, it's from the United Arab Emirates (UAE, or AE as a country-code).
Made the difference appear.
