### ISSUE TITLE
Edit: Berkah Shop TV [ID] fix channel replace

### ISSUE THREAD

**Issue by singkie** [iptv-org/database#11047]
### Channel ID (required)

BerkahShopTV.id

### NSFW

None

### Replaced By

iBerkah.id

**Comment by singkie** [comment]
@BellezaEmporium i dont know, BerkahShopTV.id must be tagged to *closed* and iBerkah.id is exist

**Comment by BellezaEmporium** [comment]
Can't seem to trace out when it has closed, so I'll say it's approved.

**Comment by singkie** [comment]
@BellezaEmporium how to remove `closed` tag?
![image](https://github.com/iptv-org/database/assets/134305038/7fa5c5f3-e62a-48bf-839e-d0c8a8e20779)

**Comment by singkie** [comment]
@BellezaEmporium it's because `replaced_by` is not empty
