### ISSUE TITLE
Edit: Usee Prime [ID] fix channel replace

### ISSUE THREAD

**Issue by singkie** [iptv-org/database#11043]
### Channel ID (required)

UseePrime.id

### NSFW

None

### Closed

2023-10-10

### Replaced By

AllPlayEnt.id

**Comment by BellezaEmporium** [comment]
Do you appear to know when this channel was closed and replaced ?

**Comment by singkie** [comment]
@BellezaEmporium it seem 10/oct/2023 https://gadget.jagatreview.com/2023/10/indihometv-rans-taulany-comic-con/

**Comment by BellezaEmporium** [comment]
Confirmed by some video : https://m.youtube.com/watch?v=yC_bAN9e1QE

**Comment by singkie** [comment]
please remove `closed` tag on `AllPlayEnt.id`
