### ISSUE TITLE
Edit: Ratih TV [ID] fix channel replace

### ISSUE THREAD

**Issue by singkie** [iptv-org/database#11045]
### Channel ID (required)

RatihTV.id

### NSFW

None

### Closed

2023-08-21

### Replaced By

KebumenTV.id

**Comment by BellezaEmporium** [comment]
Do you appear to know when this channel was closed and replaced ?

**Comment by singkie** [comment]
@BellezaEmporium RatihTV.id was changed as KebumenTV.id where replaced at 21 August 2023.
https://wonoyoso.kec-kuwarasan.kebumenkab.go.id/index.php/web/artikel/4/692

**Comment by singkie** [comment]
@BellezaEmporium please remove `closed` tag on `KebumenTV.id`. `RatihTV.id` was replaced with `KebumentTV.id`

**Comment by singkie** [comment]
i've wrote new update #11108
