### ISSUE TITLE
Add: Canal Red1

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#11049]
### Channel Name

Canal Red1

### Owners (optional)

MZ Producciones

### Country

CR

### City (optional)

San Jose

### Broadcast Area

c/CR

### Languages

spa

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://www.mzproducciones.com/

### Logo

https://i.ytimg.com/vi/GEtbShXxtPg/mqdefault.jpg

### Notes

https://app.viloud.tv/hls/channel/3fb163ed91023cdc277bfa748c62e162.m3u8

Note: This stream was not working for me in Canada

**Comment by AntiPontifex** [comment]
I see there is another entry for this: maybe use mine instead?

**Comment by BellezaEmporium** [comment]
Well, one's been tackling it hours before yours. I've made the necessary modifications there and approved it. Consider this a duplicate.

**Comment by AntiPontifex** [comment]
No problem
