### ISSUE TITLE
Edit: All Play Ent [ID] fix channel replace

### ISSUE THREAD

**Issue by singkie** [iptv-org/database#11042]
### Channel ID (required)

AllPlayEnt.id

### NSFW

None

### Replaced By

~

**Comment by singkie** [comment]
@BellezaEmporium how to remove channel changed? i think `~` is to remove value. is it right?

**Comment by BellezaEmporium** [comment]
If the channel was opened at the same time another one has closed, then just precise the launch date. However if this is just a channel fusion, nothing more to do than close the concerned channel.
