### ISSUE TITLE
Add: Peer TV Südtirol

### ISSUE THREAD

**Issue by raphaelbarbieri** [iptv-org/database#11051]
### Channel Name

Peer TV Sudtirol

### Alternative Names (optional)

Peer TV Südtirol;Peer TV

### Network (optional)

Peer TV

### Owners (optional)

Peer GmbH / SRL

### Country

IT

### Subdivision (optional)

IT-32

### Broadcast Area

r/EU;c/IT;s/IT-32

### Languages

deu

### Categories (optional)

outdoor;travel

### NSFW

FALSE

### Website (optional)

https://www.peer.tv/

### Logo

https://www.peer.biz/peertv-iptv/peer-tv-suedtirol.png

**Comment by BellezaEmporium** [comment]
Same remarks as in https://github.com/iptv-org/database/issues/11055

**Comment by raphaelbarbieri** [comment]
I have also adjusted this. Now the data should suit :)
