### ISSUE TITLE
Add: Peer TV Alto Adige

### ISSUE THREAD

**Issue by raphaelbarbieri** [iptv-org/database#11052]
### Channel Name

Peer TV Alto Adige

### Alternative Names (optional)

Peer TV

### Network (optional)

Peer TV

### Owners (optional)

Peer GmbH / SRL

### Country

IT

### Subdivision (optional)

IT-32

### Broadcast Area

r/EU;c/IT;s/IT-32

### Languages

ita

### Categories (optional)

outdoor;travel

### NSFW

FALSE

### Website (optional)

https://www.peer.tv/it

### Logo

https://www.peer.biz/peertv-iptv/peer-tv-alto-adige.png

**Comment by BellezaEmporium** [comment]
Same remarks as in #11055
