### ISSUE TITLE
Add: Peer TV South Tyrol

### ISSUE THREAD

**Issue by raphaelbarbieri** [iptv-org/database#11055]
### Channel Name

Peer TV South Tyrol

### Alternative Names (optional)

Peer TV

### Network (optional)

Peer TV

### Owners (optional)

Peer GmbH / SRL

### Country

IT

### Subdivision (optional)

IT-32

### Broadcast Area

r/EU;c/IT;s/IT-32

### Languages

eng

### Categories (optional)

outdoor;travel

### NSFW

FALSE

### Website (optional)

https://www.peer.tv/en

### Logo

https://www.peer.biz/peertv-iptv/peer-tv-south-tyrol.png

**Comment by BellezaEmporium** [comment]
Quite extensive, though few remarks.

- If Peer TV South Tyrol proposes a different programmation than the main Peer TV channel, it would be counter-productive to give alternative names corresponding to the main channel.
- Tons of categories. Maybe is it better to just classify it as a "general" purpose channel ?

**Comment by raphaelbarbieri** [comment]
The content differs minimally, the German channel has additional news, but the videos are more or less the same only in a different language.

A German can't do much with the Italian channel because he doesn't understand it. But then the German channel would make sense again.
That's why I thought it would be better to create different channels, because it's a different language audience. :thinking: 


> Tons of categories. Maybe is it better to just classify it as a "general" purpose channel ?

Hmm maybe only `outdoor` and `travel` that might fit best (according to the content)

**Comment by BellezaEmporium** [comment]
> The content differs minimally, the German channel has additional news, but the videos are more or less the same only in a different language.
> 
> A German can't do much with the Italian channel because he doesn't understand it. But then the German channel would make sense again. That's why I thought it would be better to create different channels, because it's a different language audience. 🤔
> 
> > Tons of categories. Maybe is it better to just classify it as a "general" purpose channel ?
> 
> Hmm maybe only `outdoor` and `travel` that might fit best (according to the content)

I understand your remarks. Keeping "Peer TV" should be OK as an alternative name.
The channel seems to be a "tourism service" channel, permitting the foreigners and diasporas to take a better look at the region. Travel would fit.

**Comment by raphaelbarbieri** [comment]
> > The content differs minimally, the German channel has additional news, but the videos are more or less the same only in a different language.
> > A German can't do much with the Italian channel because he doesn't understand it. But then the German channel would make sense again. That's why I thought it would be better to create different channels, because it's a different language audience. 🤔
> > > Tons of categories. Maybe is it better to just classify it as a "general" purpose channel ?
> > 
> > 
> > Hmm maybe only `outdoor` and `travel` that might fit best (according to the content)
> 
> I understand your remarks. Keeping "Peer TV" should be OK as an alternative name. The channel seems to be a "tourism service" channel, permitting the foreigners and diasporas to take a better look at the region. Travel would fit.

Okay updated.

**Comment by BellezaEmporium** [comment]
Works for me. Approved.
