### ISSUE TITLE
Edit: TV Zepce Etno

### ISSUE THREAD

**Issue by dariohzv** [iptv-org/database#11171]
### Channel ID (required)

TVZepceEtno.ba

### Channel Name

TV Zepce Etno

### Alternative Names

TV Žepče Etno

### Country

BA

### City

Žepče

### Languages

hrv

### Categories

music

### NSFW

None

### Launched

2023-07-01

### Website

https://tvzepce.wixsite.com/tvzepce

**Comment by BellezaEmporium** [comment]
In order for all users to get a proper view of the channel name, we tend to remove special characters or accents that aren't in the US standard. However, having them as a an alternative name is accepted. Made the necessary changes, thanks for your issue.
