### ISSUE TITLE
Edit: UU TV 1

### ISSUE THREAD

**Issue by nvmd** [iptv-org/database#11178]
### Channel ID (required)

UUTV1.tr

### Channel Name

Uskudar Universitesi Televizyonu 1

### Alternative Names

Üsküdar Üniversitesi Televizyonu 1;ÜÜTV 1

### Network

ÜÜTV

### Owners

Üsküdar Üniversitesi

### NSFW

None

### Website

https://tv.uskudar.edu.tr/

### Notes

I would be nice to have full name of the channel in the list, same for `UUTV2.tr`

**Comment by BellezaEmporium** [comment]
In order for all users to get a proper view of the channel name, we prevent adding accents or special characters that aren't in the US format. However, adding them as an alternative name is accepted. Made the necessary changes, thanks for your issue.
