### ISSUE TITLE
Add: Campo Rural TV [UY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#11207]
### Channel Name

Campo Rural TV

### Country

UY

### City (optional)

Montevideo

### Broadcast Area

c/UY

### Languages

spa

### Categories (optional)

outdoor

### NSFW

FALSE

### Website (optional)

https://camporural.tv/

### Logo

https://i.imgur.com/MO2jDMn.jpeg

**Comment by BellezaEmporium** [comment]
Can't seem to pinpoint the owners, but it's a coalition of Radio Rural 610 AM and Campo TV, both of them being in Montevideo, UY.
