### ISSUE TITLE
Add: MMC TV [US/LK] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#11257]
### Channel Name

MMC TV USA

### Alternative Names (optional)

Mindfulness Meditation Center 

### Country

US

### Subdivision (optional)

US-CA

### City (optional)

Los Angeles

### Broadcast Area

c/US;c/LK

### Languages

eng;sin

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://www.mmctvusa.com/

### Logo

https://i.imgur.com/0MwrSYE.png

**Comment by Alstruit** [comment]
MMCTV.us exists under a different channel.

**Comment by Carlinhos027** [comment]
> MMCTV.us exists under a different channel.

Ok fixed it.

**Comment by Alstruit** [comment]
Looks okay for now.
