### ISSUE TITLE
Edit: FOX Türkiye

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/database#11268]
### Channel ID (required)

Fox.tr

### Channel Name

Fox

### Alternative Names

FOX Türk; Fox TV

### Owners

The Walt Disney Company

### Country

TR

### Broadcast Area

c/TR

### Languages

tur

### NSFW

None

### Launched

2007-02-24

### Closed

2024-02-12

### Replaced By

NOWTV.tr

### Website

https://www.nowtv.com.tr/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/FOX_wordmark-red.svg/320px-FOX_wordmark-red.svg.png

### Notes

it was announced on January 24, 2024 that it will be named NOW specifically for Turkey, and the change took place as of February 12, 2024.
https://tr.m.wikipedia.org/wiki/NOW_(T%C3%BCrkiye)

**Comment by R4IN2007** [comment]
Odd, Closed?
https://iptv-org.github.io/channels/tr/NOWTV
It just rebranded to NOW, The one that is closed is Fox.

**Comment by Alstruit** [comment]
Might want to mark the old id as closed instead of changing the id to the new one to avoid confusion.

**Comment by Alstruit** [comment]
20840  "NOWTV.tr" has an invalid replaced_by "Fox.tr"
