### ISSUE TITLE
Add: RTA Education

### ISSUE THREAD

**Issue by fraudiay79** [iptv-org/database#11262]
### Channel Name

RTA Education

### Alternative Names (optional)

معارف ټلویزیون

### Owners (optional)

RTA (Radio Television Afghanistan)

### Country

AF

### Broadcast Area

c/AF

### Languages

pus

### NSFW

FALSE

### Website (optional)

https://rta.af/live/

### Logo

https://rta.af/artmedia/2022/12/rta-logo-final-300x185.png

**Comment by Alstruit** [comment]
Already exists under RTA.af
