### ISSUE TITLE
Remove: UseePhoto.id

### ISSUE THREAD

**Issue by singkie** [iptv-org/database#11324]
### Channel ID (required)

UseePhoto.id

### Reason (required)

Other

### Notes

this digital TV was closed.
https://id.m.wikipedia.org/wiki/IndiHome_TV#Saluran_eksklusif

**Comment by BellezaEmporium** [comment]
Best would be to edit the channel to say it's closed, rather than removing it. We use channels:remove only to remove channels that never existed, are duplicates.

**Comment by singkie** [comment]
i dont know when it was closed
