### ISSUE TITLE
Add: IGLGroup TV

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/database#11335]
### Channel Name

IGLGroup TV

### Country

AR

### City (optional)

Iglesia

### Broadcast Area

c/AR

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Logo

https://avatars.githubusercontent.com/u/163193844?v=4

### Notes

Iglesia, San Juan, Argentina.

**Comment by Alstruit** [comment]
#10331 ?

**Comment by BellezaEmporium** [comment]
Hmm, haven't found that out when I've checked. My bad.
