### ISSUE TITLE
Add: ERT Eurovision Channel (GR)

### ISSUE THREAD

**Issue by idfan92** [iptv-org/database#11550]
### Channel Name

ERT Eurovision Channel

### Owners (optional)

Hellenic Broadcasting Corporation

### Country

GR

### Broadcast Area

c/GR

### Languages

ell

### Categories (optional)

music

### NSFW

FALSE

### Logo

https://files2.app.ertflix.gr/channel/eurovisionchannel/eurovision-800x300.png?m=resize&w=512&h=192

**Comment by Alstruit** [comment]
Invalid Logo.
