### ISSUE TITLE
Edit: Eleven 1 [PT] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#11620]
### Channel ID (required)

Eleven1.pt

### NSFW

None

### Logo

https://i.imgur.com/BKkcayq.png

**Comment by Dum4G** [comment]
You wanted to change polish channel logo or add portuguese entry into db?

**Comment by Dum4G** [comment]
@Carlinhos027

**Comment by Carlinhos027** [comment]
> You wanted to change polish channel logo or add portuguese entry into db?

Just wanted to fix the logo because it seems to be bug.

**Comment by Dum4G** [comment]
> ElevenSports1.pt
Thing is we don't have ElevenSports1.pt but we do have ElevenSports1.pl

**Comment by Carlinhos027** [comment]
> > ElevenSports1.pt
> 
> Thing is we don't have ElevenSports1.pt but we do have ElevenSports1.pl

Oh, sorry. It was "Eleven1.pt". Fixed!
