### ISSUE TITLE
Add: Antara TV

### ISSUE THREAD

**Issue by singkie** [iptv-org/database#11659]
### Channel Name

Antara TV

### Country

ID

### Broadcast Area

c/ID

### Languages

ind

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.indihometv.com/livetv/antara

### Logo

https://i.postimg.cc/DzqcbY5K/antara.jpg

**Comment by ProPontifex** [comment]
Just submitted an entry
