### ISSUE TITLE
RTV ÑUBLE

### ISSUE THREAD

**Issue by RTVNUBLE** [iptv-org/database#11767]
### Channel ID (required)

RTV ÑUBLE

### Channel Name

RTV ÑUBLE

### Alternative Names

RTV ÑUBLE 

### Network

Chile 

### Owners

Ñuble

### Country

Chillan 

### Subdivision

Chile - Luble

### City

Chillan 

### Broadcast Area

Chile 

### Languages

Español 

### Categories

Generalista 

### NSFW

None

### Replaced By

canalrtv cl

### Website

canalrtv.cl

### Logo

https://www.facebook.com/share/jHzp7GecMqBCSgbw/?mibextid=xfxF2i

### Notes

EL CANAL DE ÑUBLE

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/database/assets/30985701/a9e11b24-7730-43ac-9947-e07d6a8d996d)
Your channel is already in the database, what's the main change ?
