### ISSUE TITLE
Edit: BeritaSatu English

### ISSUE THREAD

**Issue by singkie** [iptv-org/database#11792]
### Channel ID (required)

BeritaSatuEnglish.id

### Channel Name

Jakarta Globe News Channel

### Alternative Names

Berita Satu English

### Languages

ind;eng

### Categories

general;news

### NSFW

None

### Notes

is it good to change channel ID too?

**Comment by BellezaEmporium** [comment]
If there's a whole identity/channel name change, then it's better to close the channel with its older name, and add a new channel, reflecting that change.

**Comment by singkie** [comment]
@BellezaEmporium i've update with #11933 #11934
