### ISSUE TITLE
NTV stream not working

### ISSUE THREAD

**Issue by dubsy54321** [iptv-org/database#118]
Hello, I am not an experienced github user so I apologize if I'm not really using this correctly. I saw on iptv-org that I should report any issue with the database here. I've been using the lists over there for a few months now and have noticed that the NTV (Newfoundland TV) stream always just displays color bars.

**Comment by freearhey** [comment]
This repository only stores channel descriptions. If you want to report any problems with the broadcast it is better to do it here: https://github.com/iptv-org/iptv/issues
