### ISSUE TITLE
Edit: Skai TV (GR)

### ISSUE THREAD

**Issue by idfan92** [iptv-org/database#11810]
### Channel ID (required)

SkaiTV.gr

### Owners

Skai Group

### City

Piraeus

### Categories

general

### NSFW

None

### Launched

1993-09-21

### Closed

1999-09-26

### Replaced By

AlphaTV.gr

### Website

https://www.skai.gr/tv/

### Notes

The channel was initially replaced by Alpha TV in September 1999 but later relaunched in April 2006, replacing Seven TV (formerly known as Seven X).
*admin edit* See https://en.wikipedia.org/wiki/Skai_Group / https://en.wikipedia.org/wiki/Skai_TV

**Comment by BellezaEmporium** [comment]
If the group behind Skai TV is the same as their relaunch, i'll suggest not taking care of the channel replacement, and simply closing Seven TV/Seven X should do the trick.
