### ISSUE TITLE
Disney Channel (Spain) - Dead Stream

### ISSUE THREAD

**Issue by Y0gi-B3ar** [iptv-org/database#11879]
### Channel ID (required)

DisneyChannel.es

### NSFW

None

### Notes

The stream is dead and i have tested it on streamtest.in and it says offline
(see attached image)
![D Channel ES Offline](https://github.com/iptv-org/database/assets/170687436/9ddd6743-b356-47af-8a7e-d0158295ce9b)

**Comment by Alstruit** [comment]
https://github.com/iptv-org/iptv
