### ISSUE TITLE
Add: Radio New Zealand/RNZ

### ISSUE THREAD

**Issue by applecuckoo** [iptv-org/database#1187]
### Channel Name

Radio New Zealand

### Alternative Names (optional)

RNZ

### Country

NZ

### Broadcast Area

c/NZ

### Languages

eng;

### Categories (optional)

general;news

### NSFW

FALSE

### Website (optional)

https://www.rnz.co.nz/

### Logo

https://i.vimeocdn.com/portrait/2288748_640x640

### Notes

Radio service in NZ, logo found by google so not very high quality.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/0b90d394964e50bc779ec8fd63af5c80d307b9ef
