### ISSUE TITLE
Add: KBS News D

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#11871]
### Channel Name

KBS News D

### Network (optional)

KBS

### Owners (optional)

Korean Broadcasting System

### Country

KR

### City (optional)

Seoul

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://news.kbs.co.kr/news/pc/news24/news24.do?ref=pGnb

### Logo

https://static.wikia.nocookie.net/logopedia/images/8/8a/Kbs-news-d-kr.svg/revision/latest/scale-to-width-down/300?cb=20220916131000

**Comment by Alstruit** [comment]
Already Exists.
