### ISSUE TITLE
Add: Atomic TV

### ISSUE THREAD

**Issue by ovidiuuxonline** [iptv-org/database#1197]
![Atomic_TV](https://user-images.githubusercontent.com/85124797/201411767-4a04dc8f-afd2-4388-80ab-f2dfc776abae.png)

Atomic TV is the first music-specific television launched in Romania in 1999, with Romanian music, aimed at the adult audience.

Website: https://www.atomictv.ro/

#ROMANIA

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_add.yml&title=Add%3A+
