### ISSUE TITLE
Add: Atomic TV

### ISSUE THREAD

**Issue by ovidiuuxonline** [iptv-org/database#1198]
### Channel Name

Atomic TV

### Network (optional)

FTV

### Owners (optional)

Atomic Group

### Country

RO

### City (optional)

Bucharest

### Broadcast Area

r/RO

### Languages

ro;eng

### Categories (optional)

music

### NSFW

FALSE

### Website (optional)

https://www.atomictv.ro/

### Logo

https://user-images.githubusercontent.com/85124797/201411767-4a04dc8f-afd2-4388-80ab-f2dfc776abae.png

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/85e9d5a684739433e6b89ca1d401ecd62c62125b
