### ISSUE TITLE
Add: Servus TV Germany

### ISSUE THREAD

**Issue by Smark223** [iptv-org/database#1207]
### Channel Name

Servus TV Germany

### Country

DE

### Broadcast Area

c/DE

### Languages

deu

### NSFW

FALSE

### Logo

https://images.ctfassets.net/9wbsp34au6cz/308tScJyD09kbg5sb6uOfz/b36e1e25b04e44d72765369866b817fd/5bc9b3b6ef6a7379b57ae286_ServusTV_v3.png?w=350&q=90&fm=webp

### Notes

Separate channel to Servus TV (Austria). Think it used to be in database as ServusTVGermany.at and was in the German EPG but seems to have been removed.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/f1dcaf30f8f97ee7839d8abc9592caf3de1b5b5b
