### ISSUE TITLE
Edit: EnerGeek 1 & EnerGeek 3.

### ISSUE THREAD

**Issue by EnerGeekTeam** [iptv-org/database#1208]
### Channel ID (required)

EnerGeek1.cl & EnerGeek3.cl

### Channel Name

1. EnerGeek Retro | 3. EnerGeek Animate

### Network

EnerGeek

### Owners

EnerGeek

### Country

CL

### Subdivision

CL-RM

### City

Recoleta

### Languages

Spanish

### Categories

animation;

### Launched

2021-08-15

### Website

https://www.energeek.cl

### Logo

Only 3. https://energeek.cl/uploads/logos/EGAnimate.png

### Notes

This covers 2 of our channels, EnerGeek1 now known as EnerGeek Retro and EnerGeek3 now known as EnerGeek Animate.

**Comment by freearhey** [comment]
Updated in https://github.com/iptv-org/database/commit/5b155bbe786f4abbaf83fe1057fbaf259c01b102
