### ISSUE TITLE
Edit: HOT HD

### ISSUE THREAD

**Issue by 666Griyo** [iptv-org/database#12183]
### Channel ID (required)

HOTHD.pt

### Channel Name

TV Anhuin

### Owners

Televisión central 

### Country

AC

### Subdivision

CN-AC

### City

Hfei

### Broadcast Area

c/CN;r/EUR

### Languages

es;eng

### Categories

AdultIPTV.net Anal

### NSFW

TRUE

### Launched

2010-07-28

### Closed

2024-05-31

### Replaced By

HOTHD.pt

### Website

https://iptv-org.github.io/

### Logo

https://github.com/ProPontifex/database.git

**Comment by BellezaEmporium** [comment]
Nice try.
