### ISSUE TITLE
Edit: DigitAlb Family

### ISSUE THREAD

**Issue by Hashimduss21** [iptv-org/database#12199]
### Channel ID (required)

DigitAlbFamily.al

### Channel Name

Hm

### Alternative Names

Hm

### Network

Hm

### Owners

Hm

### Subdivision

Hm

### City

Hm

### Broadcast Area

Hm

### Languages

Hm

### NSFW

None

### Launched

2024.08.06

### Closed

2029.04.04

### Replaced By

Hm

**Comment by PopeyeTheSai10r** [comment]
> Closed
> 2029.04.04

Is this accurate?
