### ISSUE TITLE
Add: Sky Serie

### ISSUE THREAD

**Issue by segtun-tovcup-kopkY0** [iptv-org/database#12193]
### Channel Name

Sky Serie 

### Alternative Names (optional)

Sky Serie HD

### Network (optional)

Sky Italia 

### Owners (optional)

Sky Group Limited

### Country

Italy

### Subdivision (optional)

IT-34

### City (optional)

Rome

### Broadcast Area

Italy

### Languages

ita

### Categories (optional)

Series

### NSFW

TRUE

### Launched (optional)

2021-07-01

### Website (optional)

https://www.sky.it/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Sky_Serie.svg/512px-Sky_Serie.svg.png

**Comment by PopeyeTheSai10r** [comment]
Change logo to `https://upload.wikimedia.org/wikipedia/commons/5/54/Sky_Serie.svg`

**Comment by segtun-tovcup-kopkY0** [comment]
I changed the logo

**Comment by BellezaEmporium** [comment]
> Change logo to `https://upload.wikimedia.org/wikipedia/commons/5/54/Sky_Serie.svg`

No SVG, only JPG images.

**Comment by segtun-tovcup-kopkY0** [comment]
I did change the logo. You’re happy now. And can you please add the channel to the database?

**Comment by segtun-tovcup-kopkY0** [comment]
Please can you add the channel to the database

**Comment by Alstruit** [comment]
https://iptv-org.github.io/channels/it/SkySerie ????
