### ISSUE TITLE
Add: GalaxiaTeVe Grupo Medios del Norte

### ISSUE THREAD

**Issue by grinfelds** [iptv-org/database#12229]
### Channel Name

GalaxiaTeVe

### Country

do

### City (optional)

Santiago de Los Caballeros

### Broadcast Area

c/<do>

### Languages

spa

### Categories (optional)

Varios

### NSFW

FALSE

### Website (optional)

https://grupomediosdelnorte.com/

### Logo

https://grupomediosdelnorte.com/iptv/galaxia.png

### Notes

https://streaming.grupomediosdelnorte.com:19360/galaxiateve/galaxiateve.m3u8

**Comment by Carlinhos027** [comment]
Already on database:
https://iptv-org.github.io/channels/do/GalaxiaTeVe

**Comment by grinfelds** [comment]
The transmission link is not correct, the current is https://streaming.grupomediosdelnorte.com:19360/galaxiateve/galaxiateve.m3u8
