### ISSUE TITLE
Add: Telecontacto Grupo Medios del Norte

### ISSUE THREAD

**Issue by grinfelds** [iptv-org/database#12228]
### Channel Name

Telecontacto

### Owners (optional)

Republica Dominicana

### Country

do

### City (optional)

Santiago de Los Caballeros

### Broadcast Area

c/<do>

### Languages

spa

### Categories (optional)

Varios

### NSFW

FALSE

### Replaced By (optional)

Telecontacto.do

### Website (optional)

https://grupomediosdelnorte.com/

### Logo

https://grupomediosdelnorte.com/iptv/telecontacto.png

### Notes

https://streaming.grupomediosdelnorte.com:19360/telecontacto/telecontacto.m3u8

**Comment by Carlinhos027** [comment]
Already on database:
https://iptv-org.github.io/channels/do/Telecontacto

**Comment by grinfelds** [comment]
The transmission link is not correct, the current  is https://streaming.grupomediosdelnorte.com:19360/telecontacto/telecontacto.m3u8
