### ISSUE TITLE
Add: ECOVision Grupo Medios del Norte

### ISSUE THREAD

**Issue by grinfelds** [iptv-org/database#12230]
### Channel Name

ECOVision

### Owners (optional)

Republica Dominicana

### Country

do

### City (optional)

Santiago de Los Caballeros

### Broadcast Area

c/<do>

### Languages

spa

### Categories (optional)

Varios

### NSFW

FALSE

### Website (optional)

https://grupomediosdelnorte.com/

### Logo

https://grupomediosdelnorte.com/iptv/ecovision.png

### Notes

https://streaming.grupomediosdelnorte.com:19360/ecovision/ecovision.m3u8

**Comment by Carlinhos027** [comment]
Already on database:
https://iptv-org.github.io/channels/do/Ecovision

**Comment by grinfelds** [comment]
The transmission link is not correct, the current  is https://streaming.grupomediosdelnorte.com:19360/ecovision/ecovision.m3u8
