### ISSUE TITLE
Add: TeveExitos Grupo Medios del Norte

### ISSUE THREAD

**Issue by grinfelds** [iptv-org/database#12231]
### Channel Name

TeveExitos

### Country

do

### City (optional)

Santiago de Los Caballeros

### Broadcast Area

c/<do>

### Languages

spa

### Categories (optional)

Varios

### NSFW

FALSE

### Website (optional)

https://grupomediosdelnorte.com/

### Logo

https://grupomediosdelnorte.com/iptv/tvexitos.png

### Notes

https://streaming.grupomediosdelnorte.com:19360/tvexitos/tvexitos.m3u8

**Comment by Carlinhos027** [comment]
Already on database:
https://iptv-org.github.io/channels/do/TVExitos

**Comment by grinfelds** [comment]
The transmission link is not correct, the current is https://streaming.grupomediosdelnorte.com:19360/tvexitos/tvexitos.m3u8

**Comment by BellezaEmporium** [comment]
Links need to be added on iptv-org/iptv
