### ISSUE TITLE
VB MEDIA TV

### ISSUE THREAD

**Issue by vbmediatv** [iptv-org/database#12284]
### Channel ID (required)

VBMediaTV.mx

### Channel Name

VB Media TV

### Network

VB MEDIA QUERETARO

### Owners

VB MEDIA QUERETARO

### Country

MX

### Subdivision

MX-QUE

### City

Santiago de Querétaro

### Broadcast Area

c/MX;s/MX-QUE

### Languages

spa

### Categories

entertainment

### NSFW

None

### Launched

2020-07-07

### Website

https://www.vbmedia.com.mx

### Logo

https://i.imgur.com/5qlVblr.png

### Notes

https://stream8.mexiserver.com:19360/vbmediatv-1/vbmediatv-1.m3u8

**Comment by ebravot** [comment]
El nombre del canal es VB MEDIA TV no Televisión de medios de comunicación de VB. La liga de la señal es https://stream8.mexiserver.com:19360/vbmediatv-1/vbmediatv-1.m3u8 , la otra liga que tienen corresponde a otro canal el cual no está bajo mi control ni conozco de quien sea propiedad. Gracias por la actualización del logo.  Además de este canal, tengo otro canal que me gustaría que se agregará, ¿cómo se hace este proceso? Gracias y saludos.
