### ISSUE TITLE
Add: Disney Junior Latin America

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#12347]
### Channel Name

Disney Junior Latin America

### Owners (optional)

Disney Media Networks Latin America

### Country

AR

### City (optional)

Pilar

### Broadcast Area

c/AR

### Languages

spa;eng

### Categories (optional)

animation;kids

### NSFW

FALSE

### Website (optional)

https://www.disneylatino.com/

### Logo

https://m.media-amazon.com/images/I/51Fw+rSLbmL.jpg

**Comment by Alstruit** [comment]
Incorrect logo. Addressed in #12453.
