### ISSUE TITLE
Add: Zan TV [AF] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#12351]
### Channel Name

Zan TV

### Alternative Names (optional)

تلویزیون زن

### Owners (optional)

Hamid Samar

### Country

AF

### City (optional)

Kabul

### Broadcast Area

c/AF

### Languages

prs;pus

### Categories (optional)

lifestyle

### NSFW

FALSE

### Website (optional)

https://www.zantvnetwork.com/

### Logo

https://i.imgur.com/28U99Xx.png

**Comment by km147** [comment]
There is no live stream that I can see on the website https://www.zantvnetwork.com/
