### ISSUE TITLE
Edit: ANIMESTATION (Argentina)

### ISSUE THREAD

**Issue by MattGames123** [iptv-org/database#12352]
### Channel ID (required)

ANIMESTATION.ar

### Channel Name

Animestation (Argentina)

### Network

Locomotion

### Country

Argentina

### Languages

spa

### Categories

animation

### NSFW

None

### Website

https://animestationtv.com/en-vivo.html

### Logo

https://web.archive.org/web/20240509182044if_/https://pbs.twimg.com/profile_images/1744338643957780480/24Kv02RD_400x400.jpg

**Comment by MattGames123** [comment]
add stream URL as https://ssh101-fl.bozztv.com/ssh101/livestreamingtv/tracks-v1a1/mono.m3u8

**Comment by Alstruit** [comment]
https://github.com/iptv-org/iptv/issues
