### ISSUE TITLE
Edit: FanDuel TV

### ISSUE THREAD

**Issue by Albertop1998** [iptv-org/database#12373]
### Channel ID (required)

FanDuelTV.us

### NSFW

None

### Logo

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw0NDQ0NDQ0NDQ0NDQ4NDQ0NDQ8NDQ0NFREXFhURFRUYHSgiGRolGxUWLTEhKCksLi4wFyszRDQsNygtLisBCgoKDg0OFRAQFSsdFR8rLSstKystLSsrLSstKystKy0tLS0tLS0rLS0rLS0rLSsrLSsrLSsrKysrLSsrKy0tLf/AABEIAOEA4QMBEQACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAABAgUABgcIBAP/xABCEAACAgECAgcFBAYIBwEAAAAAAQIDBAURBiEHEjFBUXGBEyJhkaEUMlKSIzNyc7HBQkNTYoKisuE0ZIOjs8LRFf/EABoBAQEBAAMBAAAAAAAAAAAAAAEABQIDBAb/xAArEQEAAgEDAwQBBAIDAAAAAAAAAQIDBBExBRIhE0FRYTIiQnGBI2IUFbH/2gAMAwEAAhEDEQA/AOSpG2z0hREFIQSBFFIQRBFJIgRBEFIUkQYISQgiiQKQhIQwUkkQIgiChREFEEkKZsIUJlNQiCkIJIiChBEEUkiBEEQUhSRBghJCCKJApCEhDBSSIEQRBQoiCiCSFEQwgoTLahQgkiIKEEQRSSIEQRBSFJEGCEkhBFEgUhBFEQkiBEEQUKIgogkhREFCDsSUCMtpkkRBSEEQRSSRAiCIKQpIgRBQgiiQKQgiiISRAiCIKQoiCiCSQoiDsIKIEUoDKaZFFIQRBEJIkRBEFIQkSYISQgiiQKQhIQwUkkQIgiCkKIgogkhREHYQUQIgilAZTUKQgiCSSQgoQRBQpJEGCEkIIokCkISFMEJJECIIgpCiIKIJIURBEFCCQIoilAjKaZEEkkkIKEEQUKSRAiCkITqrlOXVhGU5PsjCLlJ+iCbRHMmKzPC7wuDdXvSdWnZTT7HZX7Bf9xo6ranFXmzsjDefZdY3RZrU171NNPwtyK3t+TrHVOvwx9ucaW8vtr6IdVf3rcKP/Vtf8IHH/scfxJ/4l1Fxbwdk6QqXk248/buagqZzcl1dt21KK5c1zO/T6mM28RDpy4Zx8y+HQeH8zUZ2V4dPtpVQ68/fhWopvZc5NLd+B25c9MURNp2cKYrX/GH25fBOsUJuzT8jZdvs1G//AMbZwrq8NuLOVtPkj2Ut9E6pdW2E6pfhshKEvkz0VtW3E7umazHMIJHNxIgoQkiREFCCIJAikkhDNhSgMppkUkkQIgiChCSRJ+lFM7JxrrhOyyT2jXXGU5yfgormym0RG8yYiZnw3vQOijU8pKeR1MGt8/0v6S5r93F8vVo8eTXUr4r5d9NNaefDoOjdFOk4+zujbmTXPe+fVr3/AGIbJrz3PDfW5bceHprpqRz5bhg6bjY0VHHopoiu6quNa+iPNa9rcy7orEcQ+o4uRJBknnbpI1z7fqd8ovenHbxqfDqwb60/WW/psfQaLF6eON+ZZGpyd9/4dZ6LNC+w6ZXOcdr8vbJt3XNRkv0cPSO3LxbMrW5fUyztxHh79Pj7afy3A8j0PxysOm6LjdVXbF9sbIRmvkxi0xxLjNYnmGqav0aaTk7uFM8Sb/pY0+qvyPePyR68euzU994+3RfS47e2zRNc6Kc6jeeJZDMgt31P1N6Xk3s/mvI0MXUqT4vGzx5NFaPNZ3aNlYttFjquqspsj212wlXNfHZmlS9bxvWd4eO1ZrO0w/M5uBEEQSBFJJCCIYSUBltRJECIIgoQkhTc+jrgf/8AZnbOy904+PKEbFCKdtkpJvqxb5R7O3Z+R49VqZxbREeZd+HD3+Z4dx0DhvB06HUxMeFW62lZ962fxlN82ZOTLbJO9pe+tK14hbnW5sJMJMJMJKHjjWPsGmZWRF7WKv2dP76fuxfo3v6Hdp8fqZK1dWa/ZSZcG4L0f7fqOLitb1ufXu+FMPelv57bf4je1OT08Uyy8NO+8Q9LRW2yXJLuPm2ySTCTCTCT4NX0fFza/Z5VELo93WXvRfjGXbF+Rzx5b453rOzhfHW8bTDj/SBwJDTILKx7pTx52Kt1Wc7K5NNraS+8uXhv5m5otbOWey0eWXqdLGOO6OGjGm8JFxIpJIQRBFMIKFGU1CIIgpCkiDBDsXQHZ+j1GHf7THn84zX8jK6jH6qy9+knxLrJnPWwkGSUWr8Y6XhNxyMylTXbVB+1t/LHdo7qafJfirqtmpXmWo6h0xYcd1jYmRe12OyUKIS/1P6Hqr07JPMxDotrKxxCjyemHNl+qw8av9udl38OqeiOmV97OqdbPtDWuJuNs/Va4U5PsY1Qs9ooU1ygnPZpNtye/Jv5nqwaSmKd45efLqLZI2l8XDXEGRpd8sjGVTslVKlq6DnHqOUZPbZpp7xXedmbBXNXtlxx5ZxzvDcsbpfzl+txMWz9h2VfzkeOel09rS9Ea63vC7wOmDGlssnCvqfe6bIXxXx59VnRfpl/223dtddX3htelcb6Vl7KrMrjN9ld29E2/BKW2/oeTJpctOavRXUY7cS2BPfmjzu1Iiwk0DpnntptUfxZdf0hNml0uP8AN/Txa6f8bi59CxiISSEEQRRSIEUoDKaZEFIUkQYISQh1DoHyNsvOq/tMeuxL9ibT/wBZm9Rr4rL2aSfMw7SZT3sJOI9MOq50NReL9pujiyoqthTCbrg1LeMut1fvc4vt3NjQY6TTu28s7VXtFtt/DnKW3ZyNLZ4plJIQRBEFCiIKIHYU3Ho21PNjqWHjVZNyossaspc3Kp1xhKT2i91Hs7Vszwa7Fj9K1u3y9elyX74rv4d7Pnmwwk5l03X7U4NXfK62z8sFH/3NbpNd72n6Z3UJ/TEOTG8yUkhBEEUUiBEEkoDLaZSFJEGCEkhBFNz6I8z2OtY8X2ZFd2O35wc19YL5nj11d8Uz8PRpZ2u9CGG0ySch6dcBqeBlJcnG3Hm/itpwX+v5Gr0235VeDW14lyyEW2opNyb2UUt238F3mtMxHLwREzw2LS+BtXyknXg2wg/6d+2OtvHaez28kea+sxU5tv8Aw7a6fJb2bFR0R5/Uc7srFq6sXJpe0taSW/gjzz1Km+0Vl3f8K228y56u404eKScnEogkhREN/wChrBdmo23te7j40vSyySUfopmZ1S+2OK/Mvdoa73mfh2swWsCTjXTNl9fUKKV2UYqk/hOyb3XyjH5m90mm2O1vmWR1C294hoKRrs6SIIopECIIgilAkZTUSIMEJIQRRIPt0bNeLlY2Sv6i+q17d8YyTa9Vv8zhlr3UtHy5UttaJep65qUYyi94ySkn4prdM+anx4bMJkVPxRw7j6pRHHyeuoRthcnW1GalHdbbtPk02n5nbizWxW7q8uvJji8bSnovDmBgRSxcaqp7bOe3Wtl5ze7fzC+a9/yndVxVrxC02Ot2Kni3JdOm59q5OGHkOP7Xs3t9djtw17slY+3Xlnaky80JH1TBkogkkKIgiHbOh7S/YafPIktp5drkv3UPdj9es/U+d6ll7su3w2NFTtpv8t9M97QyTzvxpn/atTzbk94+2dcPDqVpQW35d/U+r0WPsw1h89qb92SZUp63nIgpEiIIhJIQwkoTKajBCSEEUSBQhIU9EdF+rfbNIxm3vZj74tvPdp1/d384OD9T57V4+zLP21tPfupDbDzO9hJhJhJq/SZb1NGzn+KEIfmsjH+Z6dHG+aro1M7Y7PPR9Mw0kKIgoQ+rTcGzKvpxqv1l9ka496Tb+8/glz9Dry5Ix0m08Q5UpNrRD0vp+HDHoqorW1dNcKoL+7FbI+TvabWm08y+hrXtiIfQcXJUcV6osLAysndKVdUlXv32y92C/M0d2nx+pkrV1Z79lJl5z8+b72fXxG0bPnJncnJxKJEQRB2EJEmCFAZTUSSEEUSBSEJCmIQ6N0L617DNswpvavMj1q9+xXwTf1jv+VGb1HF3Vi/w9mkybT2u27mM0iSfllZNdNc7bZxrrri5znJ7RjFdrb8BiJmdoEzERvLQNa6WcGlyjiU25cl2Tf6CjfzfvP8AL6mhi6bkv5tO0PHfW1jjy0Pibj/O1KmeNZGinHm4ylCuMnN9WSkk5N+KXYkaOn0FMVotvvLx5dVbJG3s1Q9zykQRBSEOodDnD7crNSsj7sd6cbfvl/WTXl2L1MXqmo4xR/bT0GL98usGM0xuSct6ZdZ/4fT4P/mb9vVVxf8AmfojZ6Th3mck/wAMvqGXikOYG6yikIIgiDsISJEQzYUoUjKaZFEgUISFMEJIg/bEyJ0213VS6tlVkLa5eE4tNP5oL0i0TE8Sa2msxMPTPDur15+HRl19lsE5R74WLlKD8mmfM5cc47zWW3jv31iVmdbm/O6qNkZQnFShOLjKMlupRa2aZRO3kTG8PO/G/Dc9LzZ07N49m9mLN8+tVv8Adb8Yvk/R959Lo9RGan3HLF1GL07fSgPW85EEQUIWnDmi26jlVYtW6673sntyqqX3pvyXZ4tpHRqM8YaTaXbhxTktEQ9F6dg14tFWPTHq1UwUIR+C8fifK3vN7TaeZb9KxWIiH0nFyfPn5dePTbfbLq11QlZOT7opbnKlZtaKxzLje0ViZl5y1rUp5uVflWfeusctvwx7Ix9IpL0Pr9PhjFjikez5zLk9S82fGdzqIgiChCRIiChB2FKAymoSBQgiiISSIEQUMB0Poh4m+y5LwLpbUZck6W3yryezb/Etl5peJm9Q0/dX1I5jl7dJl2ntnh20xGowko+MOHKtUxJ489o2L36Ldt3Valyfk+xrwfkd+nzzhv3Q6c2KMldnnrUcC7Fusx74Ou2qXVnF/Rp96a5p/E+mxZK5KxavDEvSaTtL5ztdZSEP1opnZOFdcJTsnJQhCK3lKT5JJHG9orEzPEGtZtO0O9cBcKx0vG9/aWVdtLImuaj4Vxfgvq934bfM6zUznv8A6xw3NNg9Ov3LaTyPSwk5Z0u8R79XTKZdjjZltP1hU/o35I2ul6befVt/TL1+f9kf25jsbrJIgiChCRIiChBEEkoDKahSEEQRSSRAiCIKFJJ7c1umuaaezT8UymN/Hst9vLv3RzxWtTxepa19sx1GN67HZHsjal8dufg/Q+c1mmnDfx+M8NjT5vUr9tvPI9IZJqHSHwjVqOPK6CUMzHrlKqxL9ZFJv2Uvg+ez7m/NHs0eqtivt+2Xl1OCMld/dwdH00MSX6VVSnKMIRlOc2oxjFbylJ8kku9la0VjeeFETM7Q7V0ecELAisrKSlmzj7seTjjQa+6n3ya7X6efzut1s5Z7a/j/AOtjS6WMcd1uW8me9pJKDjLiOGmYkrXtK6e8Met/07Nu1/3V2v8A3PTpdPOfJFY493n1GaMVN/dwG+6ds522Sc7LJynOb7ZTb3bfqfWUpFKxWI8Q+ftabTvPKBzcCIKEJEiIKEEQSREKBIymokIYKSRAiCIKFEQUQWOhatdgZNeVjvayt9j+7ZB/ehL4P/fuOvNhrlpNbOzHkmlt4ehuGteo1LGhk0Pt92yttdemzvhL/wC965nzObDbFbts2sWWMld4Wx1O0Nb8u5kJeZNVw/s2TkUf2N9tXpGTS+mx9dgv3Y62fO5a9t5h2Xo64QxsSinMbV+TfTCxW7e7VCcU+rX6PnLtfwXIwNbq75bTXisezX0unrSsW5mW7I8D2Ek+LVtTpw6LMjIn1K61u33yfdGK72/A548dslorWN5lwyZK0rvPDgXE+vXanlSyLfdj92mrfeNVe/KPn4vvPq9Lpq4Kdsc+8vn8+ectt54VJ6nnIhJCCSIgoQRBJFCCKUJlNNgpJECIIgoURBRBJCiIXXCvEV+l5KvpfWhLaN9Le0Lq/B+DXc+7ybT8+p01c1dp5d2HNOO28O+6DrePqGPHIxp9aMuUovlOuffCa7n/AB7eaPmsuG2K3baPLax5a5I3hZHW7HCulTA9hq1s0to5Ndd68N9upL6w+p9J0y/dh2+GJra9uTf5dI6LtQ+0aTRFv3sdyx5fBRe8f8riZHUMfZnt9+Wjo792KPptx4nqfJqeo04lM8jIsVdVa3lJ/RJd7fckc8eO2S0VrHlwvkrSN5nw4XxlxVdqt3WfWrxq2/YUb9n9+e3bN/TsXfv9PotHGCv+0+7C1OpnLP0149zyEQkhBJEQUIKFEgUISQhgpQGU1EkQIgiChREFEEkKIgoQUQW3DuvZOm3q/GntvsrKpc67ofhkv4PtR0ajT0zV2ty7cOa2Od4dz4U4rxdUr3ql1Lope1x5te0rfivxR+K+j5Hzmo0t8M/qjx8trDnrljxy1bpn0zr42NmRXOiyVU/3dm2zflKK/Me7pOTa80+Xl6hTesW+FT0M6n7PJyMOT92+tXV+HtIcpLzcZf5Dv6ti3rW8e3h1dPyeZq6PxFxDjabS7cieze/s6o7O22XhFfz7EZGDT3zW7aw0cuauKN7OI8U8T5OqXde19SqDfsceL9yteL/FL4/wPptLo6aePHm3ywtRqLZZ88KQ9jzEQkkIJIiChBQokChCWwgimbEFCjKahEEQUhREFEEkhREHYQUQIgin74mTbRZG2mydVkHvCyD6sos43x1vXttG8Gt5rO8TtLoNHH9Wdg5GDqsepOymUYZNUHKMppbxcoL7st0ua5eRk26fbFki+LzG/D3xrIvSa5GiaZn24l9eRRLqXVPrQeyaTaaaa71s38zWyYq5azW3EvBS80tFoOo59+VbK/ItlbbLtlJ9i8EuxL4IcWGmKvbSNoGTJa872l852usiEkhBJEQUIKFEgUIS2EEUUiBEKAymoRBSFEQUQSQoiDsIKIEQRSSQgiCKJAiCIOwhIkRBQgoQSRSEJbCCKKQgkCIUBlNQpCiIKIJIURB2EFECIIpJIQRBEFIkRBEHYQkSIgoQUIJIpCEkIIopCCQIg7ElAjLahEFEEkKIgoQUQIgikkhBEEUUiBEEQUISJEQUIKEEkUhCSEEUUhBIEUdhBIKAy2oUQSQoiChB2IEQRSSQgiCKKRAiCIKEJEiIKEEQSRQhJCCKKQgkCKKEJCGEFAjKaiSFEQUIOxAiCKSSEEQRRSIEQRBQhIkRBQgiCSKEJIQRRSEEgRRQhJCCQZsKUKMpqEQUIOxAoQRSSQgiCKKRAiCISQgkiIKEEQSRSEJIQRB2JEQRSSEEQSBSEEUoEZTUJAoVJEEQUIKEEkRCQok4lCihBEFCkkIJAiChREFEEhBQoogRBEFCkkIYQf/Z

**Comment by Dum4G** [comment]
Post 512x512 (or less) image to imgur and share a direct link to the image
