### ISSUE TITLE
Add: La Que Buena Atlanta

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#12381]
### Channel Name

La Que Buena Atlanta

### Owners (optional)

WAZX-FM

### Country

US

### Subdivision (optional)

US-GA

### City (optional)

Duluth

### Broadcast Area

c/US

### Languages

spa

### Categories (optional)

culture

### NSFW

FALSE

### Website (optional)

https://laquebuenaatlanta.com/

### Logo

https://play-lh.googleusercontent.com/0r0s-s709ejCCQqBq455djdJRhzKty2hBIdOtAreNOllm9HkJLJynefhY-Xk0BqIbRY

**Comment by Dum4G** [comment]
https://iptv-org.github.io/channels/us/LaQueBuenaAtlanta
