### ISSUE TITLE
Add: TLC (France)

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/database#12425]
### Channel Name

The Learning Channel France
 

### Owners (optional)

Warner Bros. Discovery

### Country

FR

### Broadcast Area

c/FR

### Languages

fra

### Categories (optional)

entertainment

### NSFW

FALSE

### Launched (optional)

2024-02-26

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/TLC_logo_%282023%29.svg/640px-TLC_logo_%282023%29.svg.png

**Comment by Dum4G** [comment]
That will conflict with https://iptv-org.github.io/channels/fr/TLC tho

**Comment by BellezaEmporium** [comment]
Maybe by adding what's the initials of TLC, we'll make the difference.

**Comment by Dum4G** [comment]
TLCTheLearningChannelFrance.fr: "name" with value "TLC (The Learning Channel) France" fails to match the required pattern: /^[a-z0-9-!:&.+'/»#%°$@?|¡–\s_—]+$/i

Maybe call it just The Learning Channel France?

**Comment by Dum4G** [comment]
@BellezaEmporium
