### ISSUE TITLE
Add: Pluto TV Frasier (CA)

### ISSUE THREAD

**Issue by nabeelr** [iptv-org/database#12440]
### Channel Name

Frasier

### Network (optional)

Pluto TV

### Country

CA

### Broadcast Area

c/CA

### Languages

eng

### NSFW

FALSE

### Logo

https://images.pluto.tv/channels/62f4f90e39183b000769f12b/colorLogoPNG.png

**Comment by BellezaEmporium** [comment]
Same changes from the US version applied in the CA version.
