### ISSUE TITLE
Cartoon Network West (1080p) keeps constantly glitching

### ISSUE THREAD

**Issue by nikcec** [iptv-org/database#12469]
The stream keeps going backwards, and the frames freeze while the audio repeats itself. Please make sure this isn't happening to the Eastern channel.

**Comment by nikcec** [comment]
I am not lying. I am not a troll. The Cartoon Network West stream keeps glitching out, and I can prove it by sending a recording of the livestream.

**Comment by Alstruit** [comment]
This is for database not for streams.
Make an issue here: https://github.com/iptv-org/iptv/issues

**Comment by nikcec** [comment]
I have mistaken a m3u8 link from InsolenceTvGo for an IPTV.org m3u8 link. Sorry for the misunderstanding. I realized that this Github code didn't have a CN West stream in the first place. I will make a channel request instead.
