### ISSUE TITLE
Add: Cartoon Network West (1080p)

### ISSUE THREAD

**Issue by nikcec** [iptv-org/database#12470]
### Channel Name

Cartoon Network West (1080p)

### Alternative Names (optional)

Cartoon Network Pacific (1080p)

### Country

eng;spa

### Broadcast Area

AG;AI;AR;AW;BB;BL;BM;BO;BR;BS;BV;BZ;CA;CL;CO;CR;CU;CW;DM;DO;EC;FK;GD;GF;GL;GP;GS;GT;GY;HN;HT;JM;KN;KY;LC;MF;MQ;MS;MX;NI;PA;PE;PM;PR;PY;SR;SV;SX;TC;TT;US;UY;VC;VE;VG;VI

### Languages

eng

### Categories (optional)

animation,kids,

### NSFW

FALSE

### Logo

http://supersonictv.live:8080/242306/210404/21794

**Comment by Alstruit** [comment]
https://iptv-org.github.io/channels/us/CartoonNetworkWest
