### ISSUE TITLE
Add: Gold TV Sat

### ISSUE THREAD

**Issue by infid0** [iptv-org/database#1248]
### Channel Name

Gold Tivù Sat

### Country

IT

### Broadcast Area

IT

### Languages

ITA

### NSFW

FALSE

### Website (optional)

https://www.grupposciscione.it/gold-tv-sat/

### Logo

https://i.imgur.com/hdnOcr1.png

### Notes

`GoldTVSat.it`

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/a1f6ed8e6e0bd5da125b4c78b736a246e33caccc
