### ISSUE TITLE
Add: PACTV Prime

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#1249]
### Channel Name

PACTV Prime

### Country

US

### Subdivision (optional)

US-MA

### City (optional)

Duxbury

### Broadcast Area

s/US-MA

### Languages

eng

### Categories (optional)

legislative

### NSFW

FALSE

### Website (optional)

https://www.pactv.org/live

### Logo

https://pactv.secure.footprint.net/egress/bhandler/pactv/streama/playlist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=PACTV%20Prime
