### ISSUE TITLE
Some channels for Sweden

### ISSUE THREAD

**Issue by TertoGordez** [iptv-org/database#127]
Don't know how to add the right way, but here are some missing channels for sweden.
New channels for Sweden:

AnimalPlanetSverige.se,Animal Planet Sverige,,,SE,,,c/SE,swe,,FALSE,,,,,https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/2018_Animal_Planet_logo.svg/300px-2018_Animal_Planet_logo.svg.png

AxessTVSverige.se,Axess TV Sverige,,,SE,,,c/SE,swe,,FALSE,,,,,https://upload.wikimedia.org/wikipedia/commons/3/31/Axess_Television.svg

MTV80sSverige.se, MTV 80s Sverige,,,SE,,,c/SE,swe,,FALSE,,,,,https://upload.wikimedia.org/wikipedia/commons/5/5e/MTV_80s_%282020%29.png

DiscoverySienceSverige.se, Discovery Science Sverige,,,SE,,,c/SE,swe,,FALSE,,,,,https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Discovery_Science_2017_Logo.svg/1599px-Discovery_Science_2017_Logo.svg.png

**Comment by PopeyeTheSai10r** [comment]
Did you look at the[ Contributing Guide]( https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md)?

**Comment by freearhey** [comment]
`AxessTV.se` and `DiscoveryScienceSweden.se` added in https://github.com/iptv-org/database/commit/a8ffed0cf6bde0ae59f40eaf3885b56ebe43b128

As for `AnimalPlanetSweden.se` and `MTV80s.uk`, they are already in the database.
