### ISSUE TITLE
Add: PortuTV

### ISSUE THREAD

**Issue by ElvisGarces** [iptv-org/database#12749]
### Channel Name

Portuguesa Television

### Alternative Names (optional)

Portuguesa Televisión;PortuTV

### Country

VE

### Subdivision (optional)

VE-P

### City (optional)

Araure

### Broadcast Area

r/LATAM

### Languages

spa

### NSFW

FALSE

### Launched (optional)

2006-08-05

### Logo

https://intervenhosting.net/roku/portutv/portutv.jpg

### Notes

Más conocida como PortuTV, es un canal de televisión en señal abierta fundado en el año 2006, con sede en la ciudad de Araure, estado Portuguesa en Venezuela.

**Comment by Dum4G** [comment]
@ElvisGarces please specify what language did you mean by la with 3letter code from this list
https://github.com/iptv-org/database/blob/master/data/languages.csv
