### ISSUE TITLE
Add: BRICS Africa Channel

### ISSUE THREAD

**Issue by telanus** [iptv-org/database#12796]
### Channel Name

TV BRICS Africa

### Country

ZA

### Broadcast Area

r/AFR

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Logo

https://admango.cdn.mangomolo.com/analytics/uploads/188/666abcee75.jpeg

**Comment by Dum4G** [comment]
Are you sure it's not South African channel?

**Comment by telanus** [comment]
> Are you sure it's not South African channel?

It's broadcast on StarSat, and according to them "StarSat is a South African direct broadcast satellite " and is also available here: https://freevisionplay.co.za/live/394/BRICS-Africa-Channel.
