### ISSUE TITLE
Edit: Ciné+ Famiz

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/database#12835]
### Channel ID (required)

CinePlusFamiz.fr

### Channel Name

Cine+ Family

### Alternative Names

Ciné+ Family; Ciné+ family; Ciné+ Famiz; CinéCinéma Famiz; CinéCinéma Succès

### NSFW

None

### Website

https://www.canalplus.com/chaines/cine-plus-ocs/

### Logo

https://i.imgur.com/BR6m2yX.jpeg

**Comment by Alstruit** [comment]
5428   CinePlusFamily.fr: "alt_names[2]" with value " Ciné+ Famiz, Ciné + Famiz, CinéCinéma Famiz, CinéCinéma Succès" fails to match the required pattern: /^[^",]+$/

**Comment by BellezaEmporium** [comment]
See if this works.
