### ISSUE TITLE
Streaming Links (m3u8 links)

### ISSUE THREAD

**Issue by elyashivhazan** [iptv-org/database#129]
Hi, I have notice some links that need to be changed at [iptv-org/iptv](https://github.com/iptv-org/iptv). Where are they stored?

**Comment by freearhey** [comment]
Links to broadcasts are stored in the same repository in the [/streams](https://github.com/iptv-org/iptv/tree/master/streams) folder.

**Comment by elyashivhazan** [comment]
Hi, thanks for the response. I mean where are they generated from (where is the src)
