### ISSUE TITLE
Edit: ADN HD

### ISSUE THREAD

**Issue by Azkajinan12345** [iptv-org/database#12904]
### Channel ID (required)

ADNHD.al

### Country

Indonesia

### City

Makassar

### Languages

Indonesia

### Categories

Animation

### NSFW

TRUE

**Comment by BellezaEmporium** [comment]
https://www.facebook.com/p/ADN-HD-Albania-100095363627325/?paipv=0&eav=Afb51i5k-oqftimr_PwDHn5UhF20D_srJdEQn84uDTV1IpsBwRQcbjV1hS43ffz3etA&_rdr
