### ISSUE TITLE
Edit: Nickelodeon CIS

### ISSUE THREAD

**Issue by reactxge** [iptv-org/database#12948]
### Channel ID (required)

NickelodeonCIS.ru

### Channel Name

NICKELODEON CIS

### Alternative Names

Nick CiS

### Network

Viacom

### Owners

Paramount

### Country

RU

### Languages

ru,us

### Categories

kids

### NSFW

None

### Website

http://nickhd.rf.gd

### Logo

https://imgur.com/w8iE8dV

**Comment by BellezaEmporium** [comment]
Unofficial website.

**Comment by Alstruit** [comment]
Closing as stale.
