### ISSUE TITLE
Add: Marlborough Access

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#1299]
### Channel Name

Marlborough Access

### Country

US

### Subdivision (optional)

US-MA

### City (optional)

Marlborough

### Broadcast Area

s/US-MA

### Languages

eng

### Categories (optional)

community

### NSFW

FALSE

### Website (optional)

https://www.wmct-tv.com/public

### Logo

https://static.wixstatic.com/media/2a5cb9_4d3e16a6505040bb94ca9f44929c9e9c~mv2.png/v1/fill/w_229,h_115,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/png-transparent-backgroung.png

### Notes

Streaming URL:

https://watch.wmct-tv.com/live-5/live/WIFI-1096k-360p/WIFI-1096k-360p.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/commit/a87fd737a7a5ae8a58709cc7fc5bb14210e0c672
