### ISSUE TITLE
Add: Masha y El Oso

### ISSUE THREAD

**Issue by rawde90** [iptv-org/database#13012]
### Channel Name

Masha y el Oso

### Owners (optional)

Animaccord LTD

### Country

CY

### City (optional)

Limassol

### Broadcast Area

c/CY

### Languages

spa

### Categories (optional)

kids

### NSFW

FALSE

### Website (optional)

https://www.mashabear.com/

### Logo

https://i.imgur.com/YB2LEk4.png

**Comment by BellezaEmporium** [comment]
SVG files aren't allowed as images.
- You're showing the English version of that logo while the Spanish one also exists at es.svg

**Comment by rawde90** [comment]
Logo url changed
