### ISSUE TITLE
Add: Cartoon Network Animations 

### ISSUE THREAD

**Issue by segtun-tovcup-kopkY0** [iptv-org/database#13090]
### Channel Name

Cartoon Network Animations 

### Alternative Names (optional)

Cartoon Network Adventure Time 

### Network (optional)

Lollipop TV Corp

### Owners (optional)

Lollipop TV Corp

### Country

UK

### Subdivision (optional)

GB-ENG

### City (optional)

London

### Broadcast Area

UK

### Languages

English

### Categories (optional)

Kids

### NSFW

FALSE

### Launched (optional)

26th July 2023

### Logo

https://en.wikipedia.org/wiki/Cartoon_Network

### Notes

The channel was launched on the 26th July 2023

**Comment by BellezaEmporium** [comment]
"Lollipop TV Corp." ? It should be Warner Bros. Discovery Networks.

**Comment by segtun-tovcup-kopkY0** [comment]
No
