### ISSUE TITLE
ONDA DIGITAL 

### ISSUE THREAD

**Issue by GrupoOnda** [iptv-org/database#13246]
### Channel ID (required)

OndaDigital.pe

### Channel Name

ONDA DIGITAL 

### Alternative Names

Onda Digital HD

### Network

Grupo Onda

### Owners

Onda Grupo de Medios

### Country

PE

### City

Lima

### Broadcast Area

s/PE-LIM;s/PE-LAL

### NSFW

None

### Launched

2017-09-15

### Website

https://www.OndaDigital.pe

### Notes

ISDB-T Digital AirStation HD Television

**Comment by BellezaEmporium** [comment]
Thank you for editing your channel in our database. One little remark : naming citites in the "broadcast area" isn't the right way to proceed. If it's specific cities, you can use the [subdivisions CSV file](https://github.com/iptv-org/database/blob/master/data/subdivisions.csv).

Changed : 
- Lima to PE-LIM (Lima region)
- Huaura to PE-LIM (the province is in the region of Lima)
- Trujillo to PE-LAL (Trujillo is the chief-city of the La Libertad region)

**Comment by GrupoOnda** [comment]
Hello,

We have three TV Channels in different cities each.:  Lima,  Trujillo  and  Huaura.

Although Lima, and Huaura are in the same region, they are far apart, and the coverage is only in the metropolitan area of each.

The main city is Lima

How do we publish this?

Thanks.

 



 

De: Ismaël Moret ***@***.***> 
Enviado el: domingo, 18 de agosto de 2024 17:28
Para: iptv-org/database ***@***.***>
CC: GrupoOnda ***@***.***>; Author ***@***.***>
Asunto: Re: [iptv-org/database] ONDA DIGITAL (Issue #13246)

 

Thank you for editing your channel in our database. One little remark : naming citites in the "broadcast area" isn't the right way to proceed. If it's specific cities, you can use the subdivisions CSV file <https://github.com/iptv-org/database/blob/master/data/subdivisions.csv> .

Changed :

*         Lima to PE-LIM (Lima region)

*         Huaura to PE-LIM (the province is in the region of Lima)

*         Trujillo to PE-LAL (Trujillo is the chief-city of the La Libertad region)

**Comment by BellezaEmporium** [comment]
> Hello, We have three TV Channels in different cities each.: Lima, Trujillo and Huaura. Although Lima, and Huaura are in the same region, they are far apart, and the coverage is only in the metropolitan area of each. The main city is Lima How do we publish this? Thanks. De: Ismaël Moret ***@***.***> Enviado el: domingo, 18 de agosto de 2024 17:28 Para: iptv-org/database ***@***.***> CC: GrupoOnda ***@***.***>; Author ***@***.***> Asunto: Re: [iptv-org/database] ONDA DIGITAL (Issue #13246) Thank you for editing your channel in our database. One little remark : naming citites in the "broadcast area" isn't the right way to proceed. If it's specific cities, you can use the subdivisions CSV file <https://github.com/iptv-org/database/blob/master/data/subdivisions.csv> . Changed : * Lima to PE-LIM (Lima region) * Huaura to PE-LIM (the province is in the region of Lima) * Trujillo to PE-LAL (Trujillo is the chief-city of the La Libertad region)  >

Since it's quite specific, it's a bit difficult to properly target. We do not accept providing cities as a broadcast area (for now). This would need further discussion with our team to see what solution we can give.
