### ISSUE TITLE
Edit: A2Z

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#13356]
### Channel ID (required)

A2Z.ph

### Channel Name

A2Z

### Network

Zoe TV

### Owners

Zoe Broadcating Network

### Country

Philippines

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Philippines

### Languages

tag;eng

### Categories

entertainment;current affairs

### NSFW

None

### Logo

https://i.imgur.com/1zsdloF.png

**Comment by Margoux-bit** [comment]
https://m3u.ch/pl/0832ddc3f00b6517e0f8510ce3cf6930_bf5d1d5e7a4840262d2a40a414e5d635.m3u?fbclid=IwY2xjawE9JRFleHRuA2FlbQIxMQABHaKmip5c7oR5_lW6z8VCr0gpmF6xcG134e8Pg7gst8L01Mnz5YZCW9yDCw_aem_YxrG2PY7kU1uTelSztyO1w

**Comment by BellezaEmporium** [comment]
Few things : 

- Current affairs isn't a category we've got in our database
- ZOE owns part of it. ABS-CBN owns the other part via Kapamilya Channel (see https://en.wikipedia.org/wiki/A2Z_(TV_channel), or https://id.wikipedia.org/wiki/A2Z_(saluran_televisi_Filipina))
