### ISSUE TITLE
Edit: BBC News Channels

### ISSUE THREAD

**Issue by fdezwonders** [iptv-org/database#13365]
### Channel ID (required)

BBCNews.uk

### Channel Name

BBC News

### Notes

There are now 2 BBC channels: United Kingdom and International (World). The links listed [here](https://iptv-org.github.io/channels/uk/BBCNews) are for the UK channel. The link for the International channel is on [BBC News North America](https://iptv-org.github.io/channels/uk/BBCNewsNorthAmerica) and [BBC News Asia Pacific](https://iptv-org.github.io/channels/uk/BBCNewsAsiaPacific) (a way to tell is that the UK feed has a the time at the bottom, while the world feed doesn't). I recommend deleting the other channels except BBC News UK and BBC News Arabic, and instead make one "BBC News (International)".

**Comment by Alstruit** [comment]
It would seem so, however some of the feeds include corresponding weather infomation  and bumper idents that relate to their respective location.

**Comment by fdezwonders** [comment]
@Alstruit Well, only for BBC News Asia Pacific, the North America feed is taken from Xumo and thus does not have any commercial breaks.
