### ISSUE TITLE
Remove: KZTV-DT2

### ISSUE THREAD

**Issue by fdezwonders** [iptv-org/database#13378]
### Channel ID (required)

KZTVDT2.us

### Reason (required)

Duplicate

### Notes

KZTV-DT2 is a simulcast of TelemundoCorpusChristi.us.

**Comment by BellezaEmporium** [comment]
I invoke @Dum4G and @Alstruit on this one.

In my opinion, keeping the station ID in our playlists pinpoints the origin streams a lot better. "TelemundoCorpusChristi.us" just doesn't mean a lot for a neophyte user. However, having the 'top-of-the-hour' identification in a US TV stream show up tells us way more information;

**Comment by fdezwonders** [comment]
@BellezaEmporium The top-of-the-hour ID for Telemundo Corpus Christi is just "You're watching Telemundo Corpus Christi: In your neighborhood." Their main station is K22JA-D (known as KAJA on air). So...idk

**Comment by BellezaEmporium** [comment]
Returning on this : Telemundo CC is actually being aired from K22JA-D, an SSA has been signed between K22JA and KZTV to simulcast their channels. K22JA is owned by E.W. Scripps, KZTV is owned by SagamoreHill Broadcasting.

**Comment by fdezwonders** [comment]
@BellezaEmporium Yes it does, but then wouldn't we just put the stream on TelemundoCorpusChristi.us onto KZTV-DT2.us?

**Comment by BellezaEmporium** [comment]
Well, since the original stream is K22JA, I would just modify KZTV into K22JA

**Comment by BellezaEmporium** [comment]
(or modify Telemundo Corpus Christi into K22JA)
