### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by mabdallah2001** [iptv-org/database#1337]
### Channel Name

BeIN Sports

### Country

United Arab Emirates

### Broadcast Area

MENA

### Languages

Arabic, English

### NSFW

FALSE

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Bein_sport_logo.png/2560px-Bein_sport_logo.png

### Notes

It says its available on the database but i cannot find it on the actual IPTV channels.

**Comment by freearhey** [comment]
BeIN Sports is already in the database: https://iptv-org.github.io/?q=BeIN%20Sports
