### ISSUE TITLE
Add: Canal 6.1

### ISSUE THREAD

**Issue by Pecaquito** [iptv-org/database#13409]
### Channel Name

Canal 6.1

### Country

Dominican Republic

### Broadcast Area

Dominican Republic

### Languages

Spanish

### NSFW

FALSE

### Website (optional)

https://canaldelsol.com/

### Logo

https://imgur.com/odAD8rL

**Comment by Alstruit** [comment]
[CanaldelSol.do](https://iptv-org.github.io/?q=canaldelsol)?
