### ISSUE TITLE
Add: Hype Visual Radio

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#13426]
### Channel Name

Hype Visual Radio

### Country

NL

### City (optional)

The Hague

### Broadcast Area

c/NL

### Languages

nld;eng

### Categories (optional)

music

### NSFW

FALSE

### Website (optional)

https://www.hyperadio.nl/

### Logo

https://cdn.onlineradiobox.com/img/fblogo/1/97371.v21.png

**Comment by Alstruit** [comment]
10802  HypeVisualRadio.nl: "logo" with value "https://static.wixstatic.com/media/553064_c854539d025442abb90c70e72b1f9b4a~mv2.png/v1/fill/w_212,h_190,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/logonoline.png" matches the inverted pattern: /,/

**Comment by ProPontifex** [comment]
Fixed.
