### ISSUE TITLE
Add: WBS TV

### ISSUE THREAD

**Issue by 4savit** [iptv-org/database#1346]
### Channel Name

WBS TV

### Alternative Names (optional)

원음방송

### Country

KR

### Subdivision (optional)

KR-11

### Broadcast Area

KR/KR-11

### Languages

kor;korean

### Categories (optional)

Religious

### NSFW

FALSE

### Website (optional)

https://wbsi.kr/index_tv.php

### Logo

https://wbsi.kr/img/logo.png

### Notes

Stream address
SD - http://192.241.153.173/live/livestream.m3u8
HD - http://157.245.196.186/live/livestream.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added next release.
