### ISSUE TITLE
Add: Must Have Ideas (UK)

### ISSUE THREAD

**Issue by Hitsmix** [iptv-org/database#13468]
### Channel Name

Must Have Ideas

### Country

UK

### Broadcast Area

c/UK

### Languages

eng

### Categories (optional)

shop

### NSFW

FALSE

### Logo

https://cdn-img.widilo.co.uk/img/must-have-ideas-logo.png?v=638548256962670412

### Notes

YouTube link : https://www.youtube.com/live/bJuaGgMrK84?si=1ecI9a1Xblxh-pnC

**Comment by Alstruit** [comment]
Broadcast should be c/UK
