### ISSUE TITLE
Remove: BRTV Winter Olympics Documentary Channel

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/database#13519]
### Channel ID (required)

BRTVWinterOlympicsDocumentaryChannel.cn

### Reason (required)

Other

### Notes

This channel merged with Science Educational channel to form Documentary and Science Educational channel on 2022.9.21
videolink:https://www.bilibili.com/video/BV1oT411N77s/

**Comment by Alstruit** [comment]
Make an edit request stating the closure date instead of removing.
