### ISSUE TITLE
Add: RaiItaliaAustralia.it / RaiItaliaAmerica.it / RaiItaliaAsia.it

### ISSUE THREAD

**Issue by ylnest2018** [iptv-org/database#13537]
### Channel Name

RAI Italia Australia / America / Asia

### Alternative Names (optional)

RAI Italia 

### Network (optional)

RAI

### Owners (optional)

RAI

### Country

IT

### Subdivision (optional)

IT-AU / IT-AMER / IT-SEA

### Broadcast Area

c/IT; c/AU

### Languages

ita

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.raitalia.it/

### Logo

https://imgur.com/1nN4rEP

### Notes

These channels are listed in your channel CSV however only 
Rai Italia America & Rai Italia Asia are in their respective playlists (AMER/SEA) however they are not functioning. Rai Italia Australia and Africa cannot be found in any playlists.

**Comment by Alstruit** [comment]
Only one channel at a time.

**Comment by ylnest2018** [comment]
Issue was with multiple..oh well I have raised an individual request now https://github.com/iptv-org/database/issues/13722
