### ISSUE TITLE
Add: Televideo Regional

### ISSUE THREAD

**Issue by Hannaplus4** [iptv-org/database#1360]
### Channel Name

Televideo Regional

### Country

AR

### Subdivision (optional)

AR-S

### City (optional)

Villa Ocampo

### Broadcast Area

s/AR-S

### Languages

spa

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

http://www.televideoinforma.com.ar/

### Logo

https://scontent.faep16-1.fna.fbcdn.net/v/t39.30808-6/309545157_466164295534949_1588451033292838165_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=RbZzUONh_w0AX-BIQRt&_nc_ht=scontent.faep16-1.fna&oh=00_AfD5OPLuS9I_Fkv9Vd1jSlQzJLt1WMmlwByKyaWSkMo_0Q&oe=638B3AF0

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
