### ISSUE TITLE
Add: Benin TV

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#13630]
### Channel Name

Benin TV

### Alternative Names (optional)

SRTB

### Owners (optional)

Societe de Radio et de Television du Benin

### Country

BJ

### City (optional)

Cotonou

### Broadcast Area

c/BJ

### Languages

fra

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://srtb.bj/benintv/

### Logo

https://i0.wp.com/sesameinfo.bj/wp-content/uploads/2023/11/ortb-1.jpg?resize=512%2C470&ssl=1

**Comment by Carlinhos027** [comment]
Same channel as "ORTB.bj"

Maybe we should add "Benin TV" as an alternative name.

**Comment by ProPontifex** [comment]
Agreed: feel free to change; as for the Juniors, I'll close it.
