### ISSUE TITLE
Add: Benin TV Juniors

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#13631]
### Channel Name

Benin TV Juniors

### Alternative Names (optional)

SRTB Juniors

### Owners (optional)

Societe de Radio et de Television du Benin

### Country

BJ

### City (optional)

Cotonou

### Broadcast Area

c/BJ

### Languages

fra

### Categories (optional)

kids

### NSFW

FALSE

### Website (optional)

https://srtb.bj/

### Logo

https://kids.kiddle.co/images/thumb/c/c0/Junior_Logo_2015.png/300px-Junior_Logo_2015.png

**Comment by Carlinhos027** [comment]
I think is the same channel as "ADO TV", that is also a youth-oriented channel:
https://fr.wikipedia.org/wiki/ADO_TV

![Screenshot_20240923_084216](https://github.com/user-attachments/assets/d376ec00-458a-468c-a1d2-f31d8273cad0)
