### ISSUE TITLE
Add: RAI Italia Australia

### ISSUE THREAD

**Issue by ylnest2018** [iptv-org/database#13722]
### Channel Name

RAI Italia Australia

### Network (optional)

RAI

### Owners (optional)

RAI

### Country

IT

### Broadcast Area

c/IT;c/AU

### Languages

ita

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.raitalia.it/

### Logo

https://i.imgur.com/1nN4rEP.png

**Comment by ylnest2018** [comment]
How is this a duplicate?

**Comment by Dum4G** [comment]
https://iptv-org.github.io/channels/it/RaiItaliaAustralia

**Comment by Dum4G** [comment]
Would be found in every country that belongs to Oceania when there's a known stream link

**Comment by ylnest2018** [comment]
Doesn’t seem to be in any of the Oceania playlists or channel database, can you share a specific playlist that contains

**Comment by Dum4G** [comment]
I just shared a link to the database entry https://iptv-org.github.io/channels/it/RaiItaliaAustralia
You don't see it in any of the playlists because currently we don't have any know stream link for this channel
