### ISSUE TITLE
Add: Meissen Fernsehen [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#13736]
### Channel Name

Meissen Fernsehen

### Alternative Names (optional)

Meißen Fernsehen;tvM

### Country

DE

### City (optional)

Meißen

### Broadcast Area

c/DE

### Languages

deu

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.meissen-fernsehen.de/

### Logo

https://i.imgur.com/QDi9G5O.jpeg

**Comment by melchiades123** [comment]
Por favor parem de mandarem mensagem 

Yahoo Mail: Busque, organize e aumente sua produtividade 
 
  Em qui., 3 3e out. 3e 2024 às 10:51, ***@***.***> escreveu:   


Channel Name

Meissen Fernsehen

Alternative Names (optional)

Meißen Fernsehen;tvM

Network (optional)

No response

Owners (optional)

No response

Country

DE

Subdivision (optional)

No response

City (optional)

Meißen

Broadcast Area

c/DE

Languages

deu

Categories (optional)

general

NSFW

FALSE

Launched (optional)

No response

Closed (optional)

No response

Replaced By (optional)

No response

Website (optional)

https://www.meissen-fernsehen.de/

Logo

https://i.imgur.com/QDi9G5O.jpeg

Notes

No response

**Comment by melchiades123** [comment]
Yahoo Mail: Busque, organize e aumente sua produtividade
