### ISSUE TITLE
Edit: TVCG Sat

### ISSUE THREAD

**Issue by Smark223** [iptv-org/database#1418]
### Channel ID (required)

TVCGSat.me

### Channel Name

TVCG Mne

### NSFW

None

### Logo

https://cdn-0.tvprofil.com/img/kanali-logo/TVCG_MNE_ME_logo.png

### Notes

TVCG Sat is now called TVCG Mne

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/database/commit/22f47d38a02e2f9299e7250fd6907d326404ee05
