### ISSUE TITLE
Edit: Boing Spain

### ISSUE THREAD

**Issue by Smark223** [iptv-org/database#1419]
### Channel ID (required)

BoingSpain.it

### Channel Name

Boing Spain

### Country

ES

### Broadcast Area

c/ES

### Languages

spa

### NSFW

FALSE

### Website

www.boing.es

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Boing_2020.svg/300px-Boing_2020.svg.png

### Notes

Boing Spain is incorrectly categorised as an Italian channel. Please change tvg-id suffix to .es

EPG is available at https://www.movistarplus.es/programacion-tv but I will raise an issue in the EPG section if necessary.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/database/commit/75bfc4bd421c88a8df01ae9783a3ce7f391de0b3
