### ISSUE TITLE
Edit: ANC

### ISSUE THREAD

**Issue by BhongIvanCapsa** [iptv-org/database#14307]
### Channel ID (required)

ANC.ph

### Owners

Abs-Cbn News Channel

### Country

PH

### Subdivision

PH-MNL

### City

Quezon City

### Broadcast Area

ASIA

### Languages

eng

### Categories

News

### NSFW

None

**Comment by freearhey** [comment]
Please update your request:

- subdivision code is incorrect
- category id should be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
