### ISSUE TITLE
Add: SBS

### ISSUE THREAD

**Issue by hydrationn** [iptv-org/database#14343]
### Channel Name

SBS

### Owners (optional)

Seoul Broadcasting System

### Country

KR

### Subdivision (optional)

KR-11

### City (optional)

Seoul

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1991-12-09

### Website (optional)

https://www.sbs.co.kr/

### Logo

https://imgur.com/a/uHlt1Lv

### Notes

a private commercial broadcast of terrestrial TV and radio

**Comment by ProPontifex** [comment]
Will add in next update and thank you for the compliments.

**Comment by ProPontifex** [comment]
Well, it appears to be there already so colour me confused.

**Comment by hydrationn** [comment]
Oh, I checked that there is Korean. It's my mistake that I didn't see. I will do my best to contribute to this project. Thank you.

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/kr/SBSTV
