### ISSUE TITLE
	 DAZN1.es

### ISSUE THREAD

**Issue by papuxino** [iptv-org/database#14410]
### Channel Name

DAZN1.es

### Alternative Names (optional)

DAZN1

### Owners (optional)

Access Industries

### Country

Spain

### City (optional)

London

### Broadcast Area

Spain

### Languages

Spanish

### Categories (optional)

Sports

### NSFW

FALSE

### Launched (optional)

10 August 2016

### Website (optional)

https://www.dazn.com/es-ES/l/sports/

### Logo

https://i.imgur.com/alzVFEm.png

**Comment by BellezaEmporium** [comment]
https://iptv-org.github.io/channels/es/DAZN1
