### ISSUE TITLE
Edit: Playboy TV en Espanol

### ISSUE THREAD

**Issue by papuxino** [iptv-org/database#14412]
### Channel ID (required)

PlayboyTVenEspanol.us

### Channel Name

Playboy TV en Espanol

### Alternative Names

Playboy TV en Espanol

### Country

United States

### Broadcast Area

United States

### Languages

Spanish

### Categories

xxx

### NSFW

TRUE

### Website

http://www.playboytv.com/

**Comment by BellezaEmporium** [comment]
https://iptv-org.github.io/channels/us/PlayboyTVenEspanol
