### ISSUE TITLE
Edit: Mnet

### ISSUE THREAD

**Issue by hydrationn** [iptv-org/database#14418]
### Channel ID (required)

Mnet.kr

### Channel Name

Mnet

### Alternative Names

엠넷

### Owners

CJ ENM Entertainment Division

### Country

KR

### Subdivision

KR-11

### City

Seoul

### Broadcast Area

c/KR

### Languages

kor

### Categories

entertainment;music

### NSFW

FALSE

### Launched

1995-03-01

### Website

http://www.mnet.com/

### Logo

https://i.imgur.com/a/9Hnqzz9

### Notes

Mnet is a South Korean pay television music channel owned by CJ ENM. It primarily focuses on K-pop music and broadcasts various music-related programs such as survival shows, award ceremonies, and concerts.

**Comment by BellezaEmporium** [comment]
Considering that a PR was opened, this issue is unnecessary.
