### ISSUE TITLE
Add: All of Serbian Sport Klub Channels

### ISSUE THREAD

**Issue by ogipaki1** [iptv-org/database#14495]
### Channel Name

Sport Klub

### Country

RS

### Broadcast Area

c/RS;r/EUR

### Languages

srp

### Categories (optional)

sports

### NSFW

FALSE

### Website (optional)

https://sportklub.n1info.rs/

### Logo

https://i.imgur.com/W0XmUAm.png

**Comment by BellezaEmporium** [comment]
I suppose something was written under the "SK" logo, though it can't be seen. Please try to have a transparent version, or get another version of that same logo.

**Comment by ogipaki1** [comment]
Here's higher quality logo with the name:
![Sportklub_Logo svg](https://github.com/user-attachments/assets/ba602473-3ac0-4f2d-bde4-fdd4c87c61f0)

**Comment by BellezaEmporium** [comment]
Thank you. Modifying issue and approving it.
