### ISSUE TITLE
Edit: TVes (Venezuela)

### ISSUE THREAD

**Issue by Naruh1010** [iptv-org/database#14566]
### Channel ID (required)

TVes.ve

### NSFW

None

### Notes

change the links stream pls.

https://github.com/user-attachments/assets/ce3e78ab-ccba-4f7b-a68c-3542deb5049c

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-report-a-broken-stream
