### ISSUE TITLE
Add: Trumpet of Faith TV [UG]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#14581]
### Channel Name

Trumpet of Faith TV

### Owners (optional)

Apostle Dr. Jean Saflo

### Country

UG

### Broadcast Area

c/UG

### Languages

eng

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://trumpetnet.com/

### Logo

https://i.imgur.com/L7aP4ai.png

**Comment by Alstruit** [comment]
`TrumpetofFaithTV.ug: "owners[0]" with value "Apostle Dr. Jean Saflo," fails to match the required pattern: /^[^",]+$/`
