### ISSUE TITLE
Add: VCAL TV

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#14591]
### Channel Name

VCAL TV

### Country

VN

### City (optional)

Westminster

### Broadcast Area

c/VN

### Languages

vie

### Categories (optional)

news;culture

### NSFW

FALSE

### Website (optional)

https://www.vcal.tv/

### Logo

https://i.imgur.com/WmEcjaB.png

**Comment by BellezaEmporium** [comment]
Image changed.
