### ISSUE TITLE
Add: Verts Paturages TV [CD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#14624]
### Channel Name

Verts Paturages TV

### Alternative Names (optional)

Verts Pâturages TV

### Country

CD

### City (optional)

Kinshasa

### Broadcast Area

c/CD

### Languages

fra

### Categories (optional)

general

### NSFW

FALSE

### Logo

https://i.imgur.com/65qrSXD.jpeg

**Comment by freearhey** [comment]
Please update your request:

- alternative name should only be specified if it differs from the main name

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
