### ISSUE TITLE
Add: Atlantico Television [ES] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#14636]
### Channel Name

Atlantico Television 

### Alternative Names (optional)

Atlántico Televisión

### Owners (optional)

Grupo Plató del Atlántico

### Country

ES

### Subdivision (optional)

ES-CN

### City (optional)

Santa Cruz de Tenerife

### Broadcast Area

c/ES

### Languages

spa

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

2022-05-30

### Website (optional)

https://www.atlanticotelevision.com/

### Logo

https://i.imgur.com/JB5QkAw.png

**Comment by freearhey** [comment]
Please update your request:

- subdivision code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * subdivision code is incorrect
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed
