### ISSUE TITLE
Add: El Futuro en tu Mano [ES] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#14666]
### Channel Name

El Futuro en tu Mano

### Country

ES

### Subdivision (optional)

ES-MD

### Broadcast Area

c/ES

### Languages

spa

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://elfuturoentumano.com/

### Logo

https://i.imgur.com/17Oj173.jpeg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/es/ElFuturoentumano
