### ISSUE TITLE
Add: Canal 7 Punta del Este [UY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1467]
### Channel Name

Canal 7 Punta del Este 

### Owners (optional)

Grupo Clarín

### Country

UY

### Subdivision (optional)

UY-MA

### City (optional)

Punta del Este

### Broadcast Area

s/UY-MA

### Languages

spa

### NSFW

FALSE

### Website (optional)

https://www.canal7.com.uy/

### Logo

http://canal7punta.tv/images/logo.png

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/42f3cba2a08103f0f05ef5f4d2abe718a10f40d6
