### ISSUE TITLE
Edit: One TV Cinema 2

### ISSUE THREAD

**Issue by ajaatv** [iptv-org/database#14797]
### Channel ID (required)

OneTVCinema2.kh

### Broadcast Area

http://43.252.18.195:5080/LiveApp/streams/topmusic.m3u8

### NSFW

None

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by BellezaEmporium** [comment]
Links are in iptv-org/iptv, not in here.
