### ISSUE TITLE
Edit: iTV HD

### ISSUE THREAD

**Issue by ajaatv** [iptv-org/database#14793]
### Channel ID (required)

iTVHD.kh

### Broadcast Area

http://43.252.18.195:5080/live/streams/itvhd.m3u8

### NSFW

None

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by BellezaEmporium** [comment]
Same reason than in the other 2 channels.
