### ISSUE TITLE
Edit: CITV Channel

### ISSUE THREAD

**Issue by ajaatv** [iptv-org/database#14794]
### Channel ID (required)

CITVChannel.kh

### Broadcast Area

https://livefta.malimarcdn.com/ftaedge00/citv.stream/chunklist.m3u8

### NSFW

None

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by BellezaEmporium** [comment]
Same reason than in One TV Cinema 2.
