### ISSUE TITLE
Edit: TeleRadyo

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14822]
### Channel ID (required)

TeleRadyo.ph

### Channel Name

Teleradyo Serbisyo (Global) (720p)

### Alternative Names

ABS-CBN TeleRadyo

### Network

ABS-CBN

### Owners

ABS-CBN Corporation

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

news;public service

### NSFW

None

### Website

https://teleradyo-abscbn-ono.amagi.tv/playlist.m3u8

### Logo

https://upload.wikimedia.org/wikipedia/en/2/2e/TeleRadyo_Serbisyo_logo.svg

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- category id is incorrect
- link to the official website is incorrect
- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
