### ISSUE TITLE
Add: Wethersfield Community Television

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#14854]
### Channel Name

Wethersfield Community Television

### Alternative Names (optional)

WCTV 14

### Country

US

### Subdivision (optional)

US-CT

### City (optional)

Wethersfield

### Broadcast Area

s/US-CT

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1984-01-01

### Website (optional)

https://www.wctv14.com/watch-live

### Logo

https://pbs.twimg.com/profile_images/418953591127162880/J1TEyp3Z_400x400.png

**Comment by freearhey** [comment]
Please update your request:

- logo URL must not contain commas

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by ProPontifex** [comment]
Fixed
