### ISSUE TITLE
Add: Blab TV

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#14850]
### Channel Name

Blab TV

### Owners (optional)

BTO Media

### Country

US

### Subdivision (optional)

US-FL

### City (optional)

Pensacola

### Broadcast Area

s/US-FL;s/US-AL

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1984-02-01

### Website (optional)

https://www.blabtv.com/

### Logo

https://i.pinimg.com/280x280_RS/e5/db/84/e5db84df3c4249a66a60161de69c4073.jpg

**Comment by freearhey** [comment]
Please update your request:

- logo URL must not contain commas

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by ProPontifex** [comment]
Fixed
