### ISSUE TITLE
Add: regionalnitelevize.cz

### ISSUE THREAD

**Issue by AsciiWolf** [iptv-org/database#14879]
### Channel Name

regionalnitelevize.cz

### Alternative Names (optional)

Regionální televize

### Country

CZ

### Broadcast Area

c/CZ;r/EUR

### Languages

ces

### NSFW

FALSE

### Website (optional)

https://www.regionalnitelevize.cz/

### Logo

https://www.regionalnitelevize.cz/img/ico_152x152.png

**Comment by AsciiWolf** [comment]
By the way, the already added [A 11 TV](https://iptv-org.github.io/channels/cz/A11) seems to be a different channel that is not affiliated with regionalnitelevize.cz.

**Comment by freearhey** [comment]
"A11 TV" is the name of their official YouTube channel (https://www.youtube.com/user/regionalnitelevize), so I guess they are somehow related.

**Comment by AsciiWolf** [comment]
That's really weird. A11 TV and regionalnitelevize.cz have completely different websites with very different content and there are no hints on these websites that point to the other one. Also, the owner addresses (and cities they are from) are completely different. But I guess you are right. A11 probably bought regionalnitelevize.cz and kept the original one while also starting a different one on their own domain for a different audience.
