### ISSUE TITLE
Edit: Disney Channel East (Canada)

### ISSUE THREAD

**Issue by BlueCapped** [iptv-org/database#14870]
### Channel ID (required)

DisneyChannelEast.ca

### NSFW

None

**Comment by BlueCapped** [comment]
I have the stream for this channel: https://fl5.moveonjoy.com/DISNEY_CHANNEL/index.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
