### ISSUE TITLE
Add: Tiva TV [PR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1488]
### Channel Name

Tiva TV 

### Alternative Names (optional)

WRUA

### Country

PR

### City (optional)

San Juan 

### Broadcast Area

c/PR

### Languages

spa

### Categories (optional)

Entertainment

### NSFW

FALSE

### Website (optional)

https://tivatv.com/

### Logo

https://tivatv.com/wp-content/uploads/2021/06/cropped-Tiva8-1350x250-1.jpg

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=WRUA
