### ISSUE TITLE
Add: Teleoro Canal 13 [PR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1489]
### Channel Name

Teleoro Canal 13 

### Alternative Names (optional)

WORO-DT

### Country

PR

### City (optional)

Carolina 

### Broadcast Area

c/PR

### Languages

spa

### NSFW

FALSE

### Website (optional)

https://www.canal13pr.tv/

### Logo

https://static.wixstatic.com/media/28f4f7_110f5dfc95ed441aaa47c5f8c468362e~mv2.png/v1/fill/w_144,h_142,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/LOGO%20TELEORO%20copy_edited.png

**Comment by AntiPontifex** [comment]
Geo-blocked? (from Canada)

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=WORO-DT
