### ISSUE TITLE
Add: Salvacion TV [PR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1490]
### Channel Name

Salvacion TV

### Alternative Names (optional)

Salvación TV

### Country

PR

### City (optional)

San Juan 

### Broadcast Area

c/PR

### Languages

spa

### Categories (optional)

Religious

### NSFW

FALSE

### Website (optional)

http://www.salvaciontv.org/

### Logo

https://www.salvaciontv.org/images/franja%20arriba.jpg

**Comment by AntiPontifex** [comment]
Added to list: thank you for the stream.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/d6ba36a4b752eea39b7e70a6c62687fa66163a33
