### ISSUE TITLE
Add: America TeVe [PR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1491]
### Channel Name

America TeVe 

### Alternative Names (optional)

América TeVé 

### Network (optional)

América CV Network 

### Country

PR

### City (optional)

San Juan 

### Broadcast Area

c/PR

### Languages

spa

### Categories (optional)

General;entertainment 

### NSFW

FALSE

### Website (optional)

https://www.americatevepr.com/

### Logo

https://www.americatevepr.com/css-custom/189/images/header-logo-sticky.svg

**Comment by AntiPontifex** [comment]
Geo-blocked.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/ce4b777abbffb06234bb5b79aa74cbd03d896e74
