### ISSUE TITLE
Add: Win+ Fútbol

### ISSUE THREAD

**Issue by freearhey** [iptv-org/database#14935]
### Channel Name

Win+ Futbol

### Alternative Names (optional)

Win+ Fútbol

### Country

CO

### Broadcast Area

c/CO

### Languages

spa

### Categories (optional)

sports

### NSFW

FALSE

### Website (optional)

https://winplay.co/

### Logo

https://i.imgur.com/YB9k1h2.png

**Comment by BellezaEmporium** [comment]
This is mainly a rebranding of "Win Sports +".
