### ISSUE TITLE
Edit: Jeepney TV

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14956]
### Channel ID (required)

JeepneyTV.ph

### Channel Name

Jeepney TV

### Alternative Names

JTV

### Network

Creative Programs Inc.

### Owners

ABS-CBN Corporation

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

ent;general

### NSFW

None

### Website

https://mytfc.com/Jeepney-TV

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- category id is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
