### ISSUE TITLE
Edit: BuKo

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14959]
### Channel ID (required)

BuKo.ph

### Channel Name

BuKo Channel

### Alternative Names

Buhay Komedya

### Network

Cignal TV

### Owners

MediaQuest Corporation

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

ent

### NSFW

None

### Website

https://www.cignal.tv

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- category id is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
