### ISSUE TITLE
Edit: GMA News TV

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14957]
### Channel ID (required)

GMANewsTV.ph

### Channel Name

GMA News TV

### Alternative Names

GMA News TV International

### Network

GMA International

### Owners

GMA Network Inc.

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

news;public service

### NSFW

None

### Website

https://www.gmanetwork.com/international/

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- category id is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
