### ISSUE TITLE
Edit: INC TV

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14958]
### Channel ID (required)

INCTV.ph

### Channel Name

INCTV

### Alternative Names

Iglesia ni Cristo Television

### Network

Christian Era

### Owners

Christian Era Broadcasting Service International

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

religious

### NSFW

None

### Website

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://inctv.iglesianicristo.net/&ved=2ahUKEwjY7tX0nsKKAxWzzTQHHVZyGyAQFnoECB8QAQ&usg=AOvVaw3TaFTXzBK-Hf5MRM9N0xLH

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
