### ISSUE TITLE
Edit: PTV (Philippines)

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14954]
### Channel ID (required)

PTV.ph

### Channel Name

People's Television

### Alternative Names

NBN 4

### Network

Presidential Communications Office (PCO)

### Owners

People Television Network Inc. (PTNI)

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

news;public service

### NSFW

None

### Website

ptvnews.ph

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- category id is incorrect
- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
