### ISSUE TITLE
Edit: PBO (Philippines)

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14955]
### Channel ID (required)

PBO.ph

### Channel Name

PBO

### Alternative Names

Pinoy Box Office

### Network

Viva Entertainmet

### Owners

Viva Entertainment, Inc.

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

ent

### NSFW

None

### Website

https://pbo.com.ph

**Comment by freearhey** [comment]
Please update your request:

- commas cannot be used in the owner name
- broadcast area code is incorrect
- category id is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
