### ISSUE TITLE
Edit: TV5 (Philippines)

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14952]
### Channel ID (required)

TV5.ph

### Channel Name

TV5 PH

### Alternative Names

5 Channel

### Network

TV5 Network, Inc.

### Owners

MediaQuest Corporation

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

news; ent

### NSFW

None

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- category id is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Also could you explain why you added “PH” to the channel name?
