### ISSUE TITLE
Edit: One PH

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14960]
### Channel ID (required)

OnePH.ph

### Channel Name

One PH

### Network

Cignal TV

### Owners

MediaQuest Corporation

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

news;public service

### NSFW

None

### Website

https://www.cignal.tv

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- category id is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
