### ISSUE TITLE
Edit: TVUP

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14964]
### Channel ID (required)

TVUP.ph

### Channel Name

TVUP

### Network

Cignal TV

### Owners

University of the Philippines

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

education

### NSFW

None

### Website

https://www.tvup.ph

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
