### ISSUE TITLE
Edit: UAAP Varsity Channel

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14965]
### Channel ID (required)

UAAPVarsityChannel.ph

### Channel Name

UAAP Varsity Channel

### Network

Cignal TV

### Owners

MediaQuest Corporation

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

sports

### NSFW

None

### Website

https://www.cignal.tv

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
