### ISSUE TITLE
Edit: Media Pilipinas TV

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14962]
### Channel ID (required)

MediaPilipinasTV.ph

### Channel Name

Media Pilipinas TV

### Alternative Names

MPTV

### Network

Cignal TV

### Owners

MediaQuest Corporation

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

ent;sports

### NSFW

None

### Website

https://www.cignal.tv

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- category id is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
