### ISSUE TITLE
Edit: One Sports+

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14963]
### Channel ID (required)

OneSportsPlus.ph

### Channel Name

One Sports+

### Alternative Names

One Sports+

### Network

Cignal TV

### Owners

MediaQuest Corporation

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

sports

### NSFW

None

### Website

https://www.cignal.tv

**Comment by freearhey** [comment]
Please update your request:

- alternative name should only be specified if it differs from the main name
- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
