### ISSUE TITLE
Edit: Tagalized Movie Channel

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14961]
### Channel ID (required)

TagalizedMovieChannel.ph

### Channel Name

Tagalized Movie Channel

### Alternative Names

TMC

### Network

Viva Television

### Owners

Viva Entertainment, Inc.

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

ent;general

### NSFW

None

### Website

https://www.viva.com.ph

**Comment by freearhey** [comment]
Please update your request:

- commas cannot be used in the owner name
- broadcast area code is incorrect
- category id is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
