### ISSUE TITLE
Edit: Viva Cinema

### ISSUE THREAD

**Issue by Margoux-bit** [iptv-org/database#14966]
### Channel ID (required)

VivaCinema.ph

### Channel Name

Viva Cinema

### Network

Viva Television

### Owners

Viva Entertainment, Inc.

### Country

PH

### Subdivision

PH-MNL

### City

Manila

### Broadcast Area

Quezon City

### Languages

tag;eng

### Categories

ent;general

### NSFW

None

### Website

https://www.cignal.tv

**Comment by freearhey** [comment]
Please update your request:

- commas cannot be used in the owner name
- broadcast area code is incorrect
- category id is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
