### ISSUE TITLE
Add: ntv

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#14975]
### Channel Name

ntv

### Owners (optional)

Mediengruppe RTL

### Country

AT

### City (optional)

Vienna

### Broadcast Area

c/AT

### Languages

deu

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1992-11-30

### Website (optional)

http://www.n-tv.de

### Logo

https://im.chip.de/ii/2/3/0/9/8/7/6/7/logo-4d865e2628fd7b00.jpg?im=AspectCrop%2Csize%3D%281%2C1%29%2Cgravity%3DCenter%3BResize%3D%28204%2C204%29%2Caspect%3Dfit%3BBackgroundColor%2Ccolor%3Dffffff&hash=44e98c135a709dba46f21144cbc77a4c70a29987c36b7ca80be18356ae3e130b

**Comment by freearhey** [comment]
https://iptv-org.github.io/channels/at/ntv
