### ISSUE TITLE
Edit: Televisiete

### ISSUE THREAD

**Issue by BlueCapped** [iptv-org/database#15022]
### Channel ID (required)

Televisiete.gt

### Alternative Names

Canal 7 (Guatemala)

### NSFW

None

**Comment by freearhey** [comment]
Please update your request:

- no need to specify the country in the channel alternative name

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Duplicate of https://github.com/iptv-org/database/issues/15018
