### ISSUE TITLE
Edit: MTV3

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15028]
### Channel ID (required)

MTV3.fi

### Channel Name

MTV3

### Alternative Names

MTV3 HD

### NSFW

None

### Logo

https://i.imgur.com/C5rQbBM.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you for the response, @freearhey . Updated the issue according to the requested changes.
