### ISSUE TITLE
Edit: TV5

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15029]
### Channel ID (required)

TV5.fi

### Channel Name

TV5

### Alternative Names

TV5 HD

### NSFW

None

### Logo

https://i.imgur.com/7tzaznY.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you for the response, @freearhey . Updated the issue according to the requested changes.
