### ISSUE TITLE
Remove: Sub

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15031]
### Channel ID (required)

Sub.fi

### Reason (required)

Other

### Notes

New Channel ID should be MTVSub.fi

**Comment by freearhey** [comment]
In this case, you simply need to update the `Sub.fi` record and add the old name to the list of alternatives: https://github.com/iptv-org/database/issues/new?labels=channels%3Aedit&template=__channels_edit.yml&title=Edit%3A%20Sub&id=Sub.fi
