### ISSUE TITLE
Add: MTV Sub

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15032]
### Channel Name

MTV Sub

### Alternative Names (optional)

MTV Sub HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Website (optional)

https://fi.wikipedia.org/wiki/MTV_Sub

### Logo

https://img.prod.telkku.com/channel-logos/MTV_Sub_logo.png

**Comment by freearhey** [comment]
Duplicate of https://iptv-org.github.io/channels/fi/Sub
