### ISSUE TITLE
Add: MTV Ava

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15034]
### Channel Name

MTV Ava

### Alternative Names (optional)

MTV Ava HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Website (optional)

https://fi.wikipedia.org/wiki/MTV_Ava

### Logo

https://img.prod.telkku.com/channel-logos/MTV_Ava_logo.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Dupicate of https://iptv-org.github.io/channels/fi/AVA
