### ISSUE TITLE
Edit: Kutonen

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15030]
### Channel ID (required)

Kutonen.fi

### Channel Name

Kutonen

### Alternative Names

Kutonen HD

### NSFW

None

### Logo

https://i.imgur.com/OiB7Opu.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey . Updated the issue according to the requested changes.
