### ISSUE TITLE
Edit: TLC

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15035]
### Channel ID (required)

TLC.fi

### Channel Name

TLC

### Alternative Names

TLC HD

### NSFW

None

### Logo

https://i.imgur.com/gwfGyRM.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey . Updated the issue according to the requested changes.
