### ISSUE TITLE
Edit: MTV

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15038]
### Channel ID (required)

MTV.fi

### NSFW

None

### Logo

https://images.ctfassets.net/989y85n5kcxs/4pY8jQ0e6kUeoakoKyOUaK/0cec6f3a2e26bca175d01d096a08d73b/mtv_play_1.png

### Notes

Old icon MTV.fi is closed for some reason

**Comment by freearhey** [comment]
What do you mean, “closed”?

**Comment by jeirasmus** [comment]
Hi, @freearhey . 

When searching from here https://iptv-org.github.io/?q=MTV.fi it seems that there is a closed tag above the icon.
![kuva](https://github.com/user-attachments/assets/7aa0a315-ae6b-4059-87d9-cf9f0ce45da8)

**Comment by freearhey** [comment]
This mark means that the channel has a closing date:

![image](https://github.com/user-attachments/assets/1a7e8717-4bad-4265-b9d6-349018ff98bd)

If you are sure it is an error, you can remove it by specifying `~` in the “Closed” field.
