### ISSUE TITLE
Remove: AVA

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15033]
### Channel ID (required)

AVA.fi

### Reason (required)

Other

### Notes

New channel id is MTVAva.fi and I will create new issue for creating it.

**Comment by freearhey** [comment]
In this case, you simply need to update the `AVA.fi` record and add the old name to the list of alternatives: https://github.com/iptv-org/database/issues/new?labels=channels%3Aedit&template=__channels_edit.yml&title=Edit%3A%20AVA&id=AVA.fi
