### ISSUE TITLE
Add: Eurosport 2

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15045]
### Channel Name

Eurosport 2

### Alternative Names (optional)

Eurosport 2 HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Logo

https://i.imgur.com/f56dHgR.png

**Comment by freearhey** [comment]
Please update your request:

- no need to specify the country in the channel name
- no need to specify the country in the channel alternative name

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey. Updated the issue according to the requested changes.
