### ISSUE TITLE
Remove: C More Max

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15046]
### Channel ID (required)

CMoreMax.fi

### Reason (required)

Other

### Notes

Old channel name. New one is MTV Max.

**Comment by freearhey** [comment]
In this case, you simply need to update the `CMoreMax.fi` record and add the old name to the list of alternatives: https://github.com/iptv-org/database/issues/new?labels=channels%3Aedit&template=__channels_edit.yml&title=Edit%3A%20C%20More%20Max&id=CMoreMax.fi
