### ISSUE TITLE
Add: Viasat Nature

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15040]
### Channel Name

Viasat Nature

### Alternative Names (optional)

Viasat Nature HD

### Country

FI

### Broadcast Area

c/FI

### Languages

eng

### NSFW

FALSE

### Logo

https://i.imgur.com/ousRqqD.png

**Comment by freearhey** [comment]
Please update your request:

- no need to specify the country in the channel name
- no need to specify the country in the channel alternative name
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you for the response. Updated the issue according to the requested changes.
