### ISSUE TITLE
Add: Viasat History

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15043]
### Channel Name

Viasat History

### Alternative Names (optional)

Viasat History HD

### Country

FI

### Broadcast Area

c/FI

### Languages

eng

### NSFW

FALSE

### Website (optional)

https://viasathistory.eu/

### Logo

https://i.imgur.com/wRP9XA7.png

**Comment by freearhey** [comment]
Please update your request:

- no need to specify the country in the channel name
- no need to specify the country in the channel alternative name

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey. Updated the issue according to the requested changes.
