### ISSUE TITLE
Add: MTV Urheilu 2

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15049]
### Channel Name

MTV Urheilu 2

### Alternative Names (optional)

MTV Urheilu 2 HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Logo

https://i.imgur.com/tgezMDk.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey. Updated the logo url and removed the website url. There is not official channel website available so I ended up cleaning website url information (https://www.mtv.fi/urheilu might be the closest one for "official" url)
