### ISSUE TITLE
Add: MTV Urheilu 1

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15048]
### Channel Name

MTV Urheilu 1

### Alternative Names (optional)

MTV Urheilu 1 HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Logo

https://i.imgur.com/b9jZgbd.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey. Updated the icon url and website url. There is not official channel url so I ended up cleaning that information (https://www.mtv.fi/urheilu might be the closest one for "official" url for it)
