### ISSUE TITLE
Add: Eurosport 1

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15044]
### Channel Name

Eurosport 1

### Alternative Names (optional)

Eurosport 1 HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Website (optional)

https://www.eurosport.com/

### Logo

https://i.imgur.com/NaN9EgP.png

**Comment by freearhey** [comment]
Please update your request:

- no need to specify the country in the channel name
- no need to specify the country in the channel alternative name
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey. Updated the issue according to the requested changes.
