### ISSUE TITLE
Add: Viasat Explore 

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15042]
### Channel Name

Viasat Explore

### Alternative Names (optional)

Viasat Explore HD

### Country

FI

### Broadcast Area

c/FI

### Languages

eng

### NSFW

FALSE

### Website (optional)

https://viasatexplore.eu/

### Logo

https://i.imgur.com/DyT5pKB.png

**Comment by freearhey** [comment]
Please update your request:

- no need to specify the country in the channel name
- no need to specify the country in the channel alternative name

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey. Updated the issue according to the requested changes.
