### ISSUE TITLE
Add: TV Teuta [ME]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1505]
### Channel Name

TV Teuta

### Country

ME

### Subdivision (optional)

ME-20

### City (optional)

Ulcinj

### Broadcast Area

s/ME-20

### Languages

cnr

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

http://tvteuta.com/

### Logo

http://tvteuta.com/wp-content/webp-express/webp-images/uploads/2022/07/cropped-newLogo.png.webp

### Notes

Stream link: https://ub1doy938d.gjirafa.net/live/V5VHPPcRRtIuWFdnDuwjefzSqTKyBrW3/zty1gq.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
