### ISSUE TITLE
Add: MTV Viihde

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15052]
### Channel Name

MTV Viihde

### Alternative Names (optional)

MTV Viihde HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Logo

https://i.imgur.com/jIGFjRk.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
