### ISSUE TITLE
Add: MTV Aitio

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15051]
### Channel Name

MTV Aitio

### Alternative Names (optional)

MTV Aitio HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Logo

https://i.imgur.com/1Fh5bMe.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey. Updated the logo url and removed the website url. There is not official channel website available so I ended up cleaning website url information.
