### ISSUE TITLE
Add: V sport + Suomi

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15050]
### Channel Name

V sport + Suomi

### Alternative Names (optional)

V sport + Suomi HD

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### NSFW

FALSE

### Logo

https://img.prod.telkku.com/channel-logos/vsport_plus_200x200.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
