### ISSUE TITLE
Add: SkyShowtime 2

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15055]
### Channel Name

SkyShowtime 2

### Alternative Names (optional)

SkyShowtime 2 HD

### Country

FI

### Broadcast Area

c/FI

### Languages

eng

### NSFW

FALSE

### Logo

https://i.imgur.com/mgiHnYW.png

**Comment by freearhey** [comment]
Please update your request:

- no need to specify the country in the channel name
- no need to specify the country in the channel alternative name
- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you, @freearhey. I removed the website url and removed country information from channel name and channel alternative name.
