### ISSUE TITLE
Add: SF-kanalen

### ISSUE THREAD

**Issue by jeirasmus** [iptv-org/database#15056]
### Channel Name

SF-kanalen

### Alternative Names (optional)

SF-kanalen HD

### Country

FI

### Broadcast Area

c/FI

### Languages

swe

### NSFW

FALSE

### Logo

https://i.imgur.com/YpnN63k.png

**Comment by freearhey** [comment]
Please update your request:

- no need to specify the country in the channel name
- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by jeirasmus** [comment]
Thank you for the response, @freearhey . Updated the issue according to the requested changes. I removed the website link since it seems that there's no official page for that channel.
