### ISSUE TITLE
MCI TELEVISIÓN 

### ISSUE THREAD

**Issue by MCITVHD** [iptv-org/database#15060]
### Channel ID (required)

mciradio.com.co

### Channel Name

MCI TELEVISIÓN 

### NSFW

None

**Comment by MCITVHD** [comment]
Cómo se agrega un canal

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&projects=&template=__channels_add.yml&title=Add%3A+
