### ISSUE TITLE
Add: Araruna TV [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1506]
### Channel Name

Araruna TV

### Country

BR

### Subdivision (optional)

BR-PB

### Broadcast Area

s/BR-PB

### Languages

por

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://www.ararunatv.com/

### Logo

https://www.ararunatv.com/storage/71/config/QfBTq3xJhots8cMNx12VpxrCA0JU3MMDLYVCxQ8O.png

### Notes

https://video01.logicahost.com.br/ararunatv/ararunatv/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
