### ISSUE TITLE
MCI Televisión 

### ISSUE THREAD

**Issue by MCITVHD** [iptv-org/database#15061]
### Channel Name

MCI Television

### Network (optional)

MCI Radio

### Owners (optional)

MCI INC.

### Country

CO

### Subdivision (optional)

CO-BOY

### City (optional)

San Pablo De Borbur 

### Broadcast Area

c/CO

### Languages

spa;eng

### Categories (optional)

movies;family;general

### NSFW

FALSE

### Launched (optional)

2021-09-29

### Website (optional)

https://mciradio.com.co

### Logo

https://pbs.twimg.com/profile_images/1836009952420274177/FfYonU6r_400x400.jpg

### Notes

Lista M3U8 

URL M3u8 
 https://video.ejeserver.com/live/mcitelevision.m3u8

URL M3u8 Respaldo:
 https://co.ejeserver.com/live/mcitelevision.m3u8

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect
- category id is incorrect
- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by MCITVHD** [comment]
Ya actualice espero confirmación gracias

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect
- category id is incorrect
- the link to the logo is required

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by MCITVHD** [comment]
listo ya quedo actualizado  me confirma

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect
- category id is incorrect
- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by MCITVHD** [comment]
me confirma 
ya actualicé

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect
- category id is incorrect
- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect
- category ids must be separated by `;`
- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by MCITVHD** [comment]
Bueno volví a actualizar me confirma a ver si ya

**Comment by freearhey** [comment]
Please update your request:

- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by MCITVHD** [comment]
Me confirma??

**Comment by MCITVHD** [comment]
Una pregunta cómo se le pone la lista m3u8 al canal para que aparezca??

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
