### ISSUE TITLE
Add: Kuriakos Kids [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1507]
### Channel Name

Kuriakos Kids

### Owners (optional)

Motes & Ideias

### Country

BR

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

animation;kids;religious

### NSFW

FALSE

### Website (optional)

https://kuriakos-kids.com/

### Logo

https://i.ibb.co/mqvrJSq/Kurikos.png

**Comment by AntiPontifex** [comment]
No stream given, but found anyway. Included in the next release.

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=Kuriakos%20Kids
