### ISSUE TITLE
Add: Nossa TV Patos de Minas [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1508]
### Channel Name

Nossa TV Patos de Minas

### Alternative Names (optional)

NTV

### Country

BR

### Subdivision (optional)

BR-MG

### City (optional)

Patos de Minas 

### Broadcast Area

s/BR-MG

### Languages

por

### Categories (optional)

General;entertainment 

### NSFW

FALSE

### Website (optional)

https://www.ntv.tv.br/

### Logo

https://i.ibb.co/fHRV4MB/unnamed-20.jpg

### Notes

https://59f1cbe63db89.streamlock.net:1443/ntvnet/_definst_/ntvnet/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: included in the next release.
