### ISSUE TITLE
Edit: TNT Sports 1

### ISSUE THREAD

**Issue by acovenues** [iptv-org/database#15082]
TNT sport 2,http://190.110.99.102:8000/play/a02k 
TNT SPORT HD,http://190.110.99.102:8000/play/a010 
TNT Sports,http://dnsplay.xyz:80/aumdkodc/vgasdt13/124014 
TNT Sports,http://dnsplay.xyz:80/aumdkodc/vgasdt13/34684 
TNT Sports,http://dnsplay.xyz:80/aumdkodc/vgasdt13/34675[](

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
