### ISSUE TITLE
Add: Rede Mundo [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1509]
### Channel Name

Rede Mundo 

### Owners (optional)

Rede Mundo de Comunicação

### Country

BR

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

Entertainment

### NSFW

FALSE

### Website (optional)

https://www.redemundotv.com.br/

### Logo

https://www.redemundotv.com.br/assets/images/logo-rede-mundo-tv6.png

### Notes

https://video01.logicahost.com.br/mundotvbrasil/mundotvbrasil/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
