### ISSUE TITLE
Add: Rede Premium [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1510]
### Channel Name

Rede Premium 

### Country

BR

### Subdivision (optional)

BR-SP

### City (optional)

Osasco

### Broadcast Area

s/BR-SP

### Languages

por 

### Categories (optional)

Entertainment

### NSFW

FALSE

### Website (optional)

https://redepremiumtv.com.br/

### Logo

https://redepremiumtv.com.br/wp-content/uploads/2018/10/logo-site1-2.png

### Notes

https://5c483b9d1019c.streamlock.net/8066/8066/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
