### ISSUE TITLE
Add: TV A Plateia [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1511]
### Channel Name

TV A Plateia 

### Alternative Names (optional)

TV A Platéia

### Owners (optional)

Grupo A Platéia

### Country

BR

### Subdivision (optional)

BR-RS

### City (optional)

Santana do Livramento

### Broadcast Area

s/BR-RS

### Languages

Por

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://www.aplateia.com.br/

### Logo

https://i0.wp.com/directostv.teleame.com/wp-content/uploads/2017/11/tvplateia.png

### Notes

https://video01.kshost.com.br:4443/kamal3366/kamal3366/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
