### ISSUE TITLE
Add: TV Aracati [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1512]
### Channel Name

TV Aracati 

### Country

BR

### Subdivision (optional)

BR-CE

### City (optional)

Aracati

### Broadcast Area

s/BR-CE

### Languages

Por

### Categories (optional)

General 

### NSFW

FALSE

### Website (optional)

https://www.tvaracati.com.br/

### Logo

https://pa-str.srvsite.com/arquivos/6487/cabecalho-6487-20210315111823.png

### Notes

https://livefocamundo.com:8081/tvaracati/index.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
