### ISSUE TITLE
Add: TV Curuca [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1513]
### Channel Name

TV Curuca

### Alternative Names (optional)

TV Curuçá

### Country

BR

### Subdivision (optional)

BR-SP

### City (optional)

Vila Curuça

### Broadcast Area

s/BR-SP

### Languages

Por

### Categories (optional)

Entertainment

### NSFW

FALSE

### Website (optional)

https://www.tvcurucasp.com.br/

### Logo

https://www.tvcurucasp.com.br/img/logo.png

### Notes

https://stmv1.srvif.com/tvcurucasp/tvcurucasp/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
