### ISSUE TITLE
Add: TV Grande Natal [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1514]
### Channel Name

TV Grande Natal

### Country

BR

### Subdivision (optional)

BR-RN

### City (optional)

Natal

### Broadcast Area

s/BR-RN

### Languages

Por

### Categories (optional)

Entertainment

### NSFW

FALSE

### Website (optional)

https://tvgrandenatalhd.business.site/

### Logo

https://i.ibb.co/k8Qt56v/2020-11-17.png

### Notes

http://tvgrandenatalhd.duckdns.org:8080/hls/live.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
