### ISSUE TITLE
Add: TV Mais [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1515]
### Channel Name

TV Mais

### Owners (optional)

Glaúco Camargo

### Country

BR

### Subdivision (optional)

BR-SP

### City (optional)

Jundiaí

### Broadcast Area

s/BR-SP

### Languages

Por

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://www.tvmaisbrasil.com.br/

### Logo

https://fb.paineladmin.com.br/arquivos/8303/logo_face-8303-20200929212852.jpg

### Notes

https://srv5.zcast.com.br/tvmaisbrasil/tvmaisbrasil/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
