### ISSUE TITLE
Add: TV Mar [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1516]
### Channel Name

TV Mar

### Country

BR

### Subdivision (optional)

BR-AL

### City (optional)

Maceió

### Broadcast Area

s/BR-AL

### Languages

Por

### Categories (optional)

General;news

### NSFW

FALSE

### Website (optional)

https://tvmar.tv.br/

### Logo

https://i.ibb.co/n88f6QT/channels4-profile-1.jpg

### Notes

https://virtues.es:1936/tvmar/tvmar/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
