### ISSUE TITLE
Add: TV Natal [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1517]
### Channel Name

TV Natal 

### Country

BR

### Subdivision (optional)

BR-RN

### City (optional)

Natal

### Broadcast Area

s-BR-RN

### Languages

Por

### Categories (optional)

General;news;entertainment

### NSFW

FALSE

### Website (optional)

http://www.tvnatal.com.br/

### Logo

http://www.tvnatal.com.br/assets/images/logo/logo%20HD%20c%C3%B3pia.png

### Notes

https://StmV1.srvstm.com/antonioflavio9545/antonioflavio9545/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
