### ISSUE TITLE
Add: TV SIM Sao Mateus [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1520]
### Channel Name

TV SIM Sao Mateus 

### Alternative Names (optional)

TV SIM São Mateus 

### Network (optional)

Rede SIM

### Country

BR

### Subdivision (optional)

BR-ES

### City (optional)

São Mateus 

### Broadcast Area

s/BR-ES

### Languages

Por

### Categories (optional)

News

### NSFW

FALSE

### Website (optional)

https://www.simnoticias.com.br/

### Logo

https://i2.paste.pics/db2a7481ddc4276b0c2083d96105711a.png

### Notes

https://5cf4a2c2512a2.streamlock.net:443/8236/8236/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
