### ISSUE TITLE
Add: TV Vicosa [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1521]
### Channel Name

TV Vicosa

### Alternative Names (optional)

TV Viçosa

### Country

BR

### Subdivision (optional)

BR-MG

### City (optional)

Viçosa

### Broadcast Area

s/BR-MG

### Languages

Por

### Categories (optional)

Entertainment

### NSFW

FALSE

### Website (optional)

https://linktr.ee/tvvicosa

### Logo

https://i.ibb.co/vj9rvCw/wf-M9-R9-Jn-Ti-SPNBZre-CNZ-x6wn6mk-Kn-HCshw-G7.png

### Notes

http://wz4.dnip.com.br/fratevitv/fratevitv.sdp/playlist.m3u8

**Comment by AntiPontifex** [comment]
Does not work: geo-blocked?

**Comment by Carlinhos027** [comment]
> Does not work: geo-blocked?

Doesn't work for me neither (in Spain). It's strange, yesterday worked properly.
