### ISSUE TITLE
Add: TV Maceio [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1522]
### Channel Name

TV Maceio

### Alternative Names (optional)

TV Maceió

### Country

BR

### Subdivision (optional)

BR-AL

### City (optional)

Maceió

### Broadcast Area

s/BR-AL

### Languages

Por

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://tvmaceio.tv.br/

### Logo

https://i0.wp.com/directostv.teleame.com/wp-content/uploads/2018/02/TV-Maceio-en-directo-Online.png

### Notes

https://srv5.zcast.com.br/paulo4100/paulo4100/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
