### ISSUE TITLE
Add:  The Jamie Oliver Channel

### ISSUE THREAD

**Issue by oldpoem** [iptv-org/database#1529]
### Channel Name

The Jamie Oliver Channel

### Country

US

### Broadcast Area

c/US

### Languages

eng

### Categories (optional)

lifestyle

### NSFW

FALSE

### Website (optional)

https://www.xumo.tv/live-guide/the-jamie-oliver-channel

### Logo

https://image.xumo.com/v1/channels/channel/99951153/600x337.jpg?type=color_onBlack

**Comment by AntiPontifex** [comment]
Geo-blocked (from Canada).

**Comment by oldpoem** [comment]
I don't see any issue about adding existed channel in /database  or create epg in /epg.  If it is /iptv then geoblock stream url would be a remark.

Most of Xumo channels is geoblock on their website (by the player check config) but also most of xumo actual streams isn't geoblocked.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/4d91d9ed53637bb8241b60c4b8201848bbce0af4
