### ISSUE TITLE
Add: Rede NGT [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1530]
### Channel Name

Rede NGT

### Country

BR

### Subdivision (optional)

BR-SP

### Broadcast Area

s/BR-SP

### Languages

por

### Categories (optional)

Entertainment

### NSFW

FALSE

### Website (optional)

https://redengt.com.br/

### Logo

https://i.ibb.co/m82g3bN/descarga-1.png

### Notes

https://acesso.ecast.site:3922/live/redengtlive.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
