### ISSUE TITLE
Add: TV Cidada Alagoas [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1531]
### Channel Name

TV Cidada Alagoas 

### Alternative Names (optional)

TV Cidadã Alagoas 

### Owners (optional)

Tribunal de Contas do Estado de Alagoas

### Country

BR

### Subdivision (optional)

BR-AL

### Broadcast Area

s/BR-AL

### Languages

por

### Categories (optional)

legislative;news

### NSFW

FALSE

### Website (optional)

https://www.tceal.tc.br/

### Logo

https://i.ibb.co/hKd9k67/unnamed.jpg

### Notes

https://livefocamundo.com:8081/tvcidada/index.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
