### ISSUE TITLE
Add: TV A7 Plus [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1532]
### Channel Name

TV A7 Plus

### Owners (optional)

Fundação Nelson Castilho

### Country

BR

### Subdivision (optional)

BR-GO

### City (optional)

Caldas Novas

### Broadcast Area

s/BR-GO

### Languages

Por

### Categories (optional)

Entertainment;music;news

### NSFW

FALSE

### Website (optional)

https://tva7.com.br/

### Logo

https://tva7.com.br/themes/tva7/assets/images/logo.png

### Notes

https://srv3.zcast.com.br/wellington7720/wellington7720/playlist.m3u8

**Comment by AntiPontifex** [comment]
Stream does not work: geo-blocked? (from Canada)

**Comment by Carlinhos027** [comment]
> Stream does not work: geo-blocked? (from Canada)

Works properly in Spain.
