### ISSUE TITLE
Add: TV Brasil Oeste [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1533]
### Channel Name

TV Brasil Oeste

### Alternative Names (optional)

TVO

### Country

BR

### Subdivision (optional)

BR-MT

### City (optional)

Cuiabá

### Broadcast Area

s/BR-MT

### Languages

por

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.tbomt.com.br/

### Logo

http://www.tbomt.com.br/images/logo.png

### Notes

https://5ad482a77183d.streamlock.net/operacaotbomt.com/operacaotbomt.com/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
