### ISSUE TITLE
Add: TV Arapuan [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1534]
### Channel Name

TV Arapuan

### Network (optional)

RedeTV!

### Country

BR

### Subdivision (optional)

BR-PB

### City (optional)

João Pessoa

### Broadcast Area

s/BR-PB

### Languages

Por

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://www.tvarapuan.com.br/

### Logo

https://www.tvarapuan.com.br/2021/images/site/logo.png

### Notes

https://5b7f3c45ab7c2.streamlock.net/arapuan/ngrp:arapuan_all/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
