### ISSUE TITLE
Add: TVE RS [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1535]
### Channel Name

TVE RS

### Country

BR

### Subdivision (optional)

BR-RS

### City (optional)

Porto Alegre

### Broadcast Area

s/BR-RS

### Languages

Por

### Categories (optional)

culture;education

### NSFW

FALSE

### Website (optional)

https://www.tve.com.br/

### Logo

https://www.tve.com.br/themes/padrao2019/images/logos/logo.png

### Notes

https://streaming.procergs.com.br:8443/tve/stve/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
