### ISSUE TITLE
Add: SBT Interior [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1536]
### Channel Name

SBT Interior

### Network (optional)

Sistema Brasileiro de Televisão 

### Country

BR

### Subdivision (optional)

BR-SP

### City (optional)

Araçatuba

### Broadcast Area

s/BR-SP

### Languages

Por

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://sbtinterior.com/

### Logo

https://directostv.teleame.com/wp-content/uploads/2017/11/SBT-Interior-ao-Vivo-Online.png

### Notes
(https://cdn.jmvstream.com/w/LVW-10801/LVW10801_Xvg4R0u57n/playlist.m3u8)

**Comment by AntiPontifex** [comment]
No link provided, but found just the same. It will be included in the next release.

**Comment by Carlinhos027** [comment]
> No link provided, but found just the same. It will be included in the next release.

https://cdn.jmvstream.com/w/LVW-10801/LVW10801_Xvg4R0u57n/playlist.m3u8
