### ISSUE TITLE
Add: Rede UTV [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1537]
### Channel Name

Rede UTV

### Owners (optional)

Cavomd Telecomunicações

### Country

BR

### Subdivision (optional)

BR-SP

### City (optional)

Descalvado

### Broadcast Area

s/BR-SP

### Languages

Por

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://www.redeutv.com.br/

### Logo

https://i.ibb.co/P1hg5B8/m.png

### Notes

https://srv4.zcast.com.br/redetvoficial/redetvoficial/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
