### ISSUE TITLE
Add: TV Japi [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1538]
### Channel Name

TV Japi

### Country

BR

### Subdivision (optional)

BR-SP

### City (optional)

Jundiaí

### Broadcast Area

s/BR-SP

### Languages

Por

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://www.tvjapi.com.br/

### Logo

https://pa-str.srvsite.com/arquivos/6096/cabecalho-6096-20200928162906.png

### Notes

https://srv2.zcast.com.br/tvjapi/tvjapi/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
