### ISSUE TITLE
Add: STZ TV [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1539]
### Channel Name

STZ TV

### Country

BR

### Subdivision (optional)

BR-SP

### City (optional)

Sertãozinho

### Broadcast Area

s/BR-SP

### Languages

Por

### Categories (optional)

news;culture

### NSFW

FALSE

### Website (optional)

https://stztv.org.br/

### Logo

https://stztv.org.br/imagens/misc/stz-tv-logotipo-nova.png

### Notes

https://cdn.jmvstream.com/w/AVJ-11063/playlist/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
