### ISSUE TITLE
Add: TV Caravelas [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1540]
### Channel Name

TV Caravelas

### Country

BR

### Subdivision (optional)

BR-MG

### City (optional)

Ipatinga

### Broadcast Area

s/BR-MG

### Languages

Por

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://www.tvcaravelas.com/

### Logo

https://pa-str.srvsite.com/arquivos/4506/cabecalho-4506-20190507094833.png

### Notes

https://59f1cbe63db89.streamlock.net:1443/tvcaravelas/_definst_/tvcaravelas/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
