### ISSUE TITLE
Add: Cabo Frio TV [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1542]
### Channel Name

Cabo Frio TV

### Network (optional)

Rede Canal 10

### Country

BR

### Subdivision (optional)

BR-RJ

### City (optional)

Cabo Frio

### Broadcast Area

s/BR-RJ

### Languages

Por

### Categories (optional)

Entertainment

### NSFW

FALSE

### Website (optional)

https://www.redecanal10.com.br/

### Logo

https://www.redecanal10.com.br/storage/33/config/ILTU5SIUNDcrO8x5pdi885Twch4v1EdLOxIdJZzE.png

### Notes

https://59f2354c05961.streamlock.net:1443/ararutv/_definst_/ararutv/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
