### ISSUE TITLE
Add: TVBE Joinville [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1543]
### Channel Name

TVBE Joinville

### Network (optional)

TV Brasil

### Owners (optional)

Fundação Cultural e Educacional de Itajaí

### Country

BR

### Subdivision (optional)

BR-SC

### City (optional)

Joinville

### Broadcast Area

s/BR-SC

### Languages

Por

### Categories (optional)

Culture;education

### NSFW

FALSE

### Website (optional)

https://www.tvbejoinville.com.br/

### Logo

https://www.tvbejoinville.com.br/wp-content/uploads/sites/1301/2022/11/ok-2.png

### Notes

https://5c483b9d1019c.streamlock.net/8022/8022/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
