### ISSUE TITLE
Add: RDC TV [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1544]
### Channel Name

RDC TV 

### Country

BR

### Subdivision (optional)

BR-RS

### City (optional)

Porto Alegre

### Broadcast Area

s/BR-RS

### Languages

por 

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://rdctv.com.br/

### Logo

https://rdctv.com.br/wp-content/uploads/2018/05/logo-rdctv.png

### Notes

https://596639ebdd89b.streamlock.net/datavideo01/datavideo01/chunklist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
