### ISSUE TITLE
Add: Hei now 

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/database#1552]
### Channel Name

Hei now

### Country

PY

### Broadcast Area

c/PY

### Languages

es

### NSFW

FALSE

### Website (optional)

https://www.heinow.com.py/

### Logo

https://www.heinow.com.py/wp-content/themes/heinow/assets/images/logo.svg

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/517bbdb59662280076acbded2d0662169afe69dc
