### ISSUE TITLE
Add: Canal 4

### ISSUE THREAD

**Issue by Smark223** [iptv-org/database#1560]
### Channel Name

Canal 4

### Country

ES

### Subdivision (optional)

ES-CT

### Broadcast Area

s/ES-CT

### Languages

cat;spa

### NSFW

FALSE

### Website (optional)

https://www.grup4.com/?page_id=14675&lang=ca

### Logo

https://www.grup4.com/wp-content/uploads/2022/09/canal4-television.png

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/40ecd284ec61de8b0de3de979266f57e7e002301
