### ISSUE TITLE
Add: Mega TV

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/database#1568]
### Channel Name

Mega TV

### Country

PY

### Broadcast Area

c/PY

### Languages

es

### NSFW

FALSE

### Website (optional)

https://megacadena.com.py/mega-tv/

### Logo

https://megacadena.com.py/wp-content/uploads/2022/05/MegaTV-logo-10.png

### Notes

It's a free IPTV channel

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/674e9922d943746b4b02e8b2a151358201f77bec
