### ISSUE TITLE
Add: 5 Días [PY]

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/database#1575]
### Channel Name

5 Días

### Alternative Names (optional)

5 Dias

### Country

PY

### Broadcast Area

c/PY

### Languages

es

### NSFW

FALSE

### Website (optional)

https://www.5dias.com.py

### Logo

https://www.5dias.com.py/assets/img/core/5d-play-white.svg

### Notes

This is their 24/7 live youtube channel https://www.youtube.com/watch?v=U2KO1TFcpO8&ab_channel=5D%C3%8DASTELEVISI%C3%93N

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/9019ecbc8e04fe07fe691c5c61b38708c06db7d8
