### ISSUE TITLE
Remove: Nova.cz / TVNova.cz

### ISSUE THREAD

**Issue by RevGear** [iptv-org/database#1583]
### Channel ID

Nova.cz 

### Reason

Duplicate

### Notes

Is Nova.cz a duplicate of TVNova.cz ? They seem to have the same details and same logo, albeit from a different URL

**Comment by freearhey** [comment]
Removed in https://github.com/iptv-org/database/commit/7c63833df72047a58e25c9112ab4f3af08a3198f
