### ISSUE TITLE
Edit: 

### ISSUE THREAD

**Issue by ghost** [iptv-org/database#1584]
### Channel ID (required)

DreikoTV.pa

### Channel Name

DreikoTV

### Country

PA

### Languages

spa

### Categories

animations; kids

### NSFW

FALSE

### Replaced By

https://cloudvideo.servers10.com:8081/8242/rewind-3600.m3u8?DVR

### Website

https://dreikotv.online

### Notes

New Streaming provider Signal

**Comment by freearhey** [comment]
This repository only stores channel descriptions. 

If you want to share an updated link to the stream, you better post it here: https://github.com/iptv-org/iptv/issues
