### ISSUE TITLE
Edit: CanalEvelyn.pe

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/database#1597]
### Channel ID (required)

CanalEvelyn.pe

### Channel Name

Canal E

### Owners

Evelyn SAC

### NSFW

None

### Website

https://enet.pe/nuevacajamarca/

### Notes

Canal Evelyn is recalled Canal E. Updated city.

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added in the next release.
