### ISSUE TITLE
Updated information about La Urban TV and Radio

### ISSUE THREAD

**Issue by ea5iva** [iptv-org/database#165]
LaUrbanTV.es,La Urban TV,,,ES,,,c/ES,spa,,FALSE,,,,https://www.urbanrevolution.es/emision-en-directo-de-la-urban-tv/,https://www.urbanrevolution.es/wp-content/uploads/2021/09/simbolo_positivo.png
LaUrbanRadio.es,La Urban Radio,,,ES,,,c/ES,spa,,FALSE,,,,https://www.urbanrevolution.es/la-urban-radio-en-directo/,https://i.imgur.com/01UcUcX.png

**Comment by freearhey** [comment]
Updated in https://github.com/iptv-org/database/commit/a6f6ddbb0dec59c0140320e3805c088e923332b9
