### ISSUE TITLE
Add: Big Brother Brazil

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#1717]
### Channel Name

Big Brother Brazil

### Alternative Names (optional)

Big Brother Brasil

### Owners (optional)

Canais Globo

### Country

BR

### Subdivision (optional)

BR-RJ

### City (optional)

Rio de Janeiro

### Broadcast Area

s/BR-RJ

### Languages

por

### NSFW

FALSE

### Website (optional)

https://gshow.globo.com/realities/bbb

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Logo_Big_Brother_Brasil.png/1280px-Logo_Big_Brother_Brasil.png

### Notes

Opens in january and closes in end of april, same thing every year

**Comment by kaikyoofers** [comment]
Hello?

**Comment by freearhey** [comment]
Channel added in https://github.com/iptv-org/database/commit/f1dc2d2de550b4eabc02d60452ad9d2eb7a9db39
