### ISSUE TITLE
Add: HOLA Play [ES] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1806]
### Channel Name

HOLA Play

### Alternative Names (optional)

¡HOLA! Play

### Country

ES

### Broadcast Area

c/ES

### Languages

Spa

### Categories (optional)

Entertainment;news;lifestyle

### NSFW

FALSE

### Website (optional)

https://www.hola.com/tv/

### Logo

https://www.hola.com/tv/assets/videoondemand/icons/720_405_meta_logo.jpg

**Comment by freearhey** [comment]
Are you sure it's a TV channel and not a service like [BBC iPlayer](https://en.wikipedia.org/wiki/BBC_iPlayer)?

**Comment by AntiPontifex** [comment]
This does seem to be a proprietary service.
