### ISSUE TITLE
Add: KXAS-DT1

### ISSUE THREAD

**Issue by gustavogarciataunton** [iptv-org/database#1823]
### Channel Name

KXAS-DT1

### Alternative Names (optional)

NBC 5 Dallas-Fort Worth

### Network (optional)

NBC

### Country

US

### Subdivision (optional)

US-TX

### City (optional)

Dallas-Fort Worth

### Broadcast Area

s/US-TX

### Languages

eng

### NSFW

FALSE

### Website (optional)

https://www.nbcdfw.com/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/NBC_logo_2022_%28vertical%29.svg/512px-NBC_logo_2022_%28vertical%29.svg.png

### Notes

NBC's Dallas-Fort Worth channel is listed in the EPG as well as the database; however, it does not actually appear as a channel in my playlist. I have tried different playlist sorting - by all, region, country, and subdivision, but it doesn't appear in either. Thanks in advance for any help :)

**Comment by freearhey** [comment]
This repository contains only channel descriptions. If you need a link to a stream of the channel, you'd better post your request here: https://github.com/iptv-org/iptv/issues

Also note that the database contains all known channels, not just those in playlists and for which we have an EPG.
