### ISSUE TITLE
Add: PROTV Chișinău

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/database#1832]
### Channel Name

PROTV MD

### Network (optional)

CME PRO

### Owners (optional)

PRO Digital SRL

### Country

MD

### Subdivision (optional)

MD-CU

### City (optional)

Chișinău

### Broadcast Area

c/MD

### Languages

ro

### Categories (optional)

general;news

### NSFW

FALSE

### Launched (optional)

1999-09-03

### Website (optional)

https://protv.md/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Logo_Pro_TV_Chi%C8%99in%C4%83u_%282017%29.svg/1200px-Logo_Pro_TV_Chi%C8%99in%C4%83u_%282017%29.svg.png

### Notes

Stream URL:  http://hls.protv.md/hls/protv.m3u8

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/bb17e1974a9fa1fc2155f73bc661bbe63b9dbbfb
