### ISSUE TITLE
Add: Estrella TV [MX] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1840]
### Channel Name

Estrella TV

### Owners (optional)

Estrella Media

### Country

MX

### Broadcast Area

c/MX

### Languages

Spa

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://estrellatv.com/

### Logo

https://upload.wikimedia.org/wikipedia/commons/2/22/Estrella_TV_Logo_2020.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Estrella%20TV
