### ISSUE TITLE
Add: Interrobang LLC

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#1858]
### Channel Name

Interrobang LLC

### Country

CA

### Broadcast Area

c/CA

### Languages

eng

### Categories (optional)

animation

### NSFW

FALSE

### Launched (optional)

2022-06-27

### Closed (optional)

2022-07-12

### Logo

https://i.imgur.com/R99a62F.jpeg

### Notes

channel was exclusive to rogers cable

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/0307ede45076ad6037084596074faec3051c6673
