### ISSUE TITLE
Add: TV!

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#1859]
### Channel Name

TV!

### Country

BR

### Broadcast Area

c/BR

### Languages

por

### NSFW

FALSE

### Launched (optional)

1999-05-10

### Closed (optional)

1999-10-12

### Replaced By (optional)

RedeTV.br

### Logo

https://upload.wikimedia.org/wikipedia/pt/4/4b/TV%21.jpg

### Notes

Was a transitory phase between rede manchete and redetv. Rede manchete is not to be confused with TV Manchete (TVManchete.br) which is already on the database

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/8c0057ba757e854de45127ed718dba8a9fe2cf49
