### ISSUE TITLE
Add: set of Dominican Channels from PR

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/database#1867]
### Channel Name

Telenovisa Canal 43 | Tele Caribe | Television del Este | Vegavision Canal 18

### Country

DO

### Broadcast Area

s/DO_DO

### Languages

spa

### NSFW

FALSE

### Logo

https://photos.live-tv-channels.org/tv-logo/do-telenovisa-43-3697.jpg | https://scontent-cdt1-1.xx.fbcdn.net/v/t39.30808-6/305928639_493187472812612_6129318390430174000_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=MJAAYCXYN8oAX_OArE2&_nc_oc=AQnGX21wXIBf0mGMdRXn2yzu284A0qEkkaQ6Dh61Gor3NC171AuRfXgCSSzwx2DxQyA&_nc_ht=scontent-cdt1-1.xx&oh=00_AfBvCjITYSPG_f4reC0OFM2f5v44SNLA7KQWkSZqllKChg&oe=63CAA71E | https://televisiondeleste.net/wp-content/uploads/2021/04/LogoTVEste2.png | https://canalesdominicanos.live/template/images/radios/vegavision-canal-18.jpg

### Notes

From PR 11264 in the iptv-org/iptv repository.

Telenovisa43.do
TeleCaribe.do
TelevisiondelEste.do
VegavisionCanal18.do

**Comment by freearhey** [comment]
All of the listed channels are already in the database:

https://iptv-org.github.io/?q=Telenovisa43.do
https://iptv-org.github.io/?q=TeleCaribe.do
https://iptv-org.github.io/?q=TelevisiondelEste.do
https://iptv-org.github.io/?q=VegavisionCanal18.do
