### ISSUE TITLE
Add: BraziTV [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#1879]
### Channel Name

BraziTV

### Country

BR

### Broadcast Area

c/BR

### Languages

Por

### Categories (optional)

Entertainment

### NSFW

FALSE

### Website (optional)

https://www.brazitv.com/

### Logo

https://files.secure.website/wscfus/10637880/30974455/logocultura-branco-w1538-o.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=BraziTV
