### ISSUE TITLE
Duplicated channels in playlist

### ISSUE THREAD

**Issue by peaking2** [iptv-org/database#20]
There might be a reason for it, such as having various streams available for the same channel due to stream uptime and downtime. Though there are a few channels in which the channel is listed excessively in the list. Such as Red Bull TV or France 24 for example. If it were more streamlined, it would put less pressure on the software to load and a more expedient way of scrolling the channels.

**Comment by freearhey** [comment]
If you have an idea how to improve the project it would be better to publish it here: https://github.com/iptv-org/iptv/discussions
