### ISSUE TITLE
Add: TVSud.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/database#2018]
### Channel Name

TV SUD

### Alternative Names (optional)

TVSUD

### Network (optional)

 SUD MEDIA

### Owners (optional)

 SUD MEDIA PRODUCTION

### Country

RO

### Subdivision (optional)

RO-GJ

### City (optional)

Targu Jiu

### Broadcast Area

r/GJ

### Languages

ro

### Categories (optional)

news;regional

### NSFW

FALSE

### Launched (optional)

2011-06-20

### Website (optional)

https://www.tvsud.ro/

### Logo

https://www.tvsud.ro/wp-content/uploads/2021/12/Tv-Sud-Shadow-.png

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/76fa5d08c34afb1b2bc7912f44f29365674f7936
