### ISSUE TITLE
Add: Knoxville Community Media

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2028]
### Channel Name

Knoxville Community Media

### Country

US

### Subdivision (optional)

US-TN

### City (optional)

Knoxville

### Broadcast Area

s/US-TN

### Languages

eng

### Categories (optional)

community

### NSFW

FALSE

### Website (optional)

https://www.ctvknox.org/

### Logo

https://www.ctvknox.org/wp-content/uploads/2022/03/KCM.png

### Notes

Streaming URL:

https://knoxville-tn.secure.footprint.net/egress/bhandler/knoxvilletn/streama/1000000/1000000.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Knoxville%20Community%20Media
