### ISSUE TITLE
Add: Canal 40 Caucete

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2033]
### Channel Name

Canal 40 Caucete

### Country

AR

### City (optional)

San Juan

### Broadcast Area

s/AR

### Languages

esp

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://canal40hd.com.ar/

### Logo

https://lh3.googleusercontent.com/p/AF1QipNRmy5EGdR4rcvXxs643rRbaTTudXvcll17pxKH=s680-w680-h510

**Comment by Carlinhos027** [comment]
Already on the database as "Canal40Cauecte.ar"

**Comment by AntiPontifex** [comment]
Whoops!
