### ISSUE TITLE
Add: Good Shepherd

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2036]
### Channel Name

Good Shepherd

### Country

AU

### City (optional)

Melbourne

### Broadcast Area

s/AU, s/NZ

### Languages

eng

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://goodshep.org.au/

### Logo

https://goodshep.org.au/wp-content/uploads/2020/11/logo-goodshepherd.svg

**Comment by freearhey** [comment]
I could not find any mention of any TV channel in the link you provided.
