### ISSUE TITLE
Add: emcitv

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2085]
### Channel Name

emcitv

### Country

CA

### Subdivision (optional)

CA-QC

### City (optional)

Bromont

### Broadcast Area

s/CA-QC

### Languages

fre

### Categories (optional)

religious

### NSFW

FALSE

### Launched (optional)

2017-12-17

### Website (optional)

https://emcitv.com/

### Logo

https://emcitv.com/app/common/assets/img/logo/LOGO-emci-2.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=emcitv
