### ISSUE TITLE
Add: PTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2105]
### Channel Name

PTV

### Owners (optional)

Sociedad Anónima

### Country

ES

### City (optional)

Cordoba

### Broadcast Area

s/ES

### Languages

esp

### NSFW

FALSE

### Launched (optional)

1983-07-01

### Website (optional)

https://www.ptvtelecom.com/

### Logo

https://upload.wikimedia.org/wikipedia/commons/9/9e/PTV_Telecom_logo.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=^PTV%20country:ES
