### ISSUE TITLE
Add: SuperMix

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#2124]
### Channel Name

SuperMix

### Country

BR

### Broadcast Area

c/BR

### Languages

por

### NSFW

FALSE

### Launched (optional)

2012-08-30

### Closed (optional)

2014-11-03

### Replaced By (optional)

MixTV.br

### Website (optional)

http://www.tvsupermix.com.br/

### Logo

https://upload.wikimedia.org/wikipedia/commons/7/7c/Logo_supermix.png

**Comment by PopeyeTheSai10r** [comment]
> ### Closed (optional)
> 2014-11-03

Why add closed channels?

**Comment by kaikyoofers** [comment]
> > ### Closed (optional)
> > 2014-11-03
> 
> Why add closed channels?

Then why did they add The Superstation, Rede Tupi and others?
