### ISSUE TITLE
Edit: Kohavision (KTV)

### ISSUE THREAD

**Issue by Smark223** [iptv-org/database#2137]
### Channel ID (required)

Kohavision.rs

### Channel Name

Kohavision

### Alternative Names (optional)

KTV

### Country

XK

### Broadcast Area

s/XK

### Languages

sqi; srp

### NSFW

FALSE

### Website

https://www.koha.net/ktv/

### Notes

Channel is in database as being from Serbia but its headquarters are in Pristina and it broadcasts to Kosovo. Amend to Kohavision.xk

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/database/commit/170d52ca3fa1118e5e36f18fd22aa4d2c256175c
