### ISSUE TITLE
Add: Euronews Greek

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2153]
### Channel Name

Euronews Greek

### Country

FR

### City (optional)

Lyon

### Broadcast Area

s/GR

### Languages

ell

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

1993-01-01

### Website (optional)

https://gr.euronews.com/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Euronews_2016_logo.svg/1024px-Euronews_2016_logo.svg.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Euronews%20Greek
