### ISSUE TITLE
Add: NRK3/NRK Super

### ISSUE THREAD

**Issue by Smark223** [iptv-org/database#2157]
### Channel Name

NRK3/NRK Super

### Country

NO

### Broadcast Area

c/NO

### Languages

nor;eng

### NSFW

FALSE

### Logo

https://i.postimg.cc/gkpMbLCH/NRK3-NRKSuper.png

### Notes

Add combined tvg-id for NRK3/NRK Super as the channels share a stream (similar to SVT24/SVT Barn). A combined epg source exists on tv24.se, which I will add once the new tvg-id has been created.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/be6d98236882ff938545c49e1e3009286f898dc0
