### ISSUE TITLE
Add: Sula TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2172]
### Channel Name

Sula TV

### Country

HN

### City (optional)

San Pedro Sula

### Broadcast Area

s/HN

### Languages

esp

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1977-06-27

### Website (optional)

https://canal6.com.hn/

### Logo

https://upload.wikimedia.org/wikipedia/commons/8/88/Canal6.jpg

**Comment by freearhey** [comment]
The link you provided leads to the official website of the "Canal 6": https://iptv-org.github.io/?q=Canal6.hn

**Comment by Carlinhos027** [comment]
Wrong logo and website (nothing related with Canal 6).
That's its logo:
https://i.ibb.co/nsWzxTQ/1681119334186.jpg
