### ISSUE TITLE
Add: ViuTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#222]
### Channel Name

ViuTV

### Native Name (optional)

香港電視娛樂有限公司

### Network (optional)

HK Television Entertainment

### Country

HK

### City (optional)

Kowloon Bay

### Broadcast Area

s/CN-HK

### Languages

chi;eng

### NSFW

FALSE

### Website (optional)

https://viu.tv/ch/99

### Logo

https://viu.tv/assets/img/logo.png

### Notes

Geo-blocked

**Comment by freearhey** [comment]
Already in database: https://iptv-org.github.io/?q=ViuTV
