### ISSUE TITLE
Add: MagentaMusik 360 2 [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2271]
### Channel Name

MagentaMusik 360 2

### Country

DE

### Broadcast Area

c/DE

### Languages

Deu

### Categories (optional)

Music

### NSFW

FALSE

### Website (optional)

https://www.magentamusik.de/

### Logo

https://stadt-bremerhaven.de/wp-content/uploads/2019/12/Magenta-Musik-360.jpg

**Comment by freearhey** [comment]
I was unable to find any information about the MagentaMusik 360 2 channel at the link provided.
