### ISSUE TITLE
Add: Pannon RTV [HU] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2283]
### Channel Name

Pannon RTV

### Country

HU

### Broadcast Area

c/HU

### Languages

Hun

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://pannonrtv.com/

### Logo

https://pannonrtv.com/themes/custom/pannonrtv/logo.svg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Pannon%20TV
