### ISSUE TITLE
Add: Canal 6 Durazno [UY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2311]
### Channel Name

Canal 6 Durazno

### Country

UY

### Broadcast Area

c/UY

### Languages

Spa

### Categories (optional)

general

### NSFW

FALSE

### Logo

https://cds-assets.cdn.antel.net.uy/imagenes/recursos/BwiO1FjunoxF2jSqqUizku0oEoSoMYthUFRUNxfC.jpeg

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/b3e079a4f019936d827aa323411273f5c7440ee9
