### ISSUE TITLE
Add: Canal 8 Durazno [UY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2314]
### Channel Name

Canal 8 Durazno

### Country

UY

### Broadcast Area

c/UY

### Languages

spa

### Categories (optional)

General

### NSFW

FALSE

### Logo

https://cds-assets.cdn.antel.net.uy/imagenes/recursos/MjUcQ3yJp2idhOVJT47PZOEhLJPkh8ns8K7ALbFK.jpeg

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/b3e079a4f019936d827aa323411273f5c7440ee9
