### ISSUE TITLE
Add: Canal 9 Telerocha [UY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2317]
### Channel Name

Canal 9 Telerocha

### Country

UY

### Broadcast Area

c/UY

### Languages

spa

### NSFW

FALSE

### Logo

https://cds-assets.cdn.antel.net.uy/imagenes/recursos/rgcSBcko1DOx1VtMJd9MD0Ne90wrWjpGsRRNDNuP.jpeg

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/b3e079a4f019936d827aa323411273f5c7440ee9
