### ISSUE TITLE
Add: Uruguay Presidencia [UY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2342]
### Channel Name

Uruguay Presidencia 

### Country

UY

### Broadcast Area

c/UY

### Languages

Spa

### Categories (optional)

Legislative

### NSFW

FALSE

### Logo

https://cds-assets.cdn.antel.net.uy/imagenes/recursos/6qo1JPEkAV0VQNm20ijOnXCCxcDaX2PMWRnhisZm.jpeg

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/b3e079a4f019936d827aa323411273f5c7440ee9
