### ISSUE TITLE
Add: Camara de Senadores [UY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2343]
### Channel Name

Camara de Senadores

### Alternative Names (optional)

Cámara de Senadores

### Country

UY

### Broadcast Area

c/UY

### Languages

Spa

### Categories (optional)

Legislative

### NSFW

FALSE

### Logo

https://cds-assets.cdn.antel.net.uy/imagenes/recursos/0q3ZPmJVTfHvsNQgC4AuEiONcMvkKcNOZAgf7o15.jpeg

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/b3e079a4f019936d827aa323411273f5c7440ee9
