### ISSUE TITLE
Add: Siemprecine [UY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2357]
### Channel Name

Siemprecine

### Country

UY

### Broadcast Area

c/UY

### Languages

spa

### Categories (optional)

Movies

### NSFW

FALSE

### Logo

https://cds-assets.cdn.antel.net.uy/imagenes/recursos/YAusTi8KbxCp9QpjWvRWsyNDuKA2HuSuMAmm9KgK.jpeg

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/e53d232bf291f9d920684abe91bebfe1cad6124a
