### ISSUE TITLE
Add: Hum TV

### ISSUE THREAD

**Issue by yrazvi** [iptv-org/database#2387]
### Channel Name

Hum TV HD

### Country

PK

### Broadcast Area

c/PK

### Languages

Urdu

### NSFW

FALSE

### Website (optional)

https://hum.tv

### Logo

https://en.wikipedia.org/wiki/Hum_TV#/media/File:Hum_TV_2013.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Hum%20TV
