### ISSUE TITLE
Add: Opcion TV [DO] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2420]
### Channel Name

Opcion TV 

### Alternative Names (optional)

Opción TV

### Country

DO

### Broadcast Area

c/DO

### Languages

Spa

### Categories (optional)

General

### NSFW

FALSE

### Logo

https://i0.wp.com/opcioninforma.com/wp-content/uploads/2022/10/cropped-logo-opcioninforma-2.png?w=350&ssl=1

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Opcion%20TV
