### ISSUE TITLE
Add: Le Cronache

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2451]
### Channel Name

Le Cronache

### Country

IT

### City (optional)

Verona

### Broadcast Area

s/IT

### Languages

ita

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://cronachesalerno.it/

### Logo

https://cronachesalerno.it/wp-content/uploads/2015/10/adminlogo-copia.jpg

**Comment by freearhey** [comment]
I was unable to find any information about the TV channel at the link provided.
