### ISSUE TITLE
Add: ABC TV [IT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2462]
### Channel Name

ABC TV

### Country

IT

### Broadcast Area

c/IT

### Languages

ita

### Categories (optional)

News

### NSFW

FALSE

### Logo

https://abctv.it/wp-content/uploads/2022/07/logo-abc.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=%22ABC%20TV%22%20country:IT
