### ISSUE TITLE
Add: Fano TV [IT] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2531]
### Channel Name

Fano TV

### Country

IT

### Broadcast Area

c/IT

### Languages

Ita

### Categories (optional)

General

### NSFW

FALSE

### Website (optional)

https://www.fanotv.it/

### Logo

https://www.tvdream.net/img/fanotv-cover.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Fano%20TV
