### ISSUE TITLE
Add: Cerritos TV3

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#256]
### Channel Name

Cerritos TV3

### Country

US

### Subdivision (optional)

US-CA

### City (optional)

Cerritos

### Broadcast Area

s/US-CA

### Languages

eng;esp

### Categories (optional)

community

### NSFW

FALSE

### Website (optional)

http://www.cerritos.us/RESIDENTS/tv3.php

### Logo

http://www.cerritos.us/RESIDENTS/_pics/watch_tv3_live.jpg

### Notes

Streaming URL:

https://cdn3.wowza.com/5/UWpORHhLSEs5SkJs/cerritos/G0010_002/chunklist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Cerritos%20TV3
