### ISSUE TITLE
Add: Flow Sports

### ISSUE THREAD

**Issue by PrzemekSkw** [iptv-org/database#2589]
Please add Flowsports channels. I have on my list:
- Flow Sports 1 [Premier League]
- Flow Sports 2 [Premier League]
- FlowSports Rush Events 1-14 channels.

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_add.yml&title=Add%3A+
