### ISSUE TITLE
Add: Flow Sports 

### ISSUE THREAD

**Issue by PrzemekSkw** [iptv-org/database#2617]
### Channel Name

Flow Sports 1-2 [Premier League] FlowSports Rush Events 1-14

### Country

CB

### Broadcast Area

c/CB-CB

### Languages

eng

### NSFW

FALSE

### Website (optional)

https://www.flowsports.co/home

### Logo

https://w7.pngwing.com/pngs/683/355/png-transparent-premier-league-flow-sports-2018-fifa-world-cup-caribbean-premier-league-television-blue-text-thumbnail.png

### Notes

Caribbean soccer tv.

**Comment by freearhey** [comment]
Please read the description of each form field before submitting your next request.

**Comment by PrzemekSkw** [comment]
Hi @freearhey sorry for my request but I really don't know what to put there. I don't know anything about that channels. I get them from my IPTV provider and only want some EPG. If it's problem to add that channels don't bother to do that.
Regards.
