### ISSUE TITLE
Some EPG list show error 404 sometinmes

### ISSUE THREAD

**Issue by cooltom** [iptv-org/database#2619]
Hi, I am getting error 404 on epg lists :{

https://iptv-org.github.io/epg/guides/cs/m.tv.sms.cz.xml
https://iptv-org.github.io/epg/guides/cs/mujtvprogram.cz.xml

This repository has been disabled
https://github.com/iptv-org/epg

**Comment by freearhey** [comment]
https://github.com/orgs/iptv-org/discussions/12#discussioncomment-5019786
