### ISSUE TITLE
Add: ELTR

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2623]
### Channel Name

ELTR

### Country

KG

### City (optional)

Bishkek

### Broadcast Area

c/KG

### Languages

kir;rus

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://eltr.kg/

### Logo

https://www.lyngsat.com/logo/tv/ee/el_tr_kg.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=ElTR.kg
