### ISSUE TITLE
Add: CTS

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2624]
### Channel Name

CTS

### Country

KR

### City (optional)

Mokdong

### Broadcast Area

c/KR;c/US

### Languages

kor

### Categories (optional)

religious

### NSFW

FALSE

### Launched (optional)

1995-12-01

### Website (optional)

https://cts.tv/

### Logo

https://photos.live-tv-channels.org/tv-logo/kr-cts.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=CTSTV.kr
