### ISSUE TITLE
Add: Maeil Business TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2625]
### Channel Name

Maeil Business TV

### Network (optional)

Maeil Broadcasting Network

### Owners (optional)

Maeil Business Newspaper

### Country

KR

### City (optional)

Seoul

### Broadcast Area

s/KR

### Languages

kor

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

1995-03-01

### Website (optional)

https://www.mbn.co.kr/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/MBN_Logo.jpg/1200px-MBN_Logo.jpg

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=MaeilBusinessTV.kr
