### ISSUE TITLE
Edit: Gloob

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#2629]
### Channel ID (required)

Gloob.br

### NSFW

None

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Gloob_2022.svg/2504px-Gloob_2022.svg.png

### Notes

Channel got new logo

**Comment by freearhey** [comment]
Updated in https://github.com/iptv-org/database/commit/2c558987426ab14bf2c5a9882124f874cf61a0d3
