### ISSUE TITLE
Add: Next HD

### ISSUE THREAD

**Issue by nexthd** [iptv-org/database#2630]
### Channel Name

Next HD

### Owners (optional)

Next Entreteiment

### Country

PY

### City (optional)

Aregua

### Broadcast Area

a/PY-PY

### Languages

spa

### Categories (optional)

Cine:music

### NSFW

FALSE

### Launched (optional)

2022-01-10

### Website (optional)

https://nexthdpy.blogspot.com/

### Logo

https://raw.githubusercontent.com/nexthd/iptvnext/main/LOGO%20WEB.png

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/9bfda6c515181c86d798bd46460498feca544e8a
