### ISSUE TITLE
Add: Qyzylorda

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2633]
### Channel Name

Qyzylorda

### Country

KZ

### City (optional)

Qyzylorda

### Broadcast Area

c/KZ

### Languages

kaz

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://qyzylordatv.kz/kz

### Logo

https://cdn.qazaqstan.tv/regional/qyzylorda.png?w=420&h=196&format=jpg&resize=aspectfill&g=center

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=Qyzylorda.kz
