### ISSUE TITLE
Add: CTV19

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#2638]
### Channel Name

CTV19

### Country

GY

### Broadcast Area

c/GY

### Languages

eng

### NSFW

FALSE

### Logo

https://static.wikia.nocookie.net/internationaltelevision/images/d/d2/301903830_412663934303310_5561750642005333430_n.jpg/revision/latest?cb=20221220221554

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/db43f606ec836bb1535865c44e4c2a5ba3a0b1eb
