### ISSUE TITLE
Add: Sistema Michoacano

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2641]
### Channel Name

Sistema Michoacano

### Country

MX

### City (optional)

Morelia

### Broadcast Area

c/MX

### Languages

esp

### NSFW

FALSE

### Website (optional)

https://sistemamichoacano.tv/

### Logo

https://sistemamichoacano.tv/wp-content/uploads/2022/04/cropped-logo-smrtv-web-1.jpg

**Comment by Carlinhos027** [comment]
Already on list: https://iptv-org.github.io/?q=sistema%20michoacano

**Comment by AntiPontifex** [comment]
I understand this, and the other channels you've marked for completion, are on the list. I was attempting to complete _all_ of the database fields. If you look over the supposed completed records, you will see quite a number of fields were missing information. I hope you reconsider these entries.

**Comment by freearhey** [comment]
@AntiPontifex In this case it is better to use this form: https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_edit.yml&title=Edit%3A+

**Comment by AntiPontifex** [comment]
I did: you then rejected it. Please go back and check my original entry.
