### ISSUE TITLE
Add: Mexiquense

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2642]
### Channel Name

Mexiquense

### Owners (optional)

Sistema de Radio y Televisión Mexiquense

### Country

MX

### City (optional)

Mexico City

### Broadcast Area

c/MX

### Languages

esp

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1984-01-01

### Website (optional)

https://radioytvmexiquense.mx/

### Logo

https://s3.amazonaws.com/rytvmx/wpmedia/2020/07/14141848/logoNew.png

**Comment by Carlinhos027** [comment]
Already on list: https://iptv-org.github.io/?q=Mexiquense
