### ISSUE TITLE
Add: DTV Maashorst

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2645]
### Channel Name

DTV Maashorst

### Country

NL

### City (optional)

Maashorst

### Broadcast Area

c/NL

### Languages

nld

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://dtvnieuws.nl/nieuws/maashorst

### Logo

https://dtvnieuws.nl/dtvnieuws_nl/images/logo.svg

**Comment by Carlinhos027** [comment]
Already on list: https://iptv-org.github.io/?q=dtv%20maa
