### ISSUE TITLE
Add: WRUA

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2704]
### Channel Name

WRUA

### Owners (optional)

Eastern Television

### Country

PR

### City (optional)

Fajardo

### Broadcast Area

c/PR

### Languages

esp

### Categories (optional)

religious

### NSFW

FALSE

### Launched (optional)

1997-03-07

### Website (optional)

https://tivatv.com/

### Logo

https://tivatv.com/wp-content/uploads/2021/06/cropped-Tiva8-1350x250-1.jpg

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=WRUADT1.us
