### ISSUE TITLE
Add: ARtv

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2706]
### Channel Name

ARtv

### Alternative Names (optional)

Canal Parlamento

### Country

PT

### City (optional)

Lisbon

### Broadcast Area

c/PT

### Languages

por

### Categories (optional)

legislative

### NSFW

FALSE

### Launched (optional)

2013-01-03

### Website (optional)

http://www.canal.parlamento.pt/?chid=18&title=emissao-linear

### Logo

https://upload.wikimedia.org/wikipedia/commons/8/8c/Logo_ARTV.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=ARTV.pt
