### ISSUE TITLE
Add: Krasnaya Liniya

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2708]
### Channel Name

Krasnaya Liniya

### Alternative Names (optional)

Красная Линия

### Country

RU

### City (optional)

Moscow

### Broadcast Area

c/RU

### Languages

rus

### NSFW

FALSE

### Website (optional)

https://www.rline.tv/

### Logo

https://yt3.googleusercontent.com/ytc/AL5GRJUOrYkPM_e6Yl0JVxQRsv8WO7lwBP4D04Tw8oyQ=s900-c-k-c0x00ffffff-no-rj

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=RedLine.ru
