### ISSUE TITLE
Add: TVA

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#271]
### Channel Name

TVA

### Country

CA

### Subdivision (optional)

CA-QC

### City (optional)

Montreal

### Broadcast Area

s/CA-QC

### Languages

fre

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://www.qub.ca/tvaplus/tva/en-direct

### Logo

https://m1.quebecormedia.com/static-short/tva/circle.svg

### Notes

Streaming URL:

https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/02.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=TVA%20country:Canada
