### ISSUE TITLE
Add: ICI Montreal

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#272]
### Channel Name

ICI Montreal

### Country

CA

### Subdivision (optional)

CA-QC

### City (optional)

Montreal

### Broadcast Area

s/CA-QC

### Languages

fre

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://icitelevision.ca/live-video/

### Logo

http://icitelevision.ca/wp-content/uploads/2017/10/logoretina.png

### Notes

Streaming URL:

https://amdici.akamaized.net/hls/live/873426/ICI-Live-Stream/233bc8cf83124bde9c6d55842e5de3ab/1.m3u8

**Comment by freearhey** [comment]
Already in database: https://iptv-org.github.io/?q=CFHDDT.ca
