### ISSUE TITLE
Add: Televisa Tijuana [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#2729]
### Channel Name

Televisa Tijuana

### Country

MX

### Subdivision (optional)

MX-BCN

### City (optional)

Tijuana

### Broadcast Area

s/MX-BCN

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Logo

https://xewt12.com/wp-content/uploads/2022/05/logo@2x.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=XEWTTDT.mx
