### ISSUE TITLE
Add: TJK TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2739]
### Channel Name

TJK TV

### Alternative Names (optional)

TJK Anasayfa

### Owners (optional)

Turkish Jockey Club Association Horse Breeding and Racing Business Administration

### Country

TR

### City (optional)

Istanbul

### Broadcast Area

c/TR

### Languages

tur

### Categories (optional)

sports

### NSFW

FALSE

### Website (optional)

https://www.tjk.org/

### Logo

https://www.lyngsat.com/logo/tv/tt/tkj-tr.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=TJKTV.tr
