### ISSUE TITLE
Add: Kibris Kanal T

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2745]
### Channel Name

Kibris Kanal T

### Country

CY

### City (optional)

Nicosia

### Broadcast Area

c/CY

### Languages

tur

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.kanalt.com/

### Logo

https://www.lyngsat.com/logo/tv/kk/kanal-t-kibris-tr-cy.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=KibrisKanalT.cy
