### ISSUE TITLE
Add: Rada

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2768]
### Channel Name

Rada

### Alternative Names (optional)

Парламентський телеканал «РАДА»

### Owners (optional)

Verkhovna Rada

### Country

UA

### City (optional)

Kyiv

### Broadcast Area

c/UA

### Languages

ukr;rus

### Categories (optional)

legislative

### NSFW

FALSE

### Launched (optional)

1999-03-23

### Website (optional)

https://www.rada.gov.ua/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Rada_TV_%282021%29.svg/1280px-Rada_TV_%282021%29.svg.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=RadaTV.ua
