### ISSUE TITLE
Add: TBN Ukraina

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2770]
### Channel Name

TBN Ukraine

### Alternative Names (optional)

TBN Україна

### Network (optional)

Trinity Broadcasting Network

### Country

UA

### City (optional)

Kyiv

### Broadcast Area

c/UA

### Languages

ukr;rus

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://tbn-ua.org/

### Logo

https://i.imgur.com/ID7ZQLn.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=TBNUkraine.us 

If you want to edit the description of an existing channel, please use this form instead: https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aedit&template=channels_edit.yml&title=Edit%3A+
