### ISSUE TITLE
Add: Dunya News UK

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2772]
### Channel Name

Dunya News UK

### Country

UK

### City (optional)

London

### Broadcast Area

c/UK

### Languages

urd;eng

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://dunyanews.tv/

### Logo

https://i.imgur.com/dtrTfZC.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=DunyaNews.pk
