### ISSUE TITLE
Add: Sky News Arabia

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2776]
### Channel Name

Sky News Arabia

### Owners (optional)

Abu Dhabi Media Company

### Country

UK

### City (optional)

Isleworth

### Broadcast Area

c/UK

### Languages

ara

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

2012-05-06

### Website (optional)

https://www.skynewsarabia.com/

### Logo

https://www.skynewsarabia.com/asset/1643193804/16.2/assets/img/sna_logo/header_logo_color.svg

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=SkyNewsArabia.ae
