### ISSUE TITLE
Add: Telekanal Nadiya

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2779]
### Channel Name

Telekanal Nadiya

### Alternative Names (optional)

Телеканал Надія 

### Country

UA

### City (optional)

Kyiv

### Broadcast Area

c/UA

### Languages

ukr;rus;eng

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://tv.hope.ua/

### Logo

https://www.lyngsat.com/logo/tv/tt/telekanal_nadiya_ua.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=Nadiya.ua
