### ISSUE TITLE
Add: US Weekly TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2780]
### Channel Name

US Weekly TV

### Owners (optional)

a360media Entertainment Group

### Country

US

### Subdivision (optional)

US-NJ

### City (optional)

Englewood Cliffs

### Broadcast Area

c/US

### Languages

eng

### Categories (optional)

news;entertainment

### NSFW

FALSE

### Website (optional)

https://tv.usmagazine.com/

### Logo

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAABQVBMVEX/AJn///8AFyIAAAD8/Pz/AJT/AJH/z+P/6PL/AJr/cbP/JZn/sc//E5f/nsj/AJdCFTP3BJgAFxzeAIX29vbj4+O3Bm8AFh7t7e0AAAuEhYb2AJOSDFkAEyDY19cAGQrOzs//+PsAGADDxMQ4ODkADhr/ibn/abNPUVRAFiff4OAlJSRzdHQAABLW1dXjBY23tbWEEFCrqaoADgAAGBFCQkL/AImjoaH/3Ov/5O+XlZX/p80AABX/Np6+vL3/k8L/SaNpamtcXV5AACBCJDD/wdv/f7n/Vqj/vtn/b7JEIjggFiMaGyNKS08RER4lJCgWFxhAACRCKzZCOT3jSJnvcbG4rbJeaWSySH3/Z6vNRY2SfobeQZSHjourd47AaJPSWZepipa6d5ji0teDOl0eHh3PpLfdwczmiLXwmLvKA3mDLV+HAAANbElEQVR4nO2dC3fayBXHGfQivNTuirXAFUULMoQAoWwxL/PMgnAb19lNsq27mz52u9203/8DdGaEQJKxGEaSg0/nf06wDPJIP+6dOzN3RpNYjImJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiSlCZUgkExYmh1lYSJJXo+xBTWdkd5W5JigsO44YySOxDw4rkRSICkutCQoD1cc1oiiFSZgmKExnhCGLETJClxghI4xEjJARusQI/38Inx2rEydU3NKr578+VqdNqBRuai794VfH6o8vA1jxEQgbXN6ppvHZkTr78tQJ83Ejz2nNfFPL5414XLNI0VHTPopDcnwG/vgKvgH/Bn6AX+KnT2jcNApcrbF4PW/cGNrtvIGEjhbWkRY35o1F/qbR6Brxq3nhJg9BbwqNSr7SKNSMJ0DIFRTAtUGpVlSG3NVNXeGhelyzW0YHYPgnjSvxkxdleEZT43Kgx8U1o6HAk4eq0ngKhM2KAhZ1kCuoaoFr3uRAqT2ZNOBRCbTak3IDEhZBqQdyDUPTOBURxo3KBJQWJTC51Z4AYZyrg6EC1A7fqjURYbs3vH2tNbslUO4Vbl5rcUioqsoQVjqbUMvPVaWkqourp1AP49wElPm62gITQ0OEiqJyWjwPCXm+1W3GESEAfAdGGpswbrzuIQ+G+E+CsAAUvq0osPLFEWG53eEMTNhqD19YhEoR1OfchjCfh19ArQVKCP8pEGocavlVAKshJix0byq3BiLsdW+6t9hLS3MVdF4biLBTqUHXNW7boHNrPA3COLxtpdICxVoTEyqqqqJYWkJHSu8NijRlrgPUOYcIFVXJLZpPghC1BRZhGxQhwQQ639VNEfdPe5wBWwt4ABAhbC24ucpDIi6HPlVtQu2JEGocx11xHO6+GBwWhIVdnc0R+lyDHxia/fEVCqfooydCCG8XdcjicesQaXekWUebF9fH1h+cLiHqsfCw5224dIZ701DGHqH3zz47w5+f2T9OlhAD8mqh0kWq2Pr6OdSrV988//rbt2/fdm1V3r799tuvn3/zzatXz706TUKLD4YSGDdzuXq92CqVyuXy5Lt35+cvZ++q7z+ml/1BTt0MjNVcoi8t0/95X333bjY+x9qOgIMM8qMmxDcPETeEk0n7u/fmaiQl9Aevpiek9DRpzlIxWY6dcBbDxZdDfNB+7Xa7XOonCC7JQ8yLazMlCEHzVhERegxo2a/dnpRyCsH1tteFlHdjUTxpQhuwXIZ8RfUIPEv6YJlNjkUhRu2pURJiwI2HQgNS8G0uv8xeZ0SyW3gswvuAnRItHy5vsByZlBUyOsItIKyC7U79mPq3T3qWsjpGQuhoCC3AdhADbu5hdWqElgktwElwQNAnXNPzGIS8E7AVjgUBWNK2GVES5nJWFA0DkLoaRkW49VEImAsBECRoQ2lEhE4fbfFhEErUHZvwCXcmxIDlMHwU6KPLUyPc+mg9DECgV2m7NNEQbpwUmbAUtKW3NKDvfUdGGKoJwfLyhHreWydFJpyEY0J9Re2k4RNuqyE2YSkUQJBIUQNGQriNM+1w2kLYVlBH0igJsZOG0hYCQN2hiY4QddjCc1JA2+uOiNDRGBbDAUwEydSETeiuhgf7M/pAkpaSJPV9sosBxhVRElrDpgNtxWA1Tm01q06Xg/3nEV7+sQmhkx4INJI7uyQLopi5G+2hDJROjIbQqoadsm+p+r68hCBeiivPPfXpOzSfljBxt7fUZzEBQeo7+09PzIa7QNPxbyweIMSQ4mUm29d168QgbcUnJdT9bPNMFsW7dB8xBmoroiNslSaHCIE09p92EcTxVEqA9NMlBFI15c8oi5nkOuCq6U9KCPT0aiaK/oYM0hZ+ekLIKI0QZFCMT0Xo31psS5dGUzMjBp4KfTRCfkc4ISKE0vtLaEohElNGRVhEhG1SQgSZ6K+nZgSQ0RHC9rBzZJYGjjSyJow8gVYmPAahsiWkmNVO9LPjSyFExkj7pR2qXCKv91eXl/QT949I2O6RBdM90kfCZUixNdLxYa8dIBO1NP27Ap+a0GouOoGyidJdGDtMRJqn6dC7KRa/NoMzhku4tnJtu4pIEU3dV56OH6VfSjptkFruMsKYsNMLnDGVHhwnkxIuQyQcLz05705gI6JlJsF6rGESymPJPW8BjTgsB07s69NAiALJg61gSkg4cEyQFnE07Q1bQQmDTVvEhBHJJUYZIsJZ4t4kd2fYC2H+aSrS93CEKckV1mMSP5FnYLdQIQdjjWXEEBD1FT2isCK5gkSU0JOrwLGmDccaCzH4VPfApI6o+K4OKkG0FCKTBcBlRLzsstcbhlAXA0zOmCTlkwXTlOQk3NZESFg4Ziz8wB1QI6Z0kgtMSUJNKmETOtabbBALQdtFiSjY7b2tB2a0POUTVER5DLyExR3ivBOsYaReX7pxrUPSCfpO4npH6PDTcttCbMwPTSf6K00bazJEDSIYHV7vcalvznWugbaMaDnqvDFR6Q3Zpw2n8gVR+YdXP4rblnWfn2LExrzR+UmnhNQvKN1UviO7QPZQTRf17bkeI+4QC40//yW5HugPXsVH/IjWhmOSh3QO10TR4e3elewbP0WIhb+iGaVlnwJySbkwCg8ISNT37bmJpvOenYTW4yTYiBDx+x+exWRRnFFAknWs9ihFFmpgMPPJKAgzV6PjJcRGRIgf/mbtfAkhzWlaInOfjfq0Y2E5SXqJdOahS4imyxF4D6Hlpgjxw9/Pt9eFllxll+SVkjSXcp9wRvxNpsf7w5lYdXu695GZCXJTy4j/cI4RZFEY36GHEckIaZdgymOSYb4lKbln5kRMXXg2QfW0FuUNICT85zvv1QUhM7u7SBP0rKgJYzLRAGpzlXQVTWdaj3WiV0HMrJa656ztAAqb0LYgJPzw474tn2RBHpvJe6V4Rd0gxgTzmAqfQNNDl5eXoohf70bS/TtzmbCUa3V6FiB00oe+ZQi5OmBH+uGFPCbaHHd3pcRAWqZHo1F6KSXsNS/3Ce32vqjwShHRwThzz0ldkCv/bzrAUmiycf59Cp+Pds91TXAOg891YGv/4Ue/XIR8YLs3WA+fodVEeFbK/kdIaJJsl3wMO+8IM/bAkC8Nv//B1wqy3bPllX2C46fzPSJDJEpHURDChsL5wIW+vk75rEiwbwM7+H399P7zl5979PJzss0IhGuiYTA54S5P410mrEsXs1RGlvdg2l4Kq21hn77/1+/26AsyX80Q5YWJAZ0J0/upRL6fXs3GEFNwcsrbSMOrJW6/voL6va2v8G9f/oaMUEge1UM8ROh8sOuBcf1gPa2aMwiK0KDjpsYzO5QiwrOKV4Z2i368MDb7oxj419e/JSQk3E39GMLNVL7f3JM+kNajiyTSarTcfseI8EXZox7XnE/gz/YGsdntod+6X5EShlgTXZNPNM89YULvm0Uuv8BlNfCmPFqzgJxjUiEmjAkjPSiafYPOCUSaZ5wxode5S5yR76EWuPQz3qeogjKwSiNPWg/RAI9wIHzw/pxxpkMzt7bXhi0uzs2REfkF2rIov0BfXbnbJK6HcIQQUrBxz5DSpPMxYatYLLbq6PtR0GGxzcWNNzhzPuG0uPbzEJ1YyGtHEIbkp65H1zpUj3HjWFpbLBa1Ifrz3AIdd9GGYQ30O1/JwziDmtlWLR8/hlAmyw0fJnREUqonuxAh3uPUIqr/jHd4RZXvDV7a0YOfNvBB3jiKMCYQZt0OExIuZfchxC0Chyc76nYTaL+hcM0KQs3N4WlHEULE8AitOW6qudGHCY08rtcFrot+dNDub8cRxgTC7LAvoGPlHt2ir4cJ41wPtSJ1rgNf1QY660jCmEgzUvQQOtsKujIeJmzeYq+oIc7ybZ6CELYZ4RFSOqkfYZzDc3S4Nn7AJx1NGBOv9VAIUTWkXJnoS9i1259WN09HGHDA7wo0lMv2/AjRbrZYCmwzKAlhRD2Y1yMkpFxl4k+4sHqs9Ro2IRVhTEiNqBtGFyHlRKEvocbhNpZvWyakI4zJQnJPEvQIQiuBQbss0ZcQ9r9xrJlbp1ASwngzy9LVxq0Ni6V/f6T8mvwJNbxtdJkzghFCM5r7HsglJVTrv3ycCbPViGYm1EOYcxPC/jf+3wjiAQlhbcxUR8fbcdPx/uWjGZPh15QxV+mjIXeEDbSlcNFDaHAqKL4xghMiRnN6rKPxPLzB5YVpZ9EEIWUms8eVsiU0Kuj/GJi/OXMRwpr4wa6FAQnh/cmz5LHO2s9Wx65sKJ4+W63Jw/OWcLNpsgfw7Mz5XkBCVB9Ts2tib9X7WXOWuZ/URjNLM/NiPSBrP5QiFz8jFHmexgdSRrnM9aHqpOM8b2ZfMtumhOVURwentXXpPz98Qa7/hvL0kCzLmVTKvEhL/fuzaXoCPzyYeiBX7y4nBstJmavsuj+4v3JIH0jpC1jQ+bl3esJPYQDa9ycIoihmZuZd8mKj5J05luGbxz2saxUkOEtaXcOS8LuP/P+w7hW8wZ0Omc23IHdJ4d0hExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTE9PJ6H+uYIXNqOCQUwAAAABJRU5ErkJggg==

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=UsWeeklyTV.us
