### ISSUE TITLE
Add: QuaHZ TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2782]
### Channel Name

QuaHZ TV

### Country

US

### Broadcast Area

c/US

### Languages

eng

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://quahztv.com/

### Logo

https://quahztv.com/wp-content/uploads/2017/08/logo-red.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=QuahzTV.us
