### ISSUE TITLE
Add: Retro TV East

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2783]
### Channel Name

Retro TV East

### Owners (optional)

Get After It Media

### Country

US

### Subdivision (optional)

US-TN

### City (optional)

Chattanooga

### Broadcast Area

c/US

### Languages

eng

### Categories (optional)

entertainment

### NSFW

FALSE

### Launched (optional)

2005-07-01

### Website (optional)

https://www.getafteritmedia.com/retrotv

### Logo

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAA5FBMVEVbh6VfjauAueBejKpgjatejKlgjaxciaZdiKdjZGbqoDhjYmJbiahZhKFgjKyCvuZ9s9hxosNlaW5hXl1gc4J1mbNqeYXwoS9dfZN4o8GHj45cgZpefJF2nrphb3phaXFnl7h0qc3JkERwjKF8rc58r9JgcX5fdohlhp1llLXnnzlzkqlsgI5uhZdsfoxVjLCek3/EmF2yjF1RY3Owlm/Ylz+hgVx5j5q9mWbxoSpKcY2YfV2WkoWsgU2qkG7Rkj3Mm1d9cGJVXWVYZHCGhH68iEWdhmmQd1yMkYt1gISNf212cGmFz3VRAAARRElEQVR4nN2dD3ejNhLAZRMLWMAQIH9cbEjq2N7Ecdxed7vd9vZ6m16vd7ff//ucJITRSAJsp90YzXvdZxOQ9NOMZkYjkiL0UrHxmAvG9L82OWuQwQuFtm1JMuLyYkCAaCghsgemEyI0ECzVTEKEsemEyMKmE1aIBhOiETadsIwaRhMyRLMJKaLhhCT2m07YhWgAIbLP2hhNICQZXAuiGYTIakY0hJCkN6YTolGTFo0hJBmc6YRNUcMgwgZEkwj1iEYRahHNItQhGkaoQTSNUI395hHKGZyBhFJ6YyIhTG+MJAT+xkxCEdFQQgHRVMIa0VhCZBtPWGnRYEKuRZMJywzObEKa3hhOSLRoOiFZjKYTEpdqOmETokGEDYgmESLbeEKtuzGLUIdoGCGyLdMJ1dhvHiGyBqYTSlo0kRAGRiMJgUs1k1BENJRQQDSVsM7gjCXcuRtzCWkNznBCEhiNJ2Sx32xCimg4IUlSTSckgdF0whcjnj4hiRqmE75Qi30gpG9Pm074EkPtB+FLEHtCiOyjA2NfCJE9OjK76Q0hzeBMJ0SjoxD7RHhcYOwVIf3NKcMJj0HsG+HhiD0jJIimEx6O2DtCgnhYetM/QoJ4UNDoISHV4l6MGL8eYUDl+Mf3Q9yORttXIgzObqMoOj87mtG29wiM2++uPn4/wK9BGJyHQyrh+V+JiN9+fPPm6m/bVyAMbkvAFyESxg5E/M3Vmzdvvl3hr094XwESxLf+sa10anFbEv6wZYTbbY1HPv+lhMHtsJbJ6kWIbSqcv6OE73/8+4ct3s5/ejevFDl/99MH6y8ljATCYeIc3RCx0xbEDx8pIFmJVx/fbT9cXV09+JzwgVyqEP9ELkFEwDC5Pr4hitiU3mzflYAM8uefyJerXxji9u/08ydkfS1C73gzbUXE333cEb7/4R8U99efqZ1u/0mZf1kNvhph+gLCNsTtj+8p3cP799967ltKeBVTwjnT7XPaE0KK2HT+tv1c+tLnZy/dfk8/fwoG1pap89Nz9rJ12JqS2X8mIWkOBTZRjUo4LqPFb9fTDI8f6eeHnwkh1eyVFw8UQjpkcdgBbVqDQdjw/c35+c0N1v6cXISeZqnMRxDY4hXy0dZPGO0L39yQvm7uB/ZIouQR/zcW8bffUrDP2CovPk9lwgDfEh8fndu8p+B+MaTf5Y4DfB4NeUAPh9HtvTw0csO5SDi8mN0SOb/f3cebvqkuBOc0uizula5IU4thuMseotsbC0Bywh9Y1jb+F/3ye7D9iZG6csQPbqp2yo6rvCuMHNDnTRSC4RPKcwSGdivdsLsxwuV9ddOYfbd5k+Et1DM6l/sicnsv+B1AiP0H6mDSLcsCKj9TE9Z5VnhGm1/s2oyyHaPKV4qo6Eh3Axdcaqxugz7n13MgtEP4GhpZ3NtaQmv7bxoG//gPC4yuLeU0YhYSrXwx7Qo3ld3aiy71kOG3AA4XU+JzsJCzXgRwSnY+qTYpjdxaIx0hzqgOv6XL8eG5GEiEQqo8DC8D8etwlvvl6mkbPF9UQds9wzAPYM46LJD4NXzM+Hia5rLqbQQI+d5i+6lKAD651xiuQzD14XoJmlsk5ay2dhqWiH77TZvUBzlrWNjiA+GaTWYwaMWjcm7XhG++jKwxJcT/5Wncletiq4VweDEH44ySrBNwh9hOOI8lwvwO/Hzt+dQZdwISr0QR8YerMvN+882WEvq/loS/P68G7YSwtbtkiqDd6jt9SxrK2hwNsX9XIlyDZsM5NZc9AKlXIogYVWb5ENB0Df+vJP7s2e06hKMM14TQ2qfXKWnoom0mokQilLvKPYScfbqiXsqimSm3y4ffKOEgYInqr885lvf4bS4wdL3rQFZNyES6OMscP10MGyW89ApfaUqQO2UG2uQtUeL1j8RGycbwM0u5rfEX8vXhi5cNDiAMHz1PXoThZJPHcb65ky4/kZbiu6aQMrxMvLSVIPYKNQzSmYwidT6Hi2uCOHU///HHl2e3JBwE3i9/uG48UOo0TYRhGF0mboHgxbs48VzX9bwkh179juwEs+TyYgbun5WyIQ95gdNEGIYT0uJKXoRhtM4TKvlayabWdCmm5VCmZQEDZ/RbhvckDBfrSzqsDITf8CKhrcRFXrhJMgHePifxIvMSF1xMSiEj8UjE1xKG4d28oM3CaElkk9DLbDqTuazGlIYMe5qupnZVa8NZmjLAPQjDSV4OawXSjnBCu0wznwjK8gSsuxlRoh8ULmiHDo9JkflyDaeaNJdZhZthCLFw6QDcYpmmy8JLYtkHZiwqkpRmvKsm0iuaaqKO8JLh0WHBSEEAi8DnuaqfxeCHLmFw/AyMw8uvp0SywJfzQ34DsXqqJTcPJBUuEmosU+QzCVZuIvmxvEpQO+ulKmHEZq+YkmGBbsMNmVJhR+tMxegZXpZVJ0iYMn0jR8mAy5/PKAexCuTDB8l8UQvyq94c30898HT4xI+ojiGkjefEFB0p1yQhzUXihspfikq8KHNYmVC4XyZkVk9WArsHLvhHMskZqA/400tgMpP0WB2SyEXdQkkC1sZF4l3DosRUTLzukkMJ6ZTFnAMaKbFRL5MKID5M84besYRkXncgMCunQRt2GoAkL2G7yf0JqaJi7c/CuUd9ryxPwE/HWTehrSEMC7cucsKJjd1Maslfi0+608N0SFW42/fCCpbrypNJlZiCWXhcdZ+Q2rZKSLKn3NcPSU0t4NzEbGb2JoSKAushIutBAUROJqYT4brYw0opIiSk3QaOfkgdEubLwwhj0erBHnuSxNoqpGgywwt3j1NuWnGVCHOvVmHHtl0mLPKDCImiahXC0sVFkmdata:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAA5FBMVEVbh6VfjauAueBejKpgjatejKlgjaxciaZdiKdjZGbqoDhjYmJbiahZhKFgjKyCvuZ9s9hxosNlaW5hXl1gc4J1mbNqeYXwoS9dfZN4o8GHj45cgZpefJF2nrphb3phaXFnl7h0qc3JkERwjKF8rc58r9JgcX5fdohlhp1llLXnnzlzkqlsgI5uhZdsfoxVjLCek3/EmF2yjF1RY3Owlm/Ylz+hgVx5j5q9mWbxoSpKcY2YfV2WkoWsgU2qkG7Rkj3Mm1d9cGJVXWVYZHCGhH68iEWdhmmQd1yMkYt1gISNf212cGmFz3VRAAARRElEQVR4nN2dD3ejNhLAZRMLWMAQIH9cbEjq2N7Ecdxed7vd9vZ6m16vd7ff//ucJITRSAJsp90YzXvdZxOQ9NOMZkYjkiL0UrHxmAvG9L82OWuQwQuFtm1JMuLyYkCAaCghsgemEyI0ECzVTEKEsemEyMKmE1aIBhOiETadsIwaRhMyRLMJKaLhhCT2m07YhWgAIbLP2hhNICQZXAuiGYTIakY0hJCkN6YTolGTFo0hJBmc6YRNUcMgwgZEkwj1iEYRahHNItQhGkaoQTSNUI395hHKGZyBhFJ6YyIhTG+MJAT+xkxCEdFQQgHRVMIa0VhCZBtPWGnRYEKuRZMJywzObEKa3hhOSLRoOiFZjKYTEpdqOmETokGEDYgmESLbeEKtuzGLUIdoGCGyLdMJ1dhvHiGyBqYTSlo0kRAGRiMJgUs1k1BENJRQQDSVsM7gjCXcuRtzCWkNznBCEhiNJ2Sx32xCimg4IUlSTSckgdF0whcjnj4hiRqmE75Qi30gpG9Pm074EkPtB+FLEHtCiOyjA2NfCJE9OjK76Q0hzeBMJ0SjoxD7RHhcYOwVIf3NKcMJj0HsG+HhiD0jJIimEx6O2DtCgnhYetM/QoJ4UNDoISHV4l6MGL8eYUDl+Mf3Q9yORttXIgzObqMoOj87mtG29wiM2++uPn4/wK9BGJyHQyrh+V+JiN9+fPPm6m/bVyAMbkvAFyESxg5E/M3Vmzdvvl3hr094XwESxLf+sa10anFbEv6wZYTbbY1HPv+lhMHtsJbJ6kWIbSqcv6OE73/8+4ct3s5/ejevFDl/99MH6y8ljATCYeIc3RCx0xbEDx8pIFmJVx/fbT9cXV09+JzwgVyqEP9ELkFEwDC5Pr4hitiU3mzflYAM8uefyJerXxji9u/08ydkfS1C73gzbUXE333cEb7/4R8U99efqZ1u/0mZf1kNvhph+gLCNsTtj+8p3cP799967ltKeBVTwjnT7XPaE0KK2HT+tv1c+tLnZy/dfk8/fwoG1pap89Nz9rJ12JqS2X8mIWkOBTZRjUo4LqPFb9fTDI8f6eeHnwkh1eyVFw8UQjpkcdgBbVqDQdjw/c35+c0N1v6cXISeZqnMRxDY4hXy0dZPGO0L39yQvm7uB/ZIouQR/zcW8bffUrDP2CovPk9lwgDfEh8fndu8p+B+MaTf5Y4DfB4NeUAPh9HtvTw0csO5SDi8mN0SOb/f3cebvqkuBOc0uizula5IU4thuMseotsbC0Bywh9Y1jb+F/3ye7D9iZG6csQPbqp2yo6rvCuMHNDnTRSC4RPKcwSGdivdsLsxwuV9ddOYfbd5k+Et1DM6l/sicnsv+B1AiP0H6mDSLcsCKj9TE9Z5VnhGm1/s2oyyHaPKV4qo6Eh3Axdcaqxugz7n13MgtEP4GhpZ3NtaQmv7bxoG//gPC4yuLeU0YhYSrXwx7Qo3ld3aiy71kOG3AA4XU+JzsJCzXgRwSnY+qTYpjdxaIx0hzqgOv6XL8eG5GEiEQqo8DC8D8etwlvvl6mkbPF9UQds9wzAPYM46LJD4NXzM+Hia5rLqbQQI+d5i+6lKAD651xiuQzD14XoJmlsk5ay2dhqWiH77TZvUBzlrWNjiA+GaTWYwaMWjcm7XhG++jKwxJcT/5Wncletiq4VweDEH44ySrBNwh9hOOI8lwvwO/Hzt+dQZdwISr0QR8YerMvN+882WEvq/loS/P68G7YSwtbtkiqDd6jt9SxrK2hwNsX9XIlyDZsM5NZc9AKlXIogYVWb5ENB0Df+vJP7s2e06hKMM14TQ2qfXKWnoom0mokQilLvKPYScfbqiXsqimSm3y4ffKOEgYInqr885lvf4bS4wdL3rQFZNyES6OMscP10MGyW89ApfaUqQO2UG2uQtUeL1j8RGycbwM0u5rfEX8vXhi5cNDiAMHz1PXoThZJPHcb65ky4/kZbiu6aQMrxMvLSVIPYKNQzSmYwidT6Hi2uCOHU///HHl2e3JBwE3i9/uG48UOo0TYRhGF0mboHgxbs48VzX9bwkh179juwEs+TyYgbun5WyIQ95gdNEGIYT0uJKXoRhtM4TKvlayabWdCmm5VCmZQEDZ/RbhvckDBfrSzqsDITf8CKhrcRFXrhJMgHePifxIvMSF1xMSiEj8UjE1xKG4d28oM3CaElkk9DLbDqTuazGlIYMe5qupnZVa8NZmjLAPQjDSV4OawXSjnBCu0wznwjK8gSsuxlRoh8ULmiHDo9JkflyDaeaNJdZhZthCLFw6QDcYpmmy8JLYtkHZiwqkpRmvKsm0iuaaqKO8JLh0WHBSEEAi8DnuaqfxeCHLmFw/AyMw8uvp0SywJfzQ34DsXqqJTcPJBUuEmosU+QzCVZuIvmxvEpQO+ulKmHEZq+YkmGBbsMNmVJhR+tMxegZXpZVJ0iYMn0jR8mAy5/PKAexCuTDB8l8UQvyq94c30898HT4xI+ojiGkjefEFB0p1yQhzUXihspfikq8KHNYmVC4XyZkVk9WArsHLvhHMskZqA/400tgMpP0WB2SyEXdQkkC1sZF4l3DosRUTLzukkMJ6ZTFnAMaKbFRL5MKID5M84besYRkXncgMCunQRt2GoAkL2G7yf0JqaJi7c/CuUd9ryxPwE/HWTehrSEMC7cucsKJjd1Maslfi0+608N0SFW42/fCCpbrypNJlZiCWXhcdZ+Q2rZKSLKn3NcPSU0t4NzEbGb2JoSKAushIutBAUROJqYT4brYw0opIiSk3QaOfkgdEubLwwhj0erBHnuSxNoqpGgywwt3j1NuWnGVCHOvVmHHtl0mLPKDCImiahXC0sVFkmqPdMCGa5bYe3gagihZaeJldYuHESaHERKXVmPIhPoTnbMQPB/Y+/hSG2b0xE0LYzrISieHEZK951KwFokw0+oQmPIsyej526GEfJhHEIZFibM34SYRAwIgJOrRASrTQN+96Y4WkHAGug1a9rQy4GPiHeRLyQOBoKgz6EsDnQ6lohkjtK3OaAEJ6cQITU7AeJtlOCloFnJIxCcJhDj6t+A5VxxFow1k/PytjdBWCcHswdQ6bhSP7hCKg7I2Wpqqf+Rcw5xGe7IKyjhkVQQ2E6uV0FYIQZtvxWrxutyQNgl3wvsTijHPyYC5RLp4KHt91+ZijdoI7VbCFei2hdDzqhR6f0KQmAVgFx9udM4UANKsgBOi0eBoQrB5CJ/yVCfL5TJdVQGs7YS0jdDPYU6oHq3CJJlsVvOK0Eb26FjCDMxslPqK8PHtxiNl0PsTpnBvtJB9jVz086jrrhEHRxLCmQ1niosLbiLxwFP2Bk97EzrZBhJEDjxShIDhRZl86bV4COESxgvpWDhwypKicMAJdDhc5OD2FkLku3J6cVMfMQfy4SutcZX96RB3hE4nIZKqTcMFFrq1d4+yo9XyIhzl4gbje8xPitsJ00e5KBrdOOxN1QDLlRbq13nyVSPqCCkiOMVTCH13Jk0eGXP5guyN+OBdZY7K+UxI95Wl7lsJEUruhopEt7e3mtQxooWIymp2orFSitiuQ3/qKc3TSrvCUT2XaYZJ1RF0EvpprHtU21zuuXW+oCIK65AgthMSJT61b+0rwim30pn+57OgU4fIk+20qbN54orvkymIO0KfInYQoutkvUe/UVL1uGm4u/C7CP3pXl2VVdZYfHJHiGRCiqjkpbIS86T1YLDsdF0R+kXDHUXWqcO9uuJlZFjXlBBrK/VlX0pGqu7M3M5+w0VSWY2f6m8OL5cO2IyFuaac5qpHMEpD9HRILLVIhmrDdUgRQXb9lJRbKlEyr6PfcOLV6yJTXRO7h2w94BpVqq/0YTd56gDcsOxYeVJAxCDi+7aVi7aTeEhBpIdmuf59obLTOZ3VaXW3q/UXd7R4INTlia3JemBduV7jOeuwPsnRbB9FLYKcxserut/wyfMQUpToX3tesh7qOw4nMZhV4i803jeMiWH5sWDBqqXx2XSTx4bpDKNSgUrBHxKi+p0oltPgLKncH7MApCqRIrqJp5zEstPbvOy0dt5+nBQLOU2IPZKD+KuE5w/hkF1Qx8kQvWRzp5Sfw3CxKU8atYBaxJLQHhdJMRnySgTbqGsQ2QlycnlRH6rTD3fzmHcq7skzeuesLnpEs0s6C0vHCbzkaUGvXHie2/CGNO+qWN/V5/fk02Kdl13JZ1I6RNsWM2/bD4gNerwSUXZrq2sxKOihYpLEl/OL2WQyma03uVf16QLfTcfI7txs5pvHyzgpj/5JluWvSFduESflYmp6kT9n95PMc7NmXV1sLl1+4k1su+EhHWJ1xcqEzXrJpmrR8VeuV52qs7P5io52KuVfGb+TCb+JeU6CWD/V+PqwPy27UvvyXM2RlB7REgidGtHL7CZEQpG6u/EJ5YtctRo/i6U7vYL/pEL0Yvkh0NVK0xW5tEJtgAri7rvjBzFdGLTWYjcjElNdxZ7YM3ki1a8KR7yT3Lbanf4z/ZB5Qa2/bOKj6xxCel4x7eCTEEdW/dWxx9fpMs12pZ0GRMf3s1Uec/uL81V5Fq4dIr2ziEkCWSzpbcLYp0t6pWusFDIteFdukU4Dv/sZCVH45th4bFm7yk4jIhs6SaGzLAscv6PLupgDZ8F3GudF01dG+6If9vwFIxFR/MI2w/zfDkTEXq1wjv+NpsPEQfuycWkgrBD30eKpi0LomIu4ixYCogMQ7Z4jAivVI/Zci2gkAToIGCq/95UHe5xUhCOZENmqQ+0xIrJUJRqDyAkteSHqEHtsqLQu1YXYY4/KCZsQRcL+KrGsLWoQ0f7520lLVSDeD7GfjLwELiMirUd95bEeJ1UFXNUh06IBa7E6xlB1SMQxQYtjHWKtRAO0OB43+xozEK0SsdahYxqidSBi/2IGgRvrAkaNiHqOKLyeYSuM7A4ZsW+GutOh6GyAodo9R7RqxLpUKisR2T3O3xihqkVxJTpKdtMrRCwi+s2I/d0u4j0R+2uoGCIqK7H/iBgiNkXFHiNiiDhqQqRSXy2/vdqgDxLMEceVEmtEGBXZP33UIq4RYchwKu8JEO3+IY4rQsXZVIiVmVaF074Z6ngsrUQZ0ZHOQXuHiEtES4toAyVy6VtdA7ciQjvlaWrPEDlgZadaLfbbUDH7sxkyorLhhw/1CnGAdVrUl97Q7pWIPiEOBjslliGDI9p6xAqmR4jlb0I3R0UJ0e4fIicUEK1WZ7Nj6Q0i/212cSm2Igo+RyA8ZcQBQNRuFfnLYI2IJ65F/pczxkL2ZnXvhrkIiPbJIg40iI0bfvaEQCIq8WS1WP1tEDEoNuyGHXEfxaUHWqz/Jx9Yg6gN/CDBAYivAdApuEYEgV9XtYEZOJeT9za4Rhx3xf09EE+QEXNEQYeEUamCS3G/T1occB2KS1Go2jScKjo9QhxoEPfZ8Ot2jOWnr47QIYNmxHYtwmZOGHHQiSjVNOQNP5fTRazA9teircZ99v1UESswTVC01DI4V2KvtIj1iBao2nSnNlR2hKeFiM8kRLDJaN/wy3KaWiwJBWczFuqnyj6q1Z+eKGLtY3b7KMHX7AS404agiE7TUAW0ClXdRzVqUZET1CIWELGqxYMSVCqnp0UQDFVDHXcgaihOTYlY2FwoUVFUoh5Rh3FiiHhvRH3c11FUlmqfBCNWEbEeUU1tGhuttXgCiAIhQBRPFSUzhYQazuCkDFUkFAx1PG45OG04cxPlhLQICNXUBiDWm4wuxFPSIpYRtamNXFzsyN5OChEriNq4z7Qovk0EtHjSiFhFbI77gjfVv6chyMkgyoTip3o3rJTeJIeqgwiC00CsAc8GALEhKCqEzQ41YK/e0E+viijosF6Jmg1/MyJrRssZBOgEEHEroiYoSiGj9W9jnAQiIDyTEXVxfwQI2xDpn8d0Xnsv9X8V7Qkf6oxZ1gAAAABJRU5ErkJggg==

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=RetroTVEast.us
