### ISSUE TITLE
Add: Uncion TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2784]
### Channel Name

Uncion TV

### Country

US

### Subdivision (optional)

US-PA

### Broadcast Area

c/US

### Languages

esp

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://unciontv.net/

### Logo

https://image.roku.com/developer_channels/prod/da2865ab4a76922a848991aca1ab981a1076213ce1e25f86949a596a6b1e80d1.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=UncionTV.us
