### ISSUE TITLE
Add: GOD TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2785]
### Channel Name

GOD TV

### Owners (optional)

Angel Christian Television Trust

### Country

US

### Subdivision (optional)

US-FL

### City (optional)

Orlando

### Broadcast Area

c/US

### Languages

eng

### Categories (optional)

religious

### NSFW

FALSE

### Launched (optional)

1995-01-01

### Website (optional)

https://www.god.tv/

### Logo

https://www.lyngsat.com/logo/tv/gg/gems_tv.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=GodTV.uk
