### ISSUE TITLE
Add: Good Idea TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2786]
### Channel Name

Good Idea TV

### Alternative Names (optional)

สถานีโทรทัศน์

### Country

US

### Subdivision (optional)

US-CA

### City (optional)

Norwalk

### Broadcast Area

c/US

### Languages

tha;khm

### Categories (optional)

culture;education;entertainment

### NSFW

FALSE

### Website (optional)

http://www.goodideatv.tv/

### Logo

http://www.goodideatv.tv/images/gtvlogo-01.png?crc=47749013

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=GoodIdeaTV.th
