### ISSUE TITLE
Add: DELUXE ROCK

### ISSUE THREAD

**Issue by diestro123** [iptv-org/database#2787]
Logo below. 
Channel from Germany (Deluxe Music group)
Website: https://deluxemusic.de/sender/deluxe-rock/
Livestream: https://sdn-global-live-streaming-packager-cache.3qsdn.com/65181/65181_264_live.m3u8

![DLX_ROCK_LOGO_RGB-1](https://user-images.githubusercontent.com/81490802/226130697-b94474d5-9aa4-4169-9d82-5ab4bb384db0.png)

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&template=channels_add.yml&title=Add%3A+
