### ISSUE TITLE
Add: GSTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2809]
### Channel Name

GSTV

### Alternative Names (optional)

GSTV宝石学研究所

### Owners (optional)

GSTV Corporation LTD

### Country

JP

### City (optional)

Tokyo

### Broadcast Area

c/JP

### Languages

jpn

### Categories (optional)

shopping

### NSFW

FALSE

### Launched (optional)

1988-05-17

### Website (optional)

https://www.gstv.jp/

### Logo

https://www.gstv.jp/library/html_publis/img/common/logo_h.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=GSTV.jp
