### ISSUE TITLE
Add: Seven

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2810]
### Channel Name

Seven

### Alternative Names (optional)

Shabakeh 7

### Country

US

### Subdivision (optional)

US-TX

### City (optional)

Dallas

### Broadcast Area

c/US

### Languages

fas

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://www.shabakeh7.tv/fa/

### Logo

https://www.lyngsat.com/logo/tv/ss/shabakah_seven.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=Shabakeh7.us
