### ISSUE TITLE
Add: CHEK

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#282]
### Channel Name

CHEK

### Country

CA

### Subdivision (optional)

CA-BC

### City (optional)

Victoria

### Broadcast Area

s/CA-BC

### Languages

eng

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://www.cheknews.ca/live-news-british-columbia/

### Logo

https://cdn.cheknews.ca/wp-content/uploads/2022/06/01161340/favicon-100x100.png

### Notes

Streaming URL:

https://zypelive-amd-uswe.akamaized.net/hls/live/2041168/main/playlist.m3u8?6pLKMQ3y=pLK0uw32&F38b1dF4=630e2136d7894e000133fb86&video_id=62ec07c17176280001fd6aa4&hdnts=exp%3D1661956790%7Eacl%3D%2F*2041168%2F*%7Ehmac%3D79fef64f85c5cc9ef6ef92a0e11d62a810c688aab4095004b7f5035915448398

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=CHEK%20country:Canada
