### ISSUE TITLE
Add: CitiCable Cincinnatti

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2820]
### Channel Name

CitiCable Cincinnatti

### Country

US

### Subdivision (optional)

US-OH

### City (optional)

Cincinnatti

### Broadcast Area

s/US-OH

### Languages

eng

### Categories (optional)

legislative

### NSFW

FALSE

### Website (optional)

https://www.cincinnati-oh.gov/citicable/

### Logo

https://www.cincinnati-oh.gov/themes/cityofcincinnati-bootstrap4/images/defaultLogo.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=CitiCableCincinnatti.us
