### ISSUE TITLE
Add: USA TODAY

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2821]
### Channel Name

USA TODAY

### Owners (optional)

Gannett

### Country

US

### Subdivision (optional)

US-VA

### City (optional)

McLean

### Broadcast Area

c/US

### Languages

eng

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.usatoday.com/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/USA_Today_%282020-01-29%29.svg/1280px-USA_Today_%282020-01-29%29.svg.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=USATODAY.us
