### ISSUE TITLE
Add: Kon Tum TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2825]
### Channel Name

Kon Tum TV

### Country

VN

### City (optional)

Kon Tum

### Broadcast Area

c/VN

### Languages

vie

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://kontumtv.vn/

### Logo

https://www.lyngsat.com/logo/tv/kk/kon-tum-tv-vn.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=KonTumTV.vn
