### ISSUE TITLE
Add: Tra Vinh TV 2

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2843]
### Channel Name

Tra Vinh TV 2

### Country

VN

### City (optional)

Tra Vinh

### Broadcast Area

c/VN

### Languages

vie

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://travinhtv.vn/

### Logo

https://i.imgur.com/uqMu5Fb.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=TraVinhTV.vn
