### ISSUE TITLE
Add: ABC News

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2849]
### Channel Name

ABC News

### Country

AL

### City (optional)

Tirana

### Broadcast Area

c/AL

### Languages

sqi

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

2010-01-01

### Website (optional)

https://abcnews.al/

### Logo

https://www.lyngsat.com/logo/tv/aa/abc-news-al.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=ABCNewsAlbania.al
