### ISSUE TITLE
Add: AlbKanale Music TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2851]
### Channel Name

AlbKanale TV

### Country

US

### Subdivision (optional)

US-NC

### City (optional)

Asheville

### Broadcast Area

c/US

### Languages

sqi

### Categories (optional)

music

### NSFW

FALSE

### Website (optional)

https://albportal.net/

### Logo

https://albportal.net/images/albkanalemusictv3.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=AlbKanaleMusicTV.al
