### ISSUE TITLE
Add: ATD TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2852]
### Channel Name

ATD TV

### Alternative Names (optional)

American TV of Dardania

### Country

XK

### City (optional)

Peje

### Broadcast Area

c/XK

### Languages

sqi

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.atd-tv.com/

### Logo

http://www.atd-tv.com/images/atd-news-/atd%20logo%20sncro.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=ATDTV.us
