### ISSUE TITLE
Add: RTV Arberia Musik

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2853]
### Channel Name

RTV Arberia Musik

### Country

XK

### Broadcast Area

c/XK

### Languages

sqi

### Categories (optional)

music

### NSFW

FALSE

### Website (optional)

https://www.rtvarberia.com/tv-arberia-4-muzike/

### Logo

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAawAAAB2CAMAAACjxFdjAAABFFBMVEX///8rKinjHiQmJSQgHhxGRUUnJiQjIiEeHBsaGRe+vr5PTk6ysrJdXFuhoaHu7++MjIyTk5MUEhD0srRnZmb29vZ3dnbrHSTjDxhsa2skKiniAADZ2dkcKikAKynp6ek1NDPypacNKynLy8uKJCfT09P+9fXiAA45ODdQKCjfHiQYKinmMzgNCgisrKzh4eG4ISXGICU6KSigIyb86eqsIiWCgYFVVFN0JifUHyRmJygxKimSJCZEKSj3x8joT1P5HCRZJyj62tvtg4b4ycq+ISV7JSeNJCZkJyj1uLpYGBgXHx3rY2fnOD7vk5XscHPdoaJhcG+2NzpPW1nmioxATUztgYPpWVzcbG7fk5WPMTPnRkp8FjDtAAAXlElEQVR4nO2dC1fiyrKACQkkAXnICJGXoIhCGF4ij6ioOKMznjuP+9h35pw7//9/3AQS0umqTgK2zp6zqLVmbwwk6e4vXV1dXV2JRHayk53sZCc72clOdrKTnexkJzvZyd9BMkDyv7tIf7jcvlvL8/Pz7ceHS/e7h3dseT579vz9EVz50vjHf0ge6e6/YcX+HeXL+aFHou/vPtyerb67K5tyTv3g8PD8/Nw8fvuhTB77+kBf+cP5U1XwiLqD9TL5chhdy+G75+Nv33+Vy7+Ol999tHvbd+I358e3t7fm0Xf5y/MoIef/oi58+dW48LISlB2szSTvlYgHxKpHXR7/Kn8htGHkA/Gb8gN62CR95r3Rf5ZPq380rEwl0UtUMr+xBL2Dokf+6781pL3Pjsu/CFoMWA/vPV3r2Hunr1qs9AfDyqSTSi6XU6fp32cVtSTZI0djDJapAfU7l9Y3HJa3a2kkXtNwKR//j/jnwkq0lFXpRSXW+E1l6KtU+50wYJmN/df687dzHNZl2dO13pF3+h69/N8/F1Yi7pZdFn4TrX0lLCyzO62xsGBFfnhGLZ345uH8QyQW/1NhJUTyORPl30IrcyD7wdJIWJfvPzgfmbA+6p6u9ex+88P8HXdYjXR2v9dHqtXbz+4n+I0tmZhXJ8ix32FmNCWq+bywoh6D7rjsDEIkrHPPfMrTtQ7v1udfHn6PcIaV7wk5VVHU7kHT+0WtYB6XlJy0z6tJC7T+USacrryJAC3oB+uy7AxCxyQsjxnx4B21biPrM255w5pI9uMueceQZtKplHrAh1alRRdcEJD+/NoCS+EDK/Lzi/2BDYvqWr/so5fvzY7FFVa+mFtfRlT33C+asqvZlWRt6xsQAh9pQc3yuPBG0qRHLH9Yfzlt7wPrI9mzood213pXtj7whLVPKvC4uH7QM0myTmph6xsQEqOtWPP5mPK48EaCPDIeWLoX1rv3NhgfWB4PSPTwy2qU/3pn/ZcjrErXcyGp6FgTE+9cRNnzvUwoqXnvtXo8Wm+tBzNT+Mj4wXrWQ8D66PEQHi6d77cru5AjrAllGTnGdL/uvYecerlN2EBgCW8+12rSM2Ia1vstYEX+6elaP80jZ19WZiE/WGDIl4qrL9K0rui+vFH3cgIUOfHi624mWagFfWEdh1GDkVvPqBX9aJmIKzchP1gJuuTx+vJ4HswblZdbAn8PWMjA6Qvrw1f7gy8szyJL1Jpf/dO+Dj9Y8DGTK9bxDDBv5YMtb+HK3wJWA2HlC+suhOkeAaPWw0PU9r/zg1UEZqy0bLwaOC5OXzxo/S3GLMQW9IV1WXYWPfxhnXm71o9vjvbkByvFgAX80oKYfDGsGtKz4q3KSy+7kWSSG/asfx06XPxhRW497txo1PEp8oMFhianZwH3GQdY2HART774qhtJA1PFPrAuv/5wPn7zhxW58y4ZO7/gB6sAoKxs9wyoj5za8haEZKHVzMFu2UjoqUoQrL/cJZJ/BcC6JUetw/U6GD9Yaajulm7AfJK+hcTBh9Gsw2fgbefEecwW9IF1W153rMCedfaT6Fr6mjE/WMA2EmOrLyb0OJzj4MKAXnfpjb3uCZQV5cFwQdxGf7rkgmBFnl1Ylu1uCz9YGdrCUNOsWvFw5dbq3suKLS4O4vCSRbWgcDIgV4q/OIDenRPggmFFvq6vQqx3cXQ3pb0Drui46vJJL0VOC097Eln0uPrGkyw4fURg6Yd3l5Gzs4fn995QtGBYz84vDr+71hhPr7sXSq7nHG94josxTl1gT3b7lhh/a+8FbgtSsL6+O7/78f1ntKx/8xjxwbDOHIPwkFja5wmrKRCaSSVMvixZsS6PEWspe7JqRzepwluzihTgUhaE9T7y8L4c/f7tmTqZDEXDYTld6/COOMZ1pbghrGuQK5BzKdfGEOPcWJnjVjYmqaqqJLNvHn9Bh4AwYJ1FHn4dfgNn/xUMK7IKnSmT4Wh8l/UbsZwsxuOi4mUVyae7inVcVgWOrEzpN3rpXuONTQtLEoyOBWBFzr6X7+gdIWFgLbvW4U9SffKObuoVY63WdAIcP/39aaseO/iNobN8BZ8R07BWi4/H5cMPXiIfQsC6tEatQ08INfdQtHyt30eVUqbf7/+7oELcMj6wIg/fy+Uft0QfCQMr8q5MOxf/3CDP3yoJhi1ownq811xx2vr5rmzahesZ0w9iJ1YZ7MNyxATpHe7AOLmDFUYQW9B+6quzT6eO/B+hxG4//IqujYWPx4ScYTew5Pj8q7fX7XrWNtKHtmA8Zn8oVV3xLLBdXm44Clx+pezIHaxtJAHNC7UBmvLF6wDHlIbcwdpGoBYUkxloIIoxvhbVDtYWkoEjltlsyNSLQxwXKTtYWwgSriMmIjXo2uW8WWIHawtBtGArj4UMmcpx65vUKs0K5ZoJgpU3zzFP2k731vrmudueTBWCLvh2V9m6KqQgtuBy8XsPhhqI2zmYM41JslWv11uxQq8WbomklpikYtY55kkH2cZGD0mmkT5Y3s86OTXp4V6NUFdKFJaFaCULe1sDqzWy66qksomX+X33YAhazoJSA4d9lq/7CVrW41u+N81JcQtMXJRzQmENnA2rMWnlFFlcfm+epORi2Sa4JUMak1hOtVy69slSTp6m2WdX2AXP7MdykrgquJRrTZwv8g1wDptkI0tVxb2Oz62ZAoPuxOW2yzxUj3GB1ZHTOVEWZdn9p6TsRygRkzw9V5andplYsBpTUaK+EhWhGCYyL2+dCxSFeajIaodszimz/T/FWQxLOxvy7bpL4nS1/pxJSmRNzX8qy5/fLILimAemTefW3jaTAjcOZaB5YXegHpx+Me1BEF8kr2DlsypoO1lcRUjgsPITEV0CkOrB5kelqDKWD2QJeuNXLUbrFTvAOlPIwYK3lgWHEZYSDiu/L6AOcjmezaO3DoyT68GhyQ7cpvfLCD6RXAxYmRSyM0VQVns8UFiNGBYYbElcTfl3rnxaZq30WEUX0TUSBqxaDGvm1QbHsLAqSazyqwslm1vBgkafINgaDO7XElkbPXFYmSJaXLt/YrCIBV8oUstv5MoXFMYK6kriSgGhhcOqTfFiNDeA1Wj5VEWuN7eAhexmlu3NTVinkxj2IAorn0J7iWyrZggrnZB921v2iXeoMLvkWtQYjMVEYWXQfuXolXCwyLwmiIhyAmweC4SF2YLOrfvw0WDpQRTWPr7yovYYsMSDum8FzV+ILE3Yj/k8x+vSQ8WAwoLh2EvpJsLDaghBVWml6F8EwoLbEeLrkMU8oiIV3B5EYOVhUPOqlE48GHQVB9RvWUVcEzbrIVhZipTuWxisLP6Qia1IaFhNAVSOFtjzgmBl4GYj2VXtoKPaU7AwsIoVRvOtnVYQVgiR0f0amTD9yhKJ3lQMYRWbjGfGCfMNAYsOLg0nQbCQp5/Y0V6BzSnjehBcR5wi28lXdXY02VawBBWZmGfwwRE9nSo/gGUWHG9o0RnxQsAqMO1APwmAhSo6Qq9DT5SIDNIYLJ8SOc/2drAwnxcz3gcRKtYZ2UjNKNbafRMMi7FxIEgCYFXg7hVP/o193463Haz1+dvCqtPD5h66cZR1ujeEGtv1jkvX0QiBsDLiq8BC2ljtEd8j4w6+hTo0LNHNIOYLq1TCPi5FSXvvjXiiLaeOUK8LiO9JkDwL3qFhievBMhAW8oiHkgBYSPBFnVRzYC+NKTnMbxwaFpFhGoNVsvLmlkrV0tXs+mT5+cT8aP5dcr6kixiJpIASjKvTdKOfqfUT2RZiI5Gnh4blapQgWBXo+Qkn/rD60EaVix4lg+wKR/ejhe9ZbkshsEqfT0tC6ar9ydANYzQyj5yOhrpujC9mJaF6ZadA9i6Cwt3zorC3fqBqE/C4eWJJwsIitGcQrE1GUI/4w8K0oFfHIFlnUHswLCxyUo3A6oy1RUeYP80G+k1Ue6oKpbmmjYbG7LRdKpV0w+5a5Ja4POj8YswzFwN+GI+NFBYWQTgAFpbbKZz4woIJWMxhlDL2YJdGk0r5wRJFd8Al9zIhsKpX98ZFtVRdPEa1aNQwFeJYMz8NZ+ax64F2YycXJ0ctGJolUV4OoB0UYlj2g0UWnNCdAbDYI5YoKYqCjKKO+MJCplHOZty1IH0aW71hwpJzYiyVitVzy8ULz+WxMatzqulPncXnk+tTXdOvqouhpt3MT+azzpVxP3IsDXHqjptg2JUo+wM+kyIxsWbBiku5eDI1jcVzyzUe0qzyh4WlK1teUFGm2XQvPZmqLDXpCwt5BlS6pg14ZRlZI2O5loRiIrPM5l9JpwTZe3nUGqy2H6OGoT1enbSj2shkF306ao+juqENZx23mGtFB/S0mAIGUIP+TddVowxYcr3QWBY809xPxUXP5M4fFtJgqwtm7b0R+cqEsbTgCwvblEW73mpILhPEHsRhSS2ijvnGNFcn5ziYGnwanxzNT/Wopj0djbToaVQbVhe6qRJHi87Rp5HzjgU3vgA0NnjcTGlRdSBsJByWkiTaIZ+I5chQIX9YuHmhpsiGTSTx5QgfWE14hgwfS6Q2nqnYSlBYcsrr5M7ve6Y4qDV4P1i0Z3o0qg2OrqzhSrs5urE2spy2F6P7kdO31oqsBh64LuKXp0ctIpYEhaUUvM2QL5Cr1P6wUAeIRC2lQato1V6w6OsGhs8AErmH7DCR4SoeBkusgwUJTxtgHbsz0u61wVCzYC2sLUTa6RKWMda1+7H7u7qNBGg4QUZqSqsmQlVisGQQcpcnD/jCqmAee6lINxi6uukDKwPWU0z9UAFvjonAi8br4OnFYLEWKh3BetZ8cd2+uDZMSsZitNwa9mgOYtGovhDaF+3F2pfhOK1AVpJ4jK6BWYc+tcJK5MXCfIN1/1AqX1jIgq1ZJriu1Ed6oA8sbAlDLACZQPchogcRWPJBQEwjOmbdjxdXBplEeSWmndG+0QZrE8NRAXBErcMqFIp0Hdx3HCCw1ivl28DCeqqCPbVIOJIPLFRby1CQX8EkYAgsRsiPLyyhNDIt9tMhgGU8mQTH7gu3bEcLtmUTqQKog/u0Ia2QC4hR9IOFTV3xVSVk2PKBxdqgH0ZAYimsZwXFnqKwji7a1bYOe9bT0Xx+5Nrutj+4sc0an0D6IyCswM0yfrBQ4xkfDnpgdGPD2raeq9LR9jGEFaRM8DGr/ThbjAwISzcGV4vxE+F/X8La29IN585xISwpKD7RD1YfDhp2vl4geRipxISFJu4MXVnavIGwEPs+DKz7e200NwCs6OdT/f6eeJeduuzbSNxBKHF9GEjPCgro94OFrSmxYi2BxmTCyoBUfBtJnLIHETUYmIIPU4PV+ez6BA5ZZte66MwWrhoUcksTgZEeLLj4LSaseGCKMz9YCcQpxBq7w4eiYUncNxDaTwBjMIJzWmGwrmcX88fhCJiDg5G+uL6au2pwNRAwYsZCCBNW8Jsq/GAhe93iLHsFbFdkwgITlM1EpOxBVqz7hrAsNXg/uEbU4OLG/OaGUINW+2AhJOFEYsIKTibuBwuZZsFJqS0N+pcsWIzEnRuItwicYAnC6PG0M0bmWcOT2eOY6FnLIXF7WOorwYLDAfs1JSB9KwvWlvE3rlCBELxglY6Ojj5FRxqFSxsPBydHR8S7cv8YWIxwsE1gvcgWXNXJYw/yUoMXo5uB9nmgjzXXfNejj0NjoQ9vRp+59SzlzWCxe1YjJCxmyrrw4l2P5QZLu9ev2trTzeB0jWt8OmzfP10Y99qMMDCWYxaSGsd6e3CwdF8J1muMWazEnRuI6pk7clOD86uLznDYMWaPg5WZoY/MXjUf6RfC5zYxJ15Zg3DxKL4PNn+i8kqwENNdZlqDdOEZsLYOwHHFaw9yMzA6R8JYm4+Mq+HpctzStNHg0+BRMIwLwtvkOPCQN8ZsmKuDMyy4ZMP2DoChCIfFQQsK3kVlXrCqA0PXrq7uZ0Lb0IZDzRho0cV1Ozqa61Fj6DpyBYXhwdj03XOcYVVgwzI9GMCTi8N6sS24LCFpD3KD9WQMZycXi871UIu2P2mDE0MzFkftdqc9MG6IH9YZvkFsVd9POMNCtvYKcfwyNehORWFx0ILU2424qUHhQjAN9M5nw9R/R2NtWH0yteFTtSSUSnPy5qvFXLg7J9h/7BXOsGpIbFPYXVI4rDwjifuGolZ87rytgbF4NOZVYRl/MT8yNL0tGFYcRql08mgQxqAdWZCHVxCDbusVzrCwyQTwei8FWUxBYbETd24kZBgyt541n9+MLy4+Dcf64GSxjJf5ZM6IR/Pr0Wgxv3bvbWs7uILHeI4jDdwo4wwLncCiy7DYEjUGC3N/yoq/YDEAxLuoeM2zngzjZhw1buYni0Xn0dSAeuf6qnN9OtQfb4bRGzcGw0YCQx8ZerAvCvsbpFbwE19YSBIlQazDtsAc6RgsGL5lSjHrLwUkFIN4dx6/nrW4Gj3djE9L1euli1Abtqul2Xg0G88W7qC13kiCrB9JmKlciclxpbUHcfGGhb23DsTkmazoUMbVz+DNkEyCIV6KjES6EWuq/OZZI+3qpPM0aI+0qDUr1nVtcDEeVTsX+tB1Da4neUiwcpxea4s4LwIXFZhTiDesCJpwQDnwtgaeWwCDhWjBEDYUEmtNRCtwg3U9svwU1Y4wn11YsLT5Vdv603Ibuk53132CrBWLIFtGw8lrIeey1DPOHRbudZXqCbdXZ9J4xiMEFmJBhZmdYNGLbhwQP1jXq/5jsjGGRlQfRMe2l6l07doXriGKFUuUvZl/EkTeBSUWsKf4pbDQl9JaZSr2Vs9JP43mSBJQWNh7duXgbHp5JG7H3dXGb55lS6k9HHXMjtU+NT6X6C9JYxiJ/TKfIqFnbwPIVPZiXfJGYo6MY+cPCwtGW1041xVjyZjSZSUDw2BhWjDMK+eR/u3ag9xhCZaFoRvG8ILeUix4N1jhUVqmNXEw2d/PFlItkNFJrk/c6nKHRb94zSOi79ZwCAvbLk1vqUYFePQFIhKIPyyhauifo7OB3gawlllh18KIw4jL1tY1WUZuEs+5zhf+sPJb+/IgLCSJe7j3V2Pe3/W8eCtYAbW6KI20x+s5/MK7OlPZfFuo++a6V4C1/cIuhIX4Q+joF4Ygj3DcyUnxCj1LEE5G2hBRgnRe5fCpLJyy+e18fDksdB4bqlw0rAzSsUKmAMe8VDm7T74KrNJCu6rCw3QgHis5IFsIRfIKsJDA6HACYGG2YFAkvlNIxP3vbEt7FVgmLYQVVBbonii25Egt+hqwIhs/PYyaIVELRNIXf0H0oJPa83VgCVAHYpvDsG2BbJHJpZ3XgdXcLm0JDYveVra8VdgXwmDbAGyP6ivBQgR9IyojQyAmotez9iqwIumtcmHQsJDEnWsPdqBgy6C2HuQDyy+rrHM/fLNTMWzfEkWv5fs6sMLEdcdb9BEaFuKOjSMOfIag25aXSoULLDmRDKqjwpi+5/HUyUCA3/CVYAVnQJSmPVB/LywkiXuI0q0F2zm8WuzjAkttBGW6hVuzHQnXt8Q6rUVeCVakFpDLU07WgkLRsO3JzC0pUJAMx7Ye5AMrEang/mjnB1O2DzM/6QaOgWoM2L2vBSvSZ2d1t+5S7wftIsEiBOIwAQK7QRA9uIrl5gUrUsHzeazaBA1mWEsvIKlxXC7AMr0arEimyK6JYr0pIwAWZgvi4RwMwXYaLjMocIMV6U9zeA+Ru+i6PCHNKXwlxVpEtR4qFIIbrEg+m8Ofnnhu2TgBsDAtqARuJyWkISK0rdpx8Q3a6WvTdWT4EZWDEFP3XpLx1gRRieGos6Dg3GCZT08Ky4Em1VdNnvCPyE2pEhA1zNtz1tJCrtDNWxML6mAuBCzqWoqd5D5SKVBrPqLUjSHxE4jU0vUuzUuU1W4yzVD2WVDwYFig4Gi+zOVP91pd6iVHatd5hU0ip9BtFqaKfzvp76fqqiRbCf9kRRWTkw0i2BPZpKAqy3NFWVIVMVZMb/RA8pXGJCm6Vamn0oHRLn+eZCqJ/UJqOk0VsnvNDd8KV7POPUhNU6niJJ3g8fa+F0mtuZctLquyn6iEntP+PzoLaVWLNcw/AAAAAElFTkSuQmCC

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=TVArberia4Muzike.xk
