### ISSUE TITLE
Add: Topestrada TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2854]
### Channel Name

Topestrada TV

### Country

MK

### City (optional)

Tetovo

### Broadcast Area

c/MK

### Languages

sqi

### Categories (optional)

music;general

### NSFW

FALSE

### Website (optional)

https://bashk.tv/en/k/TopestradaTv

### Logo

https://bashk.tv/storage/uploads/images/channel_logos/TopestradaTv_logo_5ac42e64d79bf_thumb.jpg

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=TopEstradaTV.al
