### ISSUE TITLE
Add: Canal 79 Puan

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2872]
### Channel Name

Canal 79 Puan

### Country

AR

### City (optional)

Puan

### Broadcast Area

c/AR

### Languages

esp

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://canal79tv.com.ar/

### Logo

https://canal79tv.com.ar/wp-content/uploads/2021/06/canal_79_gif.gif

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=Canal79Puan.ar
