### ISSUE TITLE
Edit: Syri TV

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/database#2906]
### Channel ID (required)

SyriTV.al

### Channel Name

Syri TV

### Country

CH

### Broadcast Area

c/CH

### Languages

sqi

### NSFW

FALSE

### Website

https://syri.tv/

### Logo

https://i.imgur.com/8WboFWj.png

### Notes

Changes: Country from "AL" to "CH" ; Broadcast Area from "c/AL" to "c/CH".

This channel broadcasts from Switzerland.

**Comment by freearhey** [comment]
Updated in https://github.com/iptv-org/database/commit/dc499b59b31aa79d9db580c1ea765707c3039173
