### ISSUE TITLE
Add: CMAC 2 - Education Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#291]
### Channel Name

CMAC 2 - Education Channel

### Country

US

### Subdivision (optional)

US-CA

### City (optional)

Fresno

### Broadcast Area

s/US-CA

### Languages

eng

### Categories (optional)

education

### NSFW

FALSE

### Website (optional)

https://cmac.tv/watch/

### Logo

https://cmac.tv/wp-content/uploads/2021/08/CMAC-Logo-White.png

### Notes

Streaming URL:

https://reflect-vod-cmac.cablecast.tv/live-12/live/WIFI-1296k-540p/WIFI-1296k-540p.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=CMAC2
