### ISSUE TITLE
Add: Canal Showsport

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2919]
### Channel Name

Canal Showsport

### Country

AR

### City (optional)

Corbdoba

### Broadcast Area

c/AR

### Languages

esp

### Categories (optional)

sports

### NSFW

FALSE

### Website (optional)

https://canalshowsport.com.ar/

### Logo

https://canalshowsport.com.ar/wp-content/uploads/2021/11/2021-11-logo-SS-HEADER-blueE.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=CanalShowsport.ar
