### ISSUE TITLE
Add: Rakuten TV Family Austria

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2922]
### Channel Name

Rakuten TV Family Austria

### Country

AT

### City (optional)

Barcelona

### Broadcast Area

c/AT

### Languages

deu

### Categories (optional)

family;entertainment

### NSFW

FALSE

### Logo

https://play-lh.googleusercontent.com/-3iQgi1MJkgsihOYW8qYV3go11dvDbj_CnMfUdLyIWOscqFs7DdiUFSR36bdadFseWY

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=RakutenTVFamilyMoviesAustria.at
