### ISSUE TITLE
Add: Kurier TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2924]
### Channel Name

Kurier TV

### Country

AT

### City (optional)

Vienna

### Broadcast Area

c/AT

### Languages

deu

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://kurier.tv/

### Logo

https://hermes.telekurier.at/images/cfs_landscape_616w_347h/7491864/221213kuriertvlivestreamstandbildv02.jpg

### Notes

https://schautv.mdn.ors.at/out/u/schautv-nodrm_4.m3u8?guid=c5bca0ef-7394-4b87-a48b-b625dfae0101&m=1677431912

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=KurierTV.at
