### ISSUE TITLE
Add: CJON-DT

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#293]
### Channel Name

CJON-DT

### Country

CA

### Subdivision (optional)

CA-NL

### City (optional)

St. John's

### Broadcast Area

s/CA-NL

### Languages

eng

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://ntv.ca/

### Logo

http://aws.ntv.ca/wp-content/uploads/2016/09/NTV_sm.png

### Notes

Streaming URL:

https://2-fss-1.streamhoster.com/pl_122/201748-1431018-1/chunklist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=CJON-DT
