### ISSUE TITLE
Add: EMCI TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#294]
### Channel Name

EMCI TV

### Country

CA

### Subdivision (optional)

CA-QC

### City (optional)

Bromont

### Broadcast Area

s/CA-QC

### Languages

fre

### Categories (optional)

religion

### NSFW

FALSE

### Website (optional)

https://emcitv.com/

### Logo

https://emcitv.com/favicon/android-icon-192x192.png

### Notes

Streaming URL:

https://stream-01.nyc.dailymotion.com/sec(mOyh5XasEoxB2izGnZ4Ls9on0W3Iy5TKqlwGL79Bf6JcG2Pr-K-9EC8ahi_1r4jn)/dm/3/x8azdl4/s/live-4.m3u8#cell=lnyc

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=EMCI%20TV
