### ISSUE TITLE
Add: Fuel TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2947]
### Channel Name

Fuel TV

### Owners (optional)

FUEL TV Global

### Country

AU

### City (optional)

Lison

### Broadcast Area

c/AU

### Languages

eng

### Categories (optional)

auto

### NSFW

FALSE

### Launched (optional)

2019-11-01

### Website (optional)

https://plus.fuel.tv/home

### Logo

https://upload.wikimedia.org/wikipedia/en/thumb/6/6a/Fuel_TV.svg/1280px-Fuel_TV.svg.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=FUELTV.at
