### ISSUE TITLE
Add: ABC News

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2948]
### Channel Name

ABC News

### Network (optional)

ABC

### Owners (optional)

Australian Broadcasting Corporation

### Country

AU

### City (optional)

Sydney

### Broadcast Area

c/AU

### Languages

eng

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

1947-06-01

### Website (optional)

https://www.abc.net.au/news/

### Logo

https://upload.wikimedia.org/wikipedia/en/thumb/d/df/ABC_News_Channel.svg/375px-ABC_News_Channel.svg.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=ABCNewsAustralia.au
