### ISSUE TITLE
Add: AUS Tamil 

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#2949]
### Channel Name

AUS Tamil

### Country

AU

### City (optional)

Preston

### Broadcast Area

c/AU

### Languages

tam;eng

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://austamil.tv/

### Logo

https://austamil.tv/wp-content/uploads/2022/05/Aus-Logo.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=AUSTamilTV.au
