### ISSUE TITLE
Add: HollyWire

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#295]
### Channel Name

HollyWire

### Country

US

### Subdivision (optional)

US-TX

### City (optional)

Austin

### Broadcast Area

c/US

### Languages

eng

### Categories (optional)

entertainment;news

### NSFW

FALSE

### Website (optional)

https://hollywire.com/

### Logo

https://www.hollywire.tv/wp-content/uploads/2020/08/cropped-HW-1-192x192.png

### Notes

Streaming URL:

https://bozztv.com/hwotta/playlist/HD3400/HD3400.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=HollyWire
