### ISSUE TITLE
Issue with stream playback

### ISSUE THREAD

**Issue by SkylerDaKat** [iptv-org/database#2986]
(Channels tested: Cartoon network east, west. Adult swim east, west. Nick on Pluto, teen Nick, nicktoons)

I used the IPTV m3u link and I keep getting looped back Everytime (won't load anything else until it loops on a future part of the broadcast), 
Used two VPNs and both didn't fix
Used 5+ IPTV apps (Tivimate, vcl, Kodi, m3u IPTV, used m3u source link on browser)
Tried it on 3 devices: TiVo Android tv, Samsung smart tv and a HP laptop

I'm still new to IPTV stuff but I don't think it's a local issue or if this is something that happens from time to time and my timing is unlucky.
Please help, thanks in advance <3
:3

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%F0%9F%9B%A0+broken+stream&template=-----broken-stream.yml&title=Replace%3A+
