### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by theraveztv** [iptv-org/database#3076]
### Channel Name

RAVE-Z

### Alternative Names (optional)

RAVE-Z TV

### Network (optional)

RAVE-Z

### Owners (optional)

RAVE-Z

### Country

EN/US

### Broadcast Area

Global

### Languages

ENG

### Categories (optional)

TV

### NSFW

FALSE

### Replaced By (optional)

https://raveztv.page.link/stream

### Logo

https://i.ibb.co/Jnq9SXQ/rave-pn5w.png

### Notes

#EXTINF:-1 tvg-id="RAVE-Z " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Undefined",RAVE-Z TV 8K (4320p)
https://raveztv.page.link/stream

used dynamic link for hls stream,tested worked on IPTV (Android app), PotPlayer & VLC

**Comment by freearhey** [comment]
Please read this guide before posting your next request: https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
