### ISSUE TITLE
Add: SinoVision

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3082]
### Channel Name

SinoVision

### Alternative Names (optional)

美国中文电视

### Owners (optional)

Asian Culture and Media Group

### Country

US

### Subdivision (optional)

US-NY

### City (optional)

New York City

### Broadcast Area

c/US-NY

### Languages

zho;eng

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1990-01-01

### Website (optional)

https://video.sinovision.net/?module=live

### Logo

https://video.sinovision.net/images/logo_live.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=SinoVision.cn
