### ISSUE TITLE
Add: Montreal Greek TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#310]
### Channel Name

Montreal Greek TV

### Country

CA

### Subdivision (optional)

CA-QC

### City (optional)

Montreal

### Broadcast Area

s/CA-QC

### Languages

gre;fre;eng

### Categories (optional)

ethnic

### NSFW

FALSE

### Website (optional)

http://greektimes.ca/greektv/

### Logo

http://greektimes.ca/wp-content/uploads/2017/12/cropped-chwb_thin-512px-favicon-192x192.png

### Notes

Streaming URL:

http://live.greektv.ca/hls1/greektv.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Montreal%20Greek%20TV
