### ISSUE TITLE
Add: NACTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#311]
### Channel Name

NACTV

### Country

CA

### Subdivision (optional)

CA-MB

### City (optional)

Neepawa

### Broadcast Area

s/CA-MB

### Languages

eng

### Categories (optional)

community

### NSFW

FALSE

### Website (optional)

https://nactv.tv/

### Logo

http://nactv.tv/wp-content/uploads/2017/11/NACTV@1-300x201.jpg

### Notes

Streaming URL:

https://s3.amazonaws.com/cdn.pivotalelements.com/NACTV-HLS.xspf

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=NACTV
