### ISSUE TITLE
Verify : French channels to add ?

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/database#313]
### Notes
NSFW channels
![image](https://user-images.githubusercontent.com/30985701/188275745-9bca4a7f-1ce0-45c0-999d-027a4e132130.png)

SFW channels
![image](https://user-images.githubusercontent.com/30985701/188275774-c1491e4f-e9dd-4cab-85f9-f01fe876a898.png)

Ignore the (bas débit), (auto) and (HD) additions since it's something added by my ISP (Free, France) to choose the quality.

These last channels are most certainly for French-speaking countries in Africa, last one being for Haiti. Not sure for the others since I don't have access to them.

![image](https://user-images.githubusercontent.com/30985701/188275830-219fec8e-57bd-42ca-a914-a1f4b1a8f32a.png)

First one in last picture is streaming Nollywood movies, assuming NCI is a channel from Côte d'Ivoire and Sen TV is from Senegal. 
![image](https://user-images.githubusercontent.com/30985701/188275928-f6937dc3-5732-405b-93b7-a8addcc4d0c7.png)
![image](https://user-images.githubusercontent.com/30985701/188276051-769a9dfc-87b3-451c-a0b5-cf0f6160d5a8.png)
![image](https://user-images.githubusercontent.com/30985701/188276125-129c57fb-49d8-45ee-86a8-e4261af6f703.png)

**Comment by freearhey** [comment]
I'm sorry, but what is the question?

**Comment by LaneSh4d0w** [comment]
It's merely to know if these channels are in the database or not. I'll need to dig up data in case it isn't.

**Comment by freearhey** [comment]
You can check the presence of the channel in the database yourself at any time via [iptv-org.github.io](https://iptv-org.github.io/) or any spreadsheet editor such as [Google Sheets](https://www.google.com/sheets/about/), [LibreOffice](https://www.libreoffice.org/discover/libreoffice/), etc.
