### ISSUE TITLE
Add: BeachTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#315]
### Channel Name

BeachTV

### Country

US

### Subdivision (optional)

US-CA

### City (optional)

Long Beach

### Broadcast Area

s/US-CA

### Languages

eng

### Categories (optional)

community

### NSFW

FALSE

### Website (optional)

https://reflect-beachtv.cablecast.tv/CablecastPublicSite/watch/1?channel=1

### Logo

https://reflect-beachtv.cablecast.tv/Cablecast/WebFiles/6701/CableCast_Banner_1200_225_L.png

### Notes

Streaming URL:

https://reflect-beachtv.cablecast.tv/live-3/live/WIFI-1596k-540p/WIFI-1596k-540p.m3u8

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=Beach%20TV%20CSULB
