### ISSUE TITLE
Add: Nasul TV [RO] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3152]
### Channel Name

Nasul TV

### Alternative Names (optional)

Nașul TV 

### Country

RO

### Broadcast Area

c/RO

### Languages

Ron

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.nasul.tv/

### Logo

https://www.nasul.tv/wp-content/uploads/logo.png

### Notes

https://5ab29cc78f681.streamlock.net/NasulTV/livestream/playlist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=NasulTV.ro
