### ISSUE TITLE
Add: TV Marti

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3178]
### Channel Name

TV Marti

### Alternative Names (optional)

Televisión Martí

### Owners (optional)

U.S. Agency for Global Media

### Country

US

### Subdivision (optional)

US-FL

### City (optional)

Miami

### Broadcast Area

c/US-FL

### Languages

esp

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1990-03-27

### Website (optional)

https://www.radiotelevisionmarti.com/

### Logo

https://www.radiotelevisionmarti.com/Content/responsive/OCB/es-CU/img/logo-compact.svg

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=RadioyTelevisionMarti.us
