### ISSUE TITLE
Add: Quo Vadis TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#320]
### Channel Name

Quo Vadis TV

### Country

CA

### Subdivision (optional)

CA-BC

### City (optional)

Langley

### Broadcast Area

s/CA-BC

### Languages

eng

### Categories (optional)

religion

### NSFW

FALSE

### Website (optional)

https://quovadisministry.org/

### Logo

https://quovadisministry.org/wp-content/uploads/2019/01/apple-icon-114x114.png

### Notes

Streaming URL:

https://qvmstream.tulix.tv/720p/720p/chunklist_w92687638.m3u8

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=Quo%20Vadis%20TV
