### ISSUE TITLE
Add: Ramgarhi ABC

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#321]
### Channel Name

Ramgarhi ABC

### Country

CA

### Subdivision (optional)

CA-BC

### City (optional)

Surrey

### Broadcast Area

s/CA-BC

### Languages

eng;pan

### Categories (optional)

religion

### NSFW

FALSE

### Website (optional)

https://ramgarhiabc.com/

### Logo

http://ramgarhiabc.com/wp-content/uploads/2014/02/headerlogo.png

### Notes

Streaming URL:

https://443-1.autopo.st/100/weblive/bcgurduwarabrookside/chunks.m3u8

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=Ramgarhi%20ABC
