### ISSUE TITLE
Add: DuMont Television Network

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#3247]
### Channel Name

DuMont Television Network

### Alternative Names (optional)

DuMont Network; DuMont Television; DuMont; Du Mont

### Country

US

### Broadcast Area

c/US

### Languages

eng

### NSFW

FALSE

### Launched (optional)

1942-06-28

### Closed (optional)

1956-08-06

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/DuMont.svg/1988px-DuMont.svg.png

### Notes

Wikipedia link: https://en.m.wikipedia.org/wiki/DuMont_Television_Network

**Comment by freearhey** [comment]
If I understand correctly, the wiki article is not about a channel, but about a TV network. If you want to add a specific channel it operated to the database, please specify its call sign as the "Channel Name".

**Comment by kaikyoofers** [comment]
Sorry about that!
