### ISSUE TITLE
Add: TCFTV [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/database#3297]
### Channel Name

TCFTV

### Alternative Names (optional)

Télévision Communautaire Frontenac

### Country

CA

### Subdivision (optional)

CA-QC

### City (optional)

Montréal

### Broadcast Area

s/CA-QC

### Languages

fra

### NSFW

FALSE

### Website (optional)

https://tcftv.ca/

### Logo

https://scontent.fymq2-1.fna.fbcdn.net/v/t39.30808-6/294196231_471699838292714_6039137323370538555_n.png?_nc_cat=107&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=pPusrD4u4E0AX9ie8zd&_nc_ht=scontent.fymq2-1.fna&oh=00_AfDNsQvOUNwkvsLEZQmUp-zJ3YwQWYSoXwmkUTcFG8REFw&oe=6440DB8B

### Notes

Community channel in Québec, Canada.

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=TCFTV.ca
