### ISSUE TITLE
Add: CTB TV [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/database#3298]
### Channel Name

CTB TV

### Alternative Names (optional)

Corporation de Télédiffusion Brandon

### Country

CA

### Subdivision (optional)

CA-QC

### City (optional)

Saint-Gabriel

### Broadcast Area

s/CA-QC

### Languages

fra

### NSFW

FALSE

### Website (optional)

https://ctbtv.ca/

### Logo

https://ctbtv.ca/wp-content/uploads/2018/04/ctb-tv-logo-2018-s.png

### Notes

Community Channel in Québec, Canada.

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=CTBTV.ca
