### ISSUE TITLE
TCM channel loops every few seconds

### ISSUE THREAD

**Issue by GithubDaveW** [iptv-org/database#3305]
TCM Channel (both East and West) on the Github Free IPTV (English language Playlist) opens fine and looks good, but stops after 5 to 30 seconds, and then plays the same 5 to 30 seconds of video over and over (indefinitely).  

The TCM channel(s) are under the category of; "Classic; Movies"  (or, are shown as such in the Tivimate Premium Player).  Please note that the TCM channel(s) worked fine for many months up until about a month ago.  Both TCM East and TCM West have this problem, but they are both the same channel - broadcast 3 hours apart.  I am having the same problem with the TCM broadcast on two different Android TV boxes. 

A gracious thank-you for any help that you can offer to restore either (or preferably both broadcasts) of the TCM channel.

**Comment by Carlinhos027** [comment]
Please, open your issue here: https://github.com/iptv-org/iptv/issues
