### ISSUE TITLE
Add: Télé-Québec

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#332]
### Channel Name

Télé-Québec

### Country

CA

### Subdivision (optional)

CA-QC

### City (optional)

Montreal

### Broadcast Area

s/CA-QC

### Languages

fre

### Categories (optional)

education

### NSFW

FALSE

### Website (optional)

https://www.telequebec.tv/

### Logo

https://www.telequebec.tv/apple-touch-icon.png

### Notes

Streaming URL:

https://bcovlive-a.akamaihd.net/575d86160eb143458d51f7ab187a4e68/us-east-1/6101674910001/profile_3/chunklist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Tele-Quebec
