### ISSUE TITLE
Add: Dox TV [RS] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3373]
### Channel Name

Dox TV

### Country

RS

### Broadcast Area

c/RS

### Languages

srb

### Categories (optional)

Documentary

### NSFW

FALSE

### Website (optional)

https://www.doxtv.rs/

### Logo

https://uploads-ssl.webflow.com/5cf82e0188aeb17f79fa5d4b/615c670a4f3e4f85b76ca033_DOXTV%20-%20logo%20-%20footer.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=DoxTV.hr
