### ISSUE TITLE
Add: TACM Channel 189

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3389]
### Channel Name

TACM Channel 189

### Alternative Names (optional)

Traverse Area Community Media Channel 189

### Country

US

### Subdivision (optional)

US-MI

### City (optional)

Traverse City

### Broadcast Area

s/US-MI

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.tacm.tv/communitytvnow.asp

### Logo

https://www.tacm.tv/media/pages/tacm_logo_lgw.png

### Notes

https://reflect-tacm.cablecast.tv/live-3/live/WIFI-1596k-540p/WIFI-1596k-540p.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=CommunityTVChannel189.us
