### ISSUE TITLE
Add: bctv 16

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3396]
### Channel Name

bctv 16

### Alternative Names (optional)

Burnsville Community Television 16

### Country

US

### Subdivision (optional)

US-MN

### City (optional)

Burnsville

### Broadcast Area

s/US-MN

### Languages

eng

### Categories (optional)

legislative

### NSFW

FALSE

### Website (optional)

https://burnsvillemn.gov/484/Burnsville-Community-Media

### Logo

https://connect.telvue.com/dynamicthumb/W1siZiIsImVmNTc1NDMwLWNmMTQtMDEzMy1iMjUwLTAwMjU5MGYwMDg1Yy9zdHJlYW1zL3RodW1iLTE1MDc1NzM0ODJfODA3NTYuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4NjQwIl1d?sha=bd048435754f73be

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=BCTV16.us
