### ISSUE TITLE
Add: Today's Shopping Choice

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#340]
### Channel Name

Today's Shopping Choice

### Country

CA

### Subdivision (optional)

CA-ON

### City (optional)

Mississauga

### Broadcast Area

s/CA-ON

### Languages

eng

### Categories (optional)

shopping

### NSFW

FALSE

### Website (optional)

https://www.tsc.ca/pages/watchuslive?ic=HP_WatchUsLive&fm=top_header

### Logo

https://src.tscimg.ca/Content/en_CA/Images/Marketing/2021/Masterbrand2_Campign/GiftCard/MB21_GiftCards_Footer.svg

### Notes

Streaming URL:

https://tscamd.akamaized.net/hls/live/503340/TSCLive/video_0/video_0.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=TSC.ca
