### ISSUE TITLE
Add: WCGtv

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#341]
### Channel Name

WCGtv

### Country

CA

### Subdivision (optional)

CA-MB

### City (optional)

Brandon

### Broadcast Area

s/CA-MB

### Languages

eng

### Categories (optional)

teleservice

### NSFW

FALSE

### Website (optional)

https://www.wcgtv.ca/player/wcgtv-public-meetings

### Logo

https://d3liapbvol766o.cloudfront.net/50779/public/public/system/posters/856617/episode/WCGtvOnline_Col_200x200-01_1606492394_1616516172.png

### Notes

Streaming URL:

https://wowzastream.westmancom.com/wcgtvlive/wcgtvPSA.stream/master.m3u8

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=WCGtv
