### ISSUE TITLE
Add: Polo TV

### ISSUE THREAD

**Issue by Eow2022yia** [iptv-org/database#3445]
### Channel Name

Polo TV

### Network (optional)

Polsat

### Owners (optional)

Telewizja Polsat

### Country

PL

### Broadcast Area

PL

### Languages

pol

### Categories (optional)

Music

### NSFW

FALSE

### Launched (optional)

2011-05-07

### Website (optional)

polotv.pl

### Logo

https://upload.wikimedia.org/wikipedia/commons/7/7a/Pollotgvg.png

### Notes

Music channel from Poland, I would love to see added, more information on station: https://wikipedia.org/wiki/Polo_TV

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=PoloTV.pl

**Comment by Eow2022yia** [comment]
Apologies and thanks :)
