### ISSUE TITLE
Add: LRT Televizija [LT]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/database#3447]
### Channel Name

LRT Televizija

### Alternative Names (optional)

Lietuvos Programme; LTV; LRT

### Country

LT

### Broadcast Area

LT

### Languages

Lithuanian

### Categories (optional)

Kids

### NSFW

FALSE

### Launched (optional)

April 30 1957

### Website (optional)

http://www.lrt.lt/en/channels/ltv

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/LRT_TV_Logo_2022.svg/1280px-LRT_TV_Logo_2022.svg.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=LRTTV.lt
