### ISSUE TITLE
Add: Temple TV [DE/GH] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3453]
### Channel Name

Temple TV

### Country

DE

### City (optional)

Düsseldorf

### Broadcast Area

c/DE, c/GH

### Languages

eng

### Categories (optional)

Religious

### NSFW

FALSE

### Logo

https://i.imgur.com/Vn9Hf6s.jpg

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=TempleTV.ng
