### ISSUE TITLE
Add: The Base Gospel [GH] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3454]
### Channel Name

The Base Gospel

### Country

GH

### Broadcast Area

c/GH

### Languages

eng

### Categories (optional)

music

### NSFW

FALSE

### Logo

https://i.imgur.com/0moSF3t.png

**Comment by freearhey** [comment]
We only add TV channels to the database.

**Comment by Carlinhos027** [comment]
> We only add TV channels to the database.

Is also TV channel.
https://asiakwa.com/thebasetv/index.m3u8
