### ISSUE TITLE
Add: Pacific Coast TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#346]
### Channel Name

Pacific Coast TV

### Country

US

### Subdivision (optional)

US-CA

### City (optional)

Pacifica

### Broadcast Area

s/US-CA

### Languages

eng

### Categories (optional)

community

### NSFW

FALSE

### Website (optional)

https://videoplayer.telvue.com/player/wuZKb9gwEY7sMACIIsr7VSJglB35kNZA/stream/159?fullscreen=true&showtabssearch=false&autostart=false

### Logo

http://pacificcoast.tv/favicon.ico

### Notes

Streaming URL:

https://pacifica-ca.secure.footprint.net/egress/bhandler/pacificaca/streama/chunklist_b2192000.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=PCTChannel26.us
