### ISSUE TITLE
Add: EWTN Canada

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#348]
### Channel Name

EWTN Canada

### Network (optional)

EWTN

### Country

CA

### City (optional)

Etobicoke

### Broadcast Area

s/CA-ON

### Languages

eng

### Categories (optional)

religion

### NSFW

FALSE

### Website (optional)

https://www.ewtn.com/tv/schedule/canada

### Logo

https://www.ewtn.com/assets/ewtn-badge-4f156d7cd046dd20f7902ec63dd3e1e6892effb9130c634b1fcd868a3a43a05f.jpg

### Notes

Streaming URL:

https://cdn3.wowza.com/1/YW5wSWZiRGd2eFlU/bGV0aVBq/hls/whb7tbvs/448/chunklist.m3u8

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=EWTN%20Canada
