### ISSUE TITLE
Add: ABS TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#349]
### Channel Name

ABS TV

### Country

AG

### City (optional)

Saint John's

### Broadcast Area

s/AG

### Languages

eng

### NSFW

FALSE

### Website (optional)

https://abstvradio.com/live-streaming/

### Logo

https://abstvradio.com/wp-content/uploads/2014/12/ABS-Logo_sm.png

### Notes

Streaming URL:

https://cdn001.tegotv.com/liveabr/Live_TV~ABS_Television~ABS_TV/live/Live_TV~FHD~854~ABS_TV_480p/chunks_dvr_timeshift-0-7200.m3u8?nimblesessionid=7507491&wmsAuthSign=c2VydmVyX3RpbWU9OS83LzIwMjIgMTowNjo1NSBBTSZoYXNoX3ZhbHVlPVFUczFkUnFnU3grM3A0QjRmMng1TGc9PSZ2YWxpZG1pbnV0ZXM9MTIwJmlkPTI0MjM1MTY0OTQ=

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=ABSTV.ag
