### ISSUE TITLE
Add: 1TV Persian

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#350]
### Channel Name

1TV Persian

### Native Name (optional)

Kanal Javan

### Country

US

### Subdivision (optional)

US-CA

### City (optional)

Los Angeles

### Broadcast Area

s/US-CA

### Languages

fas;eng

### NSFW

FALSE

### Website (optional)

https://kanaljavan.com/tv-farsi/1tv-persian/

### Logo

https://kanaljavan.com/wp-content/uploads/2021/05/logo4-1080-300x169.png

### Notes

Streaming URL:

https://stream.persiantv1.com/ptv1/playlist1/index.m3u8

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=1TV%20Persian
