### ISSUE TITLE
Add: MITV [MM]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3567]
### Channel Name

MITV

### Alternative Names (optional)

Myanmar International Television

### Country

MM

### Broadcast Area

c/MM

### Languages

mya	

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.myanmaritv.com/

### Logo

https://upload.wikimedia.org/wikipedia/en/f/f1/Logo_of_MITV.png

**Comment by freearhey** [comment]
https://iptv-org.github.io/channel?id=MyanmarInternationalTV.mm
