### ISSUE TITLE
Fix channel links

### ISSUE THREAD

**Issue by Mustakim621** [iptv-org/database#3585]
in the playlist, there are many channels but many of them do not play. it shows errors. please fix the channel links
![image](https://user-images.githubusercontent.com/107194749/236598130-ba9ccb4e-27e0-4fc2-83f6-174ff7c96855.png)

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%F0%9F%9B%A0+broken+stream&template=-----broken-stream.yml&title=Broken%3A+
