### ISSUE TITLE
Add: Pasco City Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3596]
### Channel Name

Pasco City Television

### Alternative Names (optional)

PSC-TV

### Country

US

### Subdivision (optional)

US-WA

### City (optional)

Pasco

### Broadcast Area

s/US-WA

### Languages

eng

### Categories (optional)

legilsative

### NSFW

FALSE

### Website (optional)

https://cloud.castus.tv/vod/pasco/video/620e414e1dcaf3000810f79c?page=HOME&type=live

### Logo

https://www.pasco-wa.gov/ImageRepository/Document?documentId=59850

### Notes

https://castus-vod-dev.s3.amazonaws.com/vod_clients/pasco/live/ch1/video.m3u8

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- the logo link is geoblocked
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected yet again

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
