### ISSUE TITLE
Add: Redmond City TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3597]
### Channel Name

Redmond City TV

### Alternative Names (optional)

RCTV

### Country

US

### Subdivision (optional)

US-WA

### City (optional)

Redmond

### Broadcast Area

s/US-WA

### Languages

eng

### Categories (optional)

legislative

### NSFW

FALSE

### Website (optional)

https://redmond.granicus.com/player/camera/2?&redirect=true

### Logo

https://redmond.granicus.com/core/Handlers/media/attachmentdisplay.ashx?guid=412f6f5b-6446-4bdb-9e3b-832d9994a42f

### Notes

https://cdn3.wowza.com/5/djRwZmQvTEJidmZD/redmond/G1103_002/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- logo is not available outside the US

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
No idea what to do

**Comment by freearhey** [comment]
You can either use the logo from another source or upload it to one of the free image hosting sites
