### ISSUE TITLE
Add: ATN Music [BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3599]
### Channel Name

ATN Music

### Country

BD

### Broadcast Area

c/BD

### Languages

ben

### Categories (optional)

music

### NSFW

FALSE

### Website (optional)

http://atnmusic.tv/

### Logo

https://www.jagobd.com/wp-content/uploads/2015/12/atnmusic.jpg?x50681

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
