### ISSUE TITLE
Add: Bangla21 TV [BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3601]
### Channel Name

Bangla21 TV

### Country

BD

### Broadcast Area

c/BD

### Languages

ben

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://bangla21.tv/

### Logo

https://www.jagobd.com/wp-content/uploads/2016/02/bangla21tv.jpg?x50681

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
