### ISSUE TITLE
Add: Boishakhi TV Plus [BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3603]
### Channel Name

Boishakhi TV Plus

### Country

BD

### Broadcast Area

c/BD

### Languages

ben

### Categories (optional)

entertainment

### NSFW

FALSE

### Logo

https://www.jagobd.com/wp-content/uploads/2020/12/boishakhitvplus.jpeg

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
