### ISSUE TITLE
Add: Channel Europe [BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3604]
### Channel Name

Channel Europe

### Country

BD

### Broadcast Area

c/BD

### Languages

ben

### Categories (optional)

entertainment

### NSFW

FALSE

### Logo

https://www.jagobd.com/wp-content/uploads/2022/12/cheu.png

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
