### ISSUE TITLE
Add: ATN News [BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3607]
### Channel Name

ATN News

### Country

BD

### Broadcast Area

c/BD

### Languages

ben

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.atnnewstv.com/

### Logo

https://www.jagobd.com/wp-content/uploads/2016/08/atn-news.jpg?x50681

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=ATNNews.bd
