### ISSUE TITLE
Add: Shree Bangla [IN/BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3608]
### Channel Name

Shree Bangla

### Country

IN

### Broadcast Area

c/IN;c/BD

### Languages

ben

### Categories (optional)

general

### NSFW

FALSE

### Logo

https://www.jagobd.com/wp-content/uploads/2022/07/shreebangla.jpg

**Comment by freearhey** [comment]
Please update your request:

- broadcast area codes must be separated by `;`
- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
