### ISSUE TITLE
Add: Jhankar TV [CA/BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3609]
### Channel Name

Jhankar TV

### Country

CA

### Broadcast Area

c/CA;c/BD

### Languages

ben

### Categories (optional)

culture

### NSFW

FALSE

### Logo

https://www.jagobd.com/wp-content/uploads/2019/05/Jhankartv.jpg

**Comment by freearhey** [comment]
Please update your request:

- broadcast area codes must be separated by `;`
- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
