### ISSUE TITLE
Add: Medina Live [BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3611]
### Channel Name

Medina Live

### Country

BD

### Broadcast Area

c/BD

### Languages

ben

### Categories (optional)

religious

### NSFW

FALSE

### Logo

https://www.jagobd.com/wp-content/uploads/2020/05/Medina-Live.jpg

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
