### ISSUE TITLE
Add: Movie Bangla [BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3612]
### Channel Name

Movie Bangla

### Country

BD

### Broadcast Area

c/BD

### Languages

ben

### Categories (optional)

movies

### NSFW

FALSE

### Logo

https://www.jagobd.com/wp-content/uploads/2016/02/moviebangla.jpg?x50681

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
