### ISSUE TITLE
Add: RTV Music [BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3614]
### Channel Name

RTV Music 

### Country

BD

### Broadcast Area

c/BD

### Languages

ben

### Categories (optional)

music

### NSFW

FALSE

### Logo

https://www.jagobd.com/wp-content/uploads/2017/01/rtvmusic.jpg?x50681

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
