### ISSUE TITLE
Add: ATN Islamic TV [BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3615]
### Channel Name

ATN Islamic TV

### Country

BD

### Broadcast Area

c/BD

### Languages

ben

### Categories (optional)

religious

### NSFW

FALSE

### Logo

https://www.jagobd.com/wp-content/uploads/2016/02/atnislamictv.jpg?x50681

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- language code must be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
