### ISSUE TITLE
Add: KTV Serbinow [PL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3619]
### Channel Name

KTV Serbinow

### Alternative Names (optional)

KTV Serbinów;Katolicka Telewizja Serbinów 

### Country

PL

### Broadcast Area

c/PL

### Languages

pol

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://parafiaserbinow.pl/ktv-serbinow/

### Logo

https://imgtr.ee/images/2023/05/24/wQmIA.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px
- category name should be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
