### ISSUE TITLE
Add: Manas TV [KZ/RU/TR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3621]
### Channel Name

Manas TV

### Owners (optional)

Kyrgyz-Turkish Manas University

### Country

KZ

### City (optional)

Bishkek

### Broadcast Area

c/KZ;c/RU;c/TR

### Languages

kir;rus;tur

### Categories (optional)

 education;culture;entertainment

### NSFW

FALSE

### Website (optional)

http://mediamanas.kg/

### Logo

https://i.ibb.co/10FW1yf/manaslogo.png

### Notes

http://212.42.111.136/hls/manas.m3u8

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * language code is incorrect
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed
