### ISSUE TITLE
Add: RizaNova TV [UZ]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3628]
### Channel Name

RizaNova TV

### Country

UZ

### Broadcast Area

c/UZ

### Languages

uzb

### Categories (optional)

entertainment

### NSFW

FALSE

### Logo

https://imgtr.ee/images/2023/05/24/wQLVx.png

### Notes

UCDPnSqLmYqHadD6VkrRiarg.m3u8

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
