### ISSUE TITLE
Add: Nos TV Bonaire [BQ]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3629]
### Channel Name

Nos TV Bonaire

### Country

BQ

### Broadcast Area

c/BQ

### Languages

pap;nld

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.nostvbonaire.com/

### Logo

https://i.ibb.co/R6kb44B/cropped-LOGO-NOSTV-WEBSITE-2019-1.png

### Notes

http://streaming.flamingotv.net/nostv/live.m3u8

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
