### ISSUE TITLE
Add: NCW Life Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3630]
### Channel Name

NCW Life Channel

### Country

US

### Subdivision (optional)

US-WA

### City (optional)

Wenatchee

### Broadcast Area

s/US-WA

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.ncwlife.com/

### Logo

https://bloximages.newyork1.vip.townnews.com/ncwlife.com/content/tncms/custom/image/0710ece4-98f8-11ed-8d5a-774ed0ce112e.png?resize=150%2C150

### Notes

https://live.field59.com/ncwlife/ncwlife1/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- incorrect broadcast area code

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Correected
