### ISSUE TITLE
Add: The Retro Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3635]
### Channel Name

The Retro Channel

### Country

PR

### City (optional)

Bayamon

### Broadcast Area

c/PR

### Languages

spa

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://www.theretrochannel.tv/

### Logo

https://theretrochannel.tv/img/theretrofb.jpg

### Notes

https://5fd5567570c0e.streamlock.net/theretrochannel/stream/playlist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=TheRetroChannel.us
