### ISSUE TITLE
Add: CAF TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3637]
### Channel Name

CAF TV

### Owners (optional)

Confederation of African Football

### Country

EG

### City (optional)

6th of October City

### Broadcast Area

c/EG

### Languages

ara

### Categories (optional)

sports

### NSFW

FALSE

### Website (optional)

https://www.cafonline.com/

### Logo

https://www.cafonline.com/assets/icons/caflogo_black.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
