### ISSUE TITLE
Add: TV4 Latvija [LV]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3639]
### Channel Name

TV4 Latvija

### Country

LV

### City (optional)

Riga

### Broadcast Area

c/LV

### Languages

lav

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://www.cetri.lv/

### Logo

https://imgtr.ee/images/2023/05/24/wQNPJ.png

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
