### ISSUE TITLE
Add: EBC

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3646]
### Channel Name

EBC

### Alternative Names (optional)

Ethiopian Broadcasting Corporation

### Country

ET

### City (optional)

Addis Ababa

### Broadcast Area

c/ET

### Languages

amh;orm

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1964-11-02

### Website (optional)

http://www.ebc.et/

### Logo

https://i0.wp.com/usiafrica.com/wp-content/uploads/EBC-Logo-ethiopia.png?fit=330%2C180&ssl=1

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected yet again
