### ISSUE TITLE
Add: GRTS TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3647]
### Channel Name

GRTS TV

### Country

GM

### City (optional)

Serekunda

### Broadcast Area

c/GM

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1967-01-01

### Website (optional)

https://www.grts.gm/

### Logo

https://yt3.googleusercontent.com/ytc/AGIKgqOvqFhIkjJOlczBFpNcZlcQXg8fZ5f9KIb1n-ww=s176-c-k-c0x00ffffff-no-rj

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
