### ISSUE TITLE
Add: Kantanka TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3648]
### Channel Name

Kantanka TV

### Country

GH

### City (optional)

Dansoman

### Broadcast Area

c/GH

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://kantankatv.com/page/live-tv

### Logo

https://media.licdn.com/dms/image/C560BAQGwnqLgEdTkzg/company-logo_200_200/0/1580461800839?e=2147483647&v=beta&t=CEw0TbEO-MogChSZsWo8QtOgiMDODGJ6zb3W9-l2zSM

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
