### ISSUE TITLE
Add: Tele Pam [US/HT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3653]
### Channel Name

Tele Pam

### Country

US

### Subdivision (optional)

US-FL

### Broadcast Area

c/US;c/HT

### Languages

fra;hat;eng

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://telepam.tv/

### Logo

https://i.ibb.co/xMYMyHh/telepammmm.png

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
