### ISSUE TITLE
Add: Good TV [KR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3654]
### Channel Name

Good TV

### Country

KR

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://home.goodtv.co.kr/

### Logo

https://i.ibb.co/1v913gn/logo-goodtv.png

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
