### ISSUE TITLE
Add: RUTC TV [KR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3655]
### Channel Name

RUTC TV

### Country

KR

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://rutc.tv/

### Logo

https://i.ibb.co/yPDhKBp/rutc-logo.jpg

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
