### ISSUE TITLE
Add: YTN Korean [KR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3657]
### Channel Name

YTN Korean

### Alternative Names (optional)

와이티엔 코리안

### Country

KR

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

entertainment;news;culture

### NSFW

FALSE

### Website (optional)

https://www.ytn.co.kr/replay/channel.php?idx=6

### Logo

https://image.ytn.co.kr/ytn/replay/ch_logo_6.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=YTNWorld.kr
