### ISSUE TITLE
Add: C channel [KR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3659]
### Channel Name

C channel

### Country

KR

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://www.cchannel.com/main/

### Logo

https://i.ibb.co/GC73Fxt/logo.png

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
