### ISSUE TITLE
Add: América Tucumán

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#366]
### Channel Name

America Tucuman

### Country

AR

### City (optional)

Tucumán

### Broadcast Area

s/AR

### Languages

esp

### Categories (optional)

news

### NSFW

FALSE

### Logo

https://americatucuman.com/wp-content/uploads/2020/03/cropped-faviso-america-tucuman-192x192.png

### Notes

Streaming URL:

https://youtu.be/UcQRYiWPJtY

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=America%20Tucuman
