### ISSUE TITLE
Add: KTV [KR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3660]
### Channel Name

KTV

### Alternative Names (optional)

Korea TV;國民放送

### Country

KR

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

legislative

### NSFW

FALSE

### Website (optional)

https://www.ktv.go.kr/

### Logo

https://imgtr.ee/images/2023/05/24/wQtWM.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
