### ISSUE TITLE
Add: PTV [UA]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3667]
### Channel Name

PTV

### Alternative Names (optional)

Poltavske TV;Полтавське телебачення

### Country

UA

### City (optional)

Poltava

### Broadcast Area

c/UA

### Languages

ukr

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://ptv.ua/

### Logo

https://imgtr.ee/images/2023/05/24/wQcJ1.png

### Notes

https://cdn10.live-tv.cloud/hrpl/hrpl-abr/playlist.m3u8 (720p)

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
