### ISSUE TITLE
Add: SET TV 2 [US/VN]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3679]
### Channel Name

SET TV 2

### Alternative Names (optional)

Saigon Entertainment Television 2

### Country

US

### Subdivision (optional)

US-CA

### City (optional)

Garden Grove

### Broadcast Area

c/US;c/VN

### Languages

eng;vie

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://setchannel.tv

### Logo

https://setchannel.tv/wp-content/uploads/2019/08/SET-web-logo.png

**Comment by freearhey** [comment]
Please update your request:

- broadcast area codes must be separated by `;`

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
