### ISSUE TITLE
Add: TV Santa Cruz [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3680]
### Channel Name

TV Santa Cruz

### Country

CR

### Broadcast Area

c/CR

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.tvsantacruzcr.net/

### Logo

https://imgtr.ee/images/2023/05/24/wQiUl.jpg

### Notes

https://rtmp.info/tvsantacruz/envivo/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * the logo link is geoblocked
> * the size of the logo should not exceed 512x512px
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Changes done for all requests.
