### ISSUE TITLE
Add: Guinee Buzz TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3681]
### Channel Name

Guinee Buzz TV

### Alternative Names (optional)

224infos

### Country

GN

### City (optional)

Conakry

### Broadcast Area

c/GN

### Languages

fra

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.guineebuzz.com/

### Logo

https://www.mytelevision.tv/assets/img/chaines/guineebuzz.png

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Please update your request:

- the channel name can only include letters of the Latin alphabet

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected yet again
