### ISSUE TITLE
Add: Al Masar TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3683]
### Channel Name

Al Masar TV

### Alternative Names (optional)

تلفزيون المسار

### Country

LY

### City (optional)

Benghazi

### Broadcast Area

c/LY

### Languages

ara

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://almasartv.ly/

### Logo

https://play-lh.googleusercontent.com/FHPrsr391mPFqKfTq6ZdvWPZNVfsZeTAVQ8rjQF-NosnRdNipUy5xa43RWkiF4tGcQU

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
