### ISSUE TITLE
Add: TV Mana Maputo

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3689]
### Channel Name

TV Mana Maputo

### Alternative Names (optional)

TV Maná Moçambique

### Country

MZ

### City (optional)

Maputo

### Broadcast Area

c/MZ

### Languages

por

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://manasat.com/mm1/grelhas/tv_mana_mocambique.html

### Logo

https://www.livetvcentral.com/imgs/tvs/2594.jpg

### Notes

http://c3.manasat.com:1935/tvmz/tvmz2/playlist.m3u8

[Geo-blocked]

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
