### ISSUE TITLE
Add: Trust TV

### ISSUE THREAD

**Issue by booziebatsymbol** [iptv-org/database#369]
### Channel Name

Trust TV

### Country

NG

### Broadcast Area

NG

### Languages

eng

### Categories (optional)

news;documentaries;entertainment

### NSFW

FALSE

### Website (optional)

https://trusttv.com/

### Logo

https://ibb.co/R004nkS

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/ffaffa999203aa73db91ca51472894054796b127
