### ISSUE TITLE
Add: Nollywood Capital TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3690]
### Channel Name

Nollywood Capital TV

### Country

NG

### City (optional)

Lagos

### Broadcast Area

c/NG

### Languages

eng

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://nollywoodcapitaltv.com/watch/46626541

### Logo

https://image.roku.com/developer_channels/prod/61530e2a25ef79aaa99eaf301a1135cb87f81fdfcd8af5be33c700cc772db2b8.png

### Notes

https://ssai.castify.ai/media/f49527d2-444d-4475-8912-24134347aa42/mainManifest.m3u8?player.app_bundle=com..nollywoodcapitaltv&player.did=1683886052644.27796c5f5a50d&player.us_privacy=1&player.gdpr=1&player.content_title=IndiMusic+TV+Live&player.ifa_type=sessionid&player.app_name=Nollywood+Capital+TV&player.app_store_url=&player.is_lat=false&player.height=1080&player.width=1920

**Comment by freearhey** [comment]
Please update your request:

- logo url must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
