### ISSUE TITLE
Add: Label TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3691]
### Channel Name

Label TV

### Country

SN

### City (optional)

Dakar

### Broadcast Area

c/SN

### Languages

fra

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.labeltelevision.com/direct

### Logo

https://media.licdn.com/dms/image/C4D0BAQFmjwc-YfGo4A/company-logo_200_200/0/1605524865389?e=2147483647&v=beta&t=OEuT5VoKApwTt4gJTv90FMrDx1SV6FCWbSqPCLB_xNk

### Notes

https://live1.acangroup.org:1929/publiclive/labeltv/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NS8xMi8yMDIzIDEwOjEzOjI2IEFNJmhhc2hfdmFsdWU9RHhRQS8vTWdiNUtTSlU0THVRT29hdz09JnZhbGlkbWludXRlcz01

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected yet again

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=LabelTV.ga
