### ISSUE TITLE
Add: Teletica Canal 7 Costa Rica

### ISSUE THREAD

**Issue by mariorgonzalezo22** [iptv-org/database#3692]
### Channel Name

Teletica

### Alternative Names (optional)

Canal 7

### Country

Costa Rica

### Broadcast Area

c/<CR>

### Languages

Spanish

### NSFW

FALSE

### Logo

https://logowik.com/teletica-vector-logo-3116.html

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=Teletica7.cr

**Comment by mariorgonzalezo22** [comment]
it doesn't appear in the playlist
<img width="391" alt="image" src="https://github.com/iptv-org/database/assets/133358291/1b22e918-3721-43f4-ab4e-5074ebf27c25">

**Comment by freearhey** [comment]
This repository stores only the description of the channels. If you are looking for a link to a channel broadcast, it is better to leave your request here: https://github.com/iptv-org/iptv/issues
