### ISSUE TITLE
Hello 
Tanzanian channels

### ISSUE THREAD

**Issue by Emilselimli** [iptv-org/database#3693]
EXTINF:-1, 														[TAN] TBC 1			
https://134630.global.ssl.fastly.net/5fe35eae8c53540cab83659a/live_5ffe3dc07b8f11ec89fd476d1ed4a755/tracks-v3a1/mono.m3u8
#EXTINF:-1, 														[TAN] TBC 2			
https://134630.global.ssl.fastly.net/5fe35eae8c53540cab83659a/live_36e8f510dfee11ec9dc2d5b207a2c04f/tracks-v1a1/mono.m3u8
#EXTINF:-1, 														[TAN] Tanzania Safari		
https://134630.global.ssl.fastly.net/5fe35eae8c53540cab83659a/live_0a6ef900ad0511ed8f65a940024f638d/tracks-v1a1/mono.m3u8

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&projects=&template=------channel-request.yml&title=Add%3A+
