### ISSUE TITLE
Hello
Cote' de ivuar channels added

### ISSUE THREAD

**Issue by Emilselimli** [iptv-org/database#3694]
#EXTINF:-1 tvg-id="RTI1.ci"  tvg-logo="https://www.lyngsat.com/logo/tv/rr/rti-1-ci.png", 				[COI] RTI 1 
https://www.enovativecdn.com/rticdn/smil:rti1.smil/chunklist_w1617581567_b650000_sleng.m3u8
#EXTINF:-1 tvg-id="RTI1.ci"  tvg-logo="https://www.lyngsat.com/logo/tv/rr/rti-1-ci.png", 				[COI] RTI 1 Bouake
https://www.enovativecdn.com/rticdn/smil:rti1.smil/chunklist_w694263291_b650000_sleng.m3u8
#EXTINF:-1 tvg-id="RTI2.ci"  tvg-logo="https://www.lyngsat.com/logo/tv/rr/rti-2-ci.png", 				[COI] RTI 2 
https://www.enovativecdn.com/rticdn/smil:rti2.smil/chunklist_w697163309_b650000_sleng.m3u8

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&projects=&template=------channel-request.yml&title=Add%3A+
