### ISSUE TITLE
New Channel BENIN please add

### ISSUE THREAD

**Issue by Emilselimli** [iptv-org/database#3695]
#EXTINF:-1 tvg-logo="https://www.lyngsat.com/logo/tv/oo/ortb-tv-bj.png", 						[BEN] ORTB
https://strfla209.streamakaci.tv/ortb/ortb1-multi/ortb/ortb1_480p/chunks.m3u8
#EXTINF:-1 tvg-logo="https://www.lyngsat.com/logo/tv/bb/bb_24_bj.png", 							[BEN] BB24
https://edge21.vedge.infomaniak.com/livecast/ik:bb24-1/chunklist_w1518683742.m3u8
#EXTINF:-1 tvg-logo="https://www.lyngsat.com/logo/tv/ee/e-tele-bj.png", 						[BEN] E-TELE
https://livetvsteam.com:1936/etelebenin/etelebenin/chunklist_w955976671.m3u8
#EXTINF:-1 tvg-logo="https://www.lyngsat.com/logo/tv/cc/canal_3_benin.png", 						[BEN] Canal 3
https://live.creacast.com/bluediamond/stream/chunklist_w1706461595.m3u8
#EXTINF:-1 tvg-logo="https://www.lyngsat.com/logo/tv/ee/eden_tv_bj.png", 						[BEN] Eden TV
#EXTINF:-1 tvg-logo="https://www.lyngsat.com/logo/tv/tt/tvc-benin-bj.png", 						[BEN] TVC Benin
https://live.tvcbenin.com/BENIN/TVC.stream/chunks.m3u8

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&projects=&template=------channel-request.yml&title=Add%3A+
