### ISSUE TITLE
SOUTH SUDAN

### ISSUE THREAD

**Issue by Emilselimli** [iptv-org/database#3696]
#EXTINF:-1 tvg-logo="https://www.lyngsat.com/logo/tv/aa/africa-tv-1-sd.png", 						[SUD] SSBC
http://nimplus5.bozztv.com/ssudan/ssudan/chunklist_w953133435.m3u8

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&projects=&template=------channel-request.yml&title=Add%3A+
