### ISSUE TITLE
Majid is working but there is no sound

### ISSUE THREAD

**Issue by mogaio** [iptv-org/database#3697]
I think this channel is muted for some reason, it's currently working but without any sound for a couple of months now.

Majid.ae,Majid,,,,AE,,,c/AE,ara,kids,FALSE,,,,https://majid.ae/,https://i.imgur.com/TzOKMMy.png

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%F0%9F%9B%A0+broken+stream&projects=&template=-----broken-stream.yml&title=Broken%3A+
