### ISSUE TITLE
Add: Twit.tv

### ISSUE THREAD

**Issue by baliebox4916** [iptv-org/database#3698]
### Channel Name

TWiT

### Network (optional)

TWiT.tv

### Owners (optional)

TWiT LLC

### Country

US

### Broadcast Area

s/US-CA

### Languages

eng

### Categories (optional)

science

### NSFW

FALSE

### Launched (optional)

2005-04-01

### Website (optional)

https://twit.tv/live

### Logo

https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/hbudhnzfcpx2ff8exsxj

### Notes

seeing how g4tv is dead for good now is the time to add twit.tv (the true successor to the old tech tv from back in the day)

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect
- language code must be in lowercase
- category name should be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
