### ISSUE TITLE
Add: Mouride TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3699]
### Channel Name

Mouride TV

### Country

SN

### City (optional)

Pikine

### Broadcast Area

c/SN

### Languages

fra;ara

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://www.mouridetv.net/

### Logo

https://pbs.twimg.com/profile_images/1390777164950343690/ueRW7E09_400x400.jpg

### Notes

http://51.81.109.113:1935/Livemouridetv/mouridetv/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect
- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=MourideTV.sn
