### ISSUE TITLE
Add: tvi HD

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3706]
### Channel Name

tvi HD

### Alternative Names (optional)

Tamil Vision International

### Country

CA

### Subdivision (optional)

CA-ON

### City (optional)

Toronto

### Broadcast Area

s/CA-ON

### Languages

tam;eng

### Categories (optional)

entertainment

### NSFW

FALSE

### Launched (optional)

2001-01-01

### Website (optional)

https://www.tamilvision.tv/

### Logo

https://www.tamilvision.tv/image/logo.png

### Notes

https://live.tamilvision.tv/TVI/HD/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
