### ISSUE TITLE
Add: TV Monarca

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3708]
### Channel Name

TV Monarca

### Country

MX

### City (optional)

Ciudad Hidalgo

### Broadcast Area

c/MX

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://tvmonarca.com/

### Logo

https://scontent-yyz1-1.xx.fbcdn.net/v/t39.30808-1/305741704_486164950186556_4337458455262657048_n.jpg?stp=dst-jpg_p200x200&_nc_cat=105&ccb=1-7&_nc_sid=c6021c&_nc_ohc=HzDnk6boy0EAX_2Rsf7&_nc_ht=scontent-yyz1-1.xx&oh=00_AfDVOP1cgZnj2CeaKBP_ZWGmPtxBhhzQ1KDxMqih1ickSg&oe=64766D18

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
