### ISSUE TITLE
Add: TVP Mazatlán

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3714]
### Channel Name

XHMZ-TDT1

### Alternative Names (optional)

TVP Mazatlán

### Country

MX

### City (optional)

Mazatlán

### Broadcast Area

c/MX

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://tvpacifico.mx/tv-en-linea/mazatlan

### Logo

https://scontent-yyz1-1.xx.fbcdn.net/v/t39.30808-1/271755827_5321375487891095_2432776156282125041_n.jpg?stp=dst-jpg_p200x200&_nc_cat=109&ccb=1-7&_nc_sid=c6021c&_nc_ohc=UYUE80UtS2gAX-L-nPe&_nc_oc=AQmEmLD6ZaCgGG_xOi3pK5ekU1snWjsjuC_ianbulGULE8j76EUy2VpU0fujGvPPPNo&_nc_ht=scontent-yyz1-1.xx&oh=00_AfDv9IeMHVbBKfy4rh83_wZyH4v-G-vpetBQ8QBekD0sPQ&oe=6475C189

### Notes

https://5ca3e84a76d30.streamlock.net/gpacifico4/smil:mazatlan.smil/playlist.m3u8

[Geo-blocked]

**Comment by freearhey** [comment]
Please update your request:

- the call sign should be used as the channel name
- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
