### ISSUE TITLE
Add: CITV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3715]
### Channel Name

CITV

### Country

BM

### City (optional)

Hamilton

### Broadcast Area

c/BM

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://livestream.com/citvbermuda

### Logo

https://yt3.googleusercontent.com/ytc/AGIKgqNMLMiVZaf957K6fYXMit5Q_7Ezd-td7X5t_k7e=s900-c-k-c0x00ffffff-no-rj

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=CITV.bm
