### ISSUE TITLE
Add: Blessing TV Tamil [IN]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3722]
### Channel Name

Blessing TV Tamil 

### Country

IN

### Broadcast Area

c/IN

### Languages

tam

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://www.blessingtv.tv/

### Logo

https://i.ibb.co/r5p2yMm/14579702231.png

### Notes

https://stream.blessingtv.tv:1443/blessingtv-tamillive/mystream_720p/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
