### ISSUE TITLE
Add: Metro TV [IN]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3723]
### Channel Name

Metro TV 

### Country

IN

### Broadcast Area

c/IN

### Languages

tel

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.metrotvtelugu.com/

### Logo

https://i.ibb.co/CBgJ4QV/metro-logo.jpg

### Notes

https://2nbyjxw5l53k-hls-live.qezycdn.com/metrotv/live.stream/playlist.m3u8
576p

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
