### ISSUE TITLE
Add: Gospel TV India [IN]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3726]
### Channel Name

Gospel TV India 

### Country

IN

### Broadcast Area

c/IN

### Languages

tel

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://gospeltvindia.com/

### Logo

https://i.ibb.co/xhbZvzt/cropped-final-logo-300x127.png

### Notes

http://live.adostream.com:1935/gospeltv/gospeltv/playlist.m3u8 (720p)

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * logo URL must use the HTTPS protocol
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Changes done for #3621 #3629 #3643 #3653 #3654 #3655 #3658 #3659 #3675 #3688 #3722 #3723 #3726 #3782
