### ISSUE TITLE
Add: mnews

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3729]
### Channel Name

mnews

### Alternative Names (optional)

鏡新聞

### Country

TW

### City (optional)

Taipei

### Broadcast Area

c/TW

### Languages

zho

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.mnews.tw/

### Logo

https://i.ytimg.com/vi/5n0y6b0Q25o/hqdefault_live.jpg?sqp=-oaymwEjCPYBEIoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCXIMr1Cb8PO2vs9ZtapIAlSro4cw

**Comment by freearhey** [comment]
Please update your request:

- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
