### ISSUE TITLE
Add: A News

### ISSUE THREAD

**Issue by arecki2** [iptv-org/database#3733]
### Channel Name

A News

### Owners (optional)

Turkuvaz Yayın Hizmetleri ve Ticaret A.Ş.

### Country

TR

### Broadcast Area

c/TR; r/INT

### Languages

eng

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.anews.com.tr

### Logo

https://i.tmgrup.com.tr/anews/v1/2021/07/27/kunye-1627389315403.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=ANews.tr
