### ISSUE TITLE
Add: RTL Today Radio video board

### ISSUE THREAD

**Issue by arecki2** [iptv-org/database#3734]
### Channel Name

Today Radio

### Owners (optional)

CLT-UFA S.A.

### Country

LU

### Broadcast Area

c/LU

### Languages

eng

### Categories (optional)

music

### NSFW

FALSE

### Launched (optional)

2022-03-01

### Website (optional)

https://today.rtl.lu/radio

### Logo

https://i.imgur.com/O1c6wpt.png

**Comment by DJ1999-max** [comment]
We not to do Radio channels.

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
> Please update your request:
> 
>     * logo is not loaded
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Here: https://static.wikia.nocookie.net/logopedia/images/6/62/Today_Radio.svg/revision/latest?cb=20230427205451
