### ISSUE TITLE
Add: GIS-TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3736]
### Channel Name

GIS-TV

### Alternative Names (optional)

Government Information Service of Grenada

### Country

GD

### City (optional)

St. George's

### Broadcast Area

c/GD

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://gistvgrenada.org/

### Logo

https://is2-ssl.mzstatic.com/image/thumb/Purple4/v4/ac/b2/ee/acb2eea6-d82a-c1eb-291c-a8b357ba3da6/source/512x512bb.jpg

### Notes

https://media.streambrothers.com:1936/8474/8474/playlist.m3u8

[Geo-blocked]

**Comment by AntiPontifex** [comment]
Fixed

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed?
