### ISSUE TITLE
Add: Haiti News Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3737]
### Channel Name

Haiti News Channel

### Country

HT

### City (optional)

Port-au-Prince

### Broadcast Area

c/HT

### Languages

hat;fra

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://haitinewstv.com/

### Logo

https://m.media-amazon.com/images/I/51bJg+c7vRL.png

### Notes

https://haititivi.com/website/haitinews/index.fmp4.m3u8

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
