### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by Keyzro** [iptv-org/database#3740]
### Channel Name

Motorsport.tv

### Country

US

### Broadcast Area

C/US

### Languages

English

### Categories (optional)

Sports

### NSFW

FALSE

### Website (optional)

https://www.motorsport.tv

### Logo

https://provider-static.plex.tv/epg/cms/production/f0c73aed-c190-45ee-baea-65929b1207f4/motorsporttv_logo_blackbackround_Rainier.png

### Notes

Motorsport FAST channel show replay of Motorsport events around the world and Motorsport related programming.

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=Motorsporttv.fr
