### ISSUE TITLE
Add: Amigos TV Chiquimula

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3744]
### Channel Name

Amigos TV Chiquimula

### Country

GT

### City (optional)

Chiquimula

### Broadcast Area

c/GT

### Languages

spa

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://amigostv.com.gt/

### Logo

https://scontent-yyz1-1.xx.fbcdn.net/v/t1.6435-1/162699231_125115042954479_1031828036337803300_n.jpg?stp=dst-jpg_p200x200&_nc_cat=109&ccb=1-7&_nc_sid=c6021c&_nc_ohc=WeXU8sV41lAAX-YK-y4&_nc_ht=scontent-yyz1-1.xx&oh=00_AfD4xPkUqviLTktTcjDHlkGbp5PMIeEreitB9fOis3mHHw&oe=64990405

### Notes

https://tv91.hostingnuclear.com:19360/amigostv/amigostv.m3u8

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
