### ISSUE TITLE
Add: Canal KZO

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3745]
### Channel Name

Canal KZO

### Alternative Names (optional)

KZO

### Country

AR

### City (optional)

Buenos Aires

### Broadcast Area

c/AR

### Languages

spa

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://kuarzo.com/home/institucional/

### Logo

https://kuarzo.com/home/wp-content/uploads/2020/12/Kzo_Youtube-300x300.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=KZO.ar
