### ISSUE TITLE
Add: Latina TV 42.1

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3747]
### Channel Name

Latina TV 42.1

### Country

AR

### City (optional)

Cordoba

### Broadcast Area

c/AR

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.latinatv.com.ar/online/

### Logo

https://visionlatina.com/wp-content/uploads/2023/01/Radio-Vision-Latina-96.7-FM-300x300.png

**Comment by freearhey** [comment]
Please update your request:

- commas cannot be used in the channel name
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
