### ISSUE TITLE
Add: Canal10 Entre Rios

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3748]
### Channel Name

Canal10 Entre Rios

### Country

AR

### City (optional)

San Jose

### Broadcast Area

c/AR

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.10tv.com.ar/

### Logo

https://radiosnet.com.ar/img/core-img/logo.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
