### ISSUE TITLE
Add: El 10 TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3749]
### Channel Name

El 10 TV

### Alternative Names (optional)

Televisión Salteña

### Country

AR

### City (optional)

Salta

### Broadcast Area

c/AR

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://el10tv.com/

### Logo

https://el10tv.com/wp-content/uploads/2022/10/cropped-logo-1.png

### Notes

https://restreamer.el10tv.com/memfs/725003c4-79c2-4565-8311-f429db4f7777.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=Canal10Salta.ar
