### ISSUE TITLE
Add: Canal 8 San Juan

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3750]
### Channel Name

Canal 8 San Juan

### Country

AR

### City (optional)

San Juan

### Broadcast Area

c/AR

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.canal8sanjuan.com.ar/

### Logo

https://yt3.googleusercontent.com/ytc/AGIKgqPYspgaPVcDnGMJbiJyhthRt27nGqGkdWbqyk43bg=s176-c-k-c0x00ffffff-no-rj

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
