### ISSUE TITLE
Add: Canal 13 San Juan

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3751]
### Channel Name

Canal 13 San Juan

### Country

AR

### City (optional)

San Juan

### Broadcast Area

c/AR

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.canal13sanjuan.com/

### Logo

https://pbs.twimg.com/profile_images/1617246021/Captura_de_pantalla_2011-11-01_a_las_11.42.42_400x400.png

**Comment by freearhey** [comment]
Please update your request:

- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
