### ISSUE TITLE
Add: Cinerama Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3752]
### Channel Name

Cinerama Television

### Country

BO

### City (optional)

La Paz

### Broadcast Area

c/BO

### Languages

spa

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://cineramatv.com/

### Logo

https://play-lh.googleusercontent.com/RJ49IeJve4VPALBXqrqJGeAYOEoLQIZZ4zWwtJhofisng6ZYwGemZ-VXCx9ZQ-u7fw

### Notes

https://5d00db0e0fcd5.streamlock.net/7062/7062/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
