### ISSUE TITLE
Add: Rede Cultura do Para

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3754]
### Channel Name

Rede Cultura do Para

### Alternative Names (optional)

TV Cultura do Pará

### Country

BR

### City (optional)

Belem

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

education

### NSFW

FALSE

### Website (optional)

https://www.portalcultura.com.br/

### Logo

https://upload.wikimedia.org/wikipedia/pt/3/39/Logotipo_Rede_Cultura_do_Par%C3%A1.png

### Notes

https://www.portalcultura.com.br/playerhtml/funtelpa/tv_funtelpa/playlist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=TVCulturadoPara.br
