### ISSUE TITLE
Add: TV Shoptime

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3755]
### Channel Name

TV Shoptime

### Country

BR

### City (optional)

Rio de Janeiro

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

shop

### NSFW

FALSE

### Website (optional)

https://www.shoptime.com.br/ofertasdatv/?chave=TV_FAIXA_FOOTER

### Logo

https://reclamacoes.net.br/wp-content/uploads/shoptime-reclamacoes-300x200.jpg

**Comment by freearhey** [comment]
Please update your request:

- category name is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
