### ISSUE TITLE
Add: TV Assembleia Paraiba

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3762]
### Channel Name

TV Assembleia Paraiba

### Alternative Names (optional)

TV ALPB

### Country

BR

### City (optional)

João Pessoa

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.al.pb.leg.br/tvalpb/

### Logo

https://scontent-yyz1-1.xx.fbcdn.net/v/t39.30808-1/301834607_415267340707126_3613408099424745025_n.png?stp=dst-png_p200x200&_nc_cat=110&ccb=1-7&_nc_sid=c6021c&_nc_ohc=4lmlzGFBmyoAX-Y5pyj&_nc_ht=scontent-yyz1-1.xx&oh=00_AfAnCDPloczazU5opH_JTom248ok61q6e-N7bF1RDS8d2Q&oe=6472C06D

### Notes

http://tv.al.pb.leg.br/hls/tvalpb.m3u8

**Comment by freearhey** [comment]
Please update your request:

- the channel name can only include letters of the Latin alphabet
- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed?

**Comment by freearhey** [comment]
Yes
