### ISSUE TITLE
Add: TV+ [CL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3766]
### Channel Name

TV+

### Alternative Names (optional)

TVMás

### Country

CL

### Broadcast Area

c/CL

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.tvmas.tv/

### Logo

https://imgtr.ee/images/2023/05/24/wTxb0.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=TVPlus.cl
