### ISSUE TITLE
Edit: Telefe Neuquen [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3782]
### Channel ID (required)

TelefeNeuquen.ar

### NSFW

FALSE

### Closed

2023-01-31

### Replaced By

Canal7Neuquen.ar

### Notes

Replaced by #3781

**Comment by freearhey** [comment]
Please update your request:

- invalid channel ID

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
