### ISSUE TITLE
Add: Motori TV

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/database#3796]
### Channel Name

Motori TV

### Owners (optional)

Gruppo Primantenna

### Country

IT

### City (optional)

Piemonte

### Broadcast Area

c/IT

### Languages

ita

### Categories (optional)

auto

### NSFW

FALSE

### Website (optional)

https://motori.tv/

### Logo

https://i.imgur.com/p0CWi2T.png

### Notes

The logo on the site is https://motori.tv/wp-content/uploads/2023/05/LOGO-MTV-PER-SITO-1400x373.png
 though it is apparently too big for the issue. Still, I've included it since that's the only logo there is, apart from a darkened version with the same dimensions. 
The streaming link I got from this channel's website was https://5f22d76e220e1.streamlock.net:443/primantenna/primantenna/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- country code is incorrect
- language code is incorrect
- category name should be in lowercase
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Please update your request:

- country code must be in uppercase
- broadcast area code is incorrect
- language code is incorrect
- the link to the logo is required

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Please update your request:

- language code must be in lowercase
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
