### ISSUE TITLE
Add: TV Assembleia RN

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3806]
### Channel Name

TV Assembleia RN

### Country

BR

### City (optional)

Natal

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

legislative

### NSFW

FALSE

### Website (optional)

http://www.al.rn.gov.br/tvs

### Logo

https://yt3.googleusercontent.com/ytc/AGIKgqOClirOgkUdn6sr0KXxp98HAAVFagI9NteXQvD6=s176-c-k-c0x00ffffff-no-rj

### Notes

https://video01.logicahost.com.br/assembleiarn/assembleiarn/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
