### ISSUE TITLE
Remove: ElkisiTV.id

### ISSUE THREAD

**Issue by singkie** [iptv-org/database#3820]
### Channel ID (required)

ElkisiTV.id

### Reason (required)

Not a TV channel

### Notes

reference of the website info, i think it's not TV station

**Comment by freearhey** [comment]
Maybe the channel was just closed, because there is still a page with that name on the site: https://elkisi.com/official-elkisi-tv/

**Comment by freearhey** [comment]
Closed in favor of #3829
