### ISSUE TITLE
Add: UTV Brasil

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3822]
### Channel Name

UTV Brasil

### Owners (optional)

Cavomd Telecomunicações

### Country

BR

### City (optional)

Descalvado

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

2019-01-01

### Website (optional)

https://www.redeutv.com.br/

### Logo

https://img77.uenicdn.com/image/upload/v1583204387/business/a6f43916-2fc4-4e25-8eb3-fb9a757b1327.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=RedeUTV.br
