### ISSUE TITLE
Add: TV Camara Jahu

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3823]
### Channel Name

TV Camara Jahu

### Alternative Names (optional)

TV Câmara Jaú

### Country

BR

### City (optional)

Jau

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

legislative

### NSFW

FALSE

### Website (optional)

http://tv.camarajau.sp.gov.br/

### Logo

http://sv0.camarajau.sp.gov.br/logo.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked
- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
