### ISSUE TITLE
Add: TV Camara Taubate

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3825]
### Channel Name

TV Camara Taubate

### Alternative Names (optional)

TV Câmara Taubaté

### Country

BR

### City (optional)

Taubate

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

legislative

### NSFW

FALSE

### Website (optional)

https://www.camarataubate.sp.gov.br/index

### Logo

https://www.camarataubate.sp.gov.br/imagens_temp/logo_MzE2MzI0MTM1Mjk1MDQ=.png

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Can't do anything more about that
