### ISSUE TITLE
TV ID: StarSports1Tamil.in is missing

### ISSUE THREAD

**Issue by DPX911** [iptv-org/database#3827]
Hi Team, From Data csv file, I could see channel ID StarSports1Tamil.in is grouped under country India, Language Hindi. However, I could not find it enlisted in any category. Please assist. Thanks in Advance.

![Capture](https://github.com/iptv-org/database/assets/96830443/c3650aec-88cc-4617-bb0e-e0873d822a82)

**Comment by freearhey** [comment]
This database contains only a description of the channels. If you are looking for a link to a channel stream, it is better to write here: https://github.com/iptv-org/iptv/issues
