### ISSUE TITLE
Add: Pinguino TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3837]
### Channel Name

Pinguino TV

### Alternative Names (optional)

Pingüino TV

### Country

CL

### City (optional)

Punta Arenas

### Broadcast Area

c/CL

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://elpinguino.com/

### Logo

https://elpinguino.com/assets/img/logo-v3.png

### Notes

https://streaming.elpinguino.com:5391/live/EP.smil/playlist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=ElPinguinoTV.cl
