### ISSUE TITLE
Add: Canal Trece

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3838]
### Channel Name

Canal Trece

### Alternative Names (optional)

Canal 13

### Country

CO

### City (optional)

Bogota

### Broadcast Area

c/CO

### Languages

spa

### Categories (optional)

music

### NSFW

FALSE

### Website (optional)

https://canaltrece.com.co/

### Logo

https://pbs.twimg.com/profile_images/468573511573729280/qnzXHED7_400x400.jpeg

### Notes

https://canaltrece-live.logicideas.media/canaltrece-live/smil:live.smil/playlist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=Trece.co
