### ISSUE TITLE
Add: Tv Kesehatan

### ISSUE THREAD

**Issue by antosatriani** [iptv-org/database#3851]
### Channel Name

TV Kesehatan

### Owners (optional)

Kementerian Kesehatan Republik Indonesia

### Country

ID

### Broadcast Area

c/ID

### Languages

ind;eng

### Categories (optional)

lifestyle

### NSFW

FALSE

### Website (optional)

https://www.kemkes.go.id/

### Logo

https://i.imgur.com/IGIX3o8.jpg

**Comment by antosatriani** [comment]
Actualy this channel's category is health, but there is no match in database list. Now I have changed it to education;general. I hope it will be approved. ThankYou

**Comment by freearhey** [comment]
Usually channels about health fall into the `lifestyle` category.

**Comment by antosatriani** [comment]
Okay Sir. correction is done ! Thank You
