### ISSUE TITLE
Add: Pinwheel

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#3859]
### Channel Name

Pinwheel

### Owners (optional)

Warner Communications

### Country

US

### Broadcast Area

c/US

### Languages

eng

### NSFW

FALSE

### Launched (optional)

1977-12-01

### Closed (optional)

1979-04-01

### Replaced By (optional)

NickelodeonEast.us

### Logo

https://i.imgur.com/FiuT6l1.png

### Notes

QUBE Channel https://en.m.wikipedia.org/wiki/QUBE, later turned into nickelodeon

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by kaikyoofers** [comment]
Cannot do anything

**Comment by kaikyoofers** [comment]
Reopening request because i fixed the logo.
