### ISSUE TITLE
Add: SMG Dragon TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3867]
### Channel Name

SMG Dragon TV

### Alternative Names (optional)

东方卫视

### Owners (optional)

Shanghai Media Group

### Country

CN

### City (optional)

Shanghai

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1998-10-01

### Website (optional)

https://live.kankanews.com/huikan/

### Logo

https://p8.itc.cn/q_70/images03/20211219/2ecf92b9bfb94f35b90b2c8ba0bc8e00.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=DragonTV.cn
