### ISSUE TITLE
Add: DocuTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3871]
### Channel Name

DocuTV

### Alternative Names (optional)

上海纪实人文频道

### Owners (optional)

Shanghai Media Group

### Country

CN

### City (optional)

Shanghai

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

documentary

### NSFW

FALSE

### Launched (optional)

2020-01-01

### Website (optional)

https://live.kankanews.com/huikan/

### Logo

https://upload.wikimedia.org/wikipedia/zh/thumb/9/9d/Doc_Channel.jpg/220px-Doc_Channel.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=DocuChina.cn
