### ISSUE TITLE
Add: Chinese Hope TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3875]
### Channel Name

Chinese Hope TV

### Alternative Names (optional)

希望電視台

### Owners (optional)

Chinese Union Mission of Seventh-Day Adventist Church

### Country

HK

### City (optional)

Sha Tin District

### Broadcast Area

c/HK

### Languages

zho

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://chinesehope.tv/live.php

### Logo

https://www.tvchinese.net/uploads/tv/chinesehope.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=ChineseHopeTV.cn
