### ISSUE TITLE
Add: Pingvinukas [LT]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#3877]
### Channel Name

Pingvinukas

### Alternative Names (optional)

LoLo TV

### Owners (optional)

Teledistribution Baltic

### Country

LT

### Broadcast Area

s/LT

### Languages

lit;rus

### Categories (optional)

animation;kids

### NSFW

FALSE

### Website (optional)

http://www.lolotv.lv/

### Logo

http://www.teledistribution.ru/assets/cache/images/290x-pingv%C4%ABns_%D0%BB%D0%B8%D1%82%D0%B2%D0%B0.f23.jpg

### Notes

Channel stream link: https://venera.greenhosting.ru/LoLoLT/video.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=LoloTV.lv
