### ISSUE TITLE
Edit: Lolo TV [LV]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#3878]
### Channel ID (required)

LoloTV.lv

### Channel Name

Lolo TV

### Alternative Names

Pingvīns

### Owners

Teledistribution Baltic

### Languages

rus;lat

### Categories

animation;kids

### NSFW

FALSE

### Website

http://www.lolotv.lv/

### Logo

https://static.wikia.nocookie.net/logopedia/images/2/2a/LoloTV_logo_2019.png

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
> Please update your request:
> 
>     * logo URL must use the HTTPS protocol
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed!

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
> Please update your request:
> 
>     * logo is not loaded
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

It did.
