### ISSUE TITLE
Add: Pingviin [EE]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#3879]
### Channel Name

Pingviin

### Alternative Names (optional)

LoLo TV

### Owners (optional)

Teledistribution Baltic

### Country

EE

### Broadcast Area

s/EE

### Languages

est;rus

### Categories (optional)

animation;kids

### NSFW

FALSE

### Website (optional)

http://www.lolotv.lv/

### Logo

http://www.teledistribution.ru/assets/cache/images/290x-pingv%C4%ABns_%D1%8D%D1%81%D1%82%D0%BE%D0%BD%D0%B8%D1%8F.5b8.gif

### Notes

Channel stream link: https://venera.greenhosting.ru/LoLoEE/video.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=LoloTV.lv
