### ISSUE TITLE
Add: Multimania [RU]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#3880]
### Channel Name

Multimania

### Owners (optional)

ООО Теледистрибьюция

### Country

RU

### Broadcast Area

c/RU;c/EE;c/LV

### Languages

rus

### Categories (optional)

animation;kids

### NSFW

FALSE

### Launched (optional)

2015-04-30

### Website (optional)

http://www.multimania.lv

### Logo

https://picon.ml/multimania-lv.png

### Notes

Channel stream link: https://sirius.greenhosting.ru/MultimaniaRu/video.m3u8 and https://venera.greenhosting.ru/MultimaniaLV/video.m3u8

**Comment by freearhey** [comment]
Please update your request:

- subdivision code is incorrect
- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
Hmm... this channel have connection 

> Please update your request:
> 
>     * subdivision code is incorrect
> 
>     * broadcast area code is incorrect
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed.

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
> Please update your request:
> 
>     * logo is not loaded
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Changed to see.
