### ISSUE TITLE
Add: Kino 24 [RU]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#3881]
### Channel Name

Kino 24

### Alternative Names (optional)

Kino24

### Owners (optional)

ООО Теледистрибьюция

### Country

RU

### Broadcast Area

c/RU;c/EE;c/LV

### Languages

rus

### Categories (optional)

movies

### NSFW

FALSE

### Launched (optional)

2016-03-07

### Website (optional)

http://www.teledistribution.ru

### Logo

https://picon.ml/kino-24.png

### Notes

Channel stream link: https://sirius.greenhosting.ru/Kino24Ru/video.m3u8

**Comment by freearhey** [comment]
Please update your request:

- subdivision code is incorrect
- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
> Please update your request:
> 
>     * subdivision code is incorrect
> 
>     * broadcast area code is incorrect
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed.

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
> Please update your request:
> 
>     * logo URL must use the HTTPS protocol
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed again!

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
> Please update your request:
> 
>     * logo is not loaded
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Is fixed, to see logo.
