### ISSUE TITLE
Edit: Pro100TV [RU]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#3882]
### Channel ID (required)

Pro100TV.ru

### Owners

ООО Теледистрибьюция

### Broadcast Area

c/RU;c/EE;c/LV

### Languages

rus

### Categories

movies;entertainment;family;classic;animation

### NSFW

FALSE

### Launched

2009-10-01

**Comment by freearhey** [comment]
Please update your request:

- subdivision code is incorrect
- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
I'm updated.
