### ISSUE TITLE
Add: MBS News

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3885]
### Channel Name

MBS News

### Alternative Names (optional)

毎日放送

### Owners (optional)

MBS Media Holdings

### Country

JP

### City (optional)

Osaka City

### Broadcast Area

c/JP

### Languages

jpn

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.mbs.jp/news/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Mainichi_Broadcasting_System_logo.svg/140px-Mainichi_Broadcasting_System_logo.svg.png?20110904042013

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected again
