### ISSUE TITLE
Add: Gribu visu zināt [LV]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#3886]
### Channel Name

Gribu visu zinat

### Alternative Names (optional)

Хочу всё знать

### Owners (optional)

Teledistribution Baltic

### Country

LV

### Broadcast Area

c/LV;c/EE

### Languages

rus

### Categories (optional)

documentary;culture;education;kids;science;lifestyle

### NSFW

FALSE

### Website (optional)

https://movify.tv/

### Logo

https://kabeloperatori.neplpadome.lv/lv/assets/images/Programmu%20logo/hochuvse.png

### Notes

I can't find high quality logo in online.
Channel stream link: https://venera.greenhosting.ru/HochuVsjeZnat/video.m3u8

**Comment by freearhey** [comment]
Please update your request:

- the channel name can only include letters of the Latin alphabet

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
> Please update your request:
> 
>     * the channel name can only include letters of the Latin alphabet
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

I did change, I don't believe it yet.
