### ISSUE TITLE
Add: Fujian Culture & Sports Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3913]
### Channel Name

Fujian Culture & Sports Channel

### Alternative Names (optional)

文体频道

### Owners (optional)

Fujian Media Group

### Country

CN

### City (optional)

Fuzhou

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

culture;sports

### NSFW

FALSE

### Website (optional)

http://live.fjtv.net/typd/

### Logo

https://www.tvchinese.net/uploads/tv/fjtv9.jpg

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
