### ISSUE TITLE
Add:  Cartoons Plus

### ISSUE THREAD

**Issue by JohnyGR22** [iptv-org/database#3922]
### Channel Name

Cartoons Plus

### Network (optional)

Roku

### Owners (optional)

OTT Studio

### Country

US,UK

### Broadcast Area

Us

### Languages

eng

### Categories (optional)

Kids

### NSFW

FALSE

### Website (optional)

https://channelstore.roku.com/en-gb/details/c7381354b9bbb3c2b3ca2bd615aa56f6/cartoons-plus

### Logo

https://static.wixstatic.com/media/f23a07_3b7c0160895e455ba9ea5a36306d6c69~mv2.png/v1/fill/w_560,h_368,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Cartoons-Plus-product-suite.png

**Comment by freearhey** [comment]
Please update your request:

- country code is incorrect
- broadcast area code is incorrect
- category name should be in lowercase
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
