### ISSUE TITLE
Add: Colors Cineplex Superhits [IN] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3926]
### Channel Name

Colors Cineplex Superhits

### Country

IN

### Broadcast Area

c/IN

### Languages

hin

### Categories (optional)

movies

### NSFW

FALSE

### Logo

https://i.ibb.co/KbXhstz/Screenshot-20230610-130415.jpg

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * the size of the logo should not exceed 512x512px
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

fixed
