### ISSUE TITLE
Add: Desi Channel [IN] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#3927]
### Channel Name

Desi Channel

### Country

IN

### Broadcast Area

c/IN

### Languages

pan

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

http://desichannel.in/

### Logo

https://i.ibb.co/GkNXcLX/logo.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * the size of the logo should not exceed 512x512px
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed
