### ISSUE TITLE
Add: Aio Sport 2

### ISSUE THREAD

**Issue by barfin** [iptv-org/database#3952]
### Channel Name

Aio Sport 2

### Country

IR

### Broadcast Area

s/IR-23

### Languages

fas

### Categories (optional)

sports

### NSFW

FALSE

### Website (optional)

https://www.aionet.ir

### Logo

https://assets.aionet.ir/channels/100347

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by barfin** [comment]
> Please update your request:
> 
>     * broadcast area code is incorrect
> 
>     * language code is incorrect
> 
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

fixed
