### ISSUE TITLE
Add: Antenne Reunion

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3955]
### Channel Name

Antenne Reunion

### Alternative Names (optional)

Antenne Réunion

### Country

RE

### City (optional)

Saint-Denis

### Broadcast Area

c/RE

### Languages

fra

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.antennereunion.fr/direct

### Logo

https://play-lh.googleusercontent.com/zaCC74Dzucp7GrkTYATGR527244cIwn4xC4dBKrDmbpSbMiLtUyuFi_ACeJsHA0f3g

### Notes

https://live-antenne-reunion.zeop.tv/live/c3eds/antreunihd/hls_fta/antreunihd.m3u8?location=ZEOP01

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=AntenneReunion.fr
