### ISSUE TITLE
Add: Guangdong News Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3983]
### Channel Name

Guangdong News Channel

### Alternative Names (optional)

广东新闻频道

### Owners (optional)

Guangdong Radio and Television

### Country

CN

### City (optional)

Guangzhou

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.gdtv.cn/tvChannelDetail/43

### Logo

https://www.tvchinese.net/uploads/tv/gdxwpd.jpg

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
