### ISSUE TITLE
Add: Guangdong Public Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3984]
### Channel Name

Guangdong Public Channel

### Alternative Names (optional)

广东公共频道

### Owners (optional)

Guangdong Radio and Television

### Country

CN

### City (optional)

Guangzhou

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.gdtv.cn/tvChannelDetail/43

### Logo

https://www.tvchinese.net/uploads/tv/gdggpd.jpg

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=GuangdongPublic.cn
