### ISSUE TITLE
Add: GBA Satellite TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#3985]
### Channel Name

GBA Satellite TV

### Alternative Names (optional)

大湾区卫视

### Owners (optional)

Guangdong Radio and Television

### Country

CN

### City (optional)

Guangzhou

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.gdtv.cn/tvChannelDetail/43

### Logo

https://www.tvchinese.net/uploads/tv/greaterbayarea.jpg

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected again
