### ISSUE TITLE
Add: Guangdong Economy Science and Education Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4013]
### Channel Name

Guangdong Economy Science and Education Channel

### Alternative Names (optional)

广东经济科教频道

### Owners (optional)

Guangdong Radio and Television

### Country

CN

### City (optional)

Guangzhou

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

education

### NSFW

FALSE

### Website (optional)

https://www.gdtv.cn/tvChannelDetail/43

### Logo

https://upload.wikimedia.org/wikipedia/zh/8/8d/GRT_Economy_and_Science_%26_Technology_logo_2019.png

**Comment by freearhey** [comment]
Please update your request:

- commas cannot be used in the channel name

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Updated
