### ISSUE TITLE
Add: LPPL Persada FM

### ISSUE THREAD

**Issue by antosatriani** [iptv-org/database#4019]
### Channel Name

LPPL Persada FM

### Alternative Names (optional)

Persada FM Blitar

### Country

ID

### Subdivision (optional)

ID-JI

### City (optional)

Blitar Jawa Timur

### Broadcast Area

s/ID-JI; s/ID-JT

### Languages

ind

### Categories (optional)

general;music;news;culture

### NSFW

FALSE

### Website (optional)

https://persadablitar.id

### Logo

https://i.imgur.com/KyQdrHE.png

### Notes

LPPL Persada FM is a radio station in Blitar that provides the latest news, entertaintment and podcast

**Comment by freearhey** [comment]
In this database we store only the description of TV channels.
