### ISSUE TITLE
Add: Lingnan Opera Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4020]
### Channel Name

Lingnan Opera Channel

### Alternative Names (optional)

岭南戏曲频道

### Owners (optional)

Guangdong Radio and Television

### Country

CN

### City (optional)

Guangzhou

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

music

### NSFW

FALSE

### Website (optional)

https://www.gdtv.cn/tvChannelDetail/43

### Logo

https://www.tvchinese.net/uploads/tv/gdxwpd.jpg

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
