### ISSUE TITLE
Add: Real Estate Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4021]
### Channel Name

Real Estate Channel

### Alternative Names (optional)

广东房产频道

### Owners (optional)

Guangdong Radio and Television

### Country

CN

### City (optional)

Guangzhou

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

business

### NSFW

FALSE

### Website (optional)

https://www.gdtv.cn/tvChannelDetail/43

### Logo

https://image0.lietou-static.com/bg_white_222x222/5bfe93b974719d9f609aacf903a.png

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
