### ISSUE TITLE
Add: Dongguan Comprehensive News Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4031]
### Channel Name

Dongguan Comprehensive News Channel

### Alternative Names (optional)

东莞广播电视台

### Country

CN

### City (optional)

Dongguan

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://dgrtv.sun0769.com/index.php/online2/4

### Logo

https://www.tvchinese.net/uploads/tv/dgtv1.jpg

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
