### ISSUE TITLE
Add:  Essaida FM

### ISSUE THREAD

**Issue by oussamame07** [iptv-org/database#4033]
### Channel Name

Essaida FM

### Country

TN

### Broadcast Area

348

### Languages

Arabe

### Categories (optional)

Culture

### NSFW

FALSE

### Website (optional)

https://www.essaidafm.com/ar/

### Logo

https://we.tl/t-FsVDTOVY4K

### Notes

thank you

**Comment by freearhey** [comment]
In this database we store only the description of TV channels.
