### ISSUE TITLE
Add: ESSAIDA TV

### ISSUE THREAD

**Issue by oussamame07** [iptv-org/database#4044]
### Channel Name

Essaida TV

### Country

TN

### Broadcast Area

r/ARAB

### Languages

TN-area

### NSFW

FALSE

### Website (optional)

https://www.essaidafm.com

### Logo

https://imgur.com/c5Q7FLB

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- language code is incorrect
- category name should be in lowercase
- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
