### ISSUE TITLE
Add: Nova TV Star

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/database#4047]
### Channel Name

Nova TV Star

### Country

PE

### Subdivision (optional)

PE-LOR

### City (optional)

Yurimaguas

### Broadcast Area

s/PE-LOR

### Languages

spa

### NSFW

FALSE

### Website (optional)

http://radionovastar.com/tv-en-vivo/

### Logo

https://i.imgur.com/CN2j8S3.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by sguinetti** [comment]
Updated.
