### ISSUE TITLE
Edit: EnerGeekAnimate.cl (old) to CCPRadio.cl

### ISSUE THREAD

**Issue by JustSammyV** [iptv-org/database#4057]
### Channel ID (required)

EnerGeekAnimate.cl

### Channel Name

CCP Radio

### Network

EnerGeek

### Owners

EnerGeek

### Country

CL

### Subdivision

CL-RM

### Languages

spa

### Categories

music

### NSFW

FALSE

### Website

https://ccpradio.cl

### Logo

https://cdn.energeek.cl/logos/CCPRadio-2023.png

**Comment by freearhey** [comment]
Please update your request:

- subdivision code is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by JustSammyV** [comment]
Updated. Please re-check.
