### ISSUE TITLE
Update TVS logos (Multiple channels)

### ISSUE THREAD

**Issue by cr0op** [iptv-org/database#406]
Image links in each channel name

1. [TVS Hi Tops](https://www.watchyour.tv/epg/channellogos/tvs-hi-tops.png) (TVSHiTops.us)
2. [TVS Pinball Network](https://www.watchyour.tv/epg/channellogos/tvs-cartoon-network.png) (TVSPinballNetwork.us)
3. [TVS Cipher Network](https://www.watchyour.tv/epg/channellogos/tvs-mystery-network.png) (TVSCipherNetwork.us)
4. [TVS Film Noir Network](https://www.watchyour.tv/epg/channellogos/tvs-film-noir-network.png) (TVSFilmNoirNetwork.us)
5. [TVS Front Page Detective](https://www.watchyour.tv/epg/channellogos/tvs-front-page-detective-.png) (TVSFrontPageDetective.us)
6. [TVS Hollywood History](https://www.watchyour.tv/epg/channellogos/tvs-hollywood-history.png) (TVSHollywoodHistory.us)
9. [TVS Nostalgia](https://www.watchyour.tv/epg/channellogos/tvs-nostalgia.png) (TVSNostalgia.us)
10. [TVS Pet Parade Network](https://www.watchyour.tv/epg/channellogos/pet-parade-network.png) (TVSPetParadeNetwork.us)
11. [TVS Quiz Show Network](https://www.watchyour.tv/channels/logo/tvs-game-show-network.jpg) (TVSQuizShowNetwork.us)
12. [TVS Rare Collectibles](https://www.watchyour.tv/epg/channellogos/rare-collectibles-televison.png) (TVSRareCollectibles.us)

**Comment by freearhey** [comment]
Updated in https://github.com/iptv-org/database/commit/a9565fa445beeb29285dcd2670b2471beca99267
