### ISSUE TITLE
Direct Link for Google Sheet

### ISSUE THREAD

**Issue by Talon555** [iptv-org/database#414]
Hello Guys
Please, share with us the direct link for opening directly in Google Sheet
Thanks in advance

**Comment by freearhey** [comment]
There is no such link. You need to download the file first and then open it in Google Sheet.

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#how-to-add-a-channel-to-the-database-or-edit-its-description

**Comment by Talon555** [comment]
Ok
Its possible to get directly here the downloadable link for the entire database ?
Please

**Comment by Talon555** [comment]
> There is no such link. You need to download the file first and then open it in Google Sheet.
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#how-to-add-a-channel-to-the-database-or-edit-its-description

Ok
Its possible to get directly here the downloadable link for the entire database ?
Please

**Comment by freearhey** [comment]
This link is right on the main repository page.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/7253922/190278897-dc79c83e-634b-4979-ac24-0d1741a31260.png">
