### ISSUE TITLE
Add: Rakyat Bengkulu Televisi [ID] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#4226]
### Channel Name

Rakyat Bengkulu Televisi

### Alternative Names (optional)

RBTV

### Country

ID

### City (optional)

Bengkulu

### Broadcast Area

c/ID

### Languages

ind

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://rakyatbengkulu.disway.id/

### Logo

https://i.ibb.co/DCNZyPH/RBTV-Bengkulu.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=RakyatBengkuluTV.id
