### ISSUE TITLE
Add: Radio Isla TV [PR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#4238]
### Channel Name

Radio Isla TV

### Country

PR

### City (optional)

San Juan

### Broadcast Area

c/PR

### Languages

spa

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://radioisla.tv/

### Logo

https://i.ibb.co/PDThYr5/Logo-Radio-Isla.png

**Comment by freearhey** [comment]
Are you sure that the name of the channel is not "Radio Isla TV"? 

https://radioisla.tv/radio-isla-tv/

**Comment by Carlinhos027** [comment]
> Are you sure that the name of the channel is not "Radio Isla TV"?
> 
> https://radioisla.tv/radio-isla-tv/

Yeah, you're right. Sorry!
