### ISSUE TITLE
Edit: ABC (WLPG-DT1) Miami, FL

### ISSUE THREAD

**Issue by CheddarRufflez** [iptv-org/database#4306]
### Channel ID (required)

https://16live00.akamaized.net/ABC_EAST/index.m3u8

### Channel Name

ABC (WLPG-DT1) Miami, FL

### Network

ABC

### Owners

ABC

### Country

US

### City

Miami

### Broadcast Area

r/AMER;c/US

### Languages

eng;esp

### Categories

news

### NSFW

FALSE

### Launched

1961-11-20

### Notes

Channel is broken :(  It just gives me an error every time I try to load it

**Comment by freearhey** [comment]
This repository only contains channel descriptions. To report a broken link it is better to use this form: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%F0%9F%9B%A0+broken+stream&projects=&template=-----broken-stream.yml&title=Broken%3A+
