### ISSUE TITLE
Add: Radio 1 [BE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#4323]
### Channel Name

Radio 1 

### Owners (optional)

VRT

### Country

BE

### Broadcast Area

c/BE

### Languages

nld

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://radio1.be/

### Logo

https://i.ibb.co/pwCs0YY/512px-VRT-Radio-1-logo-svg.png

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * language code is incorrect
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Done
