### ISSUE TITLE
Add: Hokkaido News UHB

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4350]
### Channel Name

Hokkaido News UHB

### Alternative Names (optional)

北海道ニュース UHB

### Owners (optional)

Hokkaido Cultural Broadcasting

### Country

JP

### City (optional)

Sapporo

### Broadcast Area

c/JP

### Languages

jpn

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.uhb.jp/news/

### Logo

https://i.ytimg.com/an/pQs_warGhUzJhBdwLfF34g/featured_channel.jpg?v=5fd1ffd6

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
