### ISSUE TITLE
Add: Al-Furqon TV

### ISSUE THREAD

**Issue by favianrizqulloh** [iptv-org/database#4374]
### Channel Name

Al-Furqon TV

### Alternative Names (optional)

Al-Furqon TV Gresik

### Network (optional)

ARTVISI

### Owners (optional)

Dakwah dan Sosial Pondok Pesantren Al-Furqon Al-Islami Gresik

### Country

ID

### Subdivision (optional)

ID-JI

### City (optional)

Gresik

### Broadcast Area

r/SEA;c/ID;s/ID-JI

### Languages

ind;jav;ara

### Categories (optional)

religious;family

### NSFW

FALSE

### Website (optional)

https://daksos.alfurqongresik.com/

### Logo

https://i.imgur.com/ZhmsbCJ.png

### Notes

**Al-Furqon TV - Islamic Da'wah & Inspiration Educational Channel**
Broadcasting via the Telkom 4 Satellite from the northern tip of Gresik City, East Java, Ma'had Al-Furqon Al-Islami Gresik presents Islamic Da'wah TV which presents programs full of advice, inspiration and scientific insights that are useful for the community.

Let's watch impressions from our programs, hopefully it will be a washilah in the spread of ahlussunnah wal jamaa'ah da'wah in all corners of the world.

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by favianrizqulloh** [comment]
Updated

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by favianrizqulloh** [comment]
Corrected.
