### ISSUE TITLE
Add: PIK TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4382]
### Channel Name

PIK TV

### Alternative Names (optional)

ПИК TV

### Country

BG

### City (optional)

Sofia

### Broadcast Area

c/BG

### Languages

bul;rus

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://pik.bg/%D0%BF%D0%B8%D0%BA-tv-cat151.html

### Logo

https://pik.bg/box/img/pik_tv_logo.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=PIKTV.bg
