### ISSUE TITLE
Add: VRT Radio 1

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4386]
### Channel Name

VRT Radio 1

### Owners (optional)

VRT

### Country

BE

### City (optional)

Brussels

### Broadcast Area

c/BE

### Languages

nld

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://radio1.be/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/VRT_Radio_1_logo.svg/512px-VRT_Radio_1_logo.svg.png?20181107182958

**Comment by Carlinhos027** [comment]
Already added as "Radio1.be"
