### ISSUE TITLE
Add: VRT Radio 2

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4387]
### Channel Name

VRT Radio 2

### Owners (optional)

VRT

### Country

BE

### City (optional)

Brussels

### Broadcast Area

c/BE

### Languages

nld

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://radio2.be/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/VRT_Radio_2_%282022%29.svg/150px-VRT_Radio_2_%282022%29.svg.png

**Comment by Carlinhos027** [comment]
Already added as "Radio2.be"
