### ISSUE TITLE
Add: 770 Live

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/database#4414]
### Channel Name

770 Live

### Alternative Names (optional)

770Live.com

### Country

US

### Subdivision (optional)

NY

### City (optional)

Brooklyn

### Broadcast Area

NY

### Languages

English; hebrew

### Categories (optional)

Religious

### NSFW

FALSE

### Website (optional)

https://www.770live.com/

### Logo

https://www.770live.com/Heb770/Images/Rebbe_mikdosh.jpg

### Notes

Jewish Synagogue live stream.

**Comment by freearhey** [comment]
Please update your request:

- subdivision code is incorrect
- broadcast area code is incorrect
- language code is incorrect
- category name should be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
