### ISSUE TITLE
Add: Sports News Highlights

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4444]
### Channel Name

Sports News Highlights

### Alternative Names (optional)

SNHtv

### Owners (optional)

Bridge News LLC

### Country

US

### Subdivision (optional)

US-MI

### City (optional)

Cadillac

### Broadcast Area

c/US

### Languages

eng

### Categories (optional)

news;sports

### NSFW

FALSE

### Website (optional)

https://sports.newsnetmedia.com/

### Logo

https://play-lh.googleusercontent.com/9w-Zd77j2DRRcviMIXebnKknar_E1Ykj0a42TAFFX6xmpHKMi_v4yp2w5_fqAm7GvU0

### Notes

https://amg01756-newsnet-sportsnewshigh-ono-2rbfq.amagi.tv/playlist/amg01756-newsnet-sportsnewshigh-ono/cb573b1c65716c909bc33778d1f94382bb7b3dcb0e6c886470af4a9765d97800dbe8ae84ae5b910c4c9e1fc061017d360439cd1dd56c49c1da71b813727616749886b262c9ee475ae98710282ab27a1e50fe0f05a67c1177dfe60247d46de7375551ac5a6a5531d4ea50ab6b50c6d50e967e28def8c0693b740f429c5f5bb0a55fa7ade45a4cd966858b281fc16f07c5be78f3b669dbfca528eb2cfb03fb05a7b3a1df900ed3c6d10cea13ed260c67376f95f215f9a36f93eab6481ab94e056344228cc492fa5d728249572e9495a18d40cf3fefaa00be4d12e179f22685349925ad0ca9f34bd2c1d1b570640988e57844188dc0fafd915232b975b5a6e0d90110f39c265d77e54cfb071415b5a7b77ee8c21185f82295a4561339cd9437f7f7d8b1ca80a16bbf00f5ead1c2432820620011c848b1a57dc920cb79abd7614d36277688aa79e5a5fc611d4715ffea37d51708f7d88493cf0f49a60a7168cd50f57a2649f319492692479e9b387fc73318894751913207a572d0990fd098f6c05c4ddfb8c646ec21e6b678be9c689b480c752390d71372601601ba826109206bfc46ebddd9e4791d72809da7cce56314261a326d21aeb8991af58fc43a5317d1431962611e139a01a405b56a7b251ee53ff0893659a05c614796a63b4e146b92d8a3be84d9c457b071c7bd915345097c539112260351fe93d72197504a7a6913870b7451cf6b3028d8b0f9c9b8a34bf1b141f042087e76d6cf07530044726013e9fc02bd6cc7a33198b8ef63e1cabf0c2ff4541caa8dfcaabe4fd9afe7e44e0191ae566b1ffdb109e403e0438ab651e5fc7fcaa45d463d31455acb8d558532d139105149e84a9e4e1170e379f9ee8b244ef53495f3651d496e7a196b53642503f2bfbf072e2cdfee628e38977fc81d5add2d1a67a7f28989498b80283c7f1141a8a5d982aecb4c24c57cfb7bdd6f395636671eccc322e38fbef2b5d22104409181a242bfae9f928cf8fe662f5b2260c081685c798e72abcc1fb7f9463cfd9fd1b48a3cd925ab759c81b525eb73f29bed5efec1cdafbb511e4c5f51f3d9b8ab4489f25a37ce11b17a24169885f3e725aa8ace6056de1db1d5493ed47b143ae4a4e10dc427b99c480cee956c5fda6c728ca0c82f12cc2bb033701ad5c892652fc0d305f01cc2c209a985248ae872bf2aa7c89242125828/197/1920x1080_5252412/index.m3u8

**Comment by freearhey** [comment]
Please update your request:

- commas cannot be used in the owner name

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
