### ISSUE TITLE
Add: WOTM-LD

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4445]
### Channel Name

WOTM-LD1

### Owners (optional)

WOTM LLC

### Country

US

### Subdivision (optional)

US-AL

### City (optional)

Montevallo

### Broadcast Area

s/US-AL

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1996-11-15

### Website (optional)

https://wotm.tv/wotm-live/

### Logo

https://wotm.tv/wp-content/uploads/2023/03/WOTM-Blue-300x86.png

### Notes

https://2-fss-2.themediacdn.com/pl_120/206412-3179692-1/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- commas cannot be used in the owner name

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
