### ISSUE TITLE
Add: FOX 7 News

### ISSUE THREAD

**Issue by NotjaphyrbotTV** [iptv-org/database#4506]
### Channel Name

FOX 7 News

### Alternative Names (optional)

_KTBC_

### Network (optional)

FOX

### Owners (optional)

Fox Television Stations; NW Communications of Austin, Inc.

### Country

US

### City (optional)

Austin

### Broadcast Area

r/<512>

### Languages

eng

### Categories (optional)

News

### NSFW

FALSE

### Website (optional)

https://www.fox7austin.com/

### Logo

https://yt3.googleusercontent.com/RI_Y_U9rwHVcACtGhGQFC_ag0ztuWRrXzMnhgkKtiYahML17hGt3lgkba-6VBtOg7evOZJzPtQ=s900-c-k-c0x00ffffff-no-rj

### Notes

Broadcast link: https://tubitv.com/live/555112/fox-7-austin

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=name:KTBC
