### ISSUE TITLE
Edit: BT Sports (UK) has now become TNT Sports (UK) 

### ISSUE THREAD

**Issue by ginjaninja456** [iptv-org/database#4565]
### Channel ID (required)

BT Sport 1/2/3

### Channel Name

TNT Sports 1/2/3

### Country

UK

### NSFW

FALSE

### Notes

BT Sport (UK) has now become TNT Sports (UK), is there any way the channel names & icons can be updated to reflect this?

I have looked at how to edit this myself but I'm not sure how! Thanks

**Comment by freearhey** [comment]
Please update your request:

- invalid channel ID

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by niallobr** [comment]
@freearhey is the info below ok? If not I will attempt to compile all the data in CONTRIBUTING.md format or do the CSV option at some point. I don't have time at the moment to fetch logos etc.

**Old data**

### Channel ID (required)

BTSport1.uk
BTSport2.uk
BTSport3.uk
BTSport4.uk
BTSport5.uk
BTSport6.uk
BTSport7.uk
BTSport8.uk
BTSport9.uk
BTSport10.uk
BTSportBoxOffice.uk
BTSportBoxOffice2.uk
BTSportUltimate.uk

### Channel Name

BT Sport 1
BT Sport 2
BT Sport 3
BT Sport 4
BT Sport 5
BT Sport 6
BT Sport 7
BT Sport 8
BT Sport 9
BT Sport 10
BT Sport Box Office UK
BT Sport Box Office 2 UK
BT Sport Ultimate

**New data**

### Channel ID (required)

TNTSports1.uk
TNTSports2.uk
TNTSports3.uk
TNTSports4.uk
TNTSports5.uk
TNTSports6.uk
TNTSports7.uk
TNTSports8.uk
TNTSports9.uk
TNTSports10.uk
TNTSportsBoxOffice.uk
TNTSportsBoxOffice2.uk
TNTSportsUltimate.uk

### Channel Name

TNT Sports 1
TNT Sports 2
TNT Sports 3
TNT Sports 4
TNT Sports 5
TNT Sports 6
TNT Sports 7
TNT Sports 8
TNT Sports 9
TNT Sports 10
TNT Sports Box Office UK
TNT Sports Box Office 2 UK
TNT Sports Ultimate
