### ISSUE TITLE
Add: RTV Pendimi [CH/AL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#4588]
### Channel Name

RTV Pendimi

### Country

CH

### Broadcast Area

c/CH;c/AL

### Languages

sqi

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://www.rtvpendimi.com/

### Logo

https://i.ibb.co/tD48GMD/RTV-Pendimi.png

### Notes

http://live.rtvpendimi.com:8081/hls/RTVPendimi/index.m3u8 (720p)

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * language code is incorrect
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed
