### ISSUE TITLE
Add: RTV Islam [CH/AL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#4596]
### Channel Name

RTV Islam

### Country

CH

### Broadcast Area

c/CH;c/AL

### Languages

sqi

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://rtvislam.com/

### Logo

https://i.ibb.co/LSJqLJw/RTV-LOGO.png

### Notes

https://protokolldns.xyz/rtvislamweebstdkksdfsdjkd/index.m3u8 (1080p)

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * language code is incorrect
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed
