### ISSUE TITLE
Add: Pluto TV More Star Trek

### ISSUE THREAD

**Issue by nabeelr** [iptv-org/database#4599]
### Channel Name

More Star Trek

### Network (optional)

Pluto TV

### Country

US, CA

### Broadcast Area

s/EN-US;s/EN-CA

### Languages

eng

### Categories (optional)

series

### NSFW

FALSE

### Logo

https://webtech-web-blu-assets.pluto.tv/assets/images/favicon/large-2799d0f684129fdce330463c1dec2c98.png

### Notes

Can't find a channel specific logo.

**Comment by freearhey** [comment]
Please update your request:

- country code is incorrect
- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by nabeelr** [comment]
The information is correct. I don't understand the comment or why this ticket was closed.

**Comment by freearhey** [comment]
__Country__

Country code from which the channel is transmitted. A list of all supported countries and their codes can be found in [data/countries.csv](data/countries.csv)

__Broadcast Area__

List of codes describing the broadcasting area of the channel separated by `;`. Any combination of `r/<region_code>`, `c/<country_code>`, `s/<subdivision_code>`.

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
