### ISSUE TITLE
Add: Pluto TV Frasier (US)

### ISSUE THREAD

**Issue by nabeelr** [iptv-org/database#4600]
### Channel Name

Frasier

### Network (optional)

Pluto TV

### Country

US

### Broadcast Area

c/US

### Languages

eng

### NSFW

FALSE

### Logo

https://images.pluto.tv/channels/62f4f90e39183b000769f12b/colorLogoPNG.png

**Comment by freearhey** [comment]
Please update your request:

- country code is incorrect
- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by nabeelr** [comment]
sorry, how was this information incorrect? this should all be correct.

**Comment by freearhey** [comment]
__Country__

Country code from which the channel is transmitted. A list of all supported countries and their codes can be found in [data/countries.csv](data/countries.csv)

__Broadcast Area__

List of codes describing the broadcasting area of the channel separated by `;`. Any combination of `r/<region_code>`, `c/<country_code>`, `s/<subdivision_code>`.

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by nabeelr** [comment]
I read the document again, and it seems like I filled it correctly.

The stream is in English, in Canada and in the US.

**Comment by nabeelr** [comment]
Could I get some clarification on this? What am I doing wrong here? I've got a few channels is like to add, and this is a big barrier to bring able to contribute them.

**Comment by BellezaEmporium** [comment]
s/EN-US;s/EN-CA should be c/US;c/CA

You've used a *subdivision* pattern, while giving us countries.

To specify the broadcast area of a channel by their country, please use the "c/" suffix, as per https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels.

Subdivisions are there to say that the current channel is broadcasted in a region/state *only*.

US, CA should be split into two separate additions. One for the USA, one for Canada.

We do not accept multiple countries as an answer. This is to prevent having different conflicting feeds for the same channel. Especially in the case of Pluto TV, i'm pretty sure the link for both channels in the US and in Canada are different.

**Comment by nabeelr** [comment]
Ahh, thanks for this detail! 

`US, CA should be split into two separate additions. One for the USA, one for Canada.`

Ahh, I'll keep that in mind for the future.

`Especially in the case of Pluto TV, i'm pretty sure the link for both channels in the US and in Canada are different.`

In this case, I know this link works for both in the US and Canada because I tested it while in both countries. It is the same link but, strangely enough, you do get served different ads during the break, so I imagine the server does do some geo-locating based on the connecting users IP address. (though ads are rare... up here in canada anyways, and you usually just get served the pluto banner)

You can verify this via a VPN.


Would you like me to delete and re-create this entry, or should I just edit it?

**Comment by BellezaEmporium** [comment]
> Ahh, thanks for this detail! I really appreciate it.
> 
> `US, CA should be split into two separate additions. One for the USA, one for Canada.`
> 
> Ahh, I'll keep that in mind for the future.
> 
> `Especially in the case of Pluto TV, i'm pretty sure the link for both channels in the US and in Canada are different.`
> 
> In this case, I know this link works for both in the US and Canada because I tested it while in both countries. It is the same link but, strangely enough, you do get served different ads during the break, so I imagine the server does do some geo-locating based on the connecting users IP address. (though ads are rare... up here in canada anyways, and you usually just get served the pluto banner)
> 
> You can verify this via a VPN.
> 
> 
> Would you like me to delete and re-create this entry, or should I just edit it?

It would be best to just edit your current entry, and add another one for Canada.

**Comment by nabeelr** [comment]
Done. Thanks for your help @BellezaEmporium I really appreciate it.

I Added #12440 to compliment this entry. Please let me know if there's anything I need to fix.

**Comment by BellezaEmporium** [comment]
Made a few changes : 

- Pluto TV calls it "Frasier" only. Keeping the Pluto TV in Network is enough.
- Correct logo
