### ISSUE TITLE
Add: Kix

### ISSUE THREAD

**Issue by AzeemHadzrie** [iptv-org/database#463]
### Channel Name

Kix

### Network (optional)

Celestial Tiger Entertainment

### Country

HK

### Broadcast Area

c/HK

### Languages

eng

### NSFW

FALSE

### Launched (optional)

2009-08-01

### Website (optional)

kix-tv.com

### Logo

https://en.wikipedia.org/wiki/File:KIX_logo.svg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=kix
