### ISSUE TITLE
Add: Ramogi TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4642]
### Channel Name

Ramogi TV

### Country

KE

### City (optional)

Nairobi

### Broadcast Area

c/KE;c/TZ;c/UG

### Languages

luo

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.citizen.digital/tv/ramogi-tv-19

### Logo

https://i.ytimg.com/vi/hQgTTvf0xfc/mqdefault.jpg

### Notes

https://citizentv.castr.com/5ea49827ff3b5d7b22708777/live_9b761ff063f511eca12909b8ef1524b4/index.m3u8

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

<img width="1418" alt="image" src="https://github.com/iptv-org/database/assets/7253922/38ed5bc0-aa43-42fe-a0b0-9de66315c7a1">


https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Hopefully that fixed it
