### ISSUE TITLE
Edit: Nazali's HDTV

### ISSUE THREAD

**Issue by Patrick3101** [iptv-org/database#4645]
### Channel ID (required)

NazalisHDTV.CG

### Channel Name

Nazali's HDTV

### Network

General

### Country

CG

### Subdivision

CG-BZV

### City

Brazzaville

### Broadcast Area

CG-BZV

### Languages

Français

### Categories

General

### NSFW

FALSE

### Launched

2023-02-01

### Website

https://nazalismedia.fr

### Logo

https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=332,fit=crop,q=95/YKbPoklZwxsGljGl/logo-nazalis-orange-m7V8VewXDkhaa0V6.png

### Notes

Mon lien de streaming a changé et donc je souhaiterai que le nouveau lien soit pris en compte pour que la chaine soit répertoriée dans les chaines IPTV.

**Comment by freearhey** [comment]
Please update your request:

- invalid channel ID
- broadcast area code is incorrect
- language code is incorrect
- category name is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Patrick3101** [comment]
C'est quoi le ID de la chaine ?

**Comment by freearhey** [comment]
Author blocked for spamming.
