### ISSUE TITLE
Edit: 

### ISSUE THREAD

**Issue by Patrick3101** [iptv-org/database#4649]
### Channel ID (required)

NazalisHDTV.CG

### Channel Name

Nazali's HDTV

### Country

CG

### Subdivision

CG-BZV

### City

Brazzaville

### Broadcast Area

CG-BZV

### Languages

Fra

### Categories

general

### NSFW

FALSE

### Launched

2023-02-01

### Website

https://nazalismedia.fr

### Logo

https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=332,fit=crop,q=95/YKbPoklZwxsGljGl/logo-nazalis-final-ii-A852yVLVx0ujW9Wn.png

### Notes

Etant donné que j'ai changé de serveur, je souhaite donc que le nouveau soit pris en charge.

**Comment by freearhey** [comment]
Duplicate of #4645

**Comment by Patrick3101** [comment]
Je devine que c'est la même erreur commise sur le #4645. N'y a-t-il pas des gens qui peuvent nous aider à modifier une chaîne sans avoir à rencontrer ces problèmes ?

**Comment by freearhey** [comment]
You can edit your request to match the [guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels) at any time.

<img width="240" alt="image" src="https://github.com/iptv-org/database/assets/7253922/7c56883e-7528-4f90-9912-3f0c3d04f397">
