### ISSUE TITLE
Add: SPI LEBANON

### ISSUE THREAD

**Issue by saidghzayel** [iptv-org/database#4674]
### Channel Name

SPI Lebanon

### Alternative Names (optional)

SPI

### Country

LB

### Subdivision (optional)

LB-BA

### Broadcast Area

c/LB

### Languages

ara

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

2020-06-01

### Website (optional)

https://spilebanon.com

### Logo

https://spilebanon.com/img/spi-logo.jpg

### Notes

M3U8 Streaming URL : http://stream.spilebanon.com:1935/live/myStream/playlist.m3u8

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by saidghzayel** [comment]
> Please update your request:
> 
> * language code is incorrect
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
Language Code : ara 

i should to request new ?

**Comment by freearhey** [comment]
It would be better if you just update the current request.

<img width="218" alt="image" src="https://github.com/iptv-org/database/assets/7253922/eb2443d6-5854-41fc-b75d-e5423bcb6476">

**Comment by freearhey** [comment]
Please update your request:

- language codes must be separated by `;`

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by saidghzayel** [comment]
> Please update your request:
> 
> * language codes must be separated by `;`
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Done
