### ISSUE TITLE
Add: Yanbian Satellite TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4675]
### Channel Name

Yanbian Satellite TV

### Alternative Names (optional)

 延边卫视

### Country

CN

### City (optional)

Yanji

### Broadcast Area

c/CN

### Languages

zho

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

2006-08-10

### Website (optional)

https://www.tvchinese.net/uploads/tv/yanbiantv.jpg

### Logo

http://www.yb983.com/cys/index.html

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=YanbianSatelliteTV.cn
