### ISSUE TITLE
Add:  Clover (AL)

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/database#4678]
### Channel Name

Clover

### Country

AL

### Broadcast Area

Albania

### Languages

sqi

### Categories (optional)

kids

### NSFW

FALSE

### Launched (optional)

N/A

### Closed (optional)

N/A

### Logo

https://static.wikia.nocookie.net/international-entertainment-project/images/9/97/Clover_logo.webp/revision/latest/scale-to-width-down/120?cb=20230804040919

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
