### ISSUE TITLE
Remove: The Voice Bulgaria

### ISSUE THREAD

**Issue by dicheto** [iptv-org/database#4709]
### Channel ID (required)

TheVoiceTV.bg

### Reason (required)

Other

### Notes

This TV channel is paid and the provided link is from bypassing bulgarian TV operator service.

**Comment by freearhey** [comment]
This repository contains only a description of the channels. 

To request removal of a link from a playlist, you need to fill out this [form](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%E2%9D%8C+removal+request&projects=&template=--removal-request.yml&title=Remove%3A+).
