### ISSUE TITLE
Add: TV Besa

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4710]
### Channel Name

TV Besa

### Alternative Names (optional)

Radio dhe Televizioni Besa

### Country

XK

### City (optional)

Prizren

### Broadcast Area

c/XK

### Languages

alb

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://rtvbesa.com/live/

### Logo

https://cdn-0.tvprofil.com/cdn/100x40/4/img/kanali-logo/besa-logo.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=RTVBesa.xk
