### ISSUE TITLE
Add: The Beach Channel

### ISSUE THREAD

**Issue by vinchu734** [iptv-org/database#4729]
### Channel Name

The Beach Channel

### Country

US

### City (optional)

Miami

### Broadcast Area

s/US-FL

### Languages

eng

### NSFW

FALSE

### Website (optional)

https://www.thebeachchannel.tv

### Logo

https://images.squarespace-cdn.com/content/v1/5bbd189f840b16624eaaaa54/1564164558355-89YX9OANPEHYV71HWPT1/BC+LOGO_CH5_REVISED.png?format=1500w

### Notes

I hope I didn't do any mistake, if you need anything let me know.
the m3u link is 
https://cf-live29e5f8c.lwcdn.com/live/fallback/014dc067-4922-4168-bdcd-5278589269ed/playlist.m3u8
I found it very easy just doing a web page source. It is completely free and legal to watch on the website or other places too.
Thanks a lot!

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=TheBeachChannel.us

**Comment by vinchu734** [comment]
I see it in that database thing, but it doesn’t show up in the playlist… I have the global one and it’s not there… and I just used the US one in case it was there and it doesn’t show either. Could someone check the link for that? Thanks!

**Comment by freearhey** [comment]
This repository only stores channel descriptions.

If you want to add a link to a channel broadcast to playlist, you should leave your request here: https://github.com/iptv-org/iptv/issues

**Comment by vinchu734** [comment]
Thanks, I did that (I think) Sorry for the confusion. Hopefully it can be added to the playlist soon. Thanks!
