### ISSUE TITLE
Add: TCSM.cv

### ISSUE THREAD

**Issue by provanumero1** [iptv-org/database#473]
### Channel Name

TCSM

### Country

cv

### Broadcast Area

s/CV-SL; s/CV-BV

### Languages

por

### NSFW

FALSE

### Website (optional)

https://tcsm.cv

### Logo

https://tcsm.cv/wp-content/uploads/2022/09/logotipo-tcsm-tv300.jpg

### Notes

https://github.com/iptv-org/iptv/issues/8952

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/issues/473
