### ISSUE TITLE
Add: GCTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#4760]
### Channel Name

Greenwich Community Television

### Alternative Names (optional)

GCTV

### Country

US

### Subdivision (optional)

US-CT

### City (optional)

Greenwich

### Broadcast Area

s/US-CT

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://greenwichtv.org/

### Logo

https://greenwichtv.org/wp-content/uploads/2018/04/GCTV-logo.png

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed
