### ISSUE TITLE
Add: Mansudae TV

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/database#4761]
### Channel Name

Mansudae TV

### Country

KP

### Broadcast Area

s/KP

### Languages

kor

### NSFW

FALSE

### Logo

https://commons.wikimedia.org/wiki/File:Mansudae_TV_Logo_NK.svg

### Notes

Manbang iptv channel

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by sunyuanzhe** [comment]
https://logos.fandom.com/wiki/File:Mansuade_ident.jpg
