### ISSUE TITLE
Add: Mansudae TV

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/database#4762]
### Channel Name

Mansudae TV

### Country

KP

### Broadcast Area

c/KP

### Languages

kor

### NSFW

FALSE

### Logo

https://logos.fandom.com/wiki/File:Mansuade_ident.jpg

### Notes

Manbang IPTV

**Comment by freearhey** [comment]
Please update your request:

- country code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
