### ISSUE TITLE
Add: När-TV

### ISSUE THREAD

**Issue by las-pen** [iptv-org/database#478]
**Channel Name**
När-TV

**Native Name (optional)**
No response

**Network (optional)**
No response

**Country**
FI

**Subdivision (optional)**
FI-12

**City (optional)**
Närpiö

**Broadcast Area**
s/FI-12

**Languages**
swe

**Categories (optional)**
No Response

**NSFW**
FALSE

**Launched (optional)**
No response

**Closed (optional)**
No response

**Replaced By (optional)**
No response

**Website (optional)**
https://nartv.fi/

**Logo**
https://nartv.fi/sites/default/files/nartv-logo.png

**Notes**

Streaming URL:
https://streaming.nartv.fi/live/ngrp:NAR_TV.stream_all/playlist.m3u8

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/2a66821083a0c54354daf39141ec06567dcd039e
