### ISSUE TITLE
Add: KRS-TV

### ISSUE THREAD

**Issue by las-pen** [iptv-org/database#479]
### Channel Name

KRS-TV

### Country

FI

### Subdivision (optional)

FI-12

### City (optional)

Kristiinankaupunki

### Broadcast Area

s/FI-12

### Languages

swe; fin

### NSFW

FALSE

### Website (optional)

https://www.krstv.fi/

### Logo

https://www.krstv.fi/uploads/vT3pE7RX/121x0_97x0/logo.png

### Notes

Stream URL

https://www.youtube.com/channel/UCQ36NJ8-XNhBDvSSsh8gS2Q/live

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/72b602bf90fed5152836b866a78652ae950c1fc4
