### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by chivacoatv** [iptv-org/database#4795]
### Channel Name

CHIVACOATV INTERNACIONAL 

### Alternative Names (optional)

Impulsando lo Nuestro 

### Network (optional)

Redes rikvik

### Country

VE

### City (optional)

Chivacoa

### Broadcast Area

Venezuela 

### Languages

Es

### NSFW

FALSE

### Website (optional)

www.chivacoatv.com

### Logo

https://www.chivacoatv.com/sitepad-data/uploads/2023/06/LOGO-CANAL-CHIVACOA-TV.png

### Notes

https://vdo1.panelstreaming.live:3875/live/guarotvlive.m3u8

**Comment by freearhey** [comment]
Duplicate of #4794
