### ISSUE TITLE
Edit: chivacoatvinternacional 

### ISSUE THREAD

**Issue by chivacoatv** [iptv-org/database#4799]
### Channel ID (required)

Chivacoatvinternacional.ve

### Channel Name

Chivacoatv 

### Network

Redes

### Owners

Chivacotv

### Country

Ve

### Subdivision

Ve

### City

Chivacoa

### Languages

Ve

### Categories

Entretenimiento

### NSFW

FALSE

### Website

https://www.chivacoatv.com

### Logo

https://www.chivacoatv.com/sitepad-data/uploads/2023/06/LOGO-CANAL-CHIVACOA-TV.png

**Comment by freearhey** [comment]
Please update your request:

- country code must be in uppercase
- subdivision code is incorrect
- language code is incorrect
- category name is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
