### ISSUE TITLE
Add USA Network to Blocklist

### ISSUE THREAD

**Issue by Central302** [iptv-org/database#48]
According https://github.com/iptv-org/iptv/issues/6973 ,`
This repository is promoting access to and offering illegal IPTV playlists of Premier League licensee channels`

If it Will Effective to All Premier League Broadcasters. I Thought to Adding USA Network to Blocklist.
(This Channel is Using for Main Premier League Broadcast. Also, CNBC [US Version, Not Effect to Other Region] Airing Premier League Game)

**Comment by freearhey** [comment]
This notice specified only one specific channel, so I don't think there's any need to block anything else. But if the rights holder changes his request I will definitely let you know.
