### ISSUE TITLE
Add: Sundom TV

### ISSUE THREAD

**Issue by las-pen** [iptv-org/database#480]
### Channel Name

Sundom TV

### Country

FI

### Subdivision (optional)

FI-12

### City (optional)

Sundom

### Broadcast Area

s/FI-12

### Languages

swe

### NSFW

FALSE

### Website (optional)

https://951.fi/

### Logo

https://951.fi/wp-content/uploads/2022/05/cropped-stv_3D_951_3D.png

### Notes

Stream URL

https://www.youtube.com/user/Sundomtv/live

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/72b602bf90fed5152836b866a78652ae950c1fc4
