### ISSUE TITLE
Add: WörTV

### ISSUE THREAD

**Issue by las-pen** [iptv-org/database#481]
### Channel Name

WörTV

### Country

FI

### Subdivision (optional)

FI-12

### City (optional)

Vöyri

### Broadcast Area

s/FI-12

### Languages

swe

### NSFW

FALSE

### Website (optional)

http://www.wortv.fi/

### Logo

http://ny.wortv.fi/wp-content/uploads/2016/06/WorTV-logo.png

### Notes

Stream URL

https://www.youtube.com/channel/UCQ36NJ8-XNhBDvSSsh8gS2Q/live

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/72b602bf90fed5152836b866a78652ae950c1fc4
