### ISSUE TITLE
Add: Animax Revival

### ISSUE THREAD

**Issue by JustSammyV** [iptv-org/database#4829]
### Channel Name

Animax Revival

### Country

CL

### Broadcast Area

r/LATAM;r/LAC

### Languages

spa;jpn

### Categories (optional)

animation

### NSFW

FALSE

### Website (optional)

https://animax.lat

### Logo

https://animax.lat/assets/img/logo-512.png

### Notes

Sourced from administrator's public group chat on Telegram @AnimaxLA

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by JustSammyV** [comment]
https://animax.lat/assets/img/logo-512.png
