### ISSUE TITLE
Edit: Nickelodeon Brazil

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#4838]
### Channel ID (required)

NickelodeonBrazil.br

### NSFW

FALSE

### Logo

https://i.imgur.com/E84jnP8.png

### Notes

https://youtu.be/mqI_V-ueVBA

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by kaikyoofers** [comment]
> Please update your request:
> 
> - logo is not loaded
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels 

@freearhey fixed

**Comment by freearhey** [comment]
Still not loading:
<img width="297" alt="image" src="https://github.com/iptv-org/database/assets/7253922/dbd45f17-0f28-4c42-b6e5-cd72f14088c7">

**Comment by kaikyoofers** [comment]
> Still not loading:
> <img width="297" alt="image" src="https://github.com/iptv-org/database/assets/7253922/dbd45f17-0f28-4c42-b6e5-cd72f14088c7">
> 

Repleaced link with wikimedia commons link @freearhey

**Comment by freearhey** [comment]
Please update your request:

- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by kaikyoofers** [comment]
@freearhey fixed once again

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
