### ISSUE TITLE
Add: SSM TV [CD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#4845]
### Channel Name

SSM TV 

### Alternative Names (optional)

Studio Sango Malamu 

### Country

CD

### Broadcast Area

c/CD

### Languages

fra

### Categories (optional)

religious

### NSFW

FALSE

### Logo

https://i.imgur.com/sa09qnf.jpg

**Comment by freearhey** [comment]
Please update your request:

- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * logo must be in JPEG or PNG format
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed
