### ISSUE TITLE
Add: SGRT TV

### ISSUE THREAD

**Issue by rfnxinger** [iptv-org/database#4893]
### Channel Name

SGRT

### Network (optional)

Astra 19,2°

### Country

TR

### Broadcast Area

DE-AT

### Languages

german

### Categories (optional)

news

### NSFW

FALSE

### Logo

![image](https://github.com/iptv-org/database/assets/31359191/ead1d93c-ac49-444d-a4a2-af3ca4b350a1)

### Notes

Kanal: SGRT
Satellite: Astra 19,2° east
Frequency: 10920.75 MHz
Type: DVB-S
Transponder: 133
FEC: 7/8
![image](https://github.com/iptv-org/database/assets/31359191/787dfc0f-2f08-480c-8b73-6bcc61b7bda3)

**Comment by rfnxinger** [comment]
The logo URL is not from the channe l"SGRT" but from a news channel sending news via Satellite.
Could not find the SGRT logo but here is the  AUF1 logo

![image](https://github.com/iptv-org/database/assets/31359191/4ff7e54e-7b8c-401d-b725-a87bb0af6399)

**Comment by freearhey** [comment]
Please update your request:

- commas cannot be used in the network name
- country code is incorrect
- subdivision code is incorrect
- broadcast area code is incorrect
- language code is incorrect
- logo URL is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
