### ISSUE TITLE
Please add Almahaliya

### ISSUE THREAD

**Issue by BountyChocolate123456** [iptv-org/database#49]
``id,name,native_name,network,country,subdivision,city,broadcast_area,languages,categories,is_nsfw,website,logo
AlmahaliyaTV.sy,Almahaliya,,,SY,,,c/SY,ara,,FALSE,http://www.ortas.online/LocalTV,http://www.ortas.online/rtv_icons/Local_logo.png``

https://www.flysat.com/en/channel/29364/almahaliya-tv

I'm unable to edit the file via the web editor. Thankyou

**Comment by freearhey** [comment]
Added.

**Comment by BountyChocolate123456** [comment]
Thanks
