### ISSUE TITLE
Add: Essaida TV

### ISSUE THREAD

**Issue by oussamame07** [iptv-org/database#4900]
### Channel Name

Essaida TV

### Country

TN

### Broadcast Area

r/ARAB

### Languages

ara

### Categories (optional)

culture

### NSFW

FALSE

### Website (optional)

https://www.essaidafm.com

### Logo

https://www.essaidafm.com/images/radio/logo_ar.png

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- language code is incorrect
- category name should be in lowercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
