### ISSUE TITLE
Add: TCSM.pt

### ISSUE THREAD

**Issue by provanumero1** [iptv-org/database#492]
### Channel Name

TCSM

### Country

PT

### Broadcast Area

c/PT

### Languages

pt

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://tcsm.cv

### Logo

https://tcsm.cv/wp-content/uploads/2022/09/logotipo-tcsm-tv300.jpg

**Comment by provanumero1** [comment]
https://github.com/iptv-org/iptv/pull/9015

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=TCSM

**Comment by provanumero1** [comment]
when the https://github.com/iptv-org/iptv/issues/8952 will be completed?


Il giorno sab 24 set 2022 alle ore 18:50 Aleksandr Statciuk <
***@***.***> ha scritto:

**Comment by freearhey** [comment]
if the https://github.com/iptv-org/iptv/pull/9022 are accepted, the channel should appear in the playlist tomorrow.

**Comment by provanumero1** [comment]
thank you dear!

Il giorno sab 24 set 2022 alle ore 18:59 Aleksandr Statciuk <
***@***.***> ha scritto:
