### ISSUE TITLE
Add: KotiTV

### ISSUE THREAD

**Issue by las-pen** [iptv-org/database#493]
### Channel Name

KotiTV

### Country

FI

### Broadcast Area

c/FI

### Languages

fin;swe

### NSFW

FALSE

### Website (optional)

https://www.kotitv.fi/

### Logo

https://upload.wikimedia.org/wikipedia/commons/1/1a/KotiTV_FB_IG_profile_picture.jpg

### Notes

Not 24/7

Stream:
https://suite.icareus.com/web/kotitv/player/embed/live?channelId=83459780&playerId=83460310

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/22a0a92c13ddcae5239d75d2fa3798af147e1498
