### ISSUE TITLE
Add: Pluto TV Godzilla (720p)

### ISSUE THREAD

**Issue by ghost** [iptv-org/database#4950]
### Channel Name

Pluto TV Godzilla

### Alternative Names (optional)

Godzilla

### Country

US

### Broadcast Area

c/.us

### Languages

eng

### Categories (optional)

Sci-Fi;Movies

### NSFW

FALSE

### Logo

https://images.pluto.tv/channels/6452c8cee1979c0008608e27/colorLogoPNG.png

### Notes

I found a .m3u playlist with this channel at https://troypointinsider.com/t/updated-1-28-2022-adding-pluto-tv-and-other-urls-to-tivimate/34050

Here is the .m3u link: https://i.mjh.nz/PlutoTV/6452c8cee1979c0008608e27-alt.m3u8

Also, apologies if I got the country code wrong. I was having trouble finding out what to put since its Pluto TV.

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- category name is incorrect
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
