### ISSUE TITLE
Add: M6 International

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/database#4965]
### Channel Name

M6 International

### Network (optional)

M6

### Owners (optional)

Groupe M6

### Country

FR

### Broadcast Area

c/AE;c/CA

### Languages

fra

### Categories (optional)

entertainment

### NSFW

FALSE

### Launched (optional)

2019-10-23

### Website (optional)

https://www.m6international.tv/

### Logo

https://www.m6international.tv/wp-content/uploads/2020/12/m6-international.png

### Notes

International version of M6, Outside Europe.
Slogan: « A Daily Dose of France »
More Info: https://fr.m.wikipedia.org/wiki/M6_International

TV Channel Numbers
Canada 🇨🇦 
Bell Fibe TV: Channel 1167 
Bell Fibe TV Alt: Channel 167
Hélix: Canal 58

UAE 🇦🇪 
Du: Canal 1415

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect
- category name should be in lowercase
- invalid launched date format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
