### ISSUE TITLE
Add:Cartoon Network Canada (formerly Teletoon)

### ISSUE THREAD

**Issue by ThatQuirkyBoi** [iptv-org/database#4980]
### Channel Name

Cartoon Network

### Alternative Names (optional)

CN, CN Canada

### Owners (optional)

Corus Entertainment

### Country

CA

### Subdivision (optional)

CA-ON

### City (optional)

Ontario

### Broadcast Area

CA

### Languages

English

### Categories (optional)

animation;kids

### NSFW

FALSE

### Launched (optional)

2023-03-27

### Website (optional)

cartoonnetwork.ca

### Logo

https://commons.wikimedia.org/wiki/File:Cartoon_Network_2010.svg

### Notes

Teletoon used to be in the CA.m3u, but it was replaced by Cartoon Network Canada, and has since left. CN CA had it's own channel, separate from Teletoon, but that got rebranded to Boomerang Canada the same day Teletoon rebranded.

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=CartoonNetworkCanada.ca

**Comment by ThatQuirkyBoi** [comment]
> Already in the database: https://iptv-org.github.io/channel?id=CartoonNetworkCanada.ca

I can't find a way to watch it. Can you show me how? Thanks.

**Comment by freearhey** [comment]
> The site contains a list of all TV channels in the world and only those of them for which we have working stream links are included in the playlists.

https://github.com/iptv-org/iptv/blob/master/FAQ.md#why-is-the-channel-on-the-iptv-orggithubio-but-not-in-the-playlist
