### ISSUE TITLE
Edit: Re TV [LV]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#5000]
### Channel ID (required)

ReTV.lv

### NSFW

FALSE

### Logo

https://upload.wikimedia.org/wikipedia/lv/thumb/d/db/ReTV_Logo_2022.svg/320px-ReTV_Logo_2022.svg.png

### Notes

Or maybe convert to imgur.com

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
I do best, to add that logo.
