### ISSUE TITLE
Edit: TV3 Film [LV]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#5005]
### Channel ID (required)

TV3Film.lv

### Channel Name

Go3 Films

### Broadcast Area

c/LT;c/EE;c/LV

### Categories

movies

### NSFW

FALSE

### Website

https://go3.tv

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Go3_Films_Logo_2023.svg/233px-Go3_Films_Logo_2023.svg.png

### Notes

Name is changed.

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
Changed again.
