### ISSUE TITLE
Edit: Delfi TV [EE]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#5013]
### Channel ID (required)

DelfiTV.ee

### Country

LT

### Broadcast Area

c/LT

### NSFW

FALSE

### Website

https://www.delfi.lt/video/puslapis/tv

### Notes

TV channel is never in Estonia but in Lithuania. In Estonia and Latvia is only its programs live, on the Internet.

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DJ1999-max** [comment]
Changed.
