### ISSUE TITLE
Add: Faithlife TV - The Family Center

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#502]
### Channel Name

Faithlife TV - The Family Center

### Country

US

### Subdivision (optional)

US-WA

### City (optional)

Bellingham

### Broadcast Area

s/US-WA

### Languages

eng

### Categories (optional)

religion;family

### NSFW

FALSE

### Website (optional)

https://faithlifetv.com/

### Logo

https://files.logoscdn.com/v1/files/9154786/content.svg?signature=mKUuAU6f7RYxrskmDYNsKHbdVMU

### Notes

Streaming URL:

https://resi.media/fcc-cc-hn/Manifest.m3u8

**Comment by freearhey** [comment]
>Streaming URL:
>
>https://resi.media/fcc-cc-hn/Manifest.m3u8

This is not a live broadcast.
