### ISSUE TITLE
Add: TV Kosmos

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#5034]
### Channel Name

TV Kosmos

### Alternative Names (optional)

Τηλεόραση ΚΟΣΜΟΣ

### Country

GR

### City (optional)

Rhodes

### Broadcast Area

c/GR

### Languages

ell

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.tvkosmos.gr/livetv

### Logo

https://play-lh.googleusercontent.com/72ZSoN11sHL5AtqrapJ5nHRPGDG-CRY5WZuI2KgRWbQDwlunzCOxSa2MFHPmdJiI1UQ=w240-h480-rw

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
