### ISSUE TITLE
Add: UTRK [KG]

### ISSUE THREAD

**Issue by gohoski** [iptv-org/database#5038]
### Channel Name

UTRK

### Alternative Names (optional)

УТРК

### Network (optional)

NTRK

### Owners (optional)

NTRK

### Country

KG

### City (optional)

Bishkek

### Broadcast Area

c/KG

### Languages

kir;rus

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.utrk.kg

### Logo

https://i.ibb.co/jwPmJWK/logo-2.png

### Notes

This channel replaces KTRK.kg. I cannot find the launched date, it could be 2023-01-27, but I'm not sure.

**Comment by freearhey** [comment]
Please update your request:

- country code must be in uppercase

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
