### ISSUE TITLE
Add: Viva TV (Yurimaguas)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/database#5101]
### Channel Name

Viva TV (Yurimaguas)

### Country

PE

### City (optional)

Yurimaguas

### Broadcast Area

PE

### Languages

spa

### NSFW

FALSE

### Website (optional)

https://www.vivatvonline.com/

### Logo

https://static.wixstatic.com/media/55d1d0_54943a5ece3f446bb856b19136d7eb28~mv2.png/v1/fill/w_480,h_480,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/VIVA%20TV%20alpha%20mayor%20tama%C3%B1o.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=VivaTVYurimaguas.pe
