### ISSUE TITLE
Add: Willax TV

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/database#5102]
### Channel Name

Willax TV

### Country

PE

### Broadcast Area

PE

### Languages

spa

### NSFW

FALSE

### Website (optional)

https://willax.pe/en-vivo

### Logo

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw8NDw0NDQ8PDw8NDw4NDg8NDw8ODQ0NFhUWFhcVFRUYHSggGBoxGxYWIjEhJSstLjEuFx8zODMsNygtLisBCgoKDg0OGxAPGisiHyUtMzAyMi03MDItKy0tKystLSstLS0rLS4rLS0uKy0tKy0tOCsrLSstKysrKysrKysrK//AABEIAFsBEwMBEQACEQEDEQH/xAAcAAEAAgIDAQAAAAAAAAAAAAAABQcBBgMECAL/xABFEAABAwICBAYMDgIDAQAAAAABAAIDBBEFEgYHEyEUMTVBcbEIFSIyM1FhcnSBgrIXIzRSU1RzkZKTobPR4aPBRGKiQv/EABoBAQACAwEAAAAAAAAAAAAAAAADBAECBQb/xAAvEQEAAQIDBQYGAwEAAAAAAAAAAQIDBBEyBRMUMVISQVFhcZEVITRigaEGM0Ii/9oADAMBAAIRAxEAPwC8UBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQYQQuIeFf7PUEE2g455mxtL5HBrWi7nONgB5ViZiIzltTTNU5UxnLo9vqP6zD+Y1ab2jxhPwd/on2fTMcpHGzaiEnxB7brE37cRnNUMThL8c6J9nJ20p/po/xBacVZ64a8Pd6ZfTcRgO4SxnocE4ux1wxNi5HOmX1w2L6Rn4gscXY6492N1X4Sy2rjPE9p6CEnGYeOdce7E26o5w+uEM+c371jjsP1x7sdirwfTJGu70g9Clt3rd3RVE+jExMc32pWBAQEBAQEBAQEGEBAQEBAQZQYQZQYQEGUGEBBC4h4V/s9QQTaCE0z5Pq/syocR/XK9s36qj1UuuM9s7mE+Gb61Bif65RX9EtgXMUHbw3vz5q1q5IMRpSSjU3boON3Qob3chvdzuqBXSOE8T+kL1H8e01/hXv9yRXpEAgICAgICAg4aupZDHJNIcrImukebE2aBcmwQaxgesjCcQqI6SlqS+aXNkaYpW3sC47yLcQKCdxzGIMPgfVVb9nDHbM7K51rmw3DegitGtOsNxWV8FDOZZGM2rmmORlmXAvdwHOQgktIcepsMgNVWSbOIOazMGuf3RvYWaCeYoOjoxpph+LOlZQzGV0LQ54McjLNJsD3QCDYEBAQEGUGEGUGEBBlBCYh4V/s9QQTaCE005Pq/syo7tM1UTTTzXtm/VUeqlswXO4K/0vcdmUhgELpahkcYzOIdYDjO5Q4jBX5tz/AMyr4qqLdqaq/lDb+0NX9A772/yubwGJ6J/Tj8bY6nZocFqWuJdC4C3jb/K1q2fieif0hvYuzVT8qne7Vz/Ru+9v8rT4dieif0rcRb8X3HC6DfKCwO3C9t59SqYrCXrcR26ckV29RPKX3wqP5w/VU93V4Id5T4pXBZGuD8pvYhem/j9MxTXn5IbtUTlkk16NCICAgICAgIOtiNI2ohmgeSGzRvicW8Ya4WNkGiaK6pqHDKyGuhnnfJBnLWvLMpzNLTew8RKDsa7eRKzzoveCCr+xy5TqvQn/ALkaCwuyA5GPpUHU9BpnY1/KcS+wi98oL9QEGEGUBBhBlAQYQZQQmIeFf7PUEE2gg9NeT6z7Mre3qhf2X9XR6qSV175smrzlGDok91R3dLl7Z+kq/C5VTeGEBBBaUd7F0nqXC23po9Rry88y2HRbil6Wr0OxNNbCdXdGp6X6wKHBpY4azbB0rNowxxl7CL2O/wAf8hBIaJaVUuMQuqKNzixjzG8Pble1wAO8dBQTiDTsZ1mYVQ1fAZ5ztQQ2QsYXRxOPM9w4v9INvjka9rXNIc1wDmkbwQeIhBw4hWR00MtRMcscEb5XnxMaLlBpmBa1sMxCpho6bhDpZnZWgwkNHPcnmCDY9LyRh2IEGxFLOQRuI7goPN+pmoeccoAXvIJmuC4kH4p6C7ddvIlZ50XvhBV3Y5cp1XoT/wByNBYXZAcjH0qDqeg0zsa/lOJfYRe+UF+INPx7WZhOHzSU1RUHbRHK9kcb5C13iNggjodc2COIBnlbfndBIB1INxwXG6Wvj2tHPHOznMbgS0+IjjCDUtJNatDhlTJSVUNU2SM8YjGR7eZzTfeEGwaIaWUmMwGoo3Ehrix7HjLJG7yhBPIK9x7W/hVDUSUrjLK6I5XugaHRh/OAb70G2aM46zE6ZlXFFLFHITkE7cjnt+cB4kEsghMQ8K/2eoIJtBDaYsLqCraOMxlb29ULmz7kW8TRVVyiVM9r5PJ96uvYfE7Hm2LQKjezEIXOtYB/P5FFd0uftTHWruGqpp5rdVR5MQEGu6XztjbDm53O6lxtr2qq6aeyjru00ams9sI/L9y4fC3EfFW2zaITtkbNl5i3qXc2RaqoirtJLd2mvS2JdlIrTXzo/wAMwzhTG3loHbXdxmE7njqPqQaF2O2N7GuqKFx7mrizsB4trHv3dLSfwoLy0rxhuH0NXWOt8RE5zb88nE0fiIQePpY5qjhFWQ54a8PnkO+zpHbrnylB6R1FY6a3CmxSOzSUTzTm/Hs7ZmfobepBxa+8c4LhfBmmz66QReXZN7p3+gg1Dsc9H88tVib27ohweEn6R295HqsPaQXDpjydiHos/uFB5s1L8u4f0z/tPQXhrt5ErPOi98IKw7HLlOq9Cf8AuRoLB7IDkY+lQdT0GmdjX8pxL7CL3ygvxBWuK6nqOurquvrJ5ncIkMjYossbWCw3E7yf0QRmkGo3DzBK+jlmhlYxzmbR4kicQL2dcXA8t0FYaosUmpMZo2RvIbUS8HmbfuXsN+MdO9BfmsnQaHG6Yt3MqoQTTzW4j8x3jaUHnnRvG63RrEXZmOa6N2yqqd24Sx33j/YKCz9ZetuE0ccGEyZpayIOkkG51NGdxb5H8Y8iDVNUOrh2KSCvrWkUUbrta696uQHi82/GefiQekI4wxoY0BrWgNa1osABxABB9IIXEPCv9nqCCbQRWlHyOp8wre3qhLZ1wq1XHTTehvy2Lof1KO7pQYjRKzFUc4QEGp6fd5T+c7qXPx/KFLGcoaYuaoty0A72o85vUulgOUr2D5S21dBdcNZTMnjkhkF2SsdG4Hna4WKDyUWy4BjI4w6hqwfPiv1Fh/VBbfZAaQN7XUdPE64rnNnuDxwNFwei5CCM1c6Gio0axEub8ZiGd8RI32hvk/8AQcggNQONGlxR9G82ZWxmOx5p47ub+mYesIOLXzjRq8VFKw3bRsbCAPpXd07rAQXnq7wEYZhlJSkWkEYkm8sz+6d93F6kHc0x5OxD0Wf3Cg816l+XcP6Z/wBp6C8NdvIlZ0xe+EFX9jlynVehP/cjQWF2QHIx9Kg6noNM7Gv5TiX2EXvlBvOsLWrTYO80sTOE1YALmB2WOK+8Z3ePyBBX8OsjSbEruoKW0ZNgYKZz2jyZ3bkHzV4RpjiDHtqHzRxFrszXyxQtLbbxZm9BpOrUWxrDBziqYOtB68QUT2RUmHl1O1oviItmMdt1P4pPLfi9aCm8OfEyaF1QwyQte0ysacrnx33gFB7F0YrqWpo6eWgy8GMbRE1gADAN2UjmI4rIJRBlBCYh4V/s9QQTaCI0tfloapx5oydyktRnXCS1OVcKj7Yt8Tv0V/dy6Pbh3sE0ijpJ2TvY9zWhwIba+8W51rVZmqMoQ36s6JbT8KFL9Xn/AMf8qPgq/GFBj4UaX6vP/j/lIwNc98NK64pjM+FGl+r1H+P+VngK/GEe/jwQ+kWm0Fc2NrIpWbMknPk33HkK5u0sHVTFPzhTxd6MoQnbdnzXfouTw9Xio76G96tatsranKCLOZx9CvYO3NETm6WBriqJbqri+IKD7IvR/JNTYmwdzM3g8xH0jd7Seltx7KCs8TxifE+19M7unU0TKKEXuXEvNusD1IPW2juGNoqOlpG97BDHF0kDefvug8xaZ078Ex6Z8IsYKltXD4iwkPA/WyDt6tsOfjeOtnmF2tlfXz33jc7M1v4iB0BB6kQQ2mPJ2Ieiz+4UHmzUvy7h/TP+09BeGu3kSs6YvfCCr+xy5TqvQn/uRoLC7IDkY+lQdT0GmdjX8pxL7CL3ygrzT6N8eL4iKgOzcLlc4HjcwuuLeTLZB6M0Y06wV1JTthqoIGsjY3YvIidGQOIgoIbTnW3h9LTzR0UraqpkY5jBFcxRki2ZzvJ4ggrzUXopNV17MSkYW09IXPa8iwkn4gG+O17lBbusvTqLBKYkWfVzAini8vz3f9R+qCgtDNG6rSXEHume8sL9tWVDt+VpPEP+x4gEFs60NV0NTRRyYbE2OooYgxsbBbhEDf8A5PjdxkHn3oKv1XaeS4HUmKbMaOZ2WeM3vE/iztHMRzjnQeoaSqjnjZNC8PjkaHse03a5p4iEHKghcQ8K/wBnqCCbQQmmnJ9X9mVLZ1w3t6oUoumvOObvStqeaK7pdZSqYVtShv6WFsquWDnXI2tppU8XyhyriqSydUneVfnR9RU9nvdbZvKpYKndMQQOm2jMeMUUtDI7Z5y18cmXMY5Gm4NufnHrQV/oxqSZQ1lNWSVu3bTyCXZbDJncOLfmNt9j6kFvIK71j6r2Y5PDUtqODSRx7J/xW0EgBu08Ysd5Qd3Vrq+jwFtQdtwiWoLbybPZ5Y28TQLnn3oN3QdPGKHhVPUU2bJt4pIs1r5cwIvb1oK10K1O9qq6nr+HbbYZzs9hkzZmFvHmPjQbxpto722oZqHa7Ha5TtMufLY34ri6DV9XGrDtFUy1XC9vtITBl2OztdzXXvmPzUGw6wNFe3VEaLbbD42OXPk2ne33WuPGghdWurjtDJUy8K4RwhjGW2Wzy2N798boO/pvq6oMatJOHRVDRlE8Ng8t5g4Hc4dKDQHdj83NuxI5fLTAut+NBP4FqQwymcH1Lpqtw35ZCGRX81vH6ygsqkpY4GNihY2ONgs1jGhrWjyAIKn0k1N1GJ1UtZU4oXPkduHBt0bOZre73ABBYWh+jFPg9Kykpxe3dSSEWfNJzuP8IJtBV+mupunxOqdWQT8EdLvlYIhIx8nzhvFj40Gxau9EajBYZKaSt4VATmiYYtmYXc9jmO4+JBt6CFxDwr/Z6ggmkHRxug4XTzU+bJtW5c1r29S2oq7NUS2pnKc2kfBmfrQ/L/tWuL8k2/8AJh+rEkW4UPy/7WYxeXc1ru9qMsnF8Fh+tj8r+1vx32oT4Kz9bH5X9rMY/L/LSujtRkx8FZ+tj8r+1n4h9qLceb7ZquI/5Y/K/tU8Xd38RGWWSG7g953vr4MT9aH5f9qlufNB8N+5suiOjRw1swMu12pae9y2sOlSUUdlbw2G3OfzzzbEt1oQEBAQEBAQEBBhAQEBAQEBAQEBAQEBAQQuIeFf7PUEE2gICAgICAgICAgICAgICAgICAgICAgwgIMoCAgICAgIMICDKCExDwr/AGeoIJtAQEBAQEBAQEBAQEBAQEBAQEBAQYQEGUGEGUGEBBlBhAQEBAQEELiHhX+z1BB//9k=

### Notes

Stream link URL: https://stream-02.nyc.dailymotion.com/sec(ekpi6JmRB5KslkTtNqtBmrwEYIGOU6ZJ3nZHvraL4dYnL3lRAcbutJtIlUHVGQHz)/dm/3/x7x4dgx/s/live-1.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=WillaxTV.pe
