### ISSUE TITLE
Add: BBC Nordic

### ISSUE THREAD

**Issue by PiirateCat** [iptv-org/database#5281]
### Channel Name

BBC Nordic

### Owners (optional)

BBC Studios

### Country

UK

### Broadcast Area

r/NEUR;c/DK;c/SE;c/NO;c/IS

### Languages

dan;eng;fin;isl;nor;swe

### Categories (optional)

general;entertainment

### NSFW

FALSE

### Launched (optional)

2023-04-17

### Website (optional)

https://www.bbcnordic.com/

### Logo

https://i.imgur.com/pC4pZuz.jpg

**Comment by freearhey** [comment]
Please update your request:

- country code is incorrect
- broadcast area code is incorrect
- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by PiirateCat** [comment]
> * country code is incorrect
 i wouldnt know which country code to use as it broadcasts across scandinavia

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by PiirateCat** [comment]
Oh right i didn't know that meant country code.

Thanks

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by PiirateCat** [comment]
> Please update your request:
> 
> * broadcast area code is incorrect
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels


It said to separate countries using semi-colons i don't see what i did here if you could help me out.

Thanks

**Comment by freearhey** [comment]
<img width="1012" alt="image" src="https://github.com/iptv-org/database/assets/7253922/0654f356-fb16-4192-9ce2-0793f7bbcc68">

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
