### ISSUE TITLE
Add: TV Osaka

### ISSUE THREAD

**Issue by SuperPatrikTV10** [iptv-org/database#5291]
### Channel Name

TV Osaka

### Country

JP

### City (optional)

Osaka

### Broadcast Area

JP

### Languages

jpn

### NSFW

FALSE

### Logo

https://asianwiki.com/images/e/e1/TV_Osaka-p1.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channel?id=JOBHDTV.jp
