### ISSUE TITLE
Add: PCC-TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#552]
### Channel Name

PCC-TV

### Country

US

### Subdivision (optional)

US-FL

### City (optional)

Clearwater

### Broadcast Area

s/US-FL

### Languages

eng

### Categories (optional)

legislative

### NSFW

FALSE

### Website (optional)

https://www.pinellascounty.org/tv/default.htm

### Logo

https://www.pinellascounty.org/resident/images/pcc-tv-logo.gif

### Notes

Streaming URL:

https://cdn3.wowza.com/5/cFh0V0QwUVc4SDl2/pinellas/G1551_004/chunklist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=PCC-TV
