### ISSUE TITLE
Add: Diktyo TV [GR]

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/database#5609]
### Channel Name

Diktyo TV

### Alternative Names (optional)

Δίκτυο Τηλεόραση

### Country

GR

### Subdivision (optional)

GR-B

### City (optional)

Serrès

### Broadcast Area

c/GR

### Languages

gmy

### Categories (optional)

general

### NSFW

FALSE

### Logo

https://i.imgur.com/02V5ecC.jpg

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by BellezaEmporium** [comment]
Changed.

**Comment by iptvnikolas** [comment]
https://5d00db0e0fcd5.streamlock.net/7322/7322/playlist.m3u8
