### ISSUE TITLE
Edit: Asharq Documentary

### ISSUE THREAD

**Issue by zakaria-zahidi** [iptv-org/database#6205]
### Channel ID (required)

AsharqDocumentary.sa

### NSFW

FALSE

### Logo

https://arabtv.xyz/wp-content/uploads/2023/03/Asharq-Documentary.png

**Comment by freearhey** [comment]
> If the channel has several versions of the logo, it is better to use the one used on air.

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channel-logo-guidelines

<img width="1072" alt="image" src="https://github.com/iptv-org/database/assets/7253922/0103b730-1a6f-4581-a812-00bae3cd47d7">
