### ISSUE TITLE
Add:  RaveOne

### ISSUE THREAD

**Issue by Ravediff** [iptv-org/database#6235]
It's my Private Channel, I would like you to add it. It mostly have old cartoons (cartoon network) and Animes , tv series and, movies. Its like 60%cartoons, 20%tv series 10%anime 10%movies.

Here's the link: http://79.54.251.106:8409/iptv/channel/1.m3u8

Name: RaveOne
Genre : entertainment 
Give it a try

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
