### ISSUE TITLE
Add: Unifi Sports 1 (Malaysia)

### ISSUE THREAD

**Issue by Smark223** [iptv-org/database#625]
Channel not in database.

Stream link:
https://unifi-live05.secureswiftcontent.com/UnifiHD/live11.mpd

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_add.yml&title=Add%3A+

**Comment by Smark223** [comment]
> Please use this form instead: https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_add.yml&title=Add%3A+

Thanks. It linked me to the one I used from here: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&template=------channel-request.yml&title=Add%3A+
