### ISSUE TITLE
Add: Unifi Sports 1

### ISSUE THREAD

**Issue by Smark223** [iptv-org/database#626]
### Channel Name

Unifi Sports 1

### Country

MY

### Broadcast Area

c/MY

### Languages

msa;eng

### Categories (optional)

sports

### NSFW

FALSE

### Launched (optional)

2020-02-28

### Website (optional)

https://unifi.com.my/tv/shows-category/sports

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Unifi_Sports.png/1200px-Unifi_Sports.png

### Notes

Channel stream link: https://unifi-live05.secureswiftcontent.com/UnifiHD/live11.mpd

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/5ed3cb4357a9223750e65ff08f2eb10c871a5a4d
