### ISSUE TITLE
Add: Millennium TV 24 [US/BD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#6430]
### Channel Name

Millennium TV 24

### Country

US

### Subdivision (optional)

US-NY

### Broadcast Area

c/US;c/BD

### Languages

ben;eng

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://millenniumtv24.com/

### Logo

https://i.imgur.com/EwFzZJl.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/us/MillenniumTV24
