### ISSUE TITLE
Add: Chinese Hope Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6432]
### Channel Name

Chinese Hope Channel

### Alternative Names (optional)

希望電視台

### Country

HK

### City (optional)

Sha Tin District

### Broadcast Area

c/HK;c/CN

### Languages

zho;eng

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://chinesehope.tv/live.php

### Logo

https://www.tvchinese.net/uploads/tv/chinesehope.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/cn/HopeTVChinese
