### ISSUE TITLE
Add: ABEMA News

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6433]
### Channel Name

ABEMA News

### Country

JP

### City (optional)

Shibuya-ku

### Broadcast Area

c/JP

### Languages

jpn

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

2016-03-01

### Website (optional)

https://abema.tv/

### Logo

https://images.crunchbase.com/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/fnmxjhzj2dzjogwgjjha

**Comment by freearhey** [comment]
According to the wikipedia article and the list on the website there is more than one channel with "Abema" in the name:

https://en.wikipedia.org/wiki/Abema
https://abema.tv/

Which exact channel are you referring to?
