### ISSUE TITLE
Add: UBC

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6444]
### Channel Name

UBC

### Alternative Names (optional)

울산방송

### Country

KR

### City (optional)

Ulsan

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.ubc.co.kr/onair/web_tv_player.html

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Ubc_logo2.svg/220px-Ubc_logo2.svg.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/kr/HLDPDTV
