### ISSUE TITLE
Edit: Ananda TV

### ISSUE THREAD

**Issue by SPRGROUPBD** [iptv-org/database#6475]
### Channel ID (required)

AnandaTV.bd

### NSFW

FALSE

### Logo

https://anandatv.tv/wp-content/uploads/2023/08/cropped-Atv_Web_Logo.jpg

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
