### ISSUE TITLE
Add: El Rey, TED, UFC, 60 minutes - USA

### ISSUE THREAD

**Issue by kinghenrick** [iptv-org/database#653]
Looking for m3u8's for the following. Having great difficulty locating. Any help from community would be greatly appreciated. Thank you

El Rey - Plex
Hallmark Channel
TED - Plex
UFC Reloaded - Xumo
60 minutes - Pluto TV

**Comment by freearhey** [comment]
Then you'd better ask for help here: https://github.com/iptv-org/iptv/issues

This repository only stores channel descriptions.
