### ISSUE TITLE
Add: Moldova 2

### ISSUE THREAD

**Issue by Smark223** [iptv-org/database#655]
### Channel Name

Moldova 2

### Country

MD

### Broadcast Area

c/MD

### Languages

ron

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://trm.md/ro/moldova-2

### Logo

https://trm.md/img/pages/2018/10/18/moldova-2/moldova-2.png

### Notes

Channel stream is already in the md playlist but without a tvg-id

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/database/commit/acb2e0838e9aa0ec53295a9c4456e7dbd3cff3fb
