### ISSUE TITLE
Add: US Weekly TV

### ISSUE THREAD

**Issue by seeCURE** [iptv-org/database#669]
+ Website: https://tv.usmagazine.com/

+ Stream Link: https://a360-usweeklytv-1-us.plex.wurl.tv/playlist.m3u8
+ Resolution: 1080p
+ Language: English
+ Country: USA

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_add.yml&title=Add%3A+
