### ISSUE TITLE
Add: HKIBC

### ISSUE THREAD

**Issue by AzeemHadzrie** [iptv-org/database#672]
### Channel Name

Hong Kong Infomation Business Channel

### Native Name (optional)

香港國際財經台

### Country

HK

### Broadcast Area

c/HK

### Languages

zho;eng

### NSFW

FALSE

### Launched (optional)

2018-07-30

### Logo

https://upload.wikimedia.org/wikipedia/zh/thumb/3/3a/HKIBC_logo.png/220px-HKIBC_logo.png

**Comment by freearhey** [comment]
Added.
