### ISSUE TITLE
Add: US Weekly TV

### ISSUE THREAD

**Issue by seeCURE** [iptv-org/database#673]
### Channel Name

US Weekly TV

### Country

US

### Broadcast Area

c/us

### Languages

eng

### Categories (optional)

entertainment;news

### NSFW

FALSE

### Website (optional)

https://tv.usmagazine.com/

### Logo

https://seeklogo.com/images/U/us-weekly-logo-51928092A2-seeklogo.com.png

### Notes

+ Stream Link: https://a360-usweeklytv-1-us.plex.wurl.tv/playlist.m3u8
+ Resolution: 1080p

**Comment by freearhey** [comment]
Added.
