### ISSUE TITLE
Add: ABEMA Overseas News

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6843]
### Channel Name

ABEMA Overseas News

### Country

JP

### City (optional)

Shibuya-ku

### Broadcast Area

c/JP

### Languages

jpn;eng

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

2019-02-25

### Logo

https://www.vpndate.com/wp-content/uploads/2017/11/AbemaTV_logo.jpg

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Corrected
