### ISSUE TITLE
Add: Amhara Broadcasting Center

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6916]
### Channel Name

Amhara Broadcasting Center

### Alternative Names (optional)

ABC TV

### Country

US

### Subdivision (optional)

US-DC

### City (optional)

Washington

### Broadcast Area

c/US;c/ET

### Languages

amh;eng

### Categories (optional)

news;culture

### NSFW

FALSE

### Website (optional)

https://amharabroadcasting.com/

### Logo

https://img.et.cari.africa/2023/03/27/jobs-153244.jpg

**Comment by freearhey** [comment]
Please update your request:

- the logo link is geoblocked

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
