### ISSUE TITLE
Add: Hokkaido News UHB

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6921]
### Channel Name

Hokkaido News UHB

### Alternative Names (optional)

北海道ニュース UHB

### Country

JP

### City (optional)

Chuo-ku

### Broadcast Area

c/JP

### Languages

jpn

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.uhb.jp/news/

### Logo

https://static.wikia.nocookie.net/ultimatepopculture/images/a/a3/Uhb_logo.png/revision/latest?cb=20200821130720

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/jp/HokkaidoNewsUHB
