### ISSUE TITLE
Add: SBS News

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6922]
### Channel Name

SBS News

### Country

JP

### City (optional)

Shizuoka City

### Broadcast Area

c/JP

### Languages

jpn

### Categories (optional)

news;weather

### NSFW

FALSE

### Website (optional)

https://newsdig.tbs.co.jp/list/sbs

### Logo

https://newsdig.ismcdn.jp/common/images/station/sbs/logo_sbsnews.png

**Comment by freearhey** [comment]
I didn't find any information about the "SBS News" channel on the site. 

There is only mentions the SBS TV (JOVR-DTV):
https://www.at-s.com/sbstv/timetable/
https://en.wikipedia.org/wiki/Shizuoka_Broadcasting_System
