### ISSUE TITLE
Add: KBC

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6967]
### Channel Name

KBC

### Alternative Names (optional)

광주방송

### Country

KR

### City (optional)

Gwangju

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.ikbc.co.kr/onair

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/KBC_Gwangju_Broadcasting_logo.svg/220px-KBC_Gwangju_Broadcasting_logo.svg.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/kr/HLDHDTV
