### ISSUE TITLE
Add: OBS Gyeongin TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6973]
### Channel Name

OBS Gyeongin TV

### Alternative Names (optional)

OBS경인TV

### Country

KR

### City (optional)

Bucheon

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

about:blank

### Logo

https://www.obsnews.co.kr/image/logo/snslogo_20210106043927.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/kr/HLQSDTV
