### ISSUE TITLE
Add: Senses TV

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/database#6978]
### Channel Name

Senses TV

### Country

LB

### Broadcast Area

c/LB

### Languages

ara

### NSFW

FALSE

### Logo

https://i.imgur.com/hnTx8eK.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by CasperMcFadden95** [comment]
Thanks. Fixed.
