### ISSUE TITLE
Add: RTB News

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#6994]
### Channel Name

RTB News

### Alternative Names (optional)

Radio Televisyen Brunei

### Country

BN

### City (optional)

Bandar Seri Begawan

### Broadcast Area

c/BN

### Languages

mal;eng

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.rtbnews.rtb.gov.bn/SitePages/Home.aspx

### Logo

https://pbs.twimg.com/profile_images/946932391775420416/lbYQz3u8_400x400.jpg

**Comment by freearhey** [comment]
According to the description on their website "RTB News" is just a news program distributed through different TV channels.

https://www.rtbnews.rtb.gov.bn/SitePages/Home.aspx
