### ISSUE TITLE
Add: White Flix

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7001]
### Channel Name

White Flix

### Country

TH

### City (optional)

Bangkok

### Broadcast Area

c/TH

### Languages

tha

### Categories (optional)

religious;movies

### NSFW

FALSE

### Website (optional)

https://whiteflix.tv/livestream

### Logo

https://www.lyngsat.com/logo/tv/ww/white-flix-th.png

**Comment by freearhey** [comment]
Are you sure the logo's right? It says "White Channel" not "White Flix".

**Comment by AntiPontifex** [comment]
Whoops: thanks for that. Edited.
