### ISSUE TITLE
Add: HDTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7002]
### Channel Name

HDTV

### Alternative Names (optional)

Hải Dương TV

### Country

VN

### City (optional)

Hai Duong

### Broadcast Area

c/VN

### Languages

vie

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.haiduongtv.com.vn/truyen-hinh-truc-tuyen.html

### Logo

https://static.wikia.nocookie.net/logos/images/e/e7/THD_logo_2006.png/revision/latest/scale-to-width-down/180?cb=20220803101501&path-prefix=vi

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited

**Comment by AntiPontifex** [comment]
Edited again
