### ISSUE TITLE
Add: Tay Ninh TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7024]
### Channel Name

Tay Ninh TV

### Alternative Names (optional)

TTV 11

### Country

VN

### City (optional)

Tay Ninh

### Broadcast Area

c/VN

### Languages

vie

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://ttv11.vn/

### Logo

https://i.ytimg.com/vi/M9ZsB0FwPok/mqdefault.jpg

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
