### ISSUE TITLE
Add: Soc Trang TV 2

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7026]
### Channel Name

Soc Trang TV 2

### Alternative Names (optional)

STV2

### Country

VN

### City (optional)

Soc Trang

### Broadcast Area

c/VN

### Languages

vie

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://thst.vn/

### Logo

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHEkSxYX-9T4RDmhs0CR1Dw41gcBHi_O1DPoq-VVN6YYExp-PmSLzRdCAxVQ6zrQpuA_4&usqp=CAU

**Comment by freearhey** [comment]
Please update your request:

- logo is not loaded

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
