### ISSUE TITLE
Add: Total TV Haryana

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7137]
### Channel Name

Total TV Haryana

### Country

IN

### City (optional)

Noida

### Broadcast Area

c/IN

### Languages

hin

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.totaltv.in/

### Logo

https://www.onlinechannels.live/wp-content/uploads/2019/04/total-tv-haryana.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/in/TotalTVHaryana
