### ISSUE TITLE
Edit: 3Tamil TV

### ISSUE THREAD

**Issue by kamrajx** [iptv-org/database#7139]
### Channel ID (required)

3TamilTV.in

### Country

AU

### Languages

tam

### NSFW

FALSE

### Website

https://threetamil.tv/

### Logo

https://i.imgur.com/R43HJBp.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
