### ISSUE TITLE
Add: Al Alarabia [SA]

### ISSUE THREAD

**Issue by armaaar** [iptv-org/database#7165]
### Channel Name

Al Alarabia

### Alternative Names (optional)

العربية

### Country

SA

### Broadcast Area

r/ARAB;c/SA

### Languages

ara;arb

### Categories (optional)

news

### NSFW

FALSE

### Closed (optional)

2003-03-03

### Website (optional)

https://www.alarabiya.net/

### Logo

https://www.alarabiya.net/.resources/aa-fe-templating/webresources/dist/assets/gfx/logo/logo@2x.png

### Notes

This is their official live stream: https://live.alarabiya.net/alarabiapublish/alarabiya.smil/playlist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/ae/Alarabiya
