### ISSUE TITLE
Add: Mantavya News

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7202]
### Channel Name

Mantavya News

### Alternative Names (optional)

મંતવ્ય ન્યૂઝ

### Country

IN

### City (optional)

Ahmedabad

### Broadcast Area

c/IN

### Languages

guj

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://mantavyanews.com/livetv/

### Logo

https://mantavya-news-img.b-cdn.net/wp-content/uploads/2022/11/logo.png

**Comment by freearhey** [comment]
Please update your request:

- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
