### ISSUE TITLE
Add: Sadvidya TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7262]
### Channel Name

Sadvidya TV

### Country

IN

### City (optional)

Ahmedabad

### Broadcast Area

c/IN

### Languages

guj

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://www.sadvidyatv.in/

### Logo

https://yt3.googleusercontent.com/DAA_3sKAuuG-GS8ghz8GPSUVApnYVf75lX-DnaFBWh-TcjgCU1glBCqmCRsDmLoicN0xwyaP1w=s100-c-k-c0x00ffffff-no-rj

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect
- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
