### ISSUE TITLE
Add: Sanskruti TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7263]
### Channel Name

Sanskruti TV

### Country

IN

### City (optional)

Surat

### Broadcast Area

c/IN

### Languages

guj

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://www.sanskruti.tv/

### Logo

https://tvtolive.com/wp-content/uploads/Sanskruti-TV-tvtolive.com_.jpg

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
