### ISSUE TITLE
Edit: Massive Edit | EnerGeek Channels

### ISSUE THREAD

**Issue by JustSammyV** [iptv-org/database#7317]
### Channel ID (required)

EnerGeek.cl | EnerGeekRadio.cl | FanpopTV.cl

### Owners

Productora EnerGeek Limitada

### Country

CL

### Subdivision

CL-RM

### City

Santiago

### Broadcast Area

r/LATAM;r/LAC;r/HISPAM

### Languages

spa

### NSFW

None

### Notes

These edits apply for all EnerGeek channels.

**Comment by freearhey** [comment]
It doesn't work that way. You need to create a separate request for each channel.
