### ISSUE TITLE
Add: Daijiworld TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7319]
### Channel Name

Daijiworld TV

### Country

IN

### City (optional)

Mangalore

### Broadcast Area

c/IN

### Languages

kan;kok;eng

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.daijiworld.com/

### Logo

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREGo1f8H3uyEp0PxSGMZTuSZgdY-ggpu7xxJE-zIZNHWTU523eiNmWztcrwoBLNKLurVw&usqp=CAU

**Comment by freearhey** [comment]
Please update your request:

- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
