### ISSUE TITLE
Add: Zee News Kannada

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7320]
### Channel Name

Zee News Kannada

### Country

IN

### City (optional)

Bengaluru

### Broadcast Area

c/IN

### Languages

kan

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://zeenews.india.com/kannada/live-tv

### Logo

https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/ec/8b/6c/ec8b6c81-0707-5f97-d88a-952aff7dc73d/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/512x512bb.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/in/ZeeKannadaNews
