### ISSUE TITLE
Add: Sri Sankara TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7331]
### Channel Name

Sri Sankara TV

### Country

IN

### City (optional)

Bengaluru

### Broadcast Area

c/IN

### Languages

kan;tam

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://srisankaratv.com/

### Logo

https://upload.wikimedia.org/wikipedia/commons/8/8f/Sri_Sankara_TV_Logo.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/lk/SriSankaraTV
