### ISSUE TITLE
Add: HarPal Geo

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7355]
### Channel Name

HarPal Geo

### Country

PK

### City (optional)

Karachi

### Broadcast Area

c/PK

### Languages

urd

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://harpalgeo.tv/live/

### Logo

https://i1.sndcdn.com/avatars-000110526610-kpdamk-t500x500.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/us/HarPalGeo
