### ISSUE TITLE
Add: Nethra TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7474]
### Channel Name

Nethra TV

### Alternative Names (optional)

நேத்ரா அலைவரிசை

### Owners (optional)

Sri Lanka Rupavahini Corporation

### Country

LK

### City (optional)

Colombo

### Broadcast Area

c/LK

### Languages

tam

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://www.nethratv.lk/

### Logo

https://lakvisiontv.net/img/network/1534399499442.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/in/NethraTV
