### ISSUE TITLE
Add: TV Avisen

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7501]
### Channel Name

TV Avisen

### Country

DK

### City (optional)

Copenhagen

### Broadcast Area

c/DK

### Languages

dan

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.dr.dk/drtv/kanal/drtv_192099

### Logo

https://www.lyngsat.com/logo/tv/dd/dr-tv-avisen-dk.png

**Comment by freearhey** [comment]
Please update your request:

- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
