### ISSUE TITLE
Add: KabelJournal

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7506]
### Channel Name

KabelJournal

### Country

DE

### City (optional)

Grunhain-Beierfeld

### Broadcast Area

c/DE

### Languages

deu

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.kabeljournal.de/

### Logo

https://www.kabeljournal.de/fileadmin/kjo_bsdist/theme/img/logo.png

**Comment by Carlinhos027** [comment]
Same channel as "ErzTVStollberg.de", that its already on database.

Also same stream on its website: https://www.kabeljournal.de/livestream
