### ISSUE TITLE
Block: N1 Bosnia & Herzegovina HD

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#7509]
### Channel ID

N1BosniaHerzegovinaHD.ba

### Reference

https://github.com/iptv-org/iptv/issues/6486

### Notes (optional)

For some reason, all the N1 HD channels are not blocked.

**Comment by Alstruit** [comment]
https://iptv-org.github.io/channels/ba/N1BosniaHerzegovina

**Comment by kaikyoofers** [comment]
> https://iptv-org.github.io/channels/ba/N1BosniaHerzegovina

This is a seperate channel.

**Comment by kaikyoofers** [comment]
@freearhey can you reopen this? Along with https://github.com/iptv-org/database/issues/7511 and https://github.com/iptv-org/database/issues/7510, the rest i will do.

**Comment by kaikyoofers** [comment]
I think i misunderstood, can you also reopen this issue?
