### ISSUE TITLE
Block: IDJKids

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#7516]
### Channel ID

IDJKids.rs

### Reference

https://github.com/iptv-org/iptv/issues/6486

### Notes (optional)

IDJKids is owned by United Media, which has requested a removal request in the past.

**Comment by kaikyoofers** [comment]
https://github.com/iptv-org/database/pull/7543

**Comment by kaikyoofers** [comment]
Reopening. https://github.com/iptv-org/database/pull/7543#issuecomment-1806942897

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/pull/7543#issuecomment-1806945693
