### ISSUE TITLE
Block: Novasports Premier League

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#7524]
### Channel ID

NovasportsPremierLeague.gr

### Reference

https://github.com/iptv-org/iptv/issues/6486

### Notes (optional)

Novasports Premier League is owned by United Media, which has requested a removal request in the past.

**Comment by freearhey** [comment]
@Alstruit I don't get it, what does the Bundesliga have to do with the Premier League?

**Comment by Alstruit** [comment]
> @Alstruit I don't get it, what does the Bundesliga have to do with the Premier League?

I presume that Nova Sports covers some blocked DCMA but I provided the wrong reference.

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/pull/7543#issuecomment-1806945693
