### ISSUE TITLE
Block: Diema Sport 2 4K

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#7531]
### Channel ID

DiemaSport24K.bg

### Reference

https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md

**Comment by freearhey** [comment]
@Alstruit To avoid further confusion, I think it would be better to close the current request and open a new one with a new notice.

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/pull/7543#issuecomment-1806945693
