### ISSUE TITLE
Block: Diema Sport 3 4K

### ISSUE THREAD

**Issue by kaikyoofers** [iptv-org/database#7532]
### Channel ID

DiemaSport34K.bg

### Reference

https://github.com/iptv-org/iptv/issues/6486

### Notes (optional)

Diema Sport 3 4K is owned by United Media, which has requested a removal request in the past.

**Comment by freearhey** [comment]
@Alstruit What was wrong with the original link @kaikyoofers provided?

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/pull/7543#issuecomment-1806945693
