### ISSUE TITLE
Add: Meclis TV - TR

### ISSUE THREAD

**Issue by ramazansancar** [iptv-org/database#7536]
### Channel Name

Meclis TV

### Owners (optional)

TBMM

### Country

TR

### Subdivision (optional)

TR-06

### City (optional)

Ankara

### Broadcast Area

r/TR;c/TR;s/TR-06

### Languages

tr

### NSFW

FALSE

### Website (optional)

https://tv.tbmm.gov.tr/

### Logo

https://tbmm.gov.tr/img/tbmm-logo.png

### Notes

Channel Add Request: https://github.com/iptv-org/iptv/issues/15010

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/tr/TBMMTV
