### ISSUE TITLE
Add: Voice of God TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7538]
### Channel Name

Voice of God TV

### Country

GR

### City (optional)

Kifisia

### Broadcast Area

c/GR

### Languages

ell

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://www.voiceofgod.gr/media/el

### Logo

https://www.voiceofgod.gr/images/VoG-new-logo-preview-shot_95.png

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
