### ISSUE TITLE
Add: Lepanto TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7539]
### Channel Name

Lepanto TV

### Country

GR

### City (optional)

Patras

### Broadcast Area

c/GR

### Languages

ell

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://lepantortv.gr/

### Logo

https://static-media.streema.com/media/cache/52/5e/525e3ae49d881cb702f2d4156b3c14a3.jpg

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
