### ISSUE TITLE
Add: Extra TV Croatia

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/database#7551]
Website: https://extrafm.hr

**Comment by pukozs75** [comment]
Stream: https://streaming.social3.hr/ExtraTVudzdhr5/uUankWqpXD/1.m3u8

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&projects=&template=__channels_add.yml&title=Add%3A+
