### ISSUE TITLE
Add: Flash TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7553]
### Channel Name

Flash TV

### Country

GR

### City (optional)

Kozani

### Broadcast Area

c/GR

### Languages

ell

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://flash-tv.gr/live/

### Logo

https://flash-tv.gr/wp-content/uploads/2021/01/flash_logo-panw-1-300x62-1.png

**Comment by freearhey** [comment]
Please update your request:

- country code is incorrect
- broadcast area code is incorrect
- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Edited
