### ISSUE TITLE
Edit: EnerGeek 2 rename

### ISSUE THREAD

**Issue by EnerGeekTeam** [iptv-org/database#765]
### Channel ID (required)

EnerGeek2.cl

### Channel Name

EnerGeek Fanpop

### Network

EnerGeek

### Owners

EnerGeek

### Country

CL

### Subdivision

CL-RM

### City

Recoleta

### Languages

spa

### Categories

series

### Launched

2022-10-15

### Website

https://www.energeek.cl

### Logo

https://energeek.cl/uploads/logos/EGFanpop.png

**Comment by freearhey** [comment]
Description updated except for the logo:

https://energeek.cl/upload/logos/EGFanpop.png
<img width="632" alt="image" src="https://user-images.githubusercontent.com/7253922/196441740-4405f499-2d62-44e5-b6bf-69e8d312d413.png">

**Comment by EnerGeekTeam** [comment]
Sorry, wrong link.
https://energeek.cl/uploads/logos/EGFanpop.png

**Comment by LaneSh4d0w** [comment]
Thank you for giving feedback as channel owners. We'll make sure to change the name in a next patch. Everything seems to be OK from my point of view.

**Comment by freearhey** [comment]
Updated in https://github.com/iptv-org/database/commit/7967523d84e844305c30cee70ac3ca2c0aca1680
