### ISSUE TITLE
Add: Label TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7685]
### Channel Name

Label TV

### Country

SN

### City (optional)

Dakar

### Broadcast Area

c/SN

### Languages

fra

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.labeltelevision.com/direct

### Logo

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIvM1cQHntfFoBUYfNw8BOqmttTOTpo5VFRRao1RN9q4bLoG-awMNo7jCkiPL9eFKfYDw&usqp=CAU

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/ga/LabelTV
