### ISSUE TITLE
Add: Tele Radio Padre Pio

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7687]
### Channel Name

Tele Radio Padre Pio

### Country

IT

### City (optional)

San Giovanni Rotondo

### Broadcast Area

c/IT

### Languages

its

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://www.teleradiopadrepio.it/live-streaming/?lang=en

### Logo

https://cdn-profiles.tunein.com/s3138/images/logod.jpg?t=637903319700000000

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/it/PadrePioTV
