### ISSUE TITLE
Add: Teletutto

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7691]
### Channel Name

Teletutto

### Country

IT

### City (optional)

Brescia

### Broadcast Area

c/IT

### Languages

ita

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.teletutto.it/

### Logo

https://musical-mente.it/wp-content/uploads/2019/12/teletutto-400x289.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/it/TTTeletutto
