### ISSUE TITLE
Edit: CNNInternationalEurope.us

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/database#7739]
### Channel ID (required)

CNNInternationalEurope.us

### Broadcast Area

r/EU

### NSFW

None

**Comment by freearhey** [comment]
According to [wikipedia](https://en.wikipedia.org/wiki/CNN_International_Europe%2FMiddle_East%2FAfrica) and [lyngsat](https://www.lyngsat.com/tvchannels/us/CNN-International-Europe.html) this channel is broadcast not only in the EU countries.
