### ISSUE TITLE
Add: TVC

### ISSUE THREAD

**Issue by DenysMath** [iptv-org/database#7840]
### Channel Name

TVC

### Owners (optional)

C CORPORATION

### Country

GE

### City (optional)

Tbilisi

### Broadcast Area

c/GE

### Languages

kat

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://tvc.ge/

### Logo

https://sul.ge/images/televizia/tvc.png

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by DenysMath** [comment]
Updated logo to: https://sul.ge/images/televizia/tvc.png
