### ISSUE TITLE
Edit: TV Mana Maputo [MZ] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#7854]
### Channel ID (required)

TVManaMaputo.mz

### Channel Name

TV Mana Mocambique

### Alternative Names

TV Maná Moçambique;TV Maná Maputo

### NSFW

None

### Website

https://tvmana-mocambique.com/

### Logo

https://i.imgur.com/5UIy5tD.png

**Comment by Carlinhos027** [comment]
@freearhey what happened? Channel disappeared from playlist.

**Comment by freearhey** [comment]
The channel was removed from the database at your request https://github.com/iptv-org/database/issues/7847.

**Comment by Carlinhos027** [comment]
> The channel was removed from the database at your request #7847.

I wanted to remove "TVManaMocambique.pt". This one should be "TVManaMocambique.mz".
