### ISSUE TITLE
Edit: TGRT EU

### ISSUE THREAD

**Issue by enescakircali** [iptv-org/database#7857]
### Channel ID (required)

TGRTEU.tr

### NSFW

None

### Notes

https://tv.ensonhaber.com/tgrteu/tgrteu_720p.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+
