### ISSUE TITLE
Edit: TGRT Haber

### ISSUE THREAD

**Issue by enescakircali** [iptv-org/database#7858]
### Channel ID (required)

TGRTHaber.tr

### NSFW

None

### Notes

https://tv.ensonhaber.com/tgrthaber/tgrthaber_1080p.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+
