### ISSUE TITLE
Add: Zico TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7867]
### Channel Name

Zico TV

### Country

XK

### City (optional)

Gjilan

### Broadcast Area

c/XK

### Languages

sqi

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://zico.tv/

### Logo

https://www.lyngsat.com/logo/tv/zz/zico-tv-rs.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/rs/ZICOTV
