### ISSUE TITLE
Add: Televizioni Koha

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#7907]
### Channel Name

Televizioni Koha

### Alternative Names (optional)

TV Koha

### Country

MK

### City (optional)

Tetovo

### Broadcast Area

c/MK

### Languages

sqi

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://tvkoha.tv/

### Logo

https://ub1doy938d.gjirafa.net/storage/images/channel/desktop/tvkoha.jpg?v=gzztgz1yzx

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/mk/KohaTV
