### ISSUE TITLE
Edit: Damac Persian

### ISSUE THREAD

**Issue by katarighe** [iptv-org/database#8055]
### Channel ID (required)

DamacPersian.ae

### Channel Name

Damac Persian

### Country

AE

### Broadcast Area

c/AE

### Languages

fas

### Categories

general

### NSFW

FALSE

### Replaced By

DXBOne.ae

### Logo

https://www.lyngsat.com/logo/tv/dd/dxb-one-ae.png

### Notes

https://damactv.tv/ is dead, no longer available.

**Comment by freearhey** [comment]
Please update your request:

- broadcast area code is incorrect
- "replaced by" must contain a valid channel ID

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
> "replaced by" must contain a valid channel ID

The specified channel ID is not in our database.

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by katarighe** [comment]
Hi @freearhey 

I have updated the details again. Hope this time will be okay. 👍

**Comment by freearhey** [comment]
> "replaced by" must contain a valid channel ID

The specified channel ID is not in our database.

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
