### ISSUE TITLE
Edit: Afghanistan International

### ISSUE THREAD

**Issue by katarighe** [iptv-org/database#8059]
### Channel ID (required)

AfghanistanInternational.uk

### NSFW

None

### Notes

New stream link: https://hls.afintl.com/hls/stream.m3u8

**Comment by freearhey** [comment]
This repository contains only a description of the channels. To add a link to a stream to the playlist please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+
