### ISSUE TITLE
Add: Omroep Bollenstreek

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8064]
### Channel Name

Omroep Bollenstreek

### Country

NL

### City (optional)

Noordwijk

### Broadcast Area

c/NL

### Languages

nld

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.bollenstreekomroep.nl/

### Logo

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmdDqM4HduoqhX5rmo_E_O5dNLOIhU93U9yzSpINFI4DmRj4EUu_5vJcvKObclTUbpDHc&usqp=CAU

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed
