### ISSUE TITLE
Add: RTV Krimpenerwaard

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8065]
### Channel Name

RTV Krimpenerwaard

### Country

NL

### City (optional)

Krimpenerwaard

### Broadcast Area

c/NL

### Languages

nld

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.rtvkrimpenerwaard.nl/site/

### Logo

https://cdn-profiles.tunein.com/s107392/images/logod.jpg?t=637296477060000000

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/nl/TVKrimpenerwaard
