### ISSUE TITLE
Add: RTV Lansingerland

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8066]
### Channel Name

RTV Lansingerland

### Country

NL

### City (optional)

Lansingerland

### Broadcast Area

c/NL

### Languages

nld

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://rtvlansingerland.nl/

### Logo

https://rtvlansingerland.nl/wp-content/themes/rtvllwp5/images/logo.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/nl/LansingerlandTV
