### ISSUE TITLE
Add: RTV AS

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8070]
### Channel Name

RTV AS

### Alternative Names (optional)

РТВ АС

### Country

RS

### City (optional)

Sabac

### Broadcast Area

c/RS

### Languages

srp

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://rtvas.rs/

### Logo

https://www.rem.rs/uploads/attachment/pruzalac/1368/thumb__abac.jpg

**Comment by Carlinhos027** [comment]
Duplicated: https://iptv-org.github.io/channels/rs/TVAS
