### ISSUE TITLE
Edit: Tring Tring

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/database#8104]
### Channel ID (required)

TringTring.al

### Channel Name

Tring Tring

### Network

N/A

### Owners

N/A

### Country

AL

### City

N/A

### Broadcast Area

AL

### Languages

AL

### Categories

Kids

### NSFW

None

### Launched

?

### Closed

?

### Replaced By

?

### Website

?

### Logo

?

### Notes

pls add link

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/FAQ.md#my-favorite-channel-is-not-on-the-playlist
