### ISSUE TITLE
Add: Tele Maroc

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8107]
### Channel Name

Tele Maroc

### Alternative Names (optional)

Télé Maroc

### Country

ES

### City (optional)

Madrid

### Broadcast Area

c/ES;c/MA

### Languages

spa;ara

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

2017-05-26

### Website (optional)

https://www.telemaroc.tv/liveTV

### Logo

https://upload.wikimedia.org/wikipedia/commons/8/8f/Logotelemaroc.jpeg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/ma/TeleMaroc
