### ISSUE TITLE
Add: Malmo mediakanal

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8108]
### Channel Name

Malmo mediakanal

### Alternative Names (optional)

Malmö MK

### Country

SE

### City (optional)

Malmo

### Broadcast Area

c/SE

### Languages

swe

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://malmomediakanal.se/

### Logo

https://play-lh.googleusercontent.com/D_XfDqfM5HKkXrgVPkLAJIsVseYzMvWjNri3sQaLeF1XhVdOm5V-_AoWvCRh5A7RI7DZ

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/se/TVMalmo
