### ISSUE TITLE
Add: Safeer TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8244]
### Channel Name

Safeer TV

### Country

UK

### City (optional)

London

### Broadcast Area

c/UK

### Languages

eng;ara

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://safeertv.com/live/

### Logo

https://image.roku.com/developer_channels/prod/8389e15af8fe49ac7c36d201c24ebf62fbe5b22897c2879ca26ae936e0ed308d.png

**Comment by freearhey** [comment]
Please update your request:

- logo URL must use the HTTPS protocol

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed
