### ISSUE TITLE
Add: NTV Europe

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8245]
### Channel Name

NTV Europe

### Alternative Names (optional)

এনটিভি

### Owners (optional)

International Television Channel Ltd.

### Country

UK

### City (optional)

London

### Broadcast Area

c/UK;c/BD

### Languages

ben

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

2003-07-02

### Website (optional)

https://europentv.ntvbd.com/livetv

### Logo

https://www.bangladeshcircle.com/wp-content/uploads/2015/07/NTV-Europe-logo.jpg

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/bd/NTVEurope
