### ISSUE TITLE
Add: Mostanad Network

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8288]
### Channel Name

Mostanad Network

### Alternative Names (optional)

شبکه مستند

### Country

IR

### City (optional)

Tehran

### Broadcast Area

c/IR

### Languages

pes

### Categories (optional)

documentary

### NSFW

FALSE

### Website (optional)

https://www.doctv.ir/live

### Logo

https://static.wikia.nocookie.net/logopedia/images/c/c9/IRIB_Mostanad_Logo.png/revision/latest?cb=20200502234510

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/ir/IRIBMostanad
