### ISSUE TITLE
Add: Al Araby TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8305]
### Channel Name

Al Araby TV

### Alternative Names (optional)

التلفزيون العربي

### Network (optional)

Al Araby

### Country

QA

### City (optional)

Lusail

### Broadcast Area

c/QA

### Languages

ara

### Categories (optional)

news

### NSFW

FALSE

### Launched (optional)

2015-01-01

### Website (optional)

https://www.alaraby.com/

### Logo

https://secure.b8cdn.com/images/logo/84/2087984_logo_1638809942_n.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/uk/AlArabyTV
