### ISSUE TITLE
Add: Razavi Khorasan Network

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8351]
### Channel Name

Razavi Khorasan Network

### Alternative Names (optional)

شبکه خراسان رضوی

### Country

IR

### City (optional)

Mashhad

### Broadcast Area

c/IR

### Languages

pes

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://telewebion.com/live/khorasanrazavi

### Logo

https://upload.wikimedia.org/wikipedia/fa/thumb/b/bd/%D9%84%D9%88%DA%AF%D9%88_%D8%B4%D8%A8%DA%A9%D9%87_%D8%AE%D8%B1%D8%A7%D8%B3%D8%A7%D9%86_%D8%B1%D8%B6%D9%88%DB%8C.png/200px-%D9%84%D9%88%DA%AF%D9%88_%D8%B4%D8%A8%DA%A9%D9%87_%D8%AE%D8%B1%D8%A7%D8%B3%D8%A7%D9%86_%D8%B1%D8%B6%D9%88%DB%8C.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/ir/KhorasanRazaviTV
