### ISSUE TITLE
Add: O Dia TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8395]
### Channel Name

O Dia TV

### Country

BR

### City (optional)

Teresina

### Broadcast Area

c/BR

### Languages

por

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.televisaoodia.com.br/

### Logo

https://upload.wikimedia.org/wikipedia/pt/a/a2/Logotipo_da_O_Dia_TV.png

**Comment by freearhey** [comment]
Duplicate of https://github.com/iptv-org/database/issues/8386
