### ISSUE TITLE
Edit: Animal Planet (Brazil)

### ISSUE THREAD

**Issue by paulolope** [iptv-org/database#8457]
### Channel ID (required)

AnimalPlanet.br

### Channel Name

Animal Planet

### Alternative Names

Animal Planet Brasil

### Owners

Warner Bros. Discovery

### Country

BR

### Broadcast Area

c/BR

### Languages

por

### Categories

documentary

### NSFW

None

### Launched

1997-01-01

### Website

https://sinalpublico.com/player3/ch.php?canal=animalplanet

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/2018_Animal_Planet_logo.svg/512px-2018_Animal_Planet_logo.svg.png

**Comment by freearhey** [comment]
- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
