### ISSUE TITLE
Edit: Disney Channel (India)

### ISSUE THREAD

**Issue by anil-s-yadav** [iptv-org/database#8458]
### Channel ID (required)

DisneyChannel.in

### Channel Name

Disney Channel

### Owners

The Walt Disney Company

### Country

IN

### Broadcast Area

c/IN

### Languages

eng, Hindi, Telugu, Tmil

### Categories

kids

### NSFW

None

### Website

http://disney.in/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Disney_Channel_logo_%282014%29.svg/512px-Disney_Channel_logo_%282014%29.svg.png

**Comment by anil-s-yadav** [comment]
There is more languages available in Disney India. T added those languages into this.

**Comment by freearhey** [comment]
Please update your request:

- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
