### ISSUE TITLE
Add: beINSports 1 (French)

### ISSUE THREAD

**Issue by A-S-H-E-E** [iptv-org/database#8488]
### Channel Name

beIN SPORTS 1

### Alternative Names (optional)

No alternative name

### Network (optional)

beIN Sports

### Owners (optional)

BeIn Media Group

### Country

FR

### Subdivision (optional)

No Subdivision

### City (optional)

No specific city

### Broadcast Area

c/FR 

### Languages

fr

### Categories (optional)

sports

### NSFW

FALSE

### Launched (optional)

The First of June 2012
01/06/2012

### Closed (optional)

Still existing 

### Website (optional)

https://www.beinsports.com/fr-fr

### Logo

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.programme-tv.net%2Fprogramme%2Fchaine%2Fprogramme-bein-sports-1-183.html&psig=AOvVaw1f49r_WfjhBBIY6WRXgZkq&ust=1702241372841000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLiLorSdg4MDFQAAAAAdAAAAABAD

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/fr/beINSports1

**Comment by A-S-H-E-E** [comment]
> Already in the database: https://iptv-org.github.io/channels/fr/beINSports1

It's blocked

**Comment by A-S-H-E-E** [comment]
Put this IPTV link for beIn Sports 1 : http://vip.itvdom.com:25443/live/V17oiyuPZBQXB/Z2EtFkyVPO/9340.ts

**Comment by freearhey** [comment]
We are cannot add this channel to the playlist due to copyright holder claims: https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md
