### ISSUE TITLE
Add: beIN Sports 2 (French)

### ISSUE THREAD

**Issue by A-S-H-E-E** [iptv-org/database#8489]
### Channel Name

beIN SPORTS 2

### Alternative Names (optional)

No alternative name

### Network (optional)

BeIN Sports

### Owners (optional)

BeIN Media Group

### Country

FR

### Subdivision (optional)

No Subdivision

### City (optional)

No specific city

### Broadcast Area

c/FR

### Languages

fr

### Categories (optional)

sports

### NSFW

FALSE

### Launched (optional)

2012-07-27

### Website (optional)

https://www.beinsports.com/fr-fr

### Logo

https://www.programme-tv.net/imgre/fit/~2~channel~75c0e8eed8466425.png/1200x630/crop-from/top/quality/80/bein-sports-2.png

### Notes

IPTV link: http://vip.itvdom.com:25443/live/V17oiyuPZBQXB/Z2EtFkyVPO/9588.ts

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/fr/beINSports2
