### ISSUE TITLE
Add: Disney Channel Taiwan

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/database#8502]
### Channel Name

Disney Channel Taiwan

### Alternative Names (optional)

迪士尼频道

### Owners (optional)

The Walt Disney Company (Southeast Asia) Pte. Ltd.

### Country

TW

### Broadcast Area

c/TW;r/SEA

### Languages

zho;eng

### Categories (optional)

animation;kids

### NSFW

FALSE

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/2019_Disney_Channel_logo.svg/320px-2019_Disney_Channel_logo.svg.png

### Notes

It is listed as a closed channel, but for some reason, a functional stream still exists on the "(https://www.histar.tv/live/disney)" page.

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
