### ISSUE TITLE
Edit: FREEDOM

### ISSUE THREAD

**Issue by Mr-Musta** [iptv-org/database#8518]
### Channel ID (required)

FREEDOM.ua

### Channel Name

FREEDOM

### Alternative Names

FREEДOM;UATV;Ukraine Tomorrow

### Owners

The National News Agency of Ukraine;Ukrinform

### Country

UA

### Subdivision

UA-30

### City

Kyiv

### Broadcast Area

c/UA

### Languages

rus

### Categories

news

### NSFW

FALSE

### Launched

2015-10-01

### Website

https://tvfreedom.io/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/FreeDOMUAlogo.svg/512px-FreeDOMUAlogo.svg.png

**Comment by freearhey** [comment]
According to this article: https://uk.wikipedia.org/wiki/FREE%D0%94%D0%9E%D0%9C the channel was launched on October 1, 2015 (as UATV).

**Comment by DJ1999-max** [comment]
Is not launched on 2022.

> ### Channel ID (required)
> 
> FREEDOM.ua
> ### Channel Name
> 
> FREEDOM
> ### Alternative Names
> 
> FREEДOM;UATV;Ukraine Tomorrow
> ### Network
> 
> _No response_
> ### Owners
> 
> The National News Agency of Ukraine;Ukrinform
> ### Country
> 
> UA
> ### Subdivision
> 
> UA-30
> ### City
> 
> Kyiv
> ### Broadcast Area
> 
> c/UA
> ### Languages
> 
> rus
> ### Categories
> 
> news
> ### NSFW
> 
> FALSE
> ### Launched
> 
> 2015-10-01
> ### Closed
> 
> _No response_
> ### Replaced By
> 
> _No response_
> ### Website
> 
> https://tvfreedom.io/
> ### Logo
> 
> https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/FreeDOMUAlogo.svg/512px-FreeDOMUAlogo.svg.png
> ### Notes
> 
> _No response_

Is not launched in 2022.

**Comment by Mr-Musta** [comment]
> According to this article: https://uk.wikipedia.org/wiki/FREE%D0%94%D0%9E%D0%9C the channel was launched on October 1, 2015 (as UATV).

Fixed

**Comment by DJ1999-max** [comment]
Freedom is seen in https://iptv-org.github.io/

**Comment by Mr-Musta** [comment]
Yes, but not all information is filled out correctly
