### ISSUE TITLE
Edit: beIN Sports 1 (Qatar)

### ISSUE THREAD

**Issue by Ubada1** [iptv-org/database#8526]
### Channel ID (required)

beINSports1.qa

### Channel Name

Bein sports 1

### Country

Qatar 

### NSFW

TRUE

### Launched

2023-12-11

### Closed

2025-12-12

### Website

Http

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#data-scheme
