### ISSUE TITLE
Edit: Kanal 7 Baltics (Latvia)

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#8529]
### Channel ID (required)

Kanal7Baltics.lv

### Languages

rus;lat

### NSFW

None

### Notes

Latvian not Latin.

**Comment by DJ1999-max** [comment]
Bruh... still say Latin.

**Comment by freearhey** [comment]
The request specifies the code for Latin, the code for Latvian is `lav`.

https://github.com/iptv-org/database/blob/master/data/languages.csv

**Comment by DJ1999-max** [comment]
Oh, ok.
