### ISSUE TITLE
Add: Salvation TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8547]
### Channel Name

Salvation TV

### Country

IN

### City (optional)

Chennai

### Broadcast Area

c/IN

### Languages

eng

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://salvationtv.in/

### Logo

https://content.jdmagicbox.com/comp/bangalore/l5/080pxx80.xx80.150207120517.e4l5/catalogue/salvation-tv-network-pvt-m-g-road-bangalore-religious-organizations-1sabn2d.jpg

**Comment by freearhey** [comment]
Please update your request:

- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed
