### ISSUE TITLE
Add: GNC Evropa

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8553]
### Channel Name

GNC Evropa

### Country

KZ

### City (optional)

Riga

### Broadcast Area

c/KZ;c/RU;c/LV

### Languages

rus;kaz

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://gnctv.org/

### Logo

https://www.lyngsat.com/logo/tv/gg/gnc-kz.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/ua/GNCEurope
