### ISSUE TITLE
Add: Iran Jewish TV

### ISSUE THREAD

**Issue by katarighe** [iptv-org/database#8566]
### Channel Name

Iran Jewish TV

### Alternative Names (optional)

تلویزیون یهودیان ایرانی

### Country

IR

### Broadcast Area

c/IR

### Languages

fas

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://iran620.com/

### Logo

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjwdSjfPN5mmdN_f8zB2HesppxL_MwwsPGmA&usqp=CAU

**Comment by freearhey** [comment]
Please update your request:

- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by katarighe** [comment]
OK, the logo is updated:

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjwdSjfPN5mmdN_f8zB2HesppxL_MwwsPGmA&usqp=CAU
