### ISSUE TITLE
Add: Manas TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8571]
### Channel Name

Manas TV

### Alternative Names (optional)

Сайт Телеканал Манас

### Owners (optional)

Kyrgyzstan-Turkey Rectorate

### Country

KG

### City (optional)

Bishkek

### Broadcast Area

c/KG

### Languages

kir;tur

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://mediamanas.kg/

### Logo

https://www.lyngsat.com/logo/tv/mm/manas-tv-kg.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/kz/ManasTV
