### ISSUE TITLE
Add: Har Pal Geo

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8578]
### Channel Name

Har Pal Geo

### Country

PK

### City (optional)

Karachi

### Broadcast Area

c/PK

### Languages

urd

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://harpalgeo.tv/live

### Logo

https://www.lyngsat.com/logo/tv/gg/geo_har_pal_pk.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/us/HarPalGeo
