### ISSUE TITLE
Add: YleX

### ISSUE THREAD

**Issue by Sanzerz** [iptv-org/database#8592]
### Channel Name

YleX

### Owners (optional)

Yleisradio

### Country

FI

### Broadcast Area

c/FI

### Languages

fin

### Categories (optional)

music

### NSFW

FALSE

### Launched (optional)

2003-01-13

### Website (optional)

https://areena.yle.fi/podcastit/ohjelmat/ylex

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/YleX.svg/450px-YleX.svg.png

### Notes

YleX is a radio station in Finland that also has a live 24/7 multicam studio stream that can be added to the iptv playlist.

**Comment by freearhey** [comment]
Please update your request:

- logo must be in JPEG or PNG format

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Sanzerz** [comment]
Here's the PNG version of the same logo. https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/YleX.svg/450px-YleX.svg.png
