### ISSUE TITLE
Add: Hyundai Mall

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8596]
### Channel Name

Hyundai Mall

### Alternative Names (optional)

현대홈쇼핑

### Country

KR

### City (optional)

Seoul

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

shop

### NSFW

FALSE

### Website (optional)

https://www.hmall.com/pd/dpl/home?mainDispSeq=1

### Logo

https://www.lyngsat.com/logo/tv/hh/hyundai_home_shopping.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/kr/HyundaiHomeShopping
