### ISSUE TITLE
Add: KBC

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8597]
### Channel Name

KBC

### Alternative Names (optional)

광주방송

### Owners (optional)

Kwangju Broadcasting Corporation

### Country

KR

### City (optional)

Gwanju

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1995-05-14

### Website (optional)

https://www.ikbc.co.kr/onair/tv

### Logo

https://www.lyngsat.com/logo/tv/kk/kbc-kr.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/kr/HLDHDTV
