### ISSUE TITLE
Add: Mmoney

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8598]
### Channel Name

Mmoney

### Alternative Names (optional)

매일경제TV

### Owners (optional)

Maeil Broadcasting Network Co., Ltd

### Country

KR

### City (optional)

Seoul

### Broadcast Area

c/KR

### Languages

kor

### Categories (optional)

business

### NSFW

FALSE

### Launched (optional)

1995-03-01

### Website (optional)

https://mbnmoney.mbn.co.kr/

### Logo

https://www.lyngsat.com/logo/tv/mm/mmoney-kr.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/kr/MaeilBusinessTV
