### ISSUE TITLE
Add: Momo Shopping 2

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8673]
### Channel Name

Momo Shopping 2

### Country

TW

### City (optional)

New Taipei City

### Broadcast Area

c/TW

### Languages

zho

### Categories (optional)

shop

### NSFW

FALSE

### Website (optional)

https://www.momoshop.com.tw/main/Main.jsp

### Logo

https://www.lyngsat.com/logo/tv/mm/momo_shopping_tw.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed
