### ISSUE TITLE
Edit: EnerGeek 1 Logo

### ISSUE THREAD

**Issue by EnerGeekTeam** [iptv-org/database#869]
### Channel ID (required)

EnerGeek1.cl

### Country

CL

### Subdivision

CL-RM

### City

Recoleta

### Languages

spa

### Launched

2021-08-15

### Website

https://www.energeek.cl/

### Logo

https://energeek.cl/uploads/logos/Rosa.png

**Comment by freearhey** [comment]
Updated.
