### ISSUE TITLE
Is database in sync with api json files?

### ISSUE THREAD

**Issue by pvonmoradi** [iptv-org/database#87]
There are channels that exist in db but are missing here: `https://iptv-org.github.io/iptv/channels.json`
For example changes [here](https://github.com/iptv-org/iptv/issues/7170) (Defy TV) are not reflected in either of [api subdomain](https://iptv-org.github.io/?q=Defy%20TV) or that json file.

In general, what is the single source of truth (as a json) which contains all info (channel link, title, etc) for this project?
Thanks.

**Comment by freearhey** [comment]
The API was completely updated a few months ago (https://github.com/iptv-org/iptv/discussions/6340) and in the process the channel list was moved here:

```
https://iptv-org.github.io/api/channels.json
```

And yes, this file is fully synced with [iptv-org/database](https://github.com/iptv-org/database).

More info on the current version of the API can be found here: [iptv-org/api](https://github.com/iptv-org/api)

**Comment by pvonmoradi** [comment]
Thanks. The content differs from `/iptv/channels.json`. For example it does not contain the actual m3u8 link of channels.

**Comment by freearhey** [comment]
There is now a separate endpoint for streams: https://github.com/iptv-org/api#streams
