### ISSUE TITLE
Add: Network 10 Sydney

### ISSUE THREAD

**Issue by Alstruit** [iptv-org/database#8703]
### Channel Name

Network 10 Sydney

### Country

AU

### Broadcast Area

c/AU

### Languages

eng

### NSFW

FALSE

### Logo

https://upload.wikimedia.org/wikipedia/en/thumb/8/86/Network_10_logo_2018.svg/512px-Network_10_logo_2018.svg.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/au/10Sydney
