### ISSUE TITLE
Edit: Ant

### ISSUE THREAD

**Issue by Hieuhuynhxuan** [iptv-org/database#8707]
### Channel ID (required)

Ant.vn

### Channel Name

Ant

### Alternative Names

BPTV3 - ANT

### Owners

Binh Phuoc Newspaper Radio and Television Station

### Country

VN

### Broadcast Area

c/VN

### Languages

vie

### Categories

kids

### NSFW

None

### Launched

2017-01-01

### Closed

2022-07-01

### Logo

https://i.postimg.cc/G3fr4zrw/ANT-logo.png

**Comment by freearhey** [comment]
Please update your request:

- "replaced by" cannot contain the ID of the current channel
- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
