### ISSUE TITLE
Add: Shopping 24h

### ISSUE THREAD

**Issue by Hieuhuynhxuan** [iptv-org/database#8708]
### Channel Name

Shopping 24h

### Alternative Names (optional)

HCATV5 - Shopping 24h

### Owners (optional)

HCATV

### Country

VN

### Broadcast Area

c/VN

### Languages

vie

### Categories (optional)

shop

### NSFW

FALSE

### Launched (optional)

2022-08-27

### Logo

https://i.postimg.cc/V6gfsxg5/1699214517794.png

**Comment by freearhey** [comment]
Please update your request:

- "replaced by" cannot contain the ID of the current channel
- logo is not loading

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by freearhey** [comment]
Please update your request:

- "replaced by" should only be specified if the channel was closed and another channel replaced it

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
