### ISSUE TITLE
TNT Sports (Argentina)

### ISSUE THREAD

**Issue by Fabricio1889dmc** [iptv-org/database#8714]
### Channel ID (required)

TNTSports.ar

### Channel Name

TNT sports

### Network

Tnt

### Owners

Televisión argentina

### Country

Arkansas

### Subdivision

AR-B

### City

Buenos aires

### Languages

dea

### Categories

sports

### NSFW

None

### Website

https://tntsports.com.ar/

### Logo

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6nB4Tjmaic9JXBknMRDib9HDZKQcuL0ORjw&usqp=CAUhttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6nB4Tjmaic9JXBknMRDib9HDZKQcuL0ORjw&usqp=CAU

**Comment by freearhey** [comment]
Please update your request:

- country code is incorrect
- broadcast area code is incorrect
- language code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
