### ISSUE TITLE
Edit: MTV (Vietnam)

### ISSUE THREAD

**Issue by Hieuhuynhxuan** [iptv-org/database#8715]
### Channel ID (required)

MTV.vn

### Channel Name

MTV

### Owners

Paramount Networks EMEAA;IMC Group

### Country

VN

### Broadcast Area

c/VN

### Languages

vie

### Categories

music

### NSFW

None

### Launched

2011-07-01

### Closed

2023-01-01

### Website

http://mtvwe.com

### Logo

https://i.postimg.cc/L8dRhm3G/sl7ovhvsj4suarvt4n9jets5b0-c2996cafd622630bda13dc8e61930ba2.png

**Comment by freearhey** [comment]
Please update your request:

- category name should be in lowercase
- the size of the logo should not exceed 512x512px

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
