### ISSUE TITLE
Edit: Antena 1

### ISSUE THREAD

**Issue by nelbal** [iptv-org/database#8720]
### Channel ID (required)

Antena1.ro

### Alternative Names

Antena 1

### Country

RO

### Subdivision

RO-B

### Broadcast Area

RO

### NSFW

None

### Website

https://antenaplay.ro/

### Logo

https://i.imgur.com/EPmwuuv.png

### Notes

<img src="https://assets.antenaplay.ro/tvthumbs/antena1.jpg?1703350682" alt="Antena 1">

**Comment by freearhey** [comment]
Please update your request:

- alternative name should only be specified if it differs from the main name
- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
