### ISSUE TITLE
Add: Enlace BPB

### ISSUE THREAD

**Issue by Naruh1010** [iptv-org/database#8726]
### Channel Name

Enlace BPB

### Country

CL

### Subdivision (optional)

CL_RM

### City (optional)

Santiago

### Broadcast Area

c/CL;s/CL_RM

### Languages

spa

### NSFW

FALSE

### Website (optional)

https://www.151.cl/online/

### Logo

https://i.postimg.cc/cH4xDg39/descarga.png

**Comment by freearhey** [comment]
Please update your request:

- subdivision code is incorrect
- broadcast area code is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
