### ISSUE TITLE
Edit: Paramount Network (Vietnam)

### ISSUE THREAD

**Issue by Hieuhuynhxuan** [iptv-org/database#8736]
### Channel ID (required)

ParamountNetwork.vn

### Channel Name

Paramount Network

### Owners

Viacom Media Networks;IMC Group

### Country

VN

### Broadcast Area

c/VN

### Languages

vie;eng

### Categories

series;movies

### NSFW

None

### Launched

2017-01-01

### Closed

2022-12-31

### Website

https://www.paramountnetwork.com/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Paramount_Network.svg/512px-Paramount_Network.svg.png

**Comment by freearhey** [comment]
Please update your request:

- owner names must be separated by `;`

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels
