### ISSUE TITLE
Add: Retrox TV [CR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8810]
### Channel Name

Retrox TV

### Country

CR

### Broadcast Area

c/CR

### Languages

spa

### Categories (optional)

classic

### NSFW

FALSE

### Website (optional)

https://retroxtv.com/

### Logo

https://i.imgur.com/viJBL6f.png

**Comment by DrCalambre** [comment]
Retrox TV would not be working. Is there a way to update?

https://rpn3.bozztv.com/ssh101/ssh101/retroxtvhd/playlist.m3u8

**Comment by b4zz4** [comment]
Update URL:
https://tvservices.fullhd-streaming.com:3867/live/retroxtvlive.m3u8

**Comment by DrCalambre** [comment]
they do not work

**Comment by b4zz4** [comment]
Form Argentina:

https://github.com/iptv-org/database/assets/643833/8778bab0-f964-416e-9a75-eaf1628cddfc

**Comment by DrCalambre** [comment]
Now yes!. It's funny, for some unknown reason it didn't work yesterday. I tried it now and it works!
Thank you very much for your contribution. A hug from Patagonia
