### ISSUE TITLE
Add: Hai Duong TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8893]
### Channel Name

Hai Duong TV

### Alternative Names (optional)

Truyền hình Hải Dương

### Owners (optional)

Hai Duong Radio & Television

### Country

VN

### City (optional)

Hai Duong

### Broadcast Area

c/VN

### Languages

vie

### Categories (optional)

general

### NSFW

FALSE

### Launched (optional)

1984-01-01

### Website (optional)

http://www.haiduongtv.com.vn/truyen-hinh-truc-tuyen.html

### Logo

https://www.lyngsat.com/logo/tv/hh/hai_duong_tv_vn.png

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/channels/vn/HDTV
