### ISSUE TITLE
Add: Radio televizija Rozaje [ME] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8898]
### Channel Name

Radio televizija Rozaje

### Alternative Names (optional)

Radio televizija Rožaje

### Country

ME

### City (optional)

Rožaje

### Broadcast Area

c/ME

### Languages

srp

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.radiorozaje.me/

### Logo

https://i.imgur.com/vTZjEC5.png

**Comment by freearhey** [comment]
Please update your request:

- link to the official website is incorrect

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by Carlinhos027** [comment]
> Please update your request:
> 
> * link to the official website is incorrect
> 
> https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

Fixed
