### ISSUE TITLE
Add: Dunya TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8903]
### Channel Name

Dunya TV

### Country

AZ

### City (optional)

Sumqayit

### Broadcast Area

c/AZ

### Languages

aze

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://dunyatv.az/

### Logo

https://www.lyngsat.com/logo/tv/dd/dunya-tv-az.png

**Comment by freearhey** [comment]
Please update your request:

- the channel name can only include letters of the Latin alphabet

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by AntiPontifex** [comment]
Fixed
