### ISSUE TITLE
Edit: HBTV TicaVision [CR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8918]
### Channel ID (required)

HBTVTicaVision.cr

### Channel Name

TicaVision

### Alternative Names

TicaVisión

### Owners

Grupo Multimedios FM

### City

San José

### Categories

general

### NSFW

None

### Website

https://ticavisiontv.com/

### Logo

https://i.imgur.com/mev90pC.jpg

**Comment by mesuturuk7** [comment]
1.
