### ISSUE TITLE
Remove: Vme Kids

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#894]
### Channel ID

VmeKids.us

### Reason

Other

### Notes

Defunct.

Read https://en.wikipedia.org/wiki/V-me

**Comment by freearhey** [comment]
I could not find confirmation of the channel closure in any of the articles:

https://en.wikipedia.org/wiki/V-me
https://en.wikipedia.org/wiki/Vme_Kids

**Comment by AntiPontifex** [comment]
Looks like you're right: Wikipedia deceived me ;)
