### ISSUE TITLE
Add: AVA Family

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8940]
### Channel Name

AVA Family

### Country

IQ

### Broadcast Area

c/IQ

### Languages

ara

### Categories (optional)

family

### NSFW

FALSE

### Website (optional)

https://avafamily.avatv.live/

### Logo

https://www.lyngsat.com/logo/tv/aa/ava-family-iq.png

**Comment by BellezaEmporium** [comment]
Owned by Persiana Networks France, aimed at an Iraqi diaspora (majorly due to the content of their shows).
