### ISSUE TITLE
Add: Bostra TV [FR/CD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8944]
### Channel Name

Bostra TV

### Owners (optional)

Église évangéliste la Bonne Semence

### Country

FR

### City (optional)

Pantin

### Broadcast Area

c/FR;c/CD

### Languages

fra

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://www.bostratv.fr/

### Logo

https://i.imgur.com/MPtaSWd.jpg

**Comment by BellezaEmporium** [comment]
Are we 100% sure it's at destination of the Congo Republic diaspora ? Just by looking at the website, seems French to me.
