### ISSUE TITLE
Add: BAZIK TV [FR/CD/CG] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8950]
### Channel Name

BAZIK TV

### Country

FR

### City (optional)

Orly

### Broadcast Area

c/FR;c/CD;c/CG

### Languages

fra

### Categories (optional)

music

### NSFW

FALSE

### Website (optional)

https://bazik.tv/

### Logo

https://i.imgur.com/BmHiap5.png

**Comment by BellezaEmporium** [comment]
Keeping an eye on this, as website is 403 and according to some person on FB the channel doesn't seem to air since 3 weeks ago.
