### ISSUE TITLE
Add: Tous Congo TV [CD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8952]
### Channel Name

Tous Congo TV

### Country

CD

### Broadcast Area

c/CD

### Languages

fra

### Categories (optional)

general

### NSFW

FALSE

### Logo

https://i.imgur.com/SEKkBAu.png

**Comment by BellezaEmporium** [comment]
Logo seems to be a ripoff of Boss Brothers TV.
