### ISSUE TITLE
Add: JKM Church TV [UK/CD] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8954]
### Channel Name

JKM Church TV

### Country

UK

### Broadcast Area

c/UK;c/CD

### Languages

fra

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://www.facebook.com/PasteurJoel190/

### Logo

https://i.imgur.com/fRDD2PW.png

**Comment by BellezaEmporium** [comment]
No info on this channel since 2022. Is it still airing ?

That logo is not the correct one. This one is from an Indian Gospel TV : https://www.youtube.com/channel/UCLlbX2e5B18E4Zneux_bkeA

**Comment by Carlinhos027** [comment]
> No info on this channel since 2022. Is it still airing ?
> 
> That logo is not the correct one. This one is from an Indian Gospel TV : https://www.youtube.com/channel/UCLlbX2e5B18E4Zneux_bkeA

http://51.254.199.122:8080/JKMchurch/index.m3u8
