### ISSUE TITLE
Add: LSTV1 [US/GM] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8957]
### Channel Name

LSTV1

### Country

US

### Subdivision (optional)

US-TX

### City (optional)

Dallas

### Broadcast Area

c/US;c/GM

### Languages

eng

### Categories (optional)

general

### NSFW

FALSE

### Logo

https://i.imgur.com/kg7yPlY.jpg

**Comment by BellezaEmporium** [comment]
https://www.facebook.com/LSTV1GM/
