### ISSUE TITLE
Add: Kabbalah TV Russkij

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8965]
### Channel Name

Kabbalah TV Russkij

### Alternative Names (optional)

Каббала ТВ

### Country

IL

### Broadcast Area

c/IL;c/RU

### Languages

rus

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

http://kab.tv/rus#/stream

### Logo

https://www.lyngsat.com/logo/tv/kk/kabbalah-tv-il.png

**Comment by Dum4G** [comment]
Duplicate of KabbalaTV.ru
