### ISSUE TITLE
Add: TeleStereo [NI] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8972]
### Channel Name

TeleStereo

### Country

NI

### City (optional)

Managua

### Broadcast Area

c/NI

### Languages

spa

### Categories (optional)

music

### NSFW

FALSE

### Launched (optional)

2022-05-31

### Logo

https://i.imgur.com/7E86F9N.jpg

**Comment by BellezaEmporium** [comment]
https://www.facebook.com/p/TeleStereo-Nicaragua-100083155337980/
