### ISSUE TITLE
Add: ExtraPlus [NI] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#8985]
### Channel Name

ExtraPlus

### Country

NI

### City (optional)

Managua

### Broadcast Area

c/NI

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://extraplustv.com/

### Logo

https://i.imgur.com/wg8BMKK.jpg

**Comment by BellezaEmporium** [comment]
Website is password-protected. Channel however exists.
