### ISSUE TITLE
Add: LoveWorld Jerusalem

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8992]
### Channel Name

LoveWorld Jerusalem

### Network (optional)

LoveWorld Networks

### Country

US

### Subdivision (optional)

US-TX

### City (optional)

Houston

### Broadcast Area

c/IL;c/US

### Languages

ara

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://loveworldjerusalem.org/

### Logo

https://www.lyngsat.com/logo/tv/ll/loveworld-jerusalem-ng-il.png

**Comment by BellezaEmporium** [comment]
https://cdn3.wowza.com/5/RGtVZkFxL3FOQkxX/lwut/ngrp:lwu.rtmp_all/playlist.m3u8 for USA
https://cdn3.wowza.com/5/aVJETlF0UFdmYTFu/LWJ/ngrp:LWJ.stream_all/playlist.m3u8 for Jerusalem (Arabia)

LoveWorld Jerusalem is now called LoveWorld Arabia, and it's confirmed by looking at their own streaming service named AlphaTV : https://app.alphatv.global/guest/tv

https://go5lm6a6dawb-hls-live.5centscdn.com/lwarabic/53132d996b4263ec0d7b602292c46eaf.sdp/playlist.m3u8 for Arabic
