### ISSUE TITLE
Add: Dijlah Zaman

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#8994]
### Channel Name

Dijlah Zaman

### Alternative Names (optional)

قناة دجلة زمان

### Country

IQ

### City (optional)

_No reponse_

### Broadcast Area

c/IQ

### Languages

ara

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.dijlah.tv/index.php?page=pages&id=tarab

### Logo

https://www.lyngsat.com/logo/tv/dd/dijlah-zaman-iq.png

**Comment by BellezaEmporium** [comment]
According to https://www.dijlah.tv/index.php?page=pages&id=about, they're from Iraq, not from Jordan.

**Comment by AntiPontifex** [comment]
Changed and thanks.
