### ISSUE TITLE
Edit: Azteca Guatemala

### ISSUE THREAD

**Issue by jimmy2912k** [iptv-org/database#9003]
### Channel ID (required)

AztecaGuatemala.gt

### Network

https://ch1-tva.duin.dev/hls/1/stream.m3u8

### NSFW

None

### Website

https://ch1-tva.duin.dev/hls/1/stream.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#data-scheme
