### ISSUE TITLE
Add: An Ninh The Gioi

### ISSUE THREAD

**Issue by Hieuhuynhxuan** [iptv-org/database#9005]
### Channel Name

An Ninh The Gioi

### Alternative Names (optional)

An Ninh Thế Giới

### Owners (optional)

HCATV

### Country

VN

### Broadcast Area

c/VN

### Languages

vie

### NSFW

FALSE

### Launched (optional)

2009-10-28

### Website (optional)

https://antg.cand.com.vn/

### Logo

https://i.imgur.com/H1JjQWs.png

**Comment by BellezaEmporium** [comment]
HCA-TV 3

I believe the website should be https://antg.cand.com.vn/ as the one above doesn't answer.
