### ISSUE TITLE
Add: Alkofiya TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9014]
### Channel Name

Alkofiya TV

### Alternative Names (optional)

قناة الكوفية

### Country

EG

### City (optional)

Giza

### Broadcast Area

c/EG;c/PS

### Languages

ara

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://alkofiya.tv/

### Logo

https://www.lyngsat.com/logo/tv/aa/alkofiya-tv-ps.png

**Comment by BellezaEmporium** [comment]
Several sources are contesting.

While Google indicates they're in Egypt, their YouTube channel and Facebook page tend to say there's from Palestine (Gaza to be more exact). They may have changed recently due to the current events, but that still needs to be solved.

**Comment by AntiPontifex** [comment]
Although it has been a while, Lane, I do remember looking up the land address. I'd go with that.

**Comment by BellezaEmporium** [comment]
https://alkofiya.tv/pages/1 Confirmed, they're from Palestine.

Al-Kufiya Satellite Channel - Palestine

Channel frequency 11392 vertical / Nilesat SD

Channel frequency 11373 horizontal / Nilesat HD

Al-Kufiya Satellite Channel broadcasts around the clock with live transmission through multiple media outlets
