### ISSUE TITLE
Add: BFZ Turk

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9036]
### Channel Name

BFZ Turk

### Country

TR

### City (optional)

Sanliurfa

### Broadcast Area

c/TR

### Languages

tur

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://bfzturk.com/

### Logo

https://www.lyngsat.com/logo/tv/bb/bfz-turk-tr.png

**Comment by BellezaEmporium** [comment]
Anasayfa just means "Home page" x)
