### ISSUE TITLE
Add: Kanal Hayat International

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9113]
### Channel Name

Kanal Hayat International

### Alternative Names (optional)

Kanal Hayat Uluslararası

### Country

UK

### City (optional)

Doncaster

### Broadcast Area

c/UK;c/TR;c/AZ;c/UZ;c/TM

### Languages

tur;eng

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://www.kanalhayat.com/

### Logo

https://www.lyngsat.com/logo/tv/kk/kanal-hayat-tr.png

**Comment by Dum4G** [comment]
Is there an International stream?
![image](https://github.com/iptv-org/database/assets/5430116/ca81a6a1-a8aa-4052-934e-791ef2482983)

**Comment by AntiPontifex** [comment]
According to LyngSat there is: if not, feel free to close.
