### ISSUE TITLE
Add: MAX Anime [VE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#9123]
### Channel Name

MAX Anime

### Country

VE

### Broadcast Area

r/HISPAM

### Languages

spa

### Categories (optional)

animation

### NSFW

FALSE

### Launched (optional)

2023-12-21

### Website (optional)

https://esportsmax.tv/max-anime/

### Logo

https://i.imgur.com/Oj3hEBh.jpg

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/database/assets/5430116/899ced39-590c-40bb-a9f1-74a8260a579c)
Are they streaming somewhere?

**Comment by Carlinhos027** [comment]
> ![image](https://private-user-images.githubusercontent.com/5430116/298688865-899ced39-590c-40bb-a9f1-74a8260a579c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDk3OTAsIm5iZiI6MTcwNTk0OTQ5MCwicGF0aCI6Ii81NDMwMTE2LzI5ODY4ODg2NS04OTljZWQzOS01OTBjLTQwYmItYTlmMS03NGE4MjYwYTU3OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTg1MTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdmZmVlNDUwMTk1OTAzZGMzMjczM2M3ODM1NmI3NTY1ZWY5Y2Y3YjViNWY2Njk5ZjZkY2YzZDYyNGU3NTc1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RR0jhp1lzR4IN0pa1L9Ghf-7UEGUzihkwZOBXuwjjR4) Are they streaming somewhere?

Link is in VE playlist.
