### ISSUE TITLE
Add: TVES [HN] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#9137]
### Channel Name

TVES

### Country

HN

### City (optional)

Tegucigalpa

### Broadcast Area

c/HN

### Languages

spa

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://www.tves.hn/

### Logo

https://i.imgur.com/iLW5e2T.jpg

**Comment by Dum4G** [comment]
Does it exist outside Honduras? Why not just TV ES?

**Comment by Carlinhos027** [comment]
> Does it exist outside Honduras? Why not just TV ES?

Fixed
