### ISSUE TITLE
Add: NacionalTvPeru.pe

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/database#9156]
### Channel Name

Nacional Tv Peru

### Alternative Names (optional)

Nacional Tv Perú

### Country

PE

### Subdivision (optional)

PE-LIM

### City (optional)

Lima

### Broadcast Area

s/PE-LIM

### Languages

spa

### NSFW

FALSE

### Website (optional)

https://nacionaltvperu.com/

### Logo

https://i.imgur.com/ad0GNqa.png

### Notes

Not to be confused with other homonymous channels.

**Comment by 210100** [comment]
> ### Channel Name
> Nacional Tv Peru
> 
> ### Alternative Names (optional)
> Nacional Tv Perú
> 
> ### Network (optional)
> _No response_
> 
> ### Owners (optional)
> _No response_
> 
> ### Country
> PE
> 
> ### Subdivision (optional)
> PE-LIM
> 
> ### City (optional)
> Lima
> 
> ### Broadcast Area
> s/PE-LIM
> 
> ### Languages
> spa
> 
> ### Categories (optional)
> _No response_
> 
> ### NSFW
> FALSE
> 
> ### Launched (optional)
> _No response_
> 
> ### Closed (optional)
> _No response_
> 
> ### Replaced By (optional)
> _No response_
> 
> ### Website (optional)
> https://nacionaltvperu.com/
> 
> ### Logo
> https://i.imgur.com/ad0GNqa.png
> 
> ### Notes
> Not to be confused with other homonymous channels.
