### ISSUE TITLE
Edit: PlanetaTVAmazonas.pe -> PlaneaTVAmazonas.pe

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/database#9157]
### Channel ID (required)

PlanetaTVAmazonas.pe

### Channel Name

Planea TV Amazonas

### NSFW

None

### Notes

Error typo. The channel does not carry the letter "t". I detected this error a long time after creating this entry.

**Comment by Dum4G** [comment]
2 separate issues should be created then. One to remove an invalid id and the second one to add the channel back with proper id and relevant info

**Comment by sguinetti** [comment]
> 2 separate issues should be created then. One to remove an invalid id and the second one to add the channel back with proper id and relevant info

Right. I did not realize how it could be fixed. I will.
