### ISSUE TITLE
Add: A+ Guatemala

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/database#9158]
### Channel Name

A+ Guate

### Alternative Names (optional)

A Más Guate

### Network (optional)

TV Azteca

### Owners (optional)

Grupo Salinas ; TV Azteca (Televisión Azteca)

### Country

GT

### Broadcast Area

c/GT

### Languages

spa

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://www.tvaztecaguate.com/

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/A%2B_Guate_logo2023.webp/307px-A%2B_Guate_logo2023.webp.png

### Notes

The old TV Azteca Guatemala Website doesn't work anymore
New Link: https://tvaztecaguate.com
Wikipedia of Azteca Guatemala & A+ Guate
https://es.m.wikipedia.org/wiki/TV_Azteca_Guate

**Comment by Carlinhos027** [comment]
#9034
