### ISSUE TITLE
Edit: TVP Info

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/database#9160]
### Channel ID (required)

TVPInfo.pl

### NSFW

None

### Logo

https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Tvp-info-nowe-logo.svg/512px-Tvp-info-nowe-logo.svg.png

### Notes

Changed logo.

**Comment by Dum4G** [comment]
Just before noon on January 15, 2024, the TVP Info website and YouTube channel were restored; access to archived material was also restored where said material was not biased towards the previous Law and Justice government. Andrzej Jaszczyszyn was named as the head of the restored tvp.info service.[[30]](https://en.wikipedia.org/wiki/TVP_Info#cite_note-30)[[31]](https://en.wikipedia.org/wiki/TVP_Info#cite_note-31) On 19 January 2024, TVP Info the schedule was changed, changes have been made in the evening schedule, program Publicystyka TVP Info, is divided into two discussion programs and the "Oko na Świat" program at 23:00 CET, on same day, they moved new studio, but in same place.
