### ISSUE TITLE
Add: PlaneaTV.pe

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/database#9164]
### Channel Name

Planea TV

### Owners (optional)

 Planea Tv Amazonas & Jaén

### Country

PE

### Subdivision (optional)

PE-AMA

### City (optional)

Bagua

### Broadcast Area

s/PE-AMA

### Languages

spa

### NSFW

FALSE

### Website (optional)

https://planeatvamazonas.com/

### Logo

https://i.imgur.com/EoLhvBN.png

### Notes

Replacement of PlanetaTVAmazonas.pe

**Comment by Dum4G** [comment]
Is Amazonas necessary to be in the name?

**Comment by Dum4G** [comment]
Is Amazonas necessary to be in the name? Looks like full name is [Planea Tv Amazonas & Jaén](https://empresas.guiabbb.pe/01755023/Planea_Tv_Amazonas_&_Jaen)

**Comment by sguinetti** [comment]
I have not seen another channel called "Planea". Also, Amazonas, Jaen and Bagua are from the same department (Amazonas). For now I don't see the need to add Amazonas to a channel, although I would edit the name of the operating company.
