### ISSUE TITLE
Add: FX 1

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9168]
### Channel Name

FX 1

### Country

FR

### Broadcast Area

c/FR

### Languages

ara;fra;eng

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://fxtv.wns.live/

### Logo

https://www.lyngsat.com/logo/tv/ff/fx-1-fr.png

**Comment by Carlinhos027** [comment]
Duplicated:
https://iptv-org.github.io/?q=Fx1
