### ISSUE TITLE
Add: Mission Erweckung der Welt

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9183]
### Channel Name

Mission Erweckung der Welt

### Country

DE

### City (optional)

Offenbach am Main

### Broadcast Area

c/DE

### Languages

deu

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://revival-mission.de/

### Logo

https://www.lyngsat.com/logo/tv/mm/mission-erweckung-der-welt-de-ua.png

**Comment by Dum4G** [comment]
Do they have any web stream?

**Comment by BellezaEmporium** [comment]
The only stream that was in there is a YouTube stream hosted by her wife.

**Comment by AntiPontifex** [comment]
According to LyngSat they do have a live stream: handle this one as you wish.

**Comment by BellezaEmporium** [comment]
Found it : https://www.youtube.com/watch?v=rTzHcIZVzMU

**Comment by AntiPontifex** [comment]
Thanks
