### ISSUE TITLE
Add: Niederbayern TV Satellit

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9184]
### Channel Name

Niederbayern TV Satellit

### Country

DE

### City (optional)

Deggendorf

### Broadcast Area

c/DE

### Languages

deu

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.niederbayerntv.de/

### Logo

https://www.lyngsat.com/logo/tv/nn/niederbayern-tv-de.png

**Comment by Dum4G** [comment]
is Satellit part necessary here?

**Comment by AntiPontifex** [comment]
I'd say so: there are different feeds within the same network.
