### ISSUE TITLE
Add: Ellada TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9190]
### Channel Name

Ellada TV

### Country

GR

### City (optional)

Sparta

### Broadcast Area

c/GR

### Languages

ell

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

 http://www.elladatv.gr/

### Logo

https://www.lyngsat.com/logo/tv/ee/ellada-tv-gr.png

**Comment by Dum4G** [comment]
Are you sure it's not http://www.elladatv.gr/?

**Comment by AntiPontifex** [comment]
You're correct: thanks and edited.
