### ISSUE TITLE
Add: Mega TV [MZ] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#9361]
### Channel Name

Mega TV

### Country

MZ

### City (optional)

Maputo

### Broadcast Area

c/MZ

### Languages

por

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://www.mega.co.mz/

### Logo

https://i.imgur.com/WGwSaAK.jpg

**Comment by Dum4G** [comment]
Duplicate of https://iptv-org.github.io/channels/mz/MegaTV
