### ISSUE TITLE
Add: La Capi TV

### ISSUE THREAD

**Issue by b4zz4** [iptv-org/database#9386]
### Channel Name

La Capi TV

### Alternative Names (optional)

Servicio de Streaming Intergaláctico

### Country

AR

### Broadcast Area

c/AR

### Languages

spa

### Categories (optional)

animation

### NSFW

FALSE

### Website (optional)

https://play.lacapi.tv/

### Logo

https://play.lacapi.tv/img/favicon.png

### Notes

It is a personal channel of the development of my animation series, with movies and series in public domain and free

**Comment by b4zz4** [comment]
M3u8: https://play.lacapi.tv/canal.m3u8

**Comment by BellezaEmporium** [comment]
I must say I am not entirely sure where can I place this one up. Does it airs 24/7 ? Is it an OTT stream ? (the chunklist seems to be only mentioning the episodes one by one, not actually streaming something.) In the other case that sounds like VoD, and thus isn't accepted as an channel.

**Comment by b4zz4** [comment]
Of course it's a permanent playlist, but if I'm sorry I thought I could add channels like that.

**Comment by BellezaEmporium** [comment]
We can accept this as a channel if you can manage to create a seamless (doesn't need to be 24/7) stream of your shows.

**Comment by b4zz4** [comment]
I would have to unify the formats I think it would be possible
