### ISSUE TITLE
Add: GEM

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9440]
### Channel Name

GEM

### Country

MC

### City (optional)

Monte Carlo

### Broadcast Area

c/MC

### Languages

eng

### Categories (optional)

education;kids

### NSFW

FALSE

### Website (optional)

https://gem-tv.com/tv

### Logo

https://i.imgur.com/5dn2u4E.png

**Comment by Dum4G** [comment]
https://ezgif.com/svg-to-png is your friend
