### ISSUE TITLE
Add: Timveni TV [MW] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#9448]
### Channel Name

Timveni TV

### Country

MW

### City (optional)

Lilongwe

### Broadcast Area

c/MW

### Languages

eng

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

https://timveni.com/

### Logo

https://i.imgur.com/AqAhDEe.png

**Comment by Dum4G** [comment]
@Carlinhos027 don't use .gif in the end of the link. Thankfully in imgur you can just replace extension for png
