### ISSUE TITLE
Add: Euronews Serbia

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#945]
### Channel Name

Euronews Serbia

### Country

FR

### City (optional)

Lyon

### Broadcast Area

s/RS

### Languages

srp

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://www.euronews.rs/

### Logo

https://www.euronews.rs/files/img/logo-new.png

### Notes

Streaming URL:

https://d1ei8ofhgfmkac.cloudfront.net/app-19518-1306/ngrp:QoZfNjsg_all/playlist.m3u8

**Comment by freearhey** [comment]
Already in the database: https://iptv-org.github.io/?q=Euronews%20Serbia
