### ISSUE TITLE
Edit: Babenation

### ISSUE THREAD

**Issue by Jjb6859** [iptv-org/database#9473]
### Channel ID (required)

Babenation.uk

### NSFW

None

**Comment by sguinetti** [comment]
@Dum4G Are you sure that a channel with a XXX category has to set the parameter NSFW : False?

**Comment by Dum4G** [comment]
I'm just closing issues that are created to make attention. Ofc those should be marked as NSFW and be blocked since recent complaint from Github

**Comment by sguinetti** [comment]
I understand. I was asking this question because the user accounts that created this type of issue are newly created, and I fear that there are bots just for make attention.
