### ISSUE TITLE
Add: 8 Kanal

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9540]
### Channel Name

8 Kanal

### Alternative Names (optional)

8 канал

### Country

RU

### City (optional)

Moscow

### Broadcast Area

c/RU

### Languages

rus

### Categories (optional)

entertainment

### NSFW

FALSE

### Website (optional)

http://8tv.ru/

### Logo

https://www.lyngsat.com/logo/tv/num/8_tv_ru.png

**Comment by Dum4G** [comment]
Channel8.ru
