### ISSUE TITLE
Add: Juvelirochka

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9563]
### Channel Name

Juvelirochka

### Alternative Names (optional)

Ювелирочка

### Country

RU

### City (optional)

Moscow

### Broadcast Area

c/RU

### Languages

rus

### Categories (optional)

shop

### NSFW

FALSE

### Website (optional)

https://uvi.ru/online/

### Logo

https://www.cableman.ru/sites/default/files/yuveliroochka.png

**Comment by Dum4G** [comment]
Yuvelirochka.ru
