### ISSUE TITLE
Add: Krasnaya Liniya

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9564]
### Channel Name

Krasnaya Liniya

### Alternative Names (optional)

Красная Линия

### Country

RU

### City (optional)

Moscow

### Broadcast Area

c/RU

### Languages

rus

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.rline.tv/programs/

### Logo

https://www.lyngsat.com/logo/tv/kk/krasnaya_liniya_ru.png

**Comment by Dum4G** [comment]
lol
RedLine.ru
