### ISSUE TITLE
Add: Krim 24

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9577]
### Channel Name

Krim 24

### Alternative Names (optional)

Крым 24

### Country

RU

### City (optional)

Simferopol

### Broadcast Area

c/RU

### Languages

rus

### Categories (optional)

news

### NSFW

FALSE

### Website (optional)

https://crimea24tv.ru/broadcasting/

### Logo

https://www.lyngsat.com/logo/tv/num/24_krim_ua.png

**Comment by Dum4G** [comment]
Crimea24.ru

**Comment by Dum4G** [comment]
Use Russian names to search, it's more prominent
