### ISSUE TITLE
Add: SMA Togo TV [TG] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/database#9580]
### Channel Name

SMA Togo TV

### Country

TG

### City (optional)

Lomé

### Broadcast Area

c/TG

### Languages

fra

### Categories (optional)

religious

### NSFW

FALSE

### Website (optional)

https://smatogo.tv/

### Logo

https://i.imgur.com/mk6KJgE.jpg

**Comment by MapGuy11** [comment]
https://smatogo.tv:89/smatogo/smatogo.m3u8
