### ISSUE TITLE
Add: Schelkovo TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9585]
### Channel Name

Schelkovo TV

### Alternative Names (optional)

Щёлковское ТВ

### Country

RU

### City (optional)

Shchelkovo

### Broadcast Area

c/RU

### Languages

rus

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://stream0.tv41.ru/player/

### Logo

https://www.lyngsat.com/logo/tv/ss/schelkovo-tv-ru.png

**Comment by Dum4G** [comment]
ShchyolkovskoeTV.ru
