### ISSUE TITLE
Edit: Altyn Asyr

### ISSUE THREAD

**Issue by katarighe** [iptv-org/database#9595]
### Channel ID (required)

AltynAsyr.tm

### Categories

general

### NSFW

None

**Comment by Carlinhos027** [comment]
According to Wikipedia, the most appropriate category would be "sports":

https://en.wikipedia.org/wiki/Altyn_Asyr_(TV_channel)

**Comment by katarighe** [comment]
@Carlinhos027 it is a general network, not sports. There is a sporting club under the same name but unrelated to that TV channel.
