### ISSUE TITLE
Add: TRK Nadym

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9601]
### Channel Name

TRK Nadym

### Alternative Names (optional)

Телерадиокомпания Надым

### Country

RU

### City (optional)

Nadym

### Broadcast Area

c/RU

### Languages

rus

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

http://trknadym.ru/online/

### Logo

https://www.lyngsat.com/logo/tv/tt/trk_nadym.png

**Comment by Dum4G** [comment]
VestnikNadyma.ru
