### ISSUE TITLE
Add: TRK Rus

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9602]
### Channel Name

TRK Rus

### Alternative Names (optional)

ТРК Русь

### Country

RU

### City (optional)

Kostroma

### Broadcast Area

c/RU

### Languages

rus

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://rus-kostroma.ru/online/

### Logo

https://www.lyngsat.com/logo/tv/tt/trk-rus-ru.png

**Comment by Dum4G** [comment]
Rus.ru
