### ISSUE TITLE
Add: Za! TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9624]
### Channel Name

Za! TV

### Alternative Names (optional)

За!

### Country

RU

### City (optional)

Moscow

### Broadcast Area

c/RU

### Languages

rus;ukr

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://zatvmedia.netlify.app/zatv.html

### Logo

https://kartina-tv.site/wp-content/uploads/2020/12/logo_new.png

**Comment by Carlinhos027** [comment]
Fix the logo, please.

**Comment by AntiPontifex** [comment]
Fixed
