### ISSUE TITLE
Add: In TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9763]
### Channel Name

In TV

### Country

BO

### City (optional)

La Paz

### Broadcast Area

c/BO

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://in.tv.bo/en-vivo/

### Logo

https://www.lyngsat.com/logo/tv/ii/in-tv-bo.png

**Comment by Carlinhos027** [comment]
#9615
