### ISSUE TITLE
Update channel names

### ISSUE THREAD

**Issue by cr0op** [iptv-org/database#986]
On the playlist, I noticed "Fuse East (720p)" (ch ID 'FuseEast.us') is actually the Fuse FAST channel "Backstage" (new channel ID could be 'Backstage.us' or 'BackstageTV.us')

[Backstage Logo](https://image.xumo.com/v1/channels/channel/99991303/600x337.jpg?type=channelTile)

Also, the channel "Pluto TV Pluto After School Cartoons (480p)" has rebranded to "Pluto TV Forever Kids" as of last year. I can't find the channel ID but the new one could be 'PlutoTVForeverKids.us'

[Forever Kids Logo](https://images.pluto.tv/channels/56171fafada51f8004c4b40f/colorLogoPNG.png)

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_edit.yml&title=Edit%3A+
