### ISSUE TITLE
Edit: Rouge TV

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/database#9867]
### Channel ID (required)

RougeTV.ch

### Channel Name

Carac1

### Network

Carac Media

### Owners

Media One Group

### Country

CH

### City

Genêve

### Languages

fra

### Categories

entertainment;xxx

### NSFW

TRUE

### Replaced By

Carac1.ch

### Website

https://carac.tv/

### Logo

https://i.imgur.com/mw3PbSU.png

### Notes

Rouge TV got renamed Carac1, and have now 4 different channels. The 1st channel contains erotic programs, whilst the 3 others are thematical and are family-friendly.

**Comment by Dum4G** [comment]
We can't pass the check since ios already in database. I think we should mark this channel as closed with original name or remove it as a duplicate, maybe add old name to Carac1

**Comment by BellezaEmporium** [comment]
Yep, better do this.
