### ISSUE TITLE
Add: TNH Canal 8

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9891]
### Channel Name

TNH Canal 8

### Alternative Names (optional)

Canal Ocho

### Owners (optional)

Government of Honduras

### Country

HN

### City (optional)

Tegucigalpa

### Broadcast Area

c/HN

### Languages

spa

### Categories (optional)

entertainment

### NSFW

FALSE

### Launched (optional)

2008-08-20

### Website (optional)

https://tnh.gob.hn/en-vivo/

### Logo

https://www.lyngsat.com/logo/tv/tt/tnh-canal-8-hn.png

**Comment by Carlinhos027** [comment]
Already on database:
https://iptv-org.github.io/channels/hn/Canal8
