### ISSUE TITLE
Add: Canal 6 CDMX

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/database#9892]
### Channel Name

Canal 6 CDMX

### Owners (optional)

Grupo Multimedios

### Country

MX

### City (optional)

Monterrey

### Broadcast Area

c/MX;c/US

### Languages

spa

### Categories (optional)

general

### NSFW

FALSE

### Website (optional)

https://www.multimediostv.com/en-vivo/cdmx

### Logo

https://www.lyngsat.com/logo/tv/cc/canal-6-mx.png

**Comment by Carlinhos027** [comment]
Already on database: https://iptv-org.github.io/channels/mx/Canal6Nacional 
Shows the CDMX stream.
